"""Fynns Holz, abgetastet aus seiner Zeichnung.

Das Bild kam sechsfach vergroessert an; zurueckgerechnet liegt es
Pixel fuer Pixel so vor, wie er es gemalt hat - ohne Rateschritt,
weil die Vergroesserung genau aufging.
"""

FARBEN = {
    'a': (153, 108, 60, 255),
    'b': (204, 160, 107, 255),
    'c': (192, 145, 91, 255),
    'd': (129, 89, 49, 255),
    'e': (216, 176, 124, 255),
    'f': (171, 124, 72, 255),
    'g': (178, 131, 78, 255),
    'h': (189, 141, 87, 255),
    'i': (114, 77, 42, 255),
    'j': (146, 103, 57, 255),
    'k': (175, 127, 75, 255),
    'l': (68, 51, 35, 255),
    'm': (55, 41, 28, 255),
    'n': (60, 46, 31, 255),
    'o': (47, 36, 24, 255),
    'p': (198, 168, 120, 255),
    'q': (150, 124, 88, 255),
    'r': (172, 144, 102, 255),
    's': (126, 102, 74, 255),
    't': (212, 171, 119, 255),
    'u': (58, 44, 30, 255),
    '.': (0, 0, 0, 0),
}

MITTE = 10.0

KARTE = [
    ".........ee.........",
    "........eeee........",
    ".......eeeeee.......",
    "......eeekkeee......",
    "......eekkkkee......",
    "......eehhhhee......",
    "......eehhhhee......",
    "......eehhhhee......",
    "......bbaaakbb......",
    "......bbaaakbb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......ccaaaacc......",
    "......ccaaaacc......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ggddddgg......",
    "......ggddddgg......",
    "......ggddddgg......",
    "......ggddddgg......",
    "......ggddddgg......",
    "ctccfccffjjffccfctcf",
    "fffffcffjjjjffffffff",
    "...ffiiiiiiiiiiff...",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    "........uttu........",
    "........ctcf........",
    ".......jfcfjj.......",
    "........juuj........",
    ".........ii.........",
]
