"""Fynns Kupfer, abgetastet aus seiner Zeichnung.

Das Bild kam sechsfach vergroessert an; zurueckgerechnet liegt es
Pixel fuer Pixel so vor, wie er es gemalt hat - ohne Rateschritt,
weil die Vergroesserung genau aufging.
"""

FARBEN = {
    'a': (246, 205, 172, 255),
    'b': (191, 115, 75, 255),
    'c': (236, 185, 148, 255),
    'd': (228, 167, 125, 255),
    'e': (163, 91, 58, 255),
    'f': (211, 142, 100, 255),
    'g': (208, 137, 95, 255),
    'h': (215, 147, 105, 255),
    'i': (225, 161, 118, 255),
    'j': (183, 108, 70, 255),
    'k': (145, 77, 48, 255),
    'l': (61, 47, 35, 255),
    'm': (49, 38, 28, 255),
    'n': (54, 42, 31, 255),
    'o': (42, 32, 24, 255),
    'p': (230, 171, 130, 255),
    'q': (196, 120, 78, 255),
    'r': (214, 145, 103, 255),
    's': (173, 100, 64, 255),
    't': (186, 112, 72, 255),
    'u': (243, 199, 165, 255),
    'v': (52, 40, 30, 255),
    'w': (159, 88, 55, 255),
    '.': (0, 0, 0, 0),
}

MITTE = 10.0

KARTE = [
    ".........aa.........",
    "........aaaa........",
    ".......aaaaaa.......",
    "......aaaffaaa......",
    "......aaffffaa......",
    "......aaiiiiaa......",
    "......aaiiiiaa......",
    "......aaiiiiaa......",
    "......aafiifaa......",
    "......aaffffaa......",
    "......aaffffaa......",
    "......aaffffaa......",
    "......aabfffaa......",
    "......aabfffaa......",
    "......aabbffaa......",
    "......aabbffaa......",
    "......ccbbbfcc......",
    "......ccbbbfcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ccbbbbcc......",
    "......ddbbbbdd......",
    "......ddbbbbdd......",
    "......ddeeeedd......",
    "......ddeeeedd......",
    "......ddeeeedd......",
    "......ddeeeedd......",
    "......ddeeeedd......",
    "......ddeeeedd......",
    "......hheeeehh......",
    "......hheeeehh......",
    "......hheeeehh......",
    "......hheeeehh......",
    "......hheeeehh......",
    "duddgddggjjggddgdudg",
    "gggggdggjjjjgggggggg",
    "...ggkkkkkkkkkkgg...",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    "........lmno........",
    "........nlom........",
    "........pqrs........",
    "........rpsq........",
    ".......tvuuvt.......",
    ".......tdudgt.......",
    ".......jgdgjj.......",
    ".......tjvvjt.......",
    "........wwww........",
]
