"""Fynns Stahlschwert, abgetastet aus seinem flachen Pixelbild.

Gedacht als Ersatz fuer das Eisenschwert. Zwei Sachen waren dabei zu
beachten: Der Hintergrund war gemalt statt durchsichtig, und das Bild
hatte beim Verschicken an Genauigkeit verloren - aus vier Griffarben
waren fuenfundzwanzig geworden. Beides ist beim Abtasten behandelt.
"""

FARBEN = {'a': (163, 167, 173, 255), 'b': (237, 238, 240, 255), 'c': (192, 195, 199, 255), 'd': (131, 136, 144, 255), 'e': (214, 216, 219, 255), 'f': (102, 107, 115, 255), 'g': (85, 90, 97, 255), 'h': (62, 66, 55, 255), 'i': (122, 128, 136, 255), 'j': (52, 54, 45, 255), 'k': (164, 106, 81, 255), 'l': (133, 90, 72, 255), 'm': (147, 97, 76, 255), 'n': (117, 82, 68, 255), 'o': (67, 71, 68, 255), '.': (0, 0, 0, 0)}

KARTE = [
    ".........bb.........",
    "........bbbb........",
    ".......bbbbbb.......",
    "......bbbaabbb......",
    "......bbaaaabb......",
    "......bbccccbb......",
    "......bbccccbb......",
    "......bbccccbb......",
    "......bbaccabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbaaaabb......",
    "......bbdaaabb......",
    "......bbdaaabb......",
    "......bbddaabb......",
    "......bbddaabb......",
    "......eedddaee......",
    "......eedddaee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......eeddddee......",
    "......ccddddcc......",
    "......ccddddcc......",
    "......ccffffcc......",
    "......ccffffcc......",
    "......ccffffcc......",
    "......ccffffcc......",
    "......ccffffcc......",
    "......ccffffcc......",
    "......aaffffaa......",
    "......aaffffaa......",
    "......aaffffaa......",
    "......aaffffaa......",
    ".bb...aaffffaa...cc.",
    "cbccaccaaiiaaccacbca",
    "aaaaacaaiiiiaaaaaaaa",
    "...aaggggggggggaa...",
    "........hjhj........",
    "........hhjj........",
    "........klmn........",
    "........mknl........",
    "........ohhj........",
    "........hojh........",
    "........klmn........",
    "........mknl........",
    "........ohhj........",
    "........hojh........",
    "........klmn........",
    "........mknl........",
    "........obbj........",
    "........cbca........",
    ".......iacaii.......",
    "........iggi........",
    ".........gg.........",
]
MITTE = 10.0
