/* Das Zauberreich: ein Ereignis mit drei Orten, die einen Aufstieg erzählen.
   Erzeugt von tools/zauber.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

     'lehrling'   Lehrlingsgarten   Normal    der ummauerte Garten, in dem man es lernt
     'warte'      Sternenwarte      Profi
     'loge'       Erzmagierloge     Legende

   DIE FRAGE DIESER WELT IST: *WANN FÄNGT ES AN?*
   Jede andere Welt läuft im Takt – Fallgatter, Falltür, Stacheln, Fontäne, Wracktor gehen auf und
   zu, ohne daß jemand gefragt würde, und die Aufgabe heißt immer: den Moment abpassen. Hier
   startet der Spieler die Uhr selbst. Er stößt die Blüte an, und von da an läuft SEINE Zeit. Aus
   dem Abpassen wird eine Dosierung, und das ist es, was ein Lehrling übt.

   DIE MASCHINEN (src/obstacles_zauber.js):
     'ranke'       Die Blüte anstoßen läßt eine Ranke über die Lücke wachsen – für ein paar
                   Sekunden, dann welkt sie. Ihre Felder sind in der Karte gewöhnlicher Boden;
                   daß man ohne Ranke hindurchfällt, besorgt die Maschine. Dieselbe Umkehrung wie
                   bei der Schneebrücke, und aus demselben Grund: Boden, der zur Laufzeit
                   entsteht, müßte Wegfindung, Banden und Kamera mitziehen. Boden, der wegfällt,
                   kostet eine Abfrage.
     'zauberhut'   Drei Hüte, einer leuchtet. Wer in einen rollt, kommt aus dem leuchtenden
                   heraus; wer in den leuchtenden rollt, aus dem nächsten – es gibt keine
                   Sackgasse. Das Leuchten wandert im Takt und kündigt sich an.

   DIE OPTIK KOMMT AUS DEM BESTAND. Kein einziges neues Bild für die alten Maschinen, und trotzdem
   sieht keine aus wie im Märchenland: Das Windrad ist hier eine Ranke oder ein Besen, der
   Prellklotz ein Pilz, eine Leuchtkugel oder ein Kristall, der Magnet ein Seelenlicht, die
   Drehscheibe ein Laubwirbel.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. */

const ZAUBER_GARTEN = [
  {
    name: 'Am Gartentor', par: 3, theme: 'lehrlingsgarten',
    intro: 'Der Garten des Lehrlings, kurz vor Sonnenuntergang. Zwei Hecken stehen im Weg, und dazwischen geht es im Bogen hindurch. Die beiden Springkräuter federn den Ball zurück, sobald ihre Kapsel platzt – das lohnt sich zu wissen, bevor es schwieriger wird.',
    map: [
      '..............................',
      '..............................',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.##T#####..#######..######H##.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 6, x1: 9, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 6, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 7, x1: 18, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 7, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 14.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 23.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Die erste Blüte', par: 3, theme: 'lehrlingsgarten',
    intro: 'Über die Lücke führt nichts – bis man die Blüte anstößt. Dann wächst eine Ranke hinüber und trägt vier Sekunden lang. Zu sacht geschlagen, und man liegt noch darauf, wenn sie welkt; zu hart, und man fliegt daran vorbei. Dazwischen liegt der Schlag.',
    map: [
      '................................',
      '................................',
      '................................',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '.##T########################H##.',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'ranke', x: 14, y: 3, w: 4, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 10.5, y: 6.5 } },
      { type: 'rotor', x: 21.5, y: 6.5, blades: 3, len: 1.8, speed: 1.1, thick: 0.16, style: 'sprenger', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Der Springkrautkranz', par: 3, theme: 'lehrlingsgarten',
    intro: 'Ein Rundbeet, und mitten darin das Loch. Der Kranz aus Springkraut läßt niemanden geradewegs hinein – wer es mit Gewalt versucht, kommt weiter heraus, als er hineingekommen ist. Sanft anspielen und eine Kapsel als Wand benutzen ist der kürzere Weg.',
    map: [
      '............................',
      '............................',
      '.......##############.......',
      '....####################....',
      '...######################...',
      '..########################..',
      '..########################..',
      '..#T#########H############..',
      '..########################..',
      '..########################..',
      '..########################..',
      '...######################...',
      '....####################....',
      '.......##############.......',
      '............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 2, x1: 7, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 2, x1: 21, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 3, x1: 4, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 3, x1: 24, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 4, x1: 3, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 4, x1: 25, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 5, x1: 2, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 26, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 11, x1: 2, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 11, x1: 26, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 12, x1: 3, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 12, x1: 25, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 13, x1: 4, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 13, x1: 24, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 14, x1: 7, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 14, x1: 21, y1: 13, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 16.7, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 10.7, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 10.3, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 4.3, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Zwei Blüten', par: 4, theme: 'lehrlingsgarten',
    intro: 'Zwei Lücken, zwei Blüten. Die zweite Blüte liegt hinter der ersten Ranke – man kommt also nur an sie heran, wenn die erste noch trägt. Ein Schlag, der beide schafft, ist möglich; zwei ruhige sind sicherer.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 11, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 8.5, y: 6.5 } },
      { type: 'ranke', x: 22, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 18.5, y: 6.5 } },
      { type: 'bumper', x: 27.5, y: 6.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Der Hutständer', par: 4, theme: 'gewaechshaus',
    intro: 'Durch die erste Wand kommt nur, wer sich verzaubern läßt: hinein in einen Hut, heraus aus dem, der gerade leuchtet – und wer in den leuchtenden rollt, aus dem nächsten. Einer der beiden Ausgänge steht in einer Nische: Von dort muß man erst zur Seite und dann hinaus, das kostet einen Schlag. Danach ist die Bahn noch nicht zu Ende – die zweite Wand läßt nur oben eine Gasse, und davor dreht der Sprenger.',
    map: [
      '..........................................',
      '..........................................',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.##T########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.###########xxx##xxxxx######xxx##########.',
      '.###########xxx######x######xxx######H###.',
      '.###########xxx######x######xxx##########.',
      '.###########xxx######x######xxx##########.',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'zauberhut', takt: 2.6, phase: 0.0, r: 0.42, plaetze: [[6.0, 7.0], [18.0, 4.0], [18.0, 11.0]] },
      { type: 'bumper', x: 9.5, y: 10.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 7.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'rotor', x: 34.5, y: 6.5, blades: 2, len: 1.3, speed: 0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Das Treibhaus', par: 4, theme: 'gewaechshaus',
    intro: 'Der Bienenstand steht quer im Weg, und der Durchlaß zwischen den Körben schließt sich im Takt mit einer Wabe. Dahinter drehen zwei Rasensprenger gegeneinander – sie laufen in verschiedene Richtungen, also gibt es keinen Augenblick, in dem beide zugleich aus dem Weg sind. Einer nach dem anderen.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##T#######################H#.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'windmill', x: 15.5, y: 6.5, w: 6.8, gap: 1.5, speed: 0.85, blades: 4, axis: 'y', phase: 0.0, depth: 1.2, style: 'bienenstock' },
      { type: 'rotor', x: 21.5, y: 4.5, blades: 2, len: 1.3, speed: -0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
      { type: 'rotor', x: 21.5, y: 8.5, blades: 2, len: 1.3, speed: 0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 8.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Blüte und Hut', par: 4, theme: 'gewaechshaus',
    intro: 'Erst die Ranke über den Steg – sie trägt hier eine halbe Sekunde länger, der Weg ist weiter. Dann steht die Regalwand im Weg, und wieder helfen nur die Hüte. Wer beim Steg zu viel Kraft gibt, steht drüben zu weit oben und muß noch einmal ansetzen.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.....................######xx####.',
      '.############........######xx####.',
      '.#############......#######xx####.',
      '.##########################xx####.',
      '.##T#######################xx##H#.',
      '.##########################xx####.',
      '.#############......#############.',
      '.############........############.',
      '.....................############.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 5, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 10, x1: 20, y1: 9, t: 0.22, h: 0.5 },
      { type: 'ranke', x: 14, y: 6, w: 5, h: 3, dauer: 5.5, r: 0.6, bluete: { x: 9.5, y: 7.5 } },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.62, plaetze: [[24.0, 7.0], [30.0, 10.0]] },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Der Blätterwirbel', par: 3, theme: 'lehrlingsgarten',
    intro: 'Zwei Beete stehen versetzt, dazwischen geht es im Zickzack. Die Pusteblume zieht an allem, was an ihr vorbeirollt – ausgerechnet in der ersten Kehre, wo man ohnehin schon aufpassen muß. Die Sonnenblume dahinter fängt den Ball und wirft ihn immer nach unten aus; wer sie trifft, spart sich die halbe Bahn.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.#########...################.',
      '.#########...################.',
      '.##T######...################.',
      '.#########...################.',
      '.#########...######.#########.',
      '.##########.######...##xx####.',
      '.#################...##xx#H##.',
      '.#################...##xx####.',
      '.#################...########.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 18, y0: 8, x1: 19, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 8, x1: 12, y1: 9, t: 0.22, h: 0.5 },
      { type: 'magnet', x: 8.5, y: 9.5, r: 2.6, strength: 5.0, slow: 0, style: 'pollen' },
      { type: 'turntable', x: 15.5, y: 5.5, r: 1.8, speed: 1.8, exit: 90, eject: 4.5, style: 'sonnenblume' },
      { type: 'bumper', x: 22.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Lehrlingsprüfung', par: 3, theme: 'lehrlingsgarten',
    intro: 'Die Prüfung: erst die Ranke, dann zwischen dem Springkraut hindurch, dann der Bienenstand im Takt – und zum Schluß noch einmal die Hüte. Wer hier unter Par bleibt, hat den Lehrlingshut verdient.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T#############################.',
      '.##############################H#.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 10, y: 3, w: 3, h: 9, dauer: 4.2, r: 0.6, bluete: { x: 7.5, y: 7.5 } },
      { type: 'bumper', x: 14.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 14.5, y: 9.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'windmill', x: 18.5, y: 7.5, w: 7.6, gap: 1.2, speed: 0.9, blades: 4, axis: 'y', phase: 0.0, depth: 1.2, style: 'bienenstock' },
      { type: 'zauberhut', takt: 2.8, phase: 0.0, r: 0.42, plaetze: [[24.0, 5.0], [24.0, 10.0], [29.0, 11.0]] },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
];

const ZAUBER_WARTE = [
  {
    name: 'Der Aufgang', par: 3, theme: 'sternenwarte',
    intro: 'Der Mond über der Terrasse zieht, solange seine Scheibe voll ist, und stößt, solange sie dunkel ist. Beim Halbmond läßt er in Ruhe. Der Gang oben ist schmal, und unter ihm ist nichts - also: erst hinsehen, dann schlagen.',
    map: [
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##########.........#########.',
      '.##T######...........#####H##.',
      '.#########...........########.',
      '.#########...........########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 15.0, y: 4.0, r: 3.4, kraft: 9.0, takt: 7.0, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'crystal', kick: 7.5 },
      { type: 'bumper', x: 22.5, y: 4.5, r: 0.55, style: 'crystal', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Das erste Sternbild', par: 3, theme: 'sternenwarte',
    intro: 'Die drei Sterne wollen angefahren werden - alle drei, in einer Reihenfolge, die man sich vorher überlegt. Erst dann geht das Tor auf. Die Linien am Boden zeigen, was noch fehlt.',
    map: [
      '................................',
      '................................',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.##T########################H##.',
      '.##############################.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'sternbild', r: 0.5, sterne: [[6.0, 3.0], [11.0, 9.0], [16.0, 3.0]], tor: { x0: 20.0, y0: 6.0, x1: 20.0, y1: 8.0 } },
      { type: 'bumper', x: 13.5, y: 6.5, r: 0.55, style: 'orb', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Zwischen den Monden', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Monde stehen im Gegentakt: Zieht der eine, stößt der andere. Dazwischen liegen zwei Stege, die keinen Platz für Irrtümer lassen. Und am Ende schwingt das Lot des Astronomen.',
    map: [
      '..................................',
      '..................................',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.############.#########.#########.',
      '.################################.',
      '.###T#########################H##.',
      '.################################.',
      '.############.#########.#########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 12, y0: 5, x1: 13, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 5, x1: 23, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 24, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 10, x1: 13, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 10, x1: 23, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 10, x1: 24, y1: 9, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 9.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.0, core: 0.4 },
      { type: 'mondzieher', x: 19.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.5, core: 0.4 },
      { type: 'pendulum', x: 27.0, y: 4.0, len: 3.5, amp: 48, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Kartensaal', par: 4, theme: 'kartensaal',
    intro: 'Vier Sterne, vier Ecken, und mittendrin zwei Regale, die den Saal in zwei Hälften teilen. Das Tor steht vor dem Loch und geht erst auf, wenn alle vier brennen. Die Reihenfolge entscheidet, wie oft man den Saal durchqueren muß.',
    map: [
      '..............................',
      '..............................',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.############################.',
      '.##T######################H##.',
      '.############################.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'sternbild', r: 0.5, sterne: [[5.0, 4.0], [5.0, 11.0], [19.0, 4.0], [19.0, 11.0]], tor: { x0: 24.0, y0: 2.0, x1: 24.0, y1: 13.0 } },
      { type: 'pendulum', x: 13.0, y: 4.0, len: 3.2, amp: 55, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2 },
      { type: 'bumper', x: 18.5, y: 7.5, r: 0.55, style: 'orb', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Das Fernrohr', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Fernrohre suchen die Terrasse ab, und zwischen ihnen steht ein Mond, der jeden geraden Weg krumm zieht. Der Zickzack durch die Pfeiler ist der kurze Weg - wenn man ihn im richtigen Augenblick nimmt.',
    map: [
      '................................',
      '................................',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx######xx######xx#####.',
      '.##T####xx######xx######xx#####.',
      '.#######xx######xx######xx#####.',
      '.###############xx#############.',
      '.###############xx###########H#.',
      '.###############xx#############.',
      '.###############xx#############.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'eyetower', x: 12.5, y: 10.5, r: 1.1, range: 9.0, fov: 0.6, speed: 0.4, phase: 0.0 },
      { type: 'eyetower', x: 21.0, y: 4.0, r: 1.1, range: 9.0, fov: 0.6, speed: -0.36, phase: 1.6 },
      { type: 'mondzieher', x: 20.0, y: 10.5, r: 2.8, kraft: 7.0, takt: 6.5, phase: 0.3, core: 0.4 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Die Armillarsphäre', par: 4, theme: 'sternenwarte',
    intro: 'Der Messingring fährt über den Steg und nimmt mit, wer rechtzeitig darauf liegt. Dahinter wartet ein Nebelwirbel, der alles nach außen schleudert - am besten also gar nicht erst hinein.',
    map: [
      '................................',
      '................................',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......########H##.',
      '.#############.....############.',
      '.##############################.',
      '.##T###########################.',
      '.##############################.',
      '.#############.....############.',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......###########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 5, x1: 19, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 10, x1: 19, y1: 9, t: 0.22, h: 0.5 },
      { type: 'gearfield', x0: 12.5, y0: 7.5, x1: 19.5, y1: 7.5, wait: 2.2, travel: 3.0, r: 0.9, zaehne: 10, phase: 0.0 },
      { type: 'strudel', x: 24.5, y: 9.0, r: 2.8, dreh: 1 },
      { type: 'bumper', x: 9.5, y: 4.5, r: 0.55, style: 'crystal', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Der Wandelgang', par: 3, theme: 'kartensaal',
    intro: 'Das wandernde Tor läuft auf und ab, und der Mond davor zieht den Ball von der Lücke weg oder in sie hinein. Zwei Uhren, die nicht zusammenpassen - man muß sich die eine aussuchen und die andere aushalten.',
    map: [
      '..................................',
      '..................................',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wandergate', x0: 18, y0: 3, x1: 18, y1: 11, gap: 1.9 },
      { type: 'mondzieher', x: 13.0, y: 7.0, r: 3.0, kraft: 8.5, takt: 5.5, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'orb', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 9.5, r: 0.55, style: 'orb', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Hutkammer', par: 4, theme: 'kartensaal',
    intro: 'Die Hüte aus dem Garten, eine Stufe schärfer: Wo man herauskommt, steht fest - was danach mit dem Ball geschieht, entscheidet der Mond daneben. Wer den Hut im falschen Augenblick nimmt, landet dort, wo er nicht hin wollte.',
    map: [
      '................................',
      '................................',
      '.##########xx##################.',
      '.##########xx##################.',
      '.##########xx###############H##.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##T#######xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.42, plaetze: [[8.0, 4.0], [16.0, 11.0], [25.0, 9.0]] },
      { type: 'mondzieher', x: 16.0, y: 4.0, r: 3.0, kraft: 8.0, takt: 6.0, phase: 0.25, core: 0.4 },
      { type: 'pendulum', x: 25.0, y: 3.0, len: 3.0, amp: 45, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Sternenprüfung', par: 5, theme: 'sternenwarte',
    intro: 'Die Prüfung der Warte: erst die Blüte anstoßen und über die Ranke, dann am Mond vorbei - und dabei alle drei Sterne mitnehmen, denn sonst steht am Ende ein Tor, das nicht aufgeht. Der dritte liegt in der Nische hinter dem letzten Pfeiler. Wer hier unter Par bleibt, hat den Sternenhut verdient.',
    map: [
      '....................................',
      '....................................',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.###################xx##xx#########.',
      '.##################################.',
      '.##T############################H##.',
      '.##################################.',
      '.###################xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'ranke', x: 9, y: 5, w: 4, h: 5, dauer: 4.5, r: 0.6, bluete: { x: 6.5, y: 7.5 } },
      { type: 'mondzieher', x: 16.0, y: 7.0, r: 3.2, kraft: 8.5, takt: 6.5, phase: 0.15, core: 0.4 },
      { type: 'sternbild', r: 0.5, sterne: [[15.0, 3.0], [15.0, 11.0], [27.0, 3.0]], tor: { x0: 28.0, y0: 2.0, x1: 28.0, y1: 13.0 } },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
];

const ZAUBER_LOGE = [
  {
    name: 'Vor der Loge', par: 4, theme: 'erzmagierloge',
    intro: 'Der Spiegel ist der einzige Weg durch die Wand, und er wirft seitenverkehrt aus. Dahinter geht es nur unten weiter - wer also unten ankommen will, muss oben auftreffen. Sein Spiegelbild steht drueben und sagt einem vorher, wo das sein wird.',
    map: [
      '....................................',
      '....................................',
      '.#################xx######xx#######.',
      '.#################xx######xx#######.',
      '.#########################xx#######.',
      '.#########################xx#######.',
      '.#########################xx#######.',
      '.###T#####################xx#######.',
      '.#########################xx#######.',
      '.##################################.',
      '.##################################.',
      '.#################xx############H##.',
      '.#################xx###############.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'zauberspiegel', x0: 18, y0: 4, x1: 18, y1: 11 },
      { type: 'rotor', x: 23.0, y: 10.5, blades: 3, len: 1.5, speed: 1.2, thick: 0.16, style: 'crystal', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Der Spiegelsaal', par: 4, theme: 'erzmagierloge',
    intro: 'Zwei Spiegel, dazwischen ein Pfeiler, um den man herum muss. Zweimal seitenverkehrt waere wieder richtig herum - nur trifft man wegen des Pfeilers beim zweiten Mal woanders auf als beim ersten.',
    map: [
      '......................................',
      '......................................',
      '.############xx##########xx##########.',
      '.############xx##########xx######H###.',
      '.############xx##########xx##########.',
      '.####################################.',
      '.##################xx################.',
      '.##################xx################.',
      '.###T##############xx################.',
      '.##################xx################.',
      '.####################################.',
      '.####################################.',
      '.############xx##########xx##########.',
      '.############xx##########xx##########.',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'zauberspiegel', x0: 13, y0: 5, x1: 13, y1: 12 },
      { type: 'zauberspiegel', x0: 26, y0: 5, x1: 26, y1: 12 },
      { type: 'bumper', x: 31.5, y: 10.5, r: 0.55, style: 'crystal', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Das Bannmal', par: 5, theme: 'bannkreis',
    intro: 'In der Gruft sieht man nur, was im Licht der Lampen steht. Vier Sterne liegen in drei Kammern verteilt, und erst wenn alle brennen, geht das Bannmal vor dem Loch auf. Wer beim Hinweg nicht hinsieht, sucht sie beim Rueckweg.',
    map: [
      '....................................',
      '....................................',
      '.############xx####################.',
      '.############xx####################.',
      '.############xx####################.',
      '.############xx####################.',
      '.############xx####################.',
      '.############xx####################.',
      '.#####################xx###########.',
      '.#####################xx###########.',
      '.###T#################xx########H##.',
      '.#####################xx###########.',
      '.#####################xx###########.',
      '.#####################xx###########.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'sternbild', r: 0.5, sterne: [[5.0, 4.0], [5.0, 12.0], [18.0, 11.0], [26.0, 4.0]], tor: { x0: 28.0, y0: 2.0, x1: 28.0, y1: 14.0 } },
      { type: 'grubenlampe', x: 6.5, y: 8.5, r: 4.4 },
      { type: 'grubenlampe', x: 18.5, y: 8.5, r: 4.4 },
      { type: 'grubenlampe', x: 30.5, y: 9.5, r: 4.0 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Rat der Neun', par: 5, theme: 'erzmagierloge',
    intro: 'Vier Hueten leuchtet reihum einer, und der Takt ist schnell. Mitten zwischen ihnen steht ein Mond, der zieht und stoesst - wer im falschen Augenblick in den Hut rollt, kommt richtig heraus und landet trotzdem falsch. Am Ende schwingt das Lot des Astronomen.',
    map: [
      '........................................',
      '........................................',
      '.##############xx##########xx##########.',
      '.##############xx##########xx##########.',
      '.##############xx##########xx#######H##.',
      '.##############xx##########xx##########.',
      '.##########################xx##########.',
      '.##########################xx##########.',
      '.###T######################xx##########.',
      '.##########################xx##########.',
      '.##############xx######################.',
      '.##############xx######################.',
      '.##############xx######################.',
      '.##############xx######################.',
      '........................................',
      '........................................',
    ],
    obstacles: [
      { type: 'zauberhut', takt: 2.2, phase: 0.0, r: 0.42, plaetze: [[9.0, 4.0], [9.0, 12.0], [22.0, 4.0], [22.0, 12.0]] },
      { type: 'mondzieher', x: 21.0, y: 7.5, r: 3.2, kraft: 9.0, takt: 5.5, phase: 0.2, core: 0.4 },
      { type: 'pendulum', x: 33.0, y: 4.0, len: 3.4, amp: 52, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Die Ranken der Gruft', par: 4, theme: 'bannkreis',
    intro: 'Zwei Luecken, dazwischen ein Spiegel, und ueber allem die Dunkelheit der Gruft. Jede Bluete startet ihre eigene Uhr - und der Spiegel wirft einen seitenverkehrt aus, also gerade nicht dorthin, wo man beim Schlagen hingesehen hat.',
    map: [
      '......................................',
      '......................................',
      '.#########xxxx#######xx####xxxx######.',
      '.#########xxxx#######xx####xxxx######.',
      '.#########xxxx#######xx####xxxx######.',
      '.#########xxxx#############xxxx######.',
      '.##########################xxxx######.',
      '.####################################.',
      '.###T#############################H##.',
      '.####################################.',
      '.####################################.',
      '.#########xxxx#############xxxx######.',
      '.#########xxxx#######xx####xxxx######.',
      '.#########xxxx#######xx####xxxx######.',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'ranke', x: 10, y: 6, w: 4, h: 5, dauer: 4.5, r: 0.6, bluete: { x: 8.5, y: 7.0 } },
      { type: 'zauberspiegel', x0: 21, y0: 5, x1: 21, y1: 12 },
      { type: 'ranke', x: 27, y: 7, w: 4, h: 4, dauer: 4.5, r: 0.6, bluete: { x: 25.5, y: 9.5 } },
      { type: 'grubenlampe', x: 8.5, y: 7.0, r: 4.4 },
      { type: 'grubenlampe', x: 25.5, y: 9.5, r: 4.4 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Der Blitzgang', par: 5, theme: 'erzmagierloge',
    intro: 'Zwei Blitze schlagen im Wechsel in den mittleren Gang, und der Aufwind hebt einen ueber den ersten hinweg. Dahinter steht ein Spiegel - der wirft einen zwar auf die richtige Seite, aber nur, wenn man an der richtigen Stelle ankommt.',
    map: [
      '......................................',
      '......................................',
      '.###########xx################xx#####.',
      '.###########xx################xx#####.',
      '.###########xx#######################.',
      '.###T#######xx#######################.',
      '.###########xx#######################.',
      '.###########xx#######################.',
      '.###########xx#######################.',
      '.#######################xx###########.',
      '.#######################xx###########.',
      '.#######################xx###########.',
      '.#######################xx####xx##H##.',
      '.#######################xx####xx#####.',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'updraft', x: 7, y: 9, w: 2, h: 3, minSpeed: 2.5, land: 6.5, fly: 7.0 },
      { type: 'lightning', x: 17.0, y: 5.5, w: 2.0, h: 6.0, period: 4.0, phase: 0.0, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 20.5, y: 10.0, w: 2.0, h: 6.0, period: 4.0, phase: 0.5, warn: 1.0, strike: 0.35 },
      { type: 'zauberspiegel', x0: 30, y0: 4, x1: 30, y1: 12 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Das Wanderloch', par: 5, theme: 'bannkreis',
    intro: 'Das Loch bleibt nicht, wo es ist - es wandert zwischen drei Stellen. Und der Mond davor zieht den Ball genau dann, wenn man ihn gerade nicht ziehen lassen will. In der Dunkelheit sieht man immer nur die Stelle, die gerade im Licht liegt.',
    map: [
      '....................................',
      '....................................',
      '.#########xx#######################.',
      '.#########xx#######################.',
      '.#########xx###################H###.',
      '.#########xx#######################.',
      '.#########xx##########xx###########.',
      '.#########xx##########xx###########.',
      '.#########xx##########xx###########.',
      '.#########xx##########xx###########.',
      '.#####################xx###########.',
      '.###T#################xx###########.',
      '.#####################xx###########.',
      '.#####################xx###########.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'wanderloch', stellen: [[31.5, 4.5], [31.5, 8.5], [31.5, 12.5]], phase: 0.0 },
      { type: 'mondzieher', x: 26.0, y: 8.5, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.35, core: 0.4 },
      { type: 'grubenlampe', x: 6.5, y: 11.5, r: 4.0 },
      { type: 'grubenlampe', x: 17.5, y: 4.5, r: 4.4 },
      { type: 'grubenlampe', x: 30.5, y: 8.5, r: 5.0 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Kammer der Spiegel', par: 5, theme: 'erzmagierloge',
    intro: 'Zwei Spiegel, vier Sterne und ein Bannmal vor dem Loch. An zwei der Sterne kommt man nur durch einen Spiegel heran, und es ist nicht derselbe - man muss sich vorher ueberlegen, welchen man wofuer nimmt.',
    map: [
      '........................................',
      '........................................',
      '.###########xx###########xx############.',
      '.###########xx###########xx############.',
      '.###########xx###########xx############.',
      '.######################################.',
      '.######################################.',
      '.#################xx###################.',
      '.###T#############xx################H##.',
      '.#################xx###################.',
      '.#################xx###################.',
      '.######################################.',
      '.######################################.',
      '.###########xx###########xx############.',
      '.###########xx###########xx############.',
      '........................................',
      '........................................',
    ],
    obstacles: [
      { type: 'zauberspiegel', x0: 12, y0: 5, x1: 12, y1: 13 },
      { type: 'zauberspiegel', x0: 26, y0: 5, x1: 26, y1: 13 },
      { type: 'sternbild', r: 0.5, sterne: [[6.0, 3.0], [6.0, 13.0], [22.0, 3.0], [30.0, 13.0]], tor: { x0: 32.0, y0: 2.0, x1: 32.0, y1: 15.0 } },
      { type: 'bumper', x: 29.5, y: 6.5, r: 0.55, style: 'crystal', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Der Erzmagier', par: 6, theme: 'erzmagierloge',
    intro: 'Die Pruefung der Loge: die Bluete anstossen, durch den Spiegel, in den richtigen Hut, am Mond vorbei - und dabei die drei Sterne mitnehmen, denn sonst steht am Ende ein Bannmal, das nicht aufgeht. Wer hier unter Par bleibt, hat ausgelernt.',
    map: [
      '............................................',
      '............................................',
      '.########xxxx#####xx########xx#############.',
      '.########xxxx#####xx########xx#############.',
      '.########xxxx#####xx########xx#############.',
      '.########xxxx###############xx#############.',
      '.###########################xx#############.',
      '.###########################xx#############.',
      '.###T#######################xx#############.',
      '.#######################################H##.',
      '.##########################################.',
      '.##########################################.',
      '.########xxxx##############################.',
      '.########xxxx##############################.',
      '.########xxxx#####xx#######################.',
      '.########xxxx#####xx#######################.',
      '............................................',
      '............................................',
    ],
    obstacles: [
      { type: 'ranke', x: 9, y: 6, w: 4, h: 6, dauer: 4.5, r: 0.6, bluete: { x: 7.5, y: 8.5 } },
      { type: 'zauberspiegel', x0: 18, y0: 5, x1: 18, y1: 14 },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.42, plaetze: [[23.0, 4.0], [23.0, 13.0], [34.0, 4.0]] },
      { type: 'mondzieher', x: 33.0, y: 10.0, r: 3.2, kraft: 8.5, takt: 5.5, phase: 0.1, core: 0.4 },
      { type: 'sternbild', r: 0.5, sterne: [[15.0, 8.0], [24.0, 9.0], [33.0, 4.0]], tor: { x0: 37.0, y0: 2.0, x1: 37.0, y1: 16.0 } },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
];
