/* Die Flut (Weltkennung 'flut'): die versunkene Stadt.
   Erzeugt von tools/flut.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

   NOCH NICHT FERTIG. Zurzeit stehen hier zwei Probebahnen, an denen die Maschinen angesehen und
   gespielt werden können, bevor neun Bahnen darauf gebaut werden. Die Welt trägt darum in
   src/courses_pro.js die Kennzeichnung 'nurVorschau'; im Spiel taucht sie nicht auf.

   DAS FLUTBECKEN ist ein Hindernis wie das Wandertor oder die Falltür: Es läuft im Takt von außen
   nach innen voll und wieder leer, und solange es leer ist, geht der Weg hindurch. Ringsum bleibt
   die Bahn trocken und immer spielbar – **es gibt auf jeder Bahn einen Weg, der auch bei vollem
   Becken zum Loch führt** (tools/flut.py prüft das). Das Becken ist die Abkürzung, nicht die
   einzige Möglichkeit; warten muß man nie.

   Zuerst war die Flut eine Weltregel und stieg über die ganze Bahn. Das war gut gedacht und
   schlecht zu spielen: Wer den Augenblick verpaßte, konnte nur zusehen. Siehe src/obstacles_flut.js.

   Kartenlegende wie in courses.js: '#' Boden, '.' offenes Wasser, 'x' Block, 's' Schlick (bremst),
   'T' Abschlag, 'H' Loch. */
const FLUT_COURSES = [
  {
    name: 'Die Hafenmole', par: 4, theme: 'wasserlinie', tiefe: 0.12,
    intro: 'Ein Hafenbecken mit Kaimauern ringsum – hier geht nichts ins Meer, hier wird über die Bande gespielt. Nach oben führt eine einzige Durchfahrt, und der Kranfuß deckt das Loch. Läuft die Schleuse voll, nimmt man die Mole außen herum.',
    autoDecor: { density: 0.22, seed: 17 },
    schwebDecor: { density: 0.055, seed: 24 },
    map: [
      '......................................',
      '......................................',
      '......................................',
      '......................................',
      '........................##########....',
      '........................##########....',
      '........................##########....',
      '........................######xx##....',
      '........................######xx#H....',
      '........................######xx##....',
      '........................##########....',
      '...........................###........',
      '...#########xx####################....',
      '...#########xx####################....',
      '...###############################....',
      '...##T############################....',
      '...###############################....',
      '.......###...........###..............',
      '.......###...........###..............',
      '.......#################..............',
      '.......#################..............',
      '....................................w.',
      '......................................',
    ],
    obstacles: [
      { type: 'flut', x: 15.5, y: 14.5, w: 3, h: 5, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Der Priel', par: 4, theme: 'wasserlinie', tiefe: 0.2,
    intro: 'Vier Kehren, alle gemauert – hier kommt man nur über die Bande vorwärts. Gleich hinter dem Abschlag geht es gerade hinunter: die Abkürzung. In ihr steht ein Becken, und wenn das vollsteht, schlängelt man den ganzen Priel entlang.',
    autoDecor: { density: 0.22, seed: 29 },
    schwebDecor: { density: 0.055, seed: 36 },
    map: [
      '............................................',
      '............................................',
      '............................................',
      '...##################.......................',
      '...#T#################......................',
      '...###################......................',
      '.....###...........###......#############...',
      '.....###...........###......#############...',
      '.....###...###########......#############...',
      '.....###..############......#######xx####...',
      '.....###..###########.......#######xx####...',
      '.....###..###...............##########H##...',
      '.....###..###...............#############...',
      '.....###..###...................###.........',
      '.....##############################.........',
      '.....##############################.........',
      '......############################..........',
      '............................................',
      '............................................',
      '..........................................w.',
      '............................................',
    ],
    obstacles: [
      { type: 'pumpwerk', x: 7.5, y: 5.5, r: 0.8, dauer: 4 },
      { type: 'flut', x: 6.5, y: 10.5, w: 3, h: 5, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Buhnen', par: 4, theme: 'wasserlinie', tiefe: 0.28,
    intro: 'Ein breiter Steg im offenen Wasser – hier gibt es keinen Rand, der einen aufhält. Dafür stehen Buhnenpfähle darauf, an denen man den Winkel doch bekommt. Und zwischen ihnen drückt das Wasser zurück.',
    autoDecor: { density: 0.22, seed: 43 },
    schwebDecor: { density: 0.055, seed: 50 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww###########x############x#############ww.',
      '.ww###########x############x#############ww.',
      '.ww##T################################H##ww.',
      '.ww#################x####################ww.',
      '.ww#################x####################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 21.5, y: 10.5, w: 9, h: 3, angle: 180, tempo: 4.6 },
      { type: 'wracktor', x: 32.5, y: 8.15, len: 2.8, zuWinkel: 90, takt: 6.0, gegen: true },
    ],
  },
  {
    name: 'Der Kessel', par: 4, theme: 'flachwasser', tiefe: 0.36,
    intro: 'Ein runder Kessel, ganz aus Mauer, mit sechs Pfeilern darin. In der Mitte dreht sich das Wasser und schleudert nach außen – und außen ist die Bande, die zurückwirft. Vor dem Loch liegt ein Riegel: geradeaus geht es nicht.',
    autoDecor: { density: 0.22, seed: 59 },
    schwebDecor: { density: 0.055, seed: 66 },
    map: [
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '.........##########xx##########.........',
      '......#############xx#############......',
      '....#########xx###########xx########....',
      '...##########xx###########xx###xx####...',
      '...############################xx#H##...',
      '....###########################xx###....',
      '......############################......',
      '.........######################.........',
      '...##################################...',
      '...##########xx###########xx#########...',
      '....##T######xx###########xx########....',
      '......#############xx#############......',
      '.........##########xx##########.........',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '......................................w.',
      '........................................',
    ],
    obstacles: [
      { type: 'strudel', x: 19.5, y: 10.0, r: 3.4, dreh: 1 },
    ],
  },
  {
    name: 'Der Seegraswald', par: 5, theme: 'flachwasser', tiefe: 0.44,
    intro: 'Drei Gassen im Zickzack, alle gemauert. Hier zählt der Winkel mehr als die Kraft – und in der mittleren steht ein Tangfeld, das den Schwung frißt.',
    autoDecor: { density: 0.22, seed: 71 },
    schwebDecor: { density: 0.055, seed: 78 },
    map: [
      '..........................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.w..............................wwwwwwwww.',
      '.w.#################x##########..wwwwwwww.',
      '.w.#T###########################.wwwwwwww.',
      '.w.#################x###########.wwwwwwww.',
      '.w...........................###.wwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwww.###.wwwwwwww.',
      '.wwwwwwww....................###.wwwwwwww.',
      '.wwwwwww..########x#############.wwwwwwww.',
      '.wwwwwww.#######################.wwwwwwww.',
      '.wwwwwww.#########x############..wwwwwwww.',
      '.wwwwwww.###....................wwwwwwwww.',
      '.wwwwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwww.###..........................www.',
      '.wwwwwww.############################.www.',
      '.wwwwwww.##########################H#.www.',
      '.wwwwwww..###########################.www.',
      '.wwwwwwww.............................www.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..........................................',
    ],
    obstacles: [
      { type: 'tangwald', x: 25.5, y: 11.5, w: 3, h: 5, takt: 3.4 },
    ],
  },
  {
    name: 'Die Austernbank', par: 4, theme: 'flachwasser', tiefe: 0.52,
    intro: 'Zwei gemauerte Kammern, in jeder eine Riesenmuschel. Geschlossen ist sie ein Klotz, an dem man abprallt; offen ein Maul, das einen packt und weiterspuckt. Beide Kammern führen zum Ausgang – aber nicht gleich schnell.',
    autoDecor: { density: 0.22, seed: 89 },
    schwebDecor: { density: 0.055, seed: 96 },
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '............###############...............',
      '............###############...............',
      '............###############...............',
      '..........w.###############...............',
      '.........w..###############...............',
      '...........################...............',
      '...###########............#############...',
      '...##T########..........w.##########H##...',
      '...###########............#############...',
      '...........################...............',
      '............###############...............',
      '............###############...............',
      '............###############...............',
      '............###############...............',
      '............###############...............',
      '..........................................',
      '..........................................',
      '........................................w.',
      '..........................................',
    ],
    obstacles: [
      { type: 'muschel', x: 19.5, y: 6.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45 },
      { type: 'muschel', x: 19.5, y: 15.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45, phase: 0.5 },
    ],
  },
  {
    name: 'Die Kanalisation', par: 4, theme: 'daemmerzone', tiefe: 0.6,
    intro: 'Vier Pfeiler stehen im Platz, und über dem Brunnen dreht sich das Wasser. In der Ecke liegt ein Abflußgitter: Man spielt nicht hinein, man landet darin – und die Leitung setzt einen hinter dem Platz wieder ab.',
    autoDecor: { density: 0.22, seed: 101 },
    schwebDecor: { density: 0.055, seed: 108 },
    map: [
      '............................................',
      '............................................',
      '............................................',
      '............w...............................',
      '..............#################.............',
      '...############################.............',
      '...##T#########################.............',
      '...###############xx#####xx####.............',
      '..............####xx#####xx####.............',
      '..............#################.............',
      '..............#################.............',
      '..............#################.............',
      '..............#################.............',
      '..............#################.............',
      '..............####xx#####xx####.............',
      '..............####xx#####xx##############...',
      '..............####################a###H##...',
      '..............##A########################...',
      '..............#################.............',
      '............................................',
      '............................................',
      '..........................................w.',
      '............................................',
    ],
    obstacles: [
      { type: 'strudel', x: 22.0, y: 11.0, r: 3.4, dreh: -1 },
      { type: 'abflussrohr', pair: 'A', angle: 0 },
    ],
  },
  {
    name: 'Die Kaimauer', par: 5, theme: 'daemmerzone', tiefe: 0.68,
    intro: 'Unten hin, oben zurück. Der untere Steg liegt im offenen Wasser – dort hält einen nichts. Der obere hat die Kaimauer im Rücken, dort kann man über die Bande spielen. Über beiden schwingt ein Anker.',
    autoDecor: { density: 0.22, seed: 113 },
    schwebDecor: { density: 0.055, seed: 120 },
    map: [
      '............................................',
      '............................................',
      '............................................',
      '............................................',
      '...######################################...',
      '...##################################H###...',
      '...#######################################..',
      '...#######################################..',
      '...#######################################..',
      '...####...............................####..',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww#######################################w.',
      '.ww#######################################w.',
      '.ww###T###################################w.',
      '.ww######################################ww.',
      '.ww######################################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'ankerkette', x: 20.5, y: 12.5, len: 5.0, amp: 48, ruhe: 90, takt: 5.2 },
      { type: 'ankerkette', x: 30.5, y: 11.5, len: 5.0, amp: 48, ruhe: 270, takt: 5.2, phase: 0.5 },
      { type: 'wracktor', x: 12.5, y: 15.15, len: 2.8, zuWinkel: 90, takt: 6.0, gegen: true },
    ],
  },
  {
    name: 'Der Marktplatz', par: 5, theme: 'daemmerzone', tiefe: 0.76,
    intro: 'Sechs Häuserecken stehen auf dem Platz – hier prallt man von allem ab, und genau so kommt man weiter. Über dem Brunnen dreht sich das Wasser, in der Ecke liegt das Abflußgitter, und am Ausgang schwingt der Anker.',
    autoDecor: { density: 0.22, seed: 131 },
    schwebDecor: { density: 0.055, seed: 138 },
    map: [
      '..............................................',
      '..............................................',
      '..............................................',
      '..........w...................................',
      '............#######################...........',
      '...################################...........',
      '...##T##################xx#########...........',
      '...#####################xx#########...........',
      '............#####xx###########xx###...........',
      '............#####xx###########xx###...........',
      '............#######################...........',
      '............########ssss###########...........',
      '............########ssss###########...........',
      '............########ssss###########...........',
      '............#####xx###########xx###.........w.',
      '............#####xx###########xx###...........',
      '............############xx##################..',
      '............############xx############b##H##..',
      '............##B#############################..',
      '............#######################...........',
      '..............................................',
      '............................................w.',
      '..............................................',
    ],
    obstacles: [
      { type: 'strudel', x: 21.5, y: 12.0, r: 2.8, dreh: -1 },
      { type: 'abflussrohr', pair: 'B', angle: 0 },
      { type: 'ankerkette', x: 38.5, y: 13.5, len: 4.0, amp: 48, ruhe: 90, takt: 5.2 },
    ],
  },
  {
    name: 'Die Schlotebene', par: 4, theme: 'meeresgrund', tiefe: 0.84,
    intro: 'Unten der offene Steg, oben die gemauerte Ebene mit dem Loch. Der lange Weg führt ganz links hinauf – der kurze über den Schlot, der einen hochwirft. Er wirft auch einen Ball, der nur daliegt.',
    autoDecor: { density: 0.22, seed: 149 },
    schwebDecor: { density: 0.055, seed: 156 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww.................................www.',
      '.wwwwww.###############################.www.',
      '.wwwwww.###############################.www.',
      '.wwwwww.###########################H###.www.',
      '.wwwww..###############################.www.',
      '.wwwww.################################.www.',
      '.wwwww.###..............................www.',
      '.wwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwww.###.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.ww##T#########################wwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'raucher', x: 26.5, y: 17.5, r: 1.0, angle: 270, weite: 11.0, takt: 4.6 },
      { type: 'tangwald', x: 31.5, y: 6.5, w: 3, h: 5, takt: 3.4 },
    ],
  },
  {
    name: 'Das Kaltwasserfeld', par: 5, theme: 'meeresgrund', tiefe: 0.92,
    intro: 'Zwei Stege im offenen Wasser, auf beiden zieht es – oben nach rechts, unten nach links, und beide als Dünung: Sie kommt und geht. Hier gibt es keine Bande, die einen hält. Stehenbleiben geht nirgends.',
    autoDecor: { density: 0.22, seed: 163 },
    schwebDecor: { density: 0.055, seed: 170 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########################################ww.',
      '.ww#####################################H##ww.',
      '.ww########################################ww.',
      '.ww########################################ww.',
      '.wwwwwwwwwwwwwwwwwwwww####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww####wwwwwwwwwwwwwwwwwww.',
      '.ww########################################ww.',
      '.ww##T#####################################ww.',
      '.ww########################################ww.',
      '.ww########################################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 15.0, y: 7.5, w: 10, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 0.0 },
      { type: 'stroemung', x: 32.0, y: 7.5, w: 10, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 1.6 },
      { type: 'stroemung', x: 15.0, y: 16.5, w: 10, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 3.14 },
      { type: 'stroemung', x: 32.0, y: 16.5, w: 10, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 4.7 },
      { type: 'strudel', x: 23.5, y: 11.5, r: 2.6, dreh: 1 },
      { type: 'muschel', x: 23.5, y: 6.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45, phase: 0.3 },
    ],
  },
  {
    name: 'Der Schlund', par: 5, theme: 'meeresgrund', tiefe: 1.0,
    intro: 'Das Ende. Zwei Äste – der kurze läuft durch ein Becken, der lange tiefer herum –, und beide münden in die große Halle: zwei Pfeiler, ein Strudel – und ein Anglerfisch, der seine Bahn zieht. Wen seine Laterne erreicht, der spielt den letzten Schlag noch einmal.',
    autoDecor: { density: 0.22, seed: 181 },
    schwebDecor: { density: 0.055, seed: 188 },
    map: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '.........w......................................',
      '...........##########...........................',
      '..........############..........................',
      '..........############..........................',
      '..........###......##################...........',
      '........w.###.......#################.........w.',
      '..........###.......#####xx##########...........',
      '...##########.......#####xx###################..',
      '...##T#######.......#######################H##..',
      '...##########.......##########################..',
      '..........###.......###########xx####...........',
      '..........###.....w.###########xx####...........',
      '..........###.......#################...........',
      '..........###....w.##################...........',
      '..........###......###..........................',
      '..........############..........................',
      '..........############..........................',
      '...........##########...........................',
      '................................................',
      '..............................................w.',
      '................................................',
    ],
    obstacles: [
      { type: 'flut', x: 16.5, y: 6.5, w: 5, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'strudel', x: 28.0, y: 12.5, r: 2.6, dreh: -1 },
      { type: 'angler', x0: 22.5, y0: 12.5, x1: 34.5, y1: 12.5, tempo: 2.2 },
      { type: 'raucher', x: 38.5, y: 12.5, r: 1.0, angle: 0, weite: 5.0, takt: 5.2 },
      { type: 'pumpwerk', x: 7.0, y: 12.5, r: 0.8, dauer: 4 },
    ],
  },
];
