/* Kolosseum: die Arena – zwölf Turnierbahnen, aufsteigend von einfach nach schwer.

   Bahn 1 bis 4 führen je ein bis zwei Hindernisarten ein, 5 bis 8 mischen sie, 9 und 10 kombinieren
   alles, und 11 und 12 sind die grossen Schlussbahnen mit langem Weg zum Ass: auf Bahn 11 steht als
   einziger der Feuerturm, auf Bahn 12 als einzige die Kaiserloge.

   Zwei Hindernisse werden bewusst spät eingeführt und stehen nicht auf jeder Bahn: die Löwenpforte
   (Löwentor) ab Bahn 4, das gleitende Gitter (wanderndes Tor) ab Bahn 5.

   Die Löwentore werden nicht über Koordinaten gesetzt, sondern als Buchstaben in die Karte gemalt:
   Der Grossbuchstabe ist der Eingang, der gleiche Kleinbuchstabe der Ausgang (A/a, B/b, C/c). In der
   Hindernisliste steht je Paar nur, in welche Richtung der Ausgang ausspuckt ('angle' in Grad).
   Geschluckt wird nur, wer Schwung hat – sonst prallt der Ball am Tor ab wie an einer Wand.

   Die Karten dieser Datei entstehen mit einem Hilfsskript aus Rechtecken (siehe README): So bleiben
   alle Zeilen gleich lang, und eine Änderung an einer Kammer zieht nicht Dutzende Zeichen nach sich.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. */
const COLOSSEUM_COURSES = [
  {
    name: 'Gladiatorengasse', par: 2, theme: 'colosseum', maxStrokes: 10,
    intro: 'Der Einzug in die Arena. Zwei Gladiatoren schreiten quer über den Sand – zwischen ihnen muss der Ball hindurch. Sonst steht nichts im Weg.',
    map: [
      '........................',
      '........................',
      '..####################..',
      '..####################..',
      '..#T################H#..',
      '..####################..',
      '..####################..',
      '........................',
      '........................',
    ],
    obstacles: [
      { type: 'mover', x0: 9.5, y0: 2.5, x1: 9.5, y1: 6.5, w: 0.8, h: 0.8, period: 4.2, style: 'gladiator' },
      { type: 'mover', x0: 15.5, y0: 6.5, x1: 15.5, y1: 2.5, w: 0.8, h: 0.8, period: 5.0, phase: 0.35, style: 'gladiator' },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 4.5, s: 1.2 },
      { t: 'bannerRed', x: 22.6, y: 4.5, s: 1.2 },
      { t: 'pillarLight', x: 6.5, y: 0.6, s: 1.2 },
      { t: 'pillarLight', x: 17.5, y: 0.6, s: 1.2 },
      { t: 'urn', x: 8.5, y: 7.5, s: 1.1 },
      { t: 'urn', x: 15.5, y: 7.5, s: 1.1 },
    ],
    autoDecor: { density: 0.12, seed: 801 },
  },
  {
    name: 'Sprungpodest', par: 3, theme: 'colosseum', maxStrokes: 10,
    intro: 'Drei Podeste, dazwischen nichts als Luft. Zwei Sprungschanzen tragen über die Lücken – wer zu zaghaft anläuft, kommt nicht hinüber.',
    map: [
      '............................',
      '............................',
      '............................',
      '..#######...######...#####..',
      '..#T#####...######...###H#..',
      '..#######...######...#####..',
      '............................',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'ramp', x: 6, y: 3, w: 2, h: 3, angle: 0, minSpeed: 3, speed: 6.5, land: 5.0 },
      { type: 'ramp', x: 15, y: 3, w: 2, h: 3, angle: 0, minSpeed: 3, speed: 6.5, land: 5.0 },
    ],
    decor: [
      { t: 'pillarLight', x: 10.0, y: 1.4, s: 1.3 },
      { t: 'pillarLight', x: 19.0, y: 1.4, s: 1.3 },
      { t: 'bannerRed', x: 1.2, y: 4.5, s: 1.2 },
      { t: 'bannerRed', x: 26.6, y: 4.5, s: 1.2 },
      { t: 'obelisk', x: 10.0, y: 7.0, s: 1.3 },
      { t: 'obelisk', x: 19.0, y: 7.0, s: 1.3 },
    ],
    autoDecor: { density: 0.12, seed: 802 },
  },
  {
    name: 'Mahlsteine', par: 3, theme: 'colosseum', maxStrokes: 10,
    intro: 'Zwei steinerne Mahlräder drehen sich mitten im Sand. Sie schlagen den Ball fort, wenn man ihnen zu nah kommt – und geben zwischen den Armen den Weg frei.',
    map: [
      '........................',
      '........................',
      '..####################..',
      '..####################..',
      '..####################..',
      '..#T################H#..',
      '..####################..',
      '..####################..',
      '..####################..',
      '........................',
      '........................',
    ],
    obstacles: [
      { type: 'rotor', x: 8.5, y: 5.5, blades: 3, len: 1.9, speed: 1.4, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 15.5, y: 5.5, blades: 3, len: 1.9, speed: -1.7, phase: 0.7, style: 'stone', height: 0.6 },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 5.5, s: 1.2 },
      { t: 'bannerRed', x: 22.6, y: 5.5, s: 1.2 },
      { t: 'pillarLight', x: 12.0, y: 0.6, s: 1.3 },
      { t: 'pillarLight', x: 12.0, y: 9.4, s: 1.3 },
      { t: 'urn', x: 5.5, y: 9.4, s: 1.1 },
      { t: 'urn', x: 18.5, y: 9.4, s: 1.1 },
    ],
    autoDecor: { density: 0.12, seed: 803 },
  },
  {
    name: 'Löwenpforte', par: 3, theme: 'colosseum', maxStrokes: 12,
    intro: 'Zwei Gassen, dazwischen die Arenamauer. Nur die Löwenpforte führt hinüber – und sie schluckt nur einen Ball mit Schwung. Zu zaghaft geschlagen, und der Löwe lässt ihn abprallen.',
    map: [
      '........................',
      '..####################..',
      '.a##################H#..',
      '..####################..',
      '........................',
      '..#############.........',
      '..#T###########A........',
      '..#############.........',
      '........................',
    ],
    obstacles: [
      { type: 'liongate', pair: 'A', angle: 0 },
      { type: 'mover', x0: 13.5, y0: 1.5, x1: 13.5, y1: 3.5, w: 0.8, h: 0.8, period: 4.0, style: 'gladiator' },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 6.5, s: 1.2 },
      { t: 'bannerRed', x: 22.6, y: 2.5, s: 1.2 },
      { t: 'pillarLight', x: 18.0, y: 5.0, s: 1.3 },
      { t: 'pillarLight', x: 20.5, y: 6.5, s: 1.3 },
      { t: 'brazier', x: 16.5, y: 4.2, s: 1.0 },
      { t: 'urn', x: 8.5, y: 8.4, s: 1.1 },
    ],
    autoDecor: { density: 0.11, seed: 804 },
  },
  {
    name: 'Gleitendes Gitter', par: 3, theme: 'colosseum', maxStrokes: 14,
    intro: 'Quer durch die Arena läuft ein Gitter mit einem einzigen Durchlass – und der gleitet langsam hin und her. Dahinter mahlen zwei Steinräder. Erst den Spalt abpassen, dann durch.',
    map: [
      '............................',
      '............................',
      '............................',
      '..########################..',
      '..########################..',
      '..########################..',
      '..#T####################H#..',
      '..########################..',
      '..########################..',
      '..########################..',
      '............................',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'wandergate', x0: 14, y0: 3, x1: 14, y1: 10, gap: 2.0 },
      { type: 'rotor', x: 8.5, y: 6.5, blades: 3, len: 1.7, speed: 1.5, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 20.5, y: 6.5, blades: 3, len: 1.7, speed: -1.5, phase: 0.5, style: 'stone', height: 0.6 },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 6.5, s: 1.2 },
      { t: 'bannerRed', x: 26.6, y: 6.5, s: 1.2 },
      { t: 'pillarLight', x: 14.0, y: 1.4, s: 1.3 },
      { t: 'pillarLight', x: 14.0, y: 11.4, s: 1.3 },
      { t: 'urn', x: 6.5, y: 11.4, s: 1.1 },
      { t: 'urn', x: 21.5, y: 11.4, s: 1.1 },
      { t: 'brazier', x: 14.0, y: 10.6, s: 1.0 },
    ],
    autoDecor: { density: 0.11, seed: 805 },
  },
  {
    name: 'Wagenrennen', par: 3, theme: 'colosseum', maxStrokes: 14,
    intro: 'Der Streitwagen pendelt in seinen Rillen über den Graben und nimmt mit, wer rechtzeitig aufspringt. Wer die Fahrt verpasst, liegt im Sand. Am Ende hilft nur noch die Schanze.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..#########.....######..####..',
      '..#########.....######..####..',
      '..#T#######.....######..##H#..',
      '..#########.....######..####..',
      '..#########.....######..####..',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'rail', y: 5.5, x0: 10, x1: 17 },
      { type: 'ferry', x0: 10.5, y0: 5.5, x1: 16.5, y1: 5.5, w: 1.4, h: 1.0, wait: 1.6, travel: 2.6, style: 'chariot' },
      { type: 'ramp', x: 19, y: 3, w: 2, h: 5, angle: 0, minSpeed: 3, speed: 6.0, land: 3.5 },
    ],
    decor: [
      { t: 'pillarLight', x: 13.0, y: 1.4, s: 1.3 },
      { t: 'pillarLight', x: 13.0, y: 8.6, s: 1.3 },
      { t: 'bannerRed', x: 1.2, y: 5.5, s: 1.2 },
      { t: 'bannerRed', x: 28.6, y: 5.5, s: 1.2 },
      { t: 'obelisk', x: 22.5, y: 1.4, s: 1.3 },
      { t: 'urn', x: 22.5, y: 8.6, s: 1.1 },
    ],
    autoDecor: { density: 0.11, seed: 806 },
  },
  {
    name: 'Katapultbahn', par: 3, theme: 'colosseum', maxStrokes: 14,
    intro: 'Vom Sand der unteren Kammer geht es nur mit dem Katapult hinauf. Es schwenkt langsam – wer im richtigen Moment geladen wird, fliegt in die obere Kammer. Dort warten die Wachen.',
    map: [
      '............................',
      '............................',
      '...............###########..',
      '...............###########..',
      '...............#########H#..',
      '...............###########..',
      '...............###########..',
      '............................',
      '............................',
      '..###########...............',
      '..###########...............',
      '..#T#########...............',
      '..###########...............',
      '............................',
    ],
    obstacles: [
      { type: 'cannon', style: 'catapult', x: 11.5, y: 10.5, base: -0.951, amp: 0.16, speed: 0.8, range: 7.7, catchR: 0.65, loadTime: 0.8 },
      { type: 'mover', x0: 17.5, y0: 2.5, x1: 17.5, y1: 6.5, w: 0.8, h: 0.8, period: 4.4, style: 'gladiator' },
      { type: 'mover', x0: 22.5, y0: 6.5, x1: 22.5, y1: 2.5, w: 0.8, h: 0.8, period: 5.2, phase: 0.4, style: 'gladiator' },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 10.5, s: 1.2 },
      { t: 'bannerRed', x: 26.6, y: 4.5, s: 1.2 },
      { t: 'pillarLight', x: 14.0, y: 8.0, s: 1.3 },
      { t: 'pillarLight', x: 20.0, y: 8.0, s: 1.3 },
      { t: 'brazier', x: 8.5, y: 13.4, s: 1.0 },
      { t: 'urn', x: 5.5, y: 7.5, s: 1.1 },
      { t: 'obelisk', x: 25.0, y: 8.5, s: 1.3 },
    ],
    autoDecor: { density: 0.06, seed: 807 },
  },
  {
    name: 'Tierpforten', par: 5, theme: 'colosseum', maxStrokes: 16,
    intro: 'Drei Kammern, zwei Löwenpforten. Jede will Schwung sehen, sonst bleibt sie eine Wand. In der mittleren Kammer zieht der Streitwagen seine Runden – wer aufspringt, kommt schneller voran.',
    map: [
      '..............................',
      '..............................',
      '..##########..................',
      '..##########..................',
      '..#T########A.................',
      '..##########..................',
      '..##########..................',
      '..............................',
      '..##########################..',
      '.a##########################B.',
      '..##########################..',
      '..##########################..',
      '..............................',
      '..............##############..',
      '.............b############H#..',
      '..............##############..',
      '..............................',
    ],
    obstacles: [
      { type: 'liongate', pair: 'A', angle: 0 },
      { type: 'liongate', pair: 'B', angle: 0 },
      { type: 'rail', y: 9.5, x0: 12, x1: 21 },
      // Der Wagen ist hier eine Mitfahrgelegenheit, keine Brücke: Wer ihn verpasst, rollt daneben weiter.
      { type: 'ferry', x0: 12.5, y0: 9.5, x1: 20.5, y1: 9.5, w: 1.4, h: 1.0, wait: 2.2, travel: 3.0, style: 'chariot' },
      { type: 'mover', x0: 6.5, y0: 2.5, x1: 6.5, y1: 6.5, w: 0.8, h: 0.8, period: 4.6, style: 'gladiator' },
      { type: 'mover', x0: 22.5, y0: 15.5, x1: 22.5, y1: 13.5, w: 0.8, h: 0.8, period: 3.8, phase: 0.3, style: 'gladiator' },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 4.5, s: 1.2 },
      { t: 'bannerRed', x: 28.6, y: 14.5, s: 1.2 },
      { t: 'pillarLight', x: 15.0, y: 5.0, s: 1.3 },
      { t: 'pillarLight', x: 15.0, y: 12.6, s: 1.3 },
      { t: 'brazier', x: 13.0, y: 6.6, s: 1.0 },
      { t: 'brazier', x: 29.0, y: 11.6, s: 1.0 },
      { t: 'urn', x: 5.5, y: 12.6, s: 1.1 },
      { t: 'obelisk', x: 20.0, y: 6.0, s: 1.3 },
    ],
    autoDecor: { density: 0.06, seed: 808 },
  },
  {
    name: 'Sandsturm', par: 5, theme: 'colosseum', maxStrokes: 16,
    intro: 'Alles auf einmal: das gleitende Gitter, zwei Mahlsteine, patrouillierende Gladiatoren – und am Ende die Schanze über den Graben. Wer zu kurz anläuft, fällt hinein.',
    map: [
      '................................',
      '................................',
      '................................',
      '..####################....####..',
      '..####################....####..',
      '..####################....####..',
      '..#T##################....##H#..',
      '..####################....####..',
      '..####################....####..',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'wandergate', x0: 12, y0: 3, x1: 12, y1: 9, gap: 1.8 },
      { type: 'rotor', x: 16.5, y: 4.5, blades: 3, len: 1.6, speed: 1.6, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 16.5, y: 7.5, blades: 3, len: 1.6, speed: -1.8, phase: 0.5, style: 'stone', height: 0.6 },
      { type: 'mover', x0: 7.5, y0: 3.5, x1: 7.5, y1: 8.5, w: 0.8, h: 0.8, period: 4.0, style: 'gladiator' },
      { type: 'mover', x0: 27.5, y0: 8.5, x1: 27.5, y1: 3.5, w: 0.8, h: 0.8, period: 4.8, phase: 0.4, style: 'gladiator' },
      { type: 'ramp', x: 20, y: 3, w: 2, h: 6, angle: 0, minSpeed: 3.2, speed: 6.8, land: 4.0 },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 6.5, s: 1.2 },
      { t: 'bannerRed', x: 30.6, y: 6.5, s: 1.2 },
      { t: 'pillarLight', x: 12.0, y: 1.4, s: 1.3 },
      { t: 'pillarLight', x: 12.0, y: 10.6, s: 1.3 },
      { t: 'obelisk', x: 23.5, y: 1.6, s: 1.4 },
      { t: 'obelisk', x: 23.5, y: 10.4, s: 1.4 },
      { t: 'urn', x: 5.5, y: 10.6, s: 1.1 },
      { t: 'brazier', x: 24.0, y: 6.0, s: 1.0 },
    ],
    autoDecor: { density: 0.07, seed: 809 },
  },
  {
    name: 'Die Spina', par: 6, theme: 'colosseum', maxStrokes: 18,
    intro: 'Ein voller Rundkurs um die Spina. Das Katapult wirft die lange Gerade hinauf, oben zieht der Streitwagen seine Bahn, unten mahlt der Stein – und ganz am Ende führt die Pforte in die Kammer im Herzen der Arena.',
    map: [
      '..................................',
      '..................................',
      '..##############################..',
      '..##############################..',
      '..##############################..',
      '..##############################..',
      '..######..................######..',
      '..######......######......######..',
      '..######.....a###H##......######..',
      '..######......######......######..',
      '..######......######......######..',
      '..######..................######..',
      '..##############################..',
      '..###########################A##..',
      '..##T###########################..',
      '..##############################..',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'liongate', pair: 'A', angle: 0 },
      { type: 'cannon', style: 'catapult', x: 4.5, y: 8.5, base: -Math.PI / 2, amp: 0.14, speed: 0.7, range: 5.2, catchR: 0.65, loadTime: 0.8 },
      { type: 'rail', y: 3.5, x0: 9, x1: 25 },
      { type: 'ferry', x0: 9.5, y0: 3.5, x1: 24.5, y1: 3.5, w: 1.4, h: 1.0, wait: 1.8, travel: 4.2, style: 'chariot' },
      { type: 'rotor', x: 16.5, y: 13.5, blades: 3, len: 1.7, speed: 1.5, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 28.5, y: 8.5, blades: 3, len: 1.6, speed: -1.6, phase: 0.4, style: 'stone', height: 0.6 },
      { type: 'mover', x0: 6.5, y0: 4.5, x1: 6.5, y1: 6.5, w: 0.8, h: 0.8, period: 3.6, style: 'gladiator' },
      { type: 'mover', x0: 22.5, y0: 14.5, x1: 10.5, y1: 14.5, w: 0.8, h: 0.8, period: 7.0, phase: 0.3, style: 'gladiator' },
    ],
    decor: [
      { t: 'pillarLight', x: 10.5, y: 8.5, s: 1.4 },
      { t: 'pillarLight', x: 23.5, y: 8.5, s: 1.4 },
      { t: 'pillarLight', x: 10.5, y: 9.5, s: 1.4 },
      { t: 'pillarLight', x: 23.5, y: 9.5, s: 1.4 },
      { t: 'bannerRed', x: 1.2, y: 8.5, s: 1.2 },
      { t: 'bannerRed', x: 32.6, y: 8.5, s: 1.2 },
      { t: 'obelisk', x: 11.0, y: 8.5, s: 1.5 },
      { t: 'brazier', x: 12.0, y: 6.6, s: 1.0 },
      { t: 'brazier', x: 21.5, y: 11.4, s: 1.0 },
      { t: 'urn', x: 5.5, y: 17.0, s: 1.1 },
      { t: 'urn', x: 28.5, y: 17.0, s: 1.1 },
    ],
    autoDecor: { density: 0.07, seed: 810 },
  },
  {
    name: 'Der Feuerturm', par: 7, theme: 'colosseum', maxStrokes: 20,
    intro: 'Die grosse Runde. Unten streicht der Feuerstrahl über den Sand – er geht nie aus, man muss den Moment abpassen, in dem er am Rand wendet. Oben sperrt das gleitende Gitter, und vor dem Loch klafft der Graben. Ein langer Weg zum Ass.',
    map: [
      '......................................',
      '......................................',
      '..####....##########################..',
      '..####....##########################..',
      '..#H##....##########################..',
      '..####....##########################..',
      '..####....##########################..',
      '...............................#####..',
      '...............................#####..',
      '...............................#####..',
      '...............................#####..',
      '..##################################..',
      '..##################################..',
      '..##################################..',
      '..#T################################..',
      '..##################################..',
      '..##################################..',
      '..##################################..',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'firetower', x: 18, y: 19.3, height: 3.6, zx: 13, zy: 11, zw: 8, zh: 7, achse: 'y', breit: 2, tempo: 1.9 },
      { type: 'rotor', x: 8.5, y: 14.5, blades: 3, len: 1.7, speed: 1.5, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 26.5, y: 14.5, blades: 3, len: 1.7, speed: -1.6, phase: 0.5, style: 'stone', height: 0.6 },
      { type: 'wandergate', x0: 22, y0: 2, x1: 22, y1: 7, gap: 1.8 },
      { type: 'mover', x0: 29.5, y0: 2.5, x1: 29.5, y1: 6.5, w: 0.8, h: 0.8, period: 4.2, style: 'gladiator' },
      { type: 'mover', x0: 15.5, y0: 6.5, x1: 15.5, y1: 2.5, w: 0.8, h: 0.8, period: 5.0, phase: 0.35, style: 'gladiator' },
      { type: 'ramp', x: 10, y: 2, w: 2, h: 5, angle: 180, minSpeed: 3.2, speed: 6.8, land: 5.0 },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 14.5, s: 1.2 },
      { t: 'bannerRed', x: 36.6, y: 8.5, s: 1.2 },
      { t: 'pillarLight', x: 8.0, y: 8.5, s: 1.4 },
      { t: 'pillarLight', x: 20.0, y: 8.5, s: 1.4 },
      { t: 'pillarLight', x: 27.0, y: 8.5, s: 1.4 },
      { t: 'obelisk', x: 7.5, y: 0.8, s: 1.4 },
      { t: 'obelisk', x: 30.5, y: 0.8, s: 1.4 },
      { t: 'brazier', x: 12.0, y: 9.4, s: 1.0 },
      { t: 'brazier', x: 24.0, y: 9.4, s: 1.0 },
      { t: 'urn', x: 5.5, y: 19.4, s: 1.1 },
      { t: 'urn', x: 30.5, y: 19.4, s: 1.1 },
    ],
    autoDecor: { density: 0.06, seed: 811 },
  },
  {
    name: 'Die Kaiserloge', par: 7, theme: 'colosseum', maxStrokes: 22,
    intro: 'Der Weg des Siegers: einmal unten hindurch, durch die Löwenpforte zurück nach links, über den Graben auf dem Streitwagen, mit der Schanze hinauf – und oben sitzt der Kaiser. Nach jedem Schlag dreht er den Daumen. Zeigt er nach unten, klafft die Falltür vor dem Loch.',
    map: [
      '......................................',
      '......................................',
      '..##################################..',
      '..##################################..',
      '..###H##############################..',
      '..##################################..',
      '..##################################..',
      '......................................',
      '..################.....#############..',
      '.a################.....#############..',
      '..################.....#############..',
      '..################.....#############..',
      '......................................',
      '......................................',
      '..##################################..',
      '..#T################################A.',
      '..##################################..',
      '..##################################..',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'imperialbox', x: 15, y: 0.6, w: 3.4, h: 1.6, lx: 14, ly: 2, lw: 2, lh: 5, start: 'hoch' },
      { type: 'liongate', pair: 'A', angle: 0 },
      { type: 'cannon', style: 'catapult', x: 20.5, y: 15.5, base: 0, amp: 0.1, speed: 0.7, range: 12.0, catchR: 0.65, loadTime: 0.8 },
      { type: 'rail', y: 9.5, x0: 17, x1: 24 },
      { type: 'ferry', x0: 17.5, y0: 9.5, x1: 23.5, y1: 9.5, w: 1.4, h: 1.0, wait: 1.6, travel: 2.8, style: 'chariot' },
      { type: 'ramp', x: 30, y: 8, w: 4, h: 2, angle: -90, minSpeed: 3.2, speed: 7.0, land: 4.0 },
      { type: 'rotor', x: 24.5, y: 4.5, blades: 3, len: 1.7, speed: 1.5, style: 'stone', height: 0.6 },
      { type: 'rotor', x: 9.5, y: 4.5, blades: 3, len: 1.6, speed: -1.7, phase: 0.4, style: 'stone', height: 0.6 },
      { type: 'mover', x0: 8.5, y0: 14.5, x1: 8.5, y1: 17.5, w: 0.8, h: 0.8, period: 3.8, style: 'gladiator' },
      { type: 'mover', x0: 29.5, y0: 17.5, x1: 29.5, y1: 14.5, w: 0.8, h: 0.8, period: 4.6, phase: 0.4, style: 'gladiator' },
    ],
    decor: [
      { t: 'bannerRed', x: 1.2, y: 15.5, s: 1.2 },
      { t: 'bannerRed', x: 36.6, y: 4.5, s: 1.2 },
      { t: 'pillarLight', x: 6.0, y: 12.5, s: 1.4 },
      { t: 'pillarLight', x: 20.0, y: 12.5, s: 1.4 },
      { t: 'pillarLight', x: 31.0, y: 12.5, s: 1.4 },
      { t: 'pillarLight', x: 20.0, y: 7.0, s: 1.4 },
      { t: 'pillarLight', x: 8.0, y: 7.0, s: 1.4 },
      { t: 'obelisk', x: 26.0, y: 0.8, s: 1.4 },
      { t: 'brazier', x: 12.0, y: 12.6, s: 1.0 },
      { t: 'brazier', x: 27.0, y: 7.0, s: 1.0 },
      { t: 'urn', x: 5.5, y: 18.6, s: 1.1 },
      { t: 'urn', x: 33.5, y: 18.6, s: 1.1 },
    ],
    autoDecor: { density: 0.06, seed: 812 },
  },
];
