/* Profi-Welt: acht schwerere Bahnen mit engen Wegen, Windmühlen (kleiner Durchgang), Pendeln und
   kombinierten Hindernissen. Gleiche Kartenlegende wie in courses.js. */
const PRO_COURSES = [
  {
    name: 'Mühlenwiese', par: 3, theme: 'meadow', maxStrokes: 15,
    intro: 'Eine Windmühle versperrt den Weg. Nur durch die schmale Tür geht es weiter – und die Flügel streichen daran vorbei.',
    map: [
      '........................',
      '..###ss####.............',
      '..T##ss####.............',
      '..###ss####.............',
      '........###.............',
      '........###.............',
      '........#############...',
      '........###########H#...',
      '........#############...',
      '........................',
    ],
    obstacles: [
      { type: 'windmill', x: 14, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.2 },
      { type: 'bumper', x: 9.5, y: 3.3, r: 0.4 },
    ],
    decor: [{ t: 'tower', x: 1, y: 6, s: 1.2 }, { t: 'flowerbush', x: 12, y: 9.5 }, { t: 'flowerbush', x: 4, y: 5.2 }],
    autoDecor: { density: 0.4, seed: 101 },
  },
  {
    name: 'Nebelmoor', par: 4, theme: 'forest', maxStrokes: 18,
    intro: 'Schmale Dämme zwischen Tümpeln, ein schwingender Balken und eine Mühle im Nebel.',
    map: [
      '........................',
      '..######wwww######......',
      '..T#####wwww######......',
      '..######wwww######......',
      '..wwww#######ii###......',
      '..wwww#######ii###......',
      '..######wwww######wwww..',
      '..######wwww###########.',
      '..######wwww######H###..',
      '........................',
    ],
    obstacles: [
      { type: 'rotor', x: 9.5, y: 5, blades: 1, len: 1.3, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.1, speed: 2.2 }, phase: Math.PI / 2 },
      { type: 'windmill', x: 15.5, y: 5, axis: 'y', w: 2, depth: 1.1, gap: 0.8, speed: 1.4 },
      { type: 'bumper', x: 14.5, y: 7.5, r: 0.4, style: 'mushroom' },
    ],
    decor: [{ t: 'tree', x: 11, y: 4.2, s: 1.3, glow: true }, { t: 'crystal', x: 20, y: 3 }],
    autoDecor: { density: 0.5, seed: 103 },
  },
  {
    name: 'Zwergenmine', par: 4, theme: 'forge', maxStrokes: 20,
    intro: 'Ein Damm ohne Geländer über zwei Lavaflüsse, dann die Lore – und ein Pendel vor dem Loch.',
    map: [
      '........................',
      '..#####lll##lll#######..',
      '..T####lll##lll#####H#..',
      '..#####lll##lll###x###..',
      '..#####lll##lll#######..',
      '..#####lll##lll#######..',
      '..#############lll####..',
      '..#####lll##lll#######..',
      '..#####lll##lll#######..',
      '..#####lll##lll#######..',
      '........................',
    ],
    obstacles: [
      { type: 'rail', y: 8.5, x0: 11, x1: 16 },
      { type: 'ferry', x0: 11.5, y0: 8.5, x1: 15.5, y1: 8.5, w: 1.1, h: 1.1, wait: 1.3, travel: 2, style: 'cart' },
      { type: 'rotor', x: 18.5, y: 5.5, blades: 1, len: 1.4, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.2, speed: 2.5 }, phase: 0 },
    ],
    decor: [{ t: 'brazier', x: 8, y: 0.4 }, { t: 'brazier', x: 13, y: 0.4 }, { t: 'anvil', x: 1, y: 5 }],
    autoDecor: { density: 0.35, seed: 107 },
  },
  {
    name: 'Kristallsee', par: 4, theme: 'ice', maxStrokes: 18,
    intro: 'Ein zugefrorener See mit Eislöchern, zwei Kristallsternen und einer Mühle vor dem Loch.',
    map: [
      '........................',
      '..iiiiiiiiiiiiiiiiiii...',
      '..Tiiiwwiiiiiiwwiiiii...',
      '..iiiiwwiiiiiiwwiiiii...',
      '..iiiiiiiiiiiiiiiiiii...',
      '..iiiiiiiiiiiiiiiiiii...',
      '..iiiwwiiiiwwiiiii###...',
      '..iiiwwiiiiwwiiiii#H#...',
      '..iiiiiiiiiiiiiiii###...',
      '........................',
    ],
    obstacles: [
      { type: 'rotor', x: 9.5, y: 4.5, blades: 4, len: 2.4, speed: 1.5, style: 'crystal' },
      { type: 'rotor', x: 15.5, y: 4.5, blades: 3, len: 2, speed: -1.2, style: 'crystal' },
      { type: 'windmill', x: 17.5, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.1 },
    ],
    decor: [{ t: 'crystalBlue', x: 1, y: 3, s: 1.5 }, { t: 'pineSnow', x: 22.5, y: 3, s: 1.3 }],
    autoDecor: { density: 0.4, seed: 109 },
  },
  {
    name: 'Sturmhöhe', par: 4, theme: 'sky', maxStrokes: 18,
    intro: 'Brücken von nur einer Kachel Breite, Gegenwind auf dem Aufstieg und Fallgatter.',
    map: [
      '........................',
      '..####.........####.....',
      '..T###.........#H##.....',
      '..####.........####.....',
      '....#...........#.......',
      '....#...........#.......',
      '....#####...#####.......',
      '........#...#...........',
      '........#####...........',
      '........................',
    ],
    obstacles: [
      { type: 'gate', x: 4.5, y: 4.5, w: 1, h: 0.3, period: 5, open: 0.5, phase: 0, axis: 'x' },
      { type: 'gate', x: 16.5, y: 5.3, w: 1, h: 0.3, period: 6, open: 0.5, phase: 0.5, axis: 'x' },
      { type: 'field', x: 16, y: 4, w: 1, h: 2, fx: 0, fy: 2.5, style: 'wind' },
      { type: 'boost', x: 9, y: 8, w: 3, h: 1, angle: 0, acc: 10, max: 8 },
    ],
    decor: [
      { t: 'tower', x: 1, y: 0.5, s: 1.3 }, { t: 'tower', x: 20, y: 0.6, s: 1.3 },
      { t: 'cloud', x: 11, y: 2.5, s: 1.5, z: 0.4 }, { t: 'cloud', x: 3, y: 11, s: 1.3, z: 0.2 }, { t: 'cloud', x: 19, y: 10.5, s: 1.3, z: 0.3 },
    ],
    autoDecor: { density: 0.2, seed: 113 },
  },
  {
    name: 'Drachenschlund', par: 5, theme: 'dragon', maxStrokes: 20, friction: { s: 32 },
    intro: 'Über die Lava nur per Sprungschanze – dahinter warten gleich zwei Drachen.',
    map: [
      '........................',
      '..######ssss##########..',
      '..T#####ssss##########..',
      '..######ssss##########..',
      '..####llllllllll######..',
      '..####llllllllll######..',
      '..####################..',
      '..####################..',
      '..#####xxxxxxxxxx#####..',
      '..####################..',
      '..#########H##########..',
      '........................',
    ],
    obstacles: [
      { type: 'ramp', x: 9, y: 2, w: 4, h: 2, angle: 90, minSpeed: 3, speed: 4.5, land: 2.8 },
      { type: 'mover', x0: 3.5, y0: 7, x1: 20.5, y1: 7, w: 2.4, h: 1.4, period: 8, phase: 0.2, style: 'dragon' },
      { type: 'mover', x0: 20.5, y0: 9.7, x1: 3.5, y1: 9.7, w: 2.4, h: 1.4, period: 9, phase: 0.6, style: 'dragon' },
    ],
    decor: [{ t: 'gold', x: 11.5, y: 12 }, { t: 'bones', x: 4.5, y: 11.5 }, { t: 'brazier', x: 7.5, y: 8.5 }, { t: 'brazier', x: 16.5, y: 8.5 }],
    autoDecor: { density: 0.4, seed: 127 },
  },
  {
    name: 'Hexenküche', par: 5, theme: 'witch', maxStrokes: 20,
    intro: 'Drei Inseln, nur durch Portale verbunden. Dazwischen eine Eishalle mit Kesseln und einem Pendel.',
    map: [
      '..........................',
      '..######....######....####',
      '..T#####....##ll##....#H##',
      '..######....######....####',
      '..######....######....####',
      '..........................',
      '..iiiiiiiiiiiiiiiiii......',
      '..iiiiiiiiiiiiiiiiii......',
      '..iiiiiiiiiiiiiiiiii......',
      '..........................',
    ],
    obstacles: [
      { type: 'portal', x: 6.5, y: 3.5, tx: 3.5, ty: 7.5, color: '#4fd0ff' },
      { type: 'portal', x: 18.5, y: 7.5, tx: 13.5, ty: 3.5, color: '#c77dff', twoWay: true },
      { type: 'portal', x: 16.5, y: 1.5, tx: 22.5, ty: 3.5, color: '#a6ff5e' },
      { type: 'mover', x0: 6, y0: 7.5, x1: 16, y1: 7.5, w: 1, h: 1, period: 6, phase: 0, style: 'cauldron' },
      { type: 'rotor', x: 11, y: 7.5, blades: 1, len: 1.3, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.3, speed: 2.4 }, phase: Math.PI / 2 },
      { type: 'rotor', x: 24, y: 2, blades: 2, len: 1, speed: 2, style: 'broom' },
    ],
    decor: [{ t: 'tower', x: 9.5, y: 2.5, s: 2, roof: '#2a1a3a', witch: true }, { t: 'cauldron', x: 20.5, y: 1 }, { t: 'pumpkin', x: 21, y: 7.5 }],
    autoDecor: { density: 0.4, seed: 131 },
  },
  {
    name: 'Königsburg', par: 5, theme: 'castle', maxStrokes: 25,
    intro: 'Der lange Weg zur Königsburg: zwei Mühlen, Ritter, Steigungen, Burggraben und Zugbrücke.',
    map: [
      '..........................',
      '........############......',
      '........#####H######......',
      '........############......',
      '........wwwww##wwwww......',
      '............####..........',
      '....#############.........',
      '....#############.........',
      '....#############.........',
      '....###...................',
      '....###...................',
      '....###############.......',
      '....###############.......',
      '....###############.......',
      '................###.......',
      '................###.......',
      '..#################.......',
      '..T################.......',
      '..#################.......',
      '..........................',
    ],
    obstacles: [
      { type: 'gate', x: 14, y: 4.5, w: 2, h: 0.3, period: 6, open: 0.5, phase: 0, axis: 'x' },
      { type: 'field', x: 16, y: 14, w: 3, h: 2, fx: 0, fy: 2.5, style: 'slope' },
      { type: 'field', x: 4, y: 9, w: 3, h: 2, fx: 0, fy: 2.5, style: 'slope' },
      { type: 'windmill', x: 10, y: 12.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.3 },
      { type: 'windmill', x: 9, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: -1.1, phase: 1 },
      { type: 'mover', x0: 4, y0: 17, x1: 17.5, y1: 17, w: 0.7, h: 0.7, period: 8, phase: 0.3, style: 'knight' },
      { type: 'mover', x0: 9, y0: 3, x1: 18.8, y1: 3, w: 0.7, h: 0.7, period: 6, phase: 0, style: 'knight' },
    ],
    decor: [
      { t: 'tower', x: 13.5, y: 0.3, s: 2.2, roof: '#a63d3d' }, { t: 'tower', x: 7.6, y: 0.6, s: 1.5, roof: '#a63d3d' }, { t: 'tower', x: 20.4, y: 0.6, s: 1.5, roof: '#a63d3d' },
      { t: 'pine', x: 8, y: 9.8, s: 1.4 }, { t: 'pine', x: 12, y: 10.2, s: 1.2 }, { t: 'pine', x: 8, y: 15, s: 1.3 },
    ],
    autoDecor: { density: 0.45, seed: 137 },
  },
];

/* Welten: jede mit eigener Bahnliste. Neue Welten hier anhängen. */
const WORLDS = [
  { id: 'normal', name: 'Fantasy-Welt', short: 'Fantasy', courses: COURSES },
  { id: 'pro', name: 'Profi-Welt', short: 'Profi', courses: PRO_COURSES },
];
