/* Der Alte Platz – Minigolf, wie es wirklich ist.
   Erzeugt von tools/altplatz.py; dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

   DIE EINZIGE WELT, IN DER DIE FORM DIE AUFGABE IST. Alle anderen sind um eine Maschine herum
   gebaut – die Mine um die Lampe, die Flut um den Wasserstand, die Loge um die Schleuder. Hier
   steckt die Aufgabe im Grundriß, und die vier Maschinen, die vorkommen, sind die vier, die auf
   jedem echten Platz stehen: die Mühle, der Tunnel, die Klappe und der Prellbock.

   Kein Abgrund, nichts, was fliegt, kein Wirkungsfeld. Wer schlecht spielt, liegt schlecht –
   er ist nicht weg. Sonst gilt dieselbe Kartenlegende wie in courses.js. */

const ALTPLATZ_COURSES = [
  {
    name: 'Der Anstoß', par: 2, theme: 'altplatz',
    intro: 'Die erste Bahn: eine Gerade, ein Stein darin. Unten ist Platz. Mehr muß eine erste Bahn nicht wollen.',
    map: [
      '............................',
      '............................',
      '............................',
      '..##########xx############..',
      '..##########xx#########H##..',
      '..##########xx############..',
      '..##########xx############..',
      '..##T#####################..',
      '..########################..',
      '............................',
      '............................',
      '............................',
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Der Knick', par: 3, theme: 'altplatz',
    intro: 'Rechts herum, und in der Ecke steht keine Kante, sondern eine Schräge. Wer mit Schwung hineinspielt, kommt um sie herum.',
    map: [
      '............................',
      '............................',
      '............................',
      '..################..........',
      '..#################.........',
      '..##T###############........',
      '..###################.......',
      '..###################.......',
      '...............######.......',
      '................#####.......',
      '................#####.......',
      '................#####.......',
      '................##H##.......',
      '................#####.......',
      '................#####.......',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'wall', x0: 17, y0: 3, x1: 18, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 4, x1: 19, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 5, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 6, x1: 21, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 9, x1: 15, y1: 8, t: 0.22, h: 0.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Die Pyramide', par: 3, theme: 'altplatz',
    intro: 'Mitten im Feld steht die Pyramide. Wer sie mittig trifft, bekommt den Ball zurück; wer sie streift, wird abgelenkt. Oben und unten herum geht es auch – nur steht da je ein Prellbock im Weg.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##T####################H##..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 11.6, y0: 8.5, x1: 15.0, y1: 5.1, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 15.0, y0: 5.1, x1: 18.4, y1: 8.5, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 18.4, y0: 8.5, x1: 15.0, y1: 11.9, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 15.0, y0: 11.9, x1: 11.6, y1: 8.5, t: 0.42, h: 0.85 },
      { type: 'bumper', x: 15.0, y: 3.6, r: 0.55, style: 'mushroom', kick: 7.5 },
      { type: 'bumper', x: 15.0, y: 13.4, r: 0.55, style: 'mushroom', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Die Mühle', par: 3, theme: 'altplatz',
    intro: 'Die Mühle. Durch das Tor kommt nur, wer den Augenblick abpaßt, in dem der Flügel oben steht. Zu früh ist dasselbe wie zu spät.',
    map: [
      '................................',
      '................................',
      '................................',
      '..############xx##############..',
      '..############xx##############..',
      '..############################..',
      '..##T######################H##..',
      '..############################..',
      '..############xx##############..',
      '..############xx##############..',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'windmill', x: 14.5, y: 6.0, w: 3.4, gap: 1.4, speed: 0.85, blades: 4, axis: 'y', phase: 0.0, depth: 2.0 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Der Tunnel', par: 3, theme: 'altplatz',
    intro: 'Der Tunnel nimmt den Ball auf der einen Seite und gibt ihn auf der anderen wieder heraus. Wer sein Maul verfehlt, geht unten herum – das kostet einen Schlag.',
    map: [
      '................................',
      '................................',
      '................................',
      '..############xx##############..',
      '..############xx##############..',
      '..############xx###########H##..',
      '..##T#######A#xx#a############..',
      '..############xx##############..',
      '..############xx##############..',
      '..############xx##############..',
      '..############################..',
      '..############################..',
      '..############################..',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 0 },
      { type: 'bumper', x: 22.0, y: 9.0, r: 0.55, style: 'mushroom', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Die Sandbahn', par: 3, theme: 'altplatz',
    intro: 'In der Mitte liegt Sand, und Sand frißt Tempo. Am oberen Rand bleibt ein Streifen Grün – er ist schmal, und ein Klotz steht auch noch darin.',
    map: [
      '................................',
      '................................',
      '................................',
      '..######sssssssssssssssss#####..',
      '..######sssssssssssssssss#####..',
      '..######sssssssssssssssss##H##..',
      '..######sssssssssssssssss#####..',
      '..######sssssssssssssssss#####..',
      '..##T############xx###########..',
      '..###############xx###########..',
      '................................',
      '................................',
      '................................',
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Die Brücke', par: 4, theme: 'altplatz',
    intro: 'Drei Kacheln breit, und links und rechts ist Wasser. Hinüber hilft kein Trick, nur eine gerade Linie – und drüben liegt das Loch nicht da, wo der Steg hinzeigt.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww########..',
      '..##############################..',
      '..###T##########################..',
      '..##############################..',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww####H###..',
      '..########wwwwwwwwwwwwww########..',
      '..########wwwwwwwwwwwwww########..',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'bumper', x: 26.5, y: 8.5, r: 0.55, style: 'mushroom', kick: 7.5 },
      { type: 'bumper', x: 29.5, y: 5.5, r: 0.55, style: 'mushroom', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Der Trichter', par: 3, theme: 'altplatz',
    intro: 'Die Wand oben läuft schräg zum Hals hinunter – wer sie richtig anspielt, wird hineingelenkt. Im Hals liegt die Klappe und macht im Takt zu.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..#####.............#####.....',
      '..######............######....',
      '..#######...........#######...',
      '..##T#####..........####H###..',
      '..#########.........########..',
      '..##########.......#########..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 6, y0: 3, x1: 7, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 3, x1: 25, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 4, x1: 8, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 4, x1: 26, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 5, x1: 9, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 5, x1: 27, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 9, y0: 6, x1: 10, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 6, x1: 28, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 7, x1: 11, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 11, y0: 8, x1: 12, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 8, x1: 19, y1: 9, t: 0.22, h: 0.5 },
      { type: 'gate', x: 16.0, y: 11.0, w: 2.6, h: 0.3, period: 5.0, open: 0.55, axis: 'x', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Schleife', par: 4, theme: 'altplatz',
    intro: 'Die Insel steht im Weg, und beide Wege außen herum sind gleich lang. Oben liegt die Klappe und macht im Takt zu; unten stehen drei Prellböcke und lassen immer durch – aber nicht dahin, wo man wollte.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '....##########################....',
      '...############################...',
      '..##############################..',
      '..##############################..',
      '..#########xxxxxxxxxxxx#########..',
      '..#########xxxxxxxxxxxx#########..',
      '..#########xxxxxxxxxxxx#########..',
      '..###T#####xxxxxxxxxxxx#####H###..',
      '..#########xxxxxxxxxxxx#########..',
      '..#########xxxxxxxxxxxx#########..',
      '..##############################..',
      '..##############################..',
      '...############################...',
      '....##########################....',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 5, y0: 3, x1: 4, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 3, x1: 30, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 4, x1: 3, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 4, x1: 31, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 5, x1: 2, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 5, x1: 32, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 15, x1: 2, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 15, x1: 32, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 16, x1: 3, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 16, x1: 31, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 17, x1: 4, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 17, x1: 30, y1: 16, t: 0.22, h: 0.5 },
      { type: 'gate', x: 16.5, y: 4.5, w: 3.0, h: 0.3, period: 4.8, open: 0.5, axis: 'x', phase: 0.0 },
      { type: 'bumper', x: 16.5, y: 14.5, r: 0.55, style: 'mushroom', kick: 7.5 },
      { type: 'bumper', x: 13.0, y: 14.5, r: 0.55, style: 'mushroom', kick: 7.5 },
      { type: 'bumper', x: 20.0, y: 14.5, r: 0.55, style: 'mushroom', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Die Lange Bahn', par: 4, theme: 'altplatz',
    intro: 'Drei Kehren, und in jeder steht eine Schräge statt einer Ecke. Dazwischen die Klappe, und vor dem Loch noch zwei Prellböcke. Einzeln ist nichts davon schwer – alles hintereinander schon. Wer hier im Par bleibt, kann Minigolf.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '..############........................',
      '..#############.......................',
      '..##T###########.............#######..',
      '..###############...........########..',
      '..###############..........#######H#..',
      '...........######.........##########..',
      '............#####.........##########..',
      '............######.......#######......',
      '............###################.......',
      '............###################.......',
      '.............#################........',
      '..............###############.........',
      '...............#############..........',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 3, x1: 14, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 4, x1: 15, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 5, x1: 16, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 5, x1: 29, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 6, x1: 17, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 6, x1: 28, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 7, x1: 27, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 9, x1: 11, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 8, x1: 26, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 10, x1: 18, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 10, x1: 25, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 11, x1: 32, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 13, x1: 12, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 13, x1: 31, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 14, x1: 13, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 14, x1: 30, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 15, x1: 14, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 15, x1: 29, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 16, x1: 15, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 16, x1: 28, y1: 15, t: 0.22, h: 0.5 },
      { type: 'gate', x: 14.0, y: 9.0, w: 2.6, h: 0.3, period: 4.6, open: 0.5, axis: 'y', phase: 0.0 },
      { type: 'bumper', x: 21.0, y: 13.0, r: 0.55, style: 'mushroom', kick: 7.5 },
      { type: 'bumper', x: 29.0, y: 7.0, r: 0.55, style: 'mushroom', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];
