/* Uhrenturm (Weltkennung 'clock'): zwölf Bahnen in einer Stadt, die im Takt läuft.

   Der rote Faden ist die Zeit. Jede andere Welt fragt, wie fest und wohin man schlägt; diese fragt
   zuerst *wann*. Darum steht auf jeder Bahn mindestens eine Maschine vor einer Stelle, an der kein
   Weg vorbeiführt – eine Tür, eine Lücke, ein Rohr –, und sie gibt diese Stelle nur zeitweise frei.
   Wer zusieht und mitzählt, kommt durch; wer nur fest schlägt, nicht.

   Aufbau: Bahn 1 bis 4 führen je ein bis zwei Maschinen ein, 5 bis 8 mischen sie, 9 bis 11
   kombinieren, und 12 ist der Höhepunkt. Das Kupferrohr kommt erst ab Bahn 4 vor, die Hemmung erst
   ab Bahn 5 – und beide bewusst nicht auf jeder Bahn, damit sie nicht zur Gewohnheit werden.

   Bahn 12 ist die einzige mit dem wandernden Loch: Dort springt es alle zehn Sekunden eine
   Stundenmarke weiter. Was das Loch tut, macht das Hindernis 'dial' selbst; das 'H' der Karte steht
   auf seiner ersten Marke, damit die Bahn auch ohne laufende Uhr ein Ziel hat.

   Die Kupferrohre stehen nicht als Koordinaten in der Hindernisliste, sondern als Buchstaben in der
   Karte: Der Großbuchstabe ist der Rohrmund, der gleiche Kleinbuchstabe das Rohrende (A/a, B/b).
   In der Liste steht je Paar nur, in welche Richtung es ausspuckt ('angle' in Grad).

   Die Karten dieser Datei entstehen mit tools/uhrenturm.py aus Rechtecken und Scheiben. Das Skript
   prüft schon beim Bauen, was sonst erst im Spiel auffiele: dass jeder Punkt, den eine Maschine
   braucht, auf der Bahn liegt – der Umkehrpunkt eines Pendels, das Ende eines Zahnradfelds, der
   Landepunkt einer Feder, jede Marke des Zifferblatts.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. Winkel in Grad, wo nicht anders vermerkt
   (Feder und Rohr rechnen intern im Bogenmaß), Zeiten in Sekunden, Koordinaten in Kacheln. */
const CLOCK_COURSES = [
  {
    name: 'Marktplatz', par: 3, theme: 'clocktown', maxStrokes: 12,
    intro: 'Der Platz unter der Stadtuhr. Durch die Mauer führt eine einzige Tür, und vor ihr schwingt das große Pendel. Zweimal je Schwingung gibt es die Tür frei – dann muss der Ball hindurch.',
    map: [
      '............................',
      '............................',
      '..###########x############..',
      '..###########x############..',
      '..###########x############..',
      '..##T##################H##..',
      '..###########x############..',
      '..###########x############..',
      '..###########x############..',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'pendulum', x: 13.5, y: 2, len: 3.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 13, y: 0.5, s: 2.2 },
      { t: 'lantern', x: 4.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 23.5, y: 0.6, s: 1 },
      { t: 'barrel', x: 0.9, y: 5.5, s: 1 },
      { t: 'crate', x: 26.8, y: 3.4, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 71 },
  },
  {
    name: 'Glockengasse', par: 3, theme: 'clocktown', maxStrokes: 14,
    intro: 'Zwei Türen, zwei Pendel – und sie gehen versetzt. Wer die erste im richtigen Moment nimmt, steht vor der zweiten zur falschen Zeit. Einmal zusehen lohnt sich mehr als jeder feste Schlag.',
    map: [
      '................................',
      '................................',
      '..#########x#########x########..',
      '..#########x#########x########..',
      '..#########x#########x########..',
      '..##T######################H##..',
      '..#########x#########x########..',
      '..#########x#########x########..',
      '..#########x#########x########..',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 11.5, y: 2, len: 3.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'pendulum', x: 21.5, y: 2, len: 3.5, amp: 60, ruhe: 90, phase: 0.5, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 16, y: 0.5, s: 2.2 },
      { t: 'bell', x: 8.5, y: 9.6, s: 1.2 },
      { t: 'bell', x: 24.5, y: 9.6, s: 1.2 },
      { t: 'lantern', x: 16, y: 9.7, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 23 },
  },
  {
    name: 'Räderwerkstatt', par: 4, theme: 'clocktown', maxStrokes: 16,
    intro: 'Zwischen den Hallen liegt nichts als Luft; hinüber tragen nur die Zahnräder. Sie halten an jedem Ufer kurz an – das ist der Moment zum Einsteigen. Drüben wartet noch ein Pendel.',
    map: [
      '................................',
      '................................',
      '..##########.......######x####..',
      '..##########.......######x####..',
      '..##########.......######x####..',
      '..##T#######.......#########H#..',
      '..##########.......######x####..',
      '..##########.......######x####..',
      '..##########.......######x####..',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'gearfield', x0: 11.5, y0: 5.5, x1: 19.5, y1: 5.5, wait: 2.8, travel: 3.2, r: 0.9, zaehne: 10, phase: 0 },
      { type: 'pendulum', x: 25.5, y: 2, len: 3.5, amp: 60, ruhe: 90, phase: 0.35, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 15, y: 0.5, s: 2 },
      { t: 'lantern', x: 5.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 27.5, y: 0.6, s: 1 },
      { t: 'gearFlat', x: 15, y: 9.5, s: 1.6 },
      { t: 'crate', x: 0.9, y: 5.5, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 44 },
  },
  {
    name: 'Rohrpost', par: 4, theme: 'boiler', maxStrokes: 16,
    intro: 'Die Wand hat kein Tor. Hinüber führt nur das Kupferrohr, und es schluckt nur, wer mit Schwung ankommt – wer zu sacht rollt, prallt am Rohrmund ab. Hinter der Wand wirft es den Ball von oben in die Kesselhalle, wo wieder ein Pendel vor der Tür steht.',
    map: [
      '................................',
      '................................',
      '..###########x######a####x####..',
      '..###########x###########x####..',
      '..###########x###########x####..',
      '..##T#######Ax##############H#..',
      '..###########x###########x####..',
      '..###########x###########x####..',
      '..###########x###########x####..',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'pendulum', x: 25.5, y: 2, len: 3.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 21.5, y: 9.6, s: 1 },
      { t: 'barrel', x: 30.8, y: 5.5, s: 1 },
      { t: 'gearFlat', x: 8.5, y: 9.5, s: 1.4 },
    ],
    autoDecor: { density: 0.12, seed: 88 },
  },
  {
    name: 'Hemmwerk', par: 4, theme: 'escapement', maxStrokes: 16,
    intro: 'Die Hemmung sperrt immer eine Hälfte des Ganges und gibt die andere frei; alle paar Sekunden wechselt sie. Beim Umschlagen sind beide Klinken kurz unten. Dahinter steht das Pendel vor der Tür – zwei Takte, die nicht zusammenpassen.',
    map: [
      '................................',
      '................................',
      '................................',
      '..####################x#######..',
      '..####################x#######..',
      '..##T######################H##..',
      '..####################x#######..',
      '..####################x#######..',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'escapement', x: 12.5, y: 5.5, w: 0.45, h: 5, phase: 0 },
      { type: 'pendulum', x: 22.5, y: 3, len: 2.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'gearFlat', x: 16, y: 1.4, s: 1.8 },
      { t: 'lantern', x: 8.5, y: 9.5, s: 1 },
      { t: 'lantern', x: 24.5, y: 9.5, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 12 },
  },
  {
    name: 'Federkammer', par: 4, theme: 'boiler', maxStrokes: 16,
    intro: 'Über die Kluft kommt nur, wer sich einspannen lässt. Die Feder schwenkt langsam hin und her – der leuchtende Punkt zeigt, wo der Ball landen wird. Drüben teilt die Hemmung die Kammer, und der Weg zum Loch führt nur durch die offene Hälfte.',
    map: [
      '................................',
      '................................',
      '................................',
      '.....................#########..',
      '..###########........#########..',
      '..###########........#########..',
      '..##T########........#########..',
      '..###########........#######H#..',
      '..###########........#########..',
      '..###########........#########..',
      '.....................#########..',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'springwork', x: 8.5, y: 6.5, base: 0, amp: 0.22, speed: 0.8, range: 12, catchR: 0.7, loadTime: 0.9 },
      { type: 'escapement', x: 25.5, y: 7, w: 0.45, h: 8, phase: 0 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 2.5, s: 1 },
      { t: 'lantern', x: 24.5, y: 1.5, s: 1 },
      { t: 'barrel', x: 16, y: 6.5, s: 1 },
      { t: 'gearFlat', x: 16, y: 10.5, s: 1.4 },
    ],
    autoDecor: { density: 0.12, seed: 61 },
  },
  {
    name: 'Zeigerhof', par: 4, theme: 'clocktown', maxStrokes: 16,
    intro: 'Der runde Hof unter dem großen Zeiger. Er braucht zwölf Sekunden für eine Runde und schiebt alles vor sich her, was auf dem Pflaster liegt – hinüber kommt man nur hinter ihm her. Am anderen Rand tragen die Zahnräder auf das Podest.',
    map: [
      '................................',
      '................................',
      '.............######.............',
      '............########............',
      '...........##########...........',
      '..........############..........',
      '..####################....####..',
      '..##T#################....##H#..',
      '..####################....####..',
      '..........############....####..',
      '...........##########...........',
      '............########............',
      '.............######.............',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'sweephand', x: 16, y: 7.5, r: 4.5, thick: 0.24, phase: 0 },
      { type: 'gearfield', x0: 21.5, y0: 7.5, x1: 26.5, y1: 7.5, wait: 2, travel: 2.6, r: 0.9, zaehne: 10, phase: 0 },
    ],
    decor: [
      { t: 'clock', x: 16, y: 0.6, s: 2.4 },
      { t: 'lantern', x: 5.5, y: 4.5, s: 1 },
      { t: 'lantern', x: 27.5, y: 4.5, s: 1 },
      { t: 'gearFlat', x: 16, y: 13.6, s: 1.6 },
    ],
    autoDecor: { density: 0.1, seed: 5 },
  },
  {
    name: 'Kesselhaus', par: 4, theme: 'boiler', maxStrokes: 16,
    intro: 'Erst durch die Tür, dann mit Schwung ins Rohr – beides will abgepasst sein. In der Kesselhalle wartet die Feder, die als Einzige über die Glut auf das Podest wirft.',
    map: [
      '..................................',
      '..................................',
      '.............####a#####...........',
      '.............##########...........',
      '..#####x####x##########....#####..',
      '..#####x####x##########....#####..',
      '..#T#######Ax##########....###H#..',
      '..#####x####x##########....#####..',
      '..#####x####x##########....#####..',
      '..#####x####x##########....#####..',
      '.............##########...........',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 7.5, y: 4, len: 2.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'springwork', x: 20.5, y: 6.5, base: 0, amp: 0.2, speed: 0.75, range: 9, catchR: 0.7, loadTime: 0.9 },
    ],
    decor: [
      { t: 'lantern', x: 4.5, y: 2.5, s: 1 },
      { t: 'barrel', x: 24.5, y: 6.5, s: 1 },
      { t: 'crate', x: 24.5, y: 9.5, s: 1 },
      { t: 'gearFlat', x: 17, y: 11.6, s: 1.5 },
    ],
    autoDecor: { density: 0.12, seed: 93 },
  },
  {
    name: 'Glockenturm', par: 5, theme: 'clocktown', maxStrokes: 20,
    intro: 'Die Glockenstube: erst das Pendel vor der Tür, dann die Hemmung quer durch die Halle, und vor dem Loch schwingt noch ein zweites Pendel. Drei Takte, und keiner passt zum anderen – hier gewinnt, wer wartet, nicht wer fest schlägt.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..##########x###################..',
      '..##########x###################..',
      '..##########x###################..',
      '..##########x###################..',
      '..##T###########################..',
      '..##########x###################..',
      '..##########x###################..',
      '..##########x#################H#..',
      '..##########x###################..',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 12.5, y: 3, len: 4.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'escapement', x: 22.5, y: 7.5, w: 0.45, h: 9, phase: 0.5 },
      { type: 'pendulum', x: 28, y: 3, len: 4.5, amp: 60, ruhe: 90, phase: 0.25, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'bell', x: 6.5, y: 1.4, s: 1.4 },
      { t: 'bell', x: 27.5, y: 1.4, s: 1.4 },
      { t: 'clock', x: 17, y: 0.8, s: 2.2 },
      { t: 'lantern', x: 17, y: 13.6, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 145 },
  },
  {
    name: 'Räderschacht', par: 5, theme: 'escapement', maxStrokes: 20,
    intro: 'Zwei Zahnradfelder, dazwischen die Scheibe unter dem Zeiger. Beide Felder halten nur kurz an, und der Zeiger räumt die Scheibe alle zwölf Sekunden einmal leer. Am Ausstieg teilt die Hemmung den Weg zum Loch.',
    map: [
      '....................................',
      '....................................',
      '...............####.................',
      '.............########...............',
      '............##########.....#######..',
      '..#######...##########.....#######..',
      '..#######...##########.....#######..',
      '..##T####..############....#######..',
      '..#######...##########.....#####H#..',
      '..#######...##########.....#######..',
      '..#######...##########.....#######..',
      '.............########......#######..',
      '...............####.................',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'gearfield', x0: 8.5, y0: 7.5, x1: 11.5, y1: 7.5, wait: 2, travel: 2.2, r: 0.9, zaehne: 10, phase: 0 },
      { type: 'sweephand', x: 17, y: 7.5, r: 4.2, thick: 0.24, phase: 0.25 },
      { type: 'gearfield', x0: 22.5, y0: 7.5, x1: 27.5, y1: 7.5, wait: 2, travel: 2.8, r: 0.9, zaehne: 10, phase: 0.4 },
      { type: 'escapement', x: 30, y: 8, w: 0.45, h: 8, phase: 0.5 },
    ],
    decor: [
      { t: 'gearFlat', x: 17, y: 1.4, s: 1.8 },
      { t: 'gearFlat', x: 17, y: 13.6, s: 1.6 },
      { t: 'lantern', x: 5.5, y: 2.5, s: 1 },
      { t: 'lantern', x: 30.5, y: 2.5, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 207 },
  },
  {
    name: 'Kupferlabyrinth', par: 5, theme: 'boiler', maxStrokes: 20,
    intro: 'Drei Kammern, und zwischen ihnen führt kein Weg – nur die Rohre. Beide schlucken nur mit Schwung, und zwischen ihnen steht die Hemmung: Man muss also durch die offene Hälfte schießen und gleich danach noch genug Tempo für das zweite Rohr haben. Am Ende wirft die Feder über die letzte Kluft.',
    map: [
      '....................................',
      '....................................',
      '............####a######x............',
      '............###########x............',
      '..#########x###########x###b##..###.',
      '..#########x###########x######..###.',
      '..#########x###########x######..###.',
      '..##T#####Ax##########Bx######..###.',
      '..#########x###########x######..###.',
      '..#########x###########x######..##H.',
      '..#########x###########x######..###.',
      '............###########x............',
      '............###########x............',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'escapement', x: 19, y: 7.5, w: 0.45, h: 11, phase: 0 },
      { type: 'copperpipe', pair: 'B', angle: 90 },
      { type: 'springwork', x: 27.5, y: 7.5, base: 0, amp: 0.2, speed: 0.85, range: 5, catchR: 0.7, loadTime: 0.9 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 2.5, s: 1 },
      { t: 'lantern', x: 17, y: 13.6, s: 1 },
      { t: 'barrel', x: 30.5, y: 7.5, s: 1 },
      { t: 'crate', x: 30.5, y: 4.5, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 311 },
  },
  {
    name: 'Das große Zifferblatt', par: 6, theme: 'escapement', maxStrokes: 26,
    intro: 'Die Schlussbahn steht auf dem Zifferblatt des Turms – und hier bleibt das Loch nicht liegen. Alle zehn Sekunden springt es eine Stundenmarke weiter, immer im Uhrzeigersinn. Der leuchtende Ring zeigt, wohin als Nächstes und wie lange noch. Dazwischen streicht der große Zeiger über die Mitte, und zwei Pendel hängen über dem Blatt. Hier zählt nur eines: im richtigen Moment am richtigen Ort zu sein.',
    map: [
      '..............................',
      '..............................',
      '............######............',
      '..........##########..........',
      '.........######H#####.........',
      '........##############........',
      '.......################.......',
      '.......################.......',
      '.......################.......',
      '......##################......',
      '......##################......',
      '......##################......',
      '.......################.......',
      '.......################.......',
      '.......################.......',
      '........##############........',
      '.........############.........',
      '..........#####T####..........',
      '............######............',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'dial', x: 15, y: 10.5, r: 6.5, marken: 12 },
      { type: 'sweephand', x: 15, y: 10.5, r: 4.6, thick: 0.24, phase: 0 },
      { type: 'pendulum', x: 10, y: 6.5, len: 4, amp: 45, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'pendulum', x: 20, y: 6.5, len: 4, amp: 45, ruhe: 90, phase: 0.5, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 15, y: 0.8, s: 2.6 },
      { t: 'bell', x: 4.5, y: 3.5, s: 1.3 },
      { t: 'bell', x: 25.5, y: 3.5, s: 1.3 },
      { t: 'lantern', x: 4.5, y: 17.5, s: 1 },
      { t: 'lantern', x: 25.5, y: 17.5, s: 1 },
    ],
    autoDecor: { density: 0.08, seed: 1200 },
  },
];
