/* Profi-Welt: acht Bahnen mit eigenen Mechaniken – Windmühlen, Kanone, Magnete, Drehscheiben,
   Schrumpftrank, Schalter und Zaubertor. Gleiche Kartenlegende wie in courses.js. */
const PRO_COURSES = [
  {
    name: 'Mühlenwiese', par: 3, theme: 'meadow', maxStrokes: 15,
    intro: 'Eine Windmühle versperrt den Weg. Nur durch die schmale Tür geht es weiter – und die Flügel streichen daran vorbei.',
    map: [
      '........................',
      '..###ss####.............',
      '..T##ss####.............',
      '..###ss####.............',
      '........###.............',
      '........###.............',
      '........#############...',
      '........###########H#...',
      '........#############...',
      '........................',
    ],
    obstacles: [
      { type: 'windmill', x: 14, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.2 },
      { type: 'bumper', x: 9.5, y: 3.3, r: 0.4 },
    ],
    decor: [{ t: 'tower', x: 1, y: 6, s: 1.2 }, { t: 'flowerbush', x: 12, y: 9.5 }, { t: 'flowerbush', x: 4, y: 5.2 }],
    autoDecor: { density: 0.4, seed: 101 },
  },
  {
    name: 'Nebelmoor', par: 4, theme: 'forest', maxStrokes: 18,
    intro: 'Ein breiter Fluss ohne Brücke – nur die kleine Rampe am Ufer bringt den Ball hinüber. Dahinter wacht die Mühle über das Loch.',
    map: [
      '........................',
      '..######wwww##########..',
      '..T#####wwww##########..',
      '..######wwww####ii####..',
      '..######wwww####ii####..',
      '..######wwww##########..',
      '..######wwww######wwww..',
      '..######wwww###########.',
      '..######wwww######H###..',
      '........................',
    ],
    obstacles: [
      { type: 'ramp', x: 6.5, y: 3.5, w: 1.5, h: 2, angle: 0, minSpeed: 3, speed: 4.5, land: 4.6 },
      { type: 'windmill', x: 15, y: 6, axis: 'x', w: 6, depth: 1.2, gap: 0.9, speed: 1.0 },
    ],
    atmo: 'fog',
    decor: [{ t: 'tree', x: 9.5, y: 0.3, s: 1.3, glow: true }, { t: 'crystal', x: 22.5, y: 3 }, { t: 'lantern', x: 8.4, y: 9.4 }, { t: 'lantern', x: 11.6, y: 9.4 }],
    autoDecor: { density: 0.5, seed: 103 },
  },
  {
    name: 'Zwergenkanone', par: 3, theme: 'forge', maxStrokes: 18,
    intro: 'Über den Lavasee führt kein Weg – nur die schwenkende Kanone der Zwerge. Rollt der Ball hinein, wird er abgefeuert: in die Richtung, in die das Rohr gerade zeigt.',
    map: [
      '..........................',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..T#####xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsssH#..',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..........................',
    ],
    obstacles: [
      { type: 'cannon', x: 6.9, y: 4.5, base: 0, amp: 0.5, speed: 0.9, range: 12.5, catch: 0.6, loadTime: 0.7 },
      { type: 'rotor', x: 4.5, y: 2.2, blades: 1, len: 1.2, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.1, speed: 2.2 }, phase: 0 },
      { type: 'rotor', x: 4.5, y: 6.8, blades: 1, len: 1.2, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.1, speed: 2.2 }, phase: Math.PI },
    ],
    decor: [{ t: 'brazier', x: 8.5, y: 0.4 }, { t: 'brazier', x: 8.5, y: 8.6 }, { t: 'anvil', x: 1, y: 6.5 }, { t: 'gold', x: 24.5, y: 2 }],
    autoDecor: { density: 0.35, seed: 107 },
  },
  {
    name: 'Magnetsee', par: 4, theme: 'ice', maxStrokes: 18,
    intro: 'Kristall-Magnete ziehen den Ball an oder stoßen ihn ab. Wer stur aufs Loch zielt, landet im Eisloch – die Kraftfelder wollen mitgedacht sein.',
    map: [
      '........................',
      '..###################...',
      '..T##################...',
      '..#####iiwiiiiiwiiii#...',
      '..#####iiwiiiiiwiiii#...',
      '..#####iiiiiiiiiiiii#...',
      '..#####iiiiiiiiiiiii#...',
      '..###wwiiiiiiiiiii#H#...',
      '..###wwiiiiiiiiiii###...',
      '........................',
    ],
    obstacles: [
      { type: 'magnet', x: 12.5, y: 2.4, r: 3, strength: 5.5 },
      { type: 'magnet', x: 16, y: 6.8, r: 2.8, strength: -7 },
      { type: 'magnet', x: 8.5, y: 6.5, r: 2.4, strength: 5 },
    ],
    decor: [{ t: 'crystalBlue', x: 1, y: 3, s: 1.5 }, { t: 'pineSnow', x: 22.5, y: 3, s: 1.3 }, { t: 'crystalBlue', x: 22.3, y: 8.5, s: 1.1 }],
    autoDecor: { density: 0.4, seed: 109 },
  },
  {
    name: 'Uhrwerk', par: 4, theme: 'sky', maxStrokes: 18,
    intro: 'Zwei riesige Zahnräder in den Wolken. Wer sich von der Drehscheibe tragen lässt, wird zum richtigen Ausgang geschleudert – wer zu stark schießt, dreht Runden.',
    map: [
      '..........................',
      '..######..........#####...',
      '..T#####..........##H##...',
      '..######..........#####...',
      '.....#..............#.....',
      '.....#..............#.....',
      '...#####..........#####...',
      '...#####..........#####...',
      '...####################...',
      '...#####..........#####...',
      '...#####..........#####...',
      '..........................',
    ],
    obstacles: [
      { type: 'turntable', x: 5.5, y: 8.5, r: 2, speed: 1.6, exit: 0 },
      { type: 'turntable', x: 20.5, y: 8.5, r: 2, speed: -1.6, exit: -90 },
      { type: 'gate', x: 13, y: 8.5, w: 0.3, h: 1, period: 5, open: 0.5, phase: 0, axis: 'y' },
    ],
    decor: [
      { t: 'tower', x: 1, y: 0.5, s: 1.3 }, { t: 'tower', x: 24, y: 0.6, s: 1.3 },
      { t: 'cloud', x: 12, y: 3, s: 1.5, z: 0.4 }, { t: 'cloud', x: 1, y: 11.5, s: 1.3, z: 0.2 }, { t: 'cloud', x: 24.5, y: 11.8, s: 1.3, z: 0.3 },
    ],
    autoDecor: { density: 0.2, seed: 113 },
  },
  {
    name: 'Drachenschlund', par: 5, theme: 'dragon', maxStrokes: 20, friction: { s: 32 },
    intro: 'Über die Lava nur per Sprungschanze – dahinter warten gleich zwei Drachen.',
    map: [
      '........................',
      '..######ssss##########..',
      '..T#####ssss##########..',
      '..######ssss##########..',
      '..####llllllllll######..',
      '..####llllllllll######..',
      '..####################..',
      '..####################..',
      '..#####xxxxxxxxxx#####..',
      '..####################..',
      '..#########H##########..',
      '........................',
    ],
    obstacles: [
      { type: 'ramp', x: 9, y: 2, w: 4, h: 2, angle: 90, minSpeed: 3, speed: 4.5, land: 2.8 },
      { type: 'mover', x0: 3.5, y0: 7, x1: 20.5, y1: 7, w: 2.4, h: 1.4, period: 8, phase: 0.2, style: 'dragon' },
      { type: 'mover', x0: 20.5, y0: 9.7, x1: 3.5, y1: 9.7, w: 2.4, h: 1.4, period: 9, phase: 0.6, style: 'dragon' },
    ],
    decor: [{ t: 'gold', x: 11.5, y: 12 }, { t: 'bones', x: 4.5, y: 11.5 }, { t: 'brazier', x: 7.5, y: 8.5 }, { t: 'brazier', x: 16.5, y: 8.5 }],
    autoDecor: { density: 0.4, seed: 127 },
  },
  {
    name: 'Hexenküche', par: 5, theme: 'witch', maxStrokes: 20,
    intro: 'Der Weg zum Loch führt durch einen Spalt, der viel zu schmal für den Ball ist. Der Schrumpftrank der Hexe hilft – aber nur für kurze Zeit.',
    map: [
      '........................',
      '..########....########..',
      '..T#######....######H#..',
      '..########....########..',
      '..########....########..',
      '..########....########..',
      '..####################..',
      '..####################..',
      '..####################..',
      '........................',
    ],
    obstacles: [
      { type: 'potion', x: 7.5, y: 4.5, r: 0.5, duration: 20, scale: 0.45 },
      { type: 'wall', x0: 14, y0: 5.9, x1: 14, y1: 7.24, extend: 0, h: 0.8 },
      { type: 'wall', x0: 14, y0: 7.76, x1: 14, y1: 9.1, extend: 0, h: 0.8 },
      { type: 'mover', x0: 3.5, y0: 3.2, x1: 8.5, y1: 3.2, w: 1, h: 1, period: 5, phase: 0, style: 'cauldron' },
      { type: 'rotor', x: 17.5, y: 4.5, blades: 2, len: 1.2, speed: 2, style: 'broom' },
    ],
    decor: [{ t: 'tower', x: 11.5, y: 2.5, s: 2, roof: '#2a1a3a', witch: true }, { t: 'cauldron', x: 20.5, y: 5.5 }, { t: 'pumpkin', x: 1, y: 7.5 }, { t: 'pumpkin', x: 22.8, y: 7.5 }],
    autoDecor: { density: 0.4, seed: 131 },
    atmo: 'mist',
  },
  {
    name: 'Königsburg', par: 5, theme: 'castle', maxStrokes: 25,
    intro: 'Der lange Weg zur Königsburg: zwei Mühlen, Ritter und Steigungen. Die Zugbrücke bleibt zu, bis der Ball die Schalterplatte in der Nische drückt – dann zählt die Zeit.',
    map: [
      '..........................',
      '........############......',
      '........#####H######......',
      '........############......',
      '........wwwww##wwwww......',
      '............####..........',
      '....#############.........',
      '....#############.........',
      '....#############.........',
      '....###...................',
      '....###...................',
      '....###############.......',
      '....###############.......',
      '....###############.......',
      '................###.......',
      '................###.......',
      '..#################.......',
      '..T################.......',
      '..#################.......',
      '..........................',
    ],
    obstacles: [
      { type: 'gate', x: 14, y: 4.5, w: 2, h: 0.3, linked: 'A', axis: 'x' },
      { type: 'switch', x: 16.3, y: 7.5, r: 0.5, duration: 14, target: 'A' },
      { type: 'field', x: 16, y: 14, w: 3, h: 2, fx: 0, fy: 2.5, style: 'slope' },
      { type: 'field', x: 4, y: 9, w: 3, h: 2, fx: 0, fy: 2.5, style: 'slope' },
      { type: 'windmill', x: 10, y: 12.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.3 },
      { type: 'windmill', x: 9, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: -1.1, phase: 1 },
      { type: 'mover', x0: 4, y0: 17, x1: 17.5, y1: 17, w: 0.7, h: 0.7, period: 8, phase: 0.3, style: 'knight' },
      { type: 'mover', x0: 9, y0: 3, x1: 18.8, y1: 3, w: 0.7, h: 0.7, period: 6, phase: 0, style: 'knight' },
    ],
    decor: [
      { t: 'tower', x: 13.5, y: 0.3, s: 2.2, roof: '#a63d3d' }, { t: 'tower', x: 7.6, y: 0.6, s: 1.5, roof: '#a63d3d' }, { t: 'tower', x: 20.4, y: 0.6, s: 1.5, roof: '#a63d3d' },
      { t: 'pine', x: 8, y: 9.8, s: 1.4 }, { t: 'pine', x: 12, y: 10.2, s: 1.2 }, { t: 'pine', x: 8, y: 15, s: 1.3 },
    ],
    autoDecor: { density: 0.45, seed: 137 },
  },
];

/* Welten: jede mit eigener Bahnliste. Neue Welten hier anhängen. */
const WORLDS = [
  { id: 'normal', name: 'Normal-Welt', short: 'Normal', courses: COURSES },
  { id: 'pro', name: 'Profi-Welt', short: 'Profi', courses: PRO_COURSES },
];
