/* Die Zwergenmine (Weltkennung 'mine'): neun Bahnen, ein Abstieg unter den Berg.
   Erzeugt von tools/mine.py – dort steht auch, warum sie so aussehen, wie sie aussehen.

   Der rote Faden ist die Dunkelheit. Jede andere Welt fragt, wie fest, wann oder wohin man
   schlägt; diese fragt, *was da vorn überhaupt liegt*. Ab Bahn 2 trägt jede Bahn einen Schleier
   ('dunkel'), der sich nur um den Ball und um die Grubenlampen öffnet. Die Lampen sind darum kein
   Schmuck, sondern das Wertvollste auf der Bahn – und jede dunkle Bahn ist so gebaut, dass der Weg
   mit ihnen allein lesbar bleibt (tools/mine.py prüft das).

   Die vier Abschnitte sind vier Paletten und zugleich der Abstieg:
     Bahn 1     'mundloch'  Tageslicht vor dem Berg
     Bahn 2-5   'stollen'   Grubenholz und Lampenschein
     Bahn 6-7   'kristall'  der Fels leuchtet selbst
     Bahn 8-9   'schmelze'  die unterste Sohle, wo das Erz flüssig wird

   Zwei eigene Maschinen (src/obstacles_mine.js):
     'sprengladung'  wirft im Takt alles im Umkreis nach außen, je näher desto weiter; die
                     brennende Lunte sagt es vorher an. Keine Strafe – man kann sich tragen lassen.
     'kippbuehne'    Bohle über dem Schacht, die zu der Seite kippt, auf der der Ball liegt:
                     über die Mitte hinaus wirft sie hinüber, davor schickt sie zurück.
     'grubenlampe'   leuchtet ein Stück Bahn aus.

   Sonst gilt dieselbe Kartenlegende wie in courses.js: 's' ist hier Geröll (bremst), 'x' ein
   Block (Grubenholz oder Fels), 'l' die Glut in den Spalten, '.' der offene Schacht. */
const MINE_COURSES = [
  {
    name: 'Mundloch', par: 3, theme: 'mundloch',
    intro: 'Vor dem Berg: Halde, Grubenholz, und hinten das Mundloch. Zwischen den Holzstapeln geht es hindurch – das Geröll bremst, wer zu weit ausholt. Ab hier wird es dunkel.',
    map: [
      '..........................',
      '..........................',
      '.###########xx###########.',
      '.###########xx###########.',
      '.#####ssss##xx###########.',
      '.#####ssss###############.',
      '.#T###################H##.',
      '.########################.',
      '.##############ssss######.',
      '.###########xx#ssss######.',
      '.###########xx###########.',
      '.###########xx###########.',
      '..........................',
      '..........................',
    ],
    obstacles: [
      { type: 'bumper', x: 8.5, y: 8.5, r: 0.6 },
      { type: 'bumper', x: 19.5, y: 4.5, r: 0.6 },
      { type: 'grubenlampe', x: 21.5, y: 9.5, r: 3.0 },
    ],
  },
  {
    name: 'Erster Stollen', par: 3, theme: 'stollen', dunkel: 0.62, lampe: 3.0,
    intro: 'Unter Tage sieht man nur, was im Licht steht. Der Schleier öffnet sich um den Ball und um jede Grubenlampe – dazwischen muss man sich merken, was man beim Hinweg gesehen hat. Den Lampen nach, dann findet man auch das Loch.',
    map: [
      '..............................',
      '..............................',
      '..........#############.......',
      '..........#############.......',
      '..........#############.......',
      '.############.......###.......',
      '.#T##########.......###.......',
      '.############.......###.......',
      '....................#########.',
      '....................######H##.',
      '....................#########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'grubenlampe', x: 11.5, y: 6.0, r: 3.8 },
      { type: 'grubenlampe', x: 11.5, y: 3.0, r: 3.4 },
      { type: 'grubenlampe', x: 21.5, y: 3.0, r: 3.8 },
      { type: 'grubenlampe', x: 21.5, y: 9.0, r: 3.4 },
      { type: 'grubenlampe', x: 26.5, y: 9.0, r: 3.2 },
    ],
  },
  {
    name: 'Sprengfeld', par: 4, theme: 'stollen', dunkel: 0.6, lampe: 3.0,
    intro: 'Eine Sprengladung liegt mitten im Weg. Der rote Kreis ist ihre Reichweite, die brennende Lunte ihre Uhr: Wer im Kreis liegt, wenn sie durchgebrannt ist, fliegt nach außen – umso weiter, je näher er lag. Das ist keine Strafe. Wer sich richtig hinlegt, lässt sich tragen.',
    map: [
      '..............................',
      '..............................',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '.#################xxx########.',
      '.##T##############xxx#####H##.',
      '.#################xxx########.',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '.#######xxx##################.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'sprengladung', x: 13.5, y: 7.5, phase: 0.0, weite: 3.2 },
      { type: 'sprengladung', x: 23.0, y: 3.5, phase: 0.45, weite: 3.2 },
      { type: 'grubenlampe', x: 9.0, y: 7.0, r: 3.4 },
      { type: 'grubenlampe', x: 14.0, y: 7.5, r: 4.2 },
      { type: 'grubenlampe', x: 22.0, y: 8.0, r: 3.8 },
      { type: 'grubenlampe', x: 26.0, y: 7.0, r: 3.2 },
    ],
  },
  {
    name: 'Kippbohle', par: 3, theme: 'stollen', dunkel: 0.6, lampe: 3.0,
    intro: 'Über den Schacht führt eine Bohle, die auf einer Achse ruht. Sie kippt zu der Seite, auf der der Ball liegt: Wer über die Mitte kommt, wird hinübergeworfen – wer davor liegenbleibt, rutscht zurück. Also nicht zaghaft.',
    map: [
      '............................',
      '............................',
      '............................',
      '............................',
      '.##########......##########.',
      '.##########################.',
      '.##T####################H##.',
      '.##########......##########.',
      '.##########......##########.',
      '............................',
      '............................',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'kippbuehne', x: 11.0, y: 5.0, w: 6.0, h: 2.0, angle: 0 },
      { type: 'grubenlampe', x: 8.0, y: 6.0, r: 3.6 },
      { type: 'grubenlampe', x: 13.5, y: 6.0, r: 4.0 },
      { type: 'grubenlampe', x: 19.0, y: 6.0, r: 3.6 },
    ],
  },
  {
    name: 'Lorensohle', par: 4, theme: 'stollen', dunkel: 0.62, lampe: 3.0,
    intro: 'Auf dieser Sohle fahren die Hunte. Zwei Loren queren den Gang im eigenen Takt – man wartet sie ab oder schlägt zwischen ihnen hindurch. Kurz vor dem Loch liegt noch eine Ladung.',
    map: [
      '................................',
      '................................',
      '................................',
      '.########xx########xx##########.',
      '.########xx########xx##########.',
      '.########xx########xx#######H##.',
      '.##################xx##########.',
      '.##T####################xx#####.',
      '.########xx#############xx#####.',
      '.########xx#############xx#####.',
      '.########xx#############xx#####.',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'rail', x0: 14.5, y0: 3.2, x1: 14.5, y1: 10.4 },
      { type: 'mover', style: 'cart', x0: 14.5, y0: 3.5, x1: 14.5, y1: 10.0, period: 4.2, r: 0.62 },
      { type: 'rail', x0: 22.5, y0: 3.2, x1: 22.5, y1: 10.4 },
      { type: 'mover', style: 'cart', x0: 22.5, y0: 10.0, x1: 22.5, y1: 3.5, period: 3.4, r: 0.62 },
      { type: 'sprengladung', x: 27.5, y: 8.5, phase: 0.3, weite: 3.0 },
      { type: 'grubenlampe', x: 7.0, y: 7.0, r: 3.4 },
      { type: 'grubenlampe', x: 14.5, y: 6.5, r: 4.0 },
      { type: 'grubenlampe', x: 22.5, y: 6.5, r: 4.0 },
      { type: 'grubenlampe', x: 28.0, y: 5.0, r: 3.4 },
    ],
  },
  {
    name: 'Kristallkammer', par: 3, theme: 'kristall', dunkel: 0.5, lampe: 3.0,
    intro: 'Die Kammer ist ausgesprengt, nicht gemauert – und der Fels leuchtet hier selbst. In der Mitte sitzt ein Magnetit, der den Ball von sich wegdrückt; die Kristalle werfen ihn zurück. Wer geradeaus zielt, kommt nie an.',
    map: [
      '..............................',
      '...........#########..........',
      '.......#################......',
      '.....#####################....',
      '....#######################...',
      '...#########################..',
      '..###########################.',
      '.############################.',
      '.#T######################H###.',
      '.############################.',
      '..###########################.',
      '...#########################..',
      '....#######################...',
      '.....#####################....',
      '.......#################......',
      '...........#########..........',
      '..............................',
    ],
    obstacles: [
      { type: 'bumper', x: 12.0, y: 5.5, r: 0.75, style: 'crystal' },
      { type: 'bumper', x: 12.0, y: 10.5, r: 0.75, style: 'crystal' },
      { type: 'bumper', x: 18.5, y: 8.0, r: 0.8, style: 'crystal' },
      { type: 'magnet', x: 15.0, y: 8.0, r: 3.4, strength: -3.2 },
      { type: 'grubenlampe', x: 8.0, y: 8.0, r: 3.6 },
      { type: 'grubenlampe', x: 15.0, y: 8.0, r: 4.4 },
      { type: 'grubenlampe', x: 22.0, y: 8.0, r: 3.8 },
    ],
  },
  {
    name: 'Zwillingsbohlen', par: 3, theme: 'kristall', dunkel: 0.55, lampe: 3.0,
    intro: 'Zweimal dasselbe, kurz hintereinander: zwei Schächte, zwei Bohlen. Zwischen ihnen ist ein schmaler Absatz. Wer über die erste Bohle zu fest hinüberkommt, steht schon auf der zweiten – und die kippt dann in die falsche Richtung.',
    map: [
      '................................',
      '................................',
      '................................',
      '................................',
      '.########.....#####.....#######.',
      '.##############################.',
      '.##T########################H##.',
      '.########.....#####.....#######.',
      '.########.....#####.....#######.',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'kippbuehne', x: 9.0, y: 5.0, w: 5.0, h: 2.0, angle: 0 },
      { type: 'kippbuehne', x: 19.0, y: 5.0, w: 5.0, h: 2.0, angle: 0 },
      { type: 'grubenlampe', x: 6.5, y: 6.0, r: 3.4 },
      { type: 'grubenlampe', x: 11.5, y: 6.0, r: 3.6 },
      { type: 'grubenlampe', x: 16.5, y: 6.0, r: 3.6 },
      { type: 'grubenlampe', x: 21.5, y: 6.0, r: 3.6 },
      { type: 'grubenlampe', x: 27.0, y: 6.0, r: 3.4 },
    ],
  },
  {
    name: 'Sohle Neun', par: 4, theme: 'schmelze', maxStrokes: 14, dunkel: 0.48, lampe: 3.0,
    intro: 'Die unterste Sohle: In den Spalten steht die Glut. Durch den Lavaspalt führt ein schmaler Steg – oder man lässt sich von der Ladung hinüberwerfen, wenn man sich traut. Dahinter wartet noch ein Schacht mit Bohle.',
    map: [
      '................................',
      '................................',
      '................................',
      '.###########ll########.....####.',
      '.###########ll########.....####.',
      '.###########ll########.....####.',
      '.##############################.',
      '.##T#########################H#.',
      '.###########ll########.....####.',
      '.###########ll########.....####.',
      '.###########ll########.....####.',
      '.###########ll########.....####.',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'sprengladung', x: 9.0, y: 7.5, phase: 0.0, weite: 3.4 },
      { type: 'kippbuehne', x: 22.0, y: 6.0, w: 5.0, h: 2.0, angle: 0 },
      { type: 'grubenlampe', x: 7.0, y: 7.0, r: 3.6 },
      { type: 'grubenlampe', x: 12.5, y: 6.5, r: 3.4 },
      { type: 'grubenlampe', x: 18.0, y: 7.0, r: 3.8 },
      { type: 'grubenlampe', x: 24.0, y: 7.0, r: 3.6 },
    ],
  },
  {
    name: 'Die Schmelze', par: 5, theme: 'schmelze', maxStrokes: 15, dunkel: 0.45, lampe: 3.0,
    intro: 'Ganz unten steht das Erz flüssig. Mitten im See liegt die Insel mit dem Loch, und nur ein schmaler Damm führt hinüber – bewacht von einer Ladung, die im Takt alles vom Damm fegt. Wer den Augenblick nach dem Knall erwischt, hat freie Bahn.',
    map: [
      '..................................',
      '..................................',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx######llll#llll##########.',
      '.#####xx####llllll#llllll########.',
      '.#####xx###lllllll#lllllll#######.',
      '.##########lllll#####lllll#######.',
      '.##T######llllll##H##llllll######.',
      '.##########lllll#####lllll##xx###.',
      '.##########lllllllllllllll##xx###.',
      '.###########lllllllllllll###xx###.',
      '.#############lllllllll#####xx###.',
      '.#################l#########xx###.',
      '.###########################xx###.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'sprengladung', x: 18.0, y: 4.5, phase: 0.0, weite: 3.0 },
      { type: 'sprengladung', x: 11.0, y: 12.5, phase: 0.5, weite: 3.2 },
      { type: 'bumper', x: 8.0, y: 4.0, r: 0.7 },
      { type: 'bumper', x: 8.0, y: 12.0, r: 0.7 },
      { type: 'grubenlampe', x: 6.0, y: 8.0, r: 3.6 },
      { type: 'grubenlampe', x: 18.0, y: 4.0, r: 3.8 },
      { type: 'grubenlampe', x: 18.0, y: 8.0, r: 4.4 },
      { type: 'grubenlampe', x: 12.0, y: 13.0, r: 3.6 },
      { type: 'grubenlampe', x: 26.0, y: 8.0, r: 3.4 },
    ],
  },
];
