/* Das Zauberreich: ein Ereignis mit drei Orten, die einen Aufstieg erzählen.
   Erzeugt von tools/zauber.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

     'lehrling'   Lehrlingsgarten   Normal    der ummauerte Garten, in dem man es lernt
     'warte'      Sternenwarte      Profi
     'loge'       Erzmagierloge     Legende

   DIE FRAGE DIESER WELT IST: *WANN FÄNGT ES AN?*
   Jede andere Welt läuft im Takt – Fallgatter, Falltür, Stacheln, Fontäne, Wracktor gehen auf und
   zu, ohne daß jemand gefragt würde, und die Aufgabe heißt immer: den Moment abpassen. Hier
   startet der Spieler die Uhr selbst. Er stößt die Blüte an, und von da an läuft SEINE Zeit. Aus
   dem Abpassen wird eine Dosierung, und das ist es, was ein Lehrling übt.

   DIE MASCHINEN (src/obstacles_zauber.js):
     'ranke'       Die Blüte anstoßen läßt eine Ranke über die Lücke wachsen – für ein paar
                   Sekunden, dann welkt sie. Ihre Felder sind in der Karte gewöhnlicher Boden;
                   daß man ohne Ranke hindurchfällt, besorgt die Maschine. Dieselbe Umkehrung wie
                   bei der Schneebrücke, und aus demselben Grund: Boden, der zur Laufzeit
                   entsteht, müßte Wegfindung, Banden und Kamera mitziehen. Boden, der wegfällt,
                   kostet eine Abfrage.
     'zauberhut'   Drei Hüte, einer leuchtet. Wer in einen rollt, kommt aus dem leuchtenden
                   heraus; wer in den leuchtenden rollt, aus dem nächsten – es gibt keine
                   Sackgasse. Das Leuchten wandert im Takt und kündigt sich an.

   DIE OPTIK KOMMT AUS DEM BESTAND. Kein einziges neues Bild für die alten Maschinen, und trotzdem
   sieht keine aus wie im Märchenland: Das Windrad ist hier eine Ranke oder ein Besen, der
   Prellklotz ein Pilz, eine Leuchtkugel oder ein Kristall, der Magnet ein Seelenlicht, die
   Drehscheibe ein Laubwirbel.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. */

const ZAUBER_GARTEN = [
  {
    name: 'Am Gartentor', par: 3, theme: 'lehrlingsgarten',
    intro: 'Der Garten des Lehrlings, kurz vor Sonnenuntergang. Zwei Hecken stehen im Weg, und dazwischen geht es im Bogen hindurch. Die beiden Springkräuter federn den Ball zurück, sobald ihre Kapsel platzt – das lohnt sich zu wissen, bevor es schwieriger wird.',
    map: [
      '..............................',
      '..............................',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.##T#####..#######..######H##.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 6, x1: 9, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 6, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 7, x1: 18, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 7, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 14.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 23.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Die erste Blüte', par: 3, theme: 'lehrlingsgarten',
    intro: 'Über die Lücke führt nichts – bis man die Blüte anstößt. Dann wächst eine Ranke hinüber und trägt vier Sekunden lang. Zu sacht geschlagen, und man liegt noch darauf, wenn sie welkt; zu hart, und man fliegt daran vorbei. Dazwischen liegt der Schlag.',
    map: [
      '................................',
      '................................',
      '................................',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '.##T########################H##.',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'ranke', x: 14, y: 3, w: 4, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 10.5, y: 6.5 } },
      { type: 'bumper', x: 21.5, y: 6.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Der Springkrautkranz', par: 3, theme: 'lehrlingsgarten',
    intro: 'Ein Rundbeet, und mitten darin das Loch. Der Kranz aus Springkraut läßt niemanden geradewegs hinein – wer es mit Gewalt versucht, kommt weiter heraus, als er hineingekommen ist. Sanft anspielen und eine Kapsel als Wand benutzen ist der kürzere Weg.',
    map: [
      '............................',
      '............................',
      '.......##############.......',
      '....####################....',
      '...######################...',
      '..########################..',
      '..########################..',
      '..#T#########H############..',
      '..########################..',
      '..########################..',
      '..########################..',
      '...######################...',
      '....####################....',
      '.......##############.......',
      '............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 2, x1: 7, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 2, x1: 21, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 3, x1: 4, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 3, x1: 24, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 4, x1: 3, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 4, x1: 25, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 5, x1: 2, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 26, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 11, x1: 2, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 11, x1: 26, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 12, x1: 3, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 12, x1: 25, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 13, x1: 4, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 13, x1: 24, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 14, x1: 7, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 14, x1: 21, y1: 13, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 16.7, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 10.7, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 10.3, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 4.3, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Zwei Blüten', par: 4, theme: 'lehrlingsgarten',
    intro: 'Zwei Lücken, zwei Blüten. Die zweite Blüte liegt hinter der ersten Ranke – man kommt also nur an sie heran, wenn die erste noch trägt. Ein Schlag, der beide schafft, ist möglich; zwei ruhige sind sicherer.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 11, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 8.5, y: 6.5 } },
      { type: 'ranke', x: 22, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 18.5, y: 6.5 } },
      { type: 'bumper', x: 27.5, y: 6.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Der Maulwurfshügel', par: 3, theme: 'lehrlingsgarten',
    intro: 'Durch die erste Hecke kommt nur, wer sich untergräbt: hinein in einen Hügel, heraus aus dem, in dem der Maulwurf gerade steckt – und wer in dessen Hügel rollt, kommt aus dem nächsten. Einer der beiden Ausgänge liegt in einer Nische: Von dort muß man erst zur Seite und dann hinaus, das kostet einen Schlag. Danach ist die Bahn noch nicht zu Ende – die zweite Hecke läßt nur oben eine Gasse, und davor federt ein Springkraut.',
    map: [
      '..........................................',
      '..........................................',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.##T########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.###########xxx##xxxxx######xxx##########.',
      '.###########xxx######x######xxx######H###.',
      '.###########xxx######x######xxx##########.',
      '.###########xxx######x######xxx##########.',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'zauberhut', takt: 2.6, phase: 0.0, r: 0.42, plaetze: [[6.0, 7.0], [18.0, 4.0], [18.0, 11.0]], style: 'maulwurf' },
      { type: 'bumper', x: 9.5, y: 10.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 7.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 34.5, y: 6.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Das Treibhaus', par: 3, theme: 'lehrlingsgarten',
    intro: 'Der Bienenstand steht quer im Weg, und der Durchlaß zwischen den Körben schließt sich im Takt mit einer Wabe. Dahinter steht in jeder der beiden Gassen ein Springkraut – wer zu gerade hindurchfährt, kommt dorthin zurück, wo er herkam. Also erst durch den Durchlaß, dann am Kraut vorbei.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##T#######################H#.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'windmill', x: 15.5, y: 6.5, w: 6.8, gap: 1.5, speed: 0.85, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'bumper', x: 21.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 21.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 8.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Blüte und Hügel', par: 4, theme: 'lehrlingsgarten',
    intro: 'Erst die Ranke über den Steg – sie trägt hier eine halbe Sekunde länger, der Weg ist weiter. Dann steht die Hecke im Weg, und wieder helfen nur die Hügel. Wer beim Steg zu viel Kraft gibt, steht drüben zu weit oben und muß noch einmal ansetzen.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.....................######xx####.',
      '.############........######xx####.',
      '.#############......#######xx####.',
      '.##########################xx####.',
      '.##T#######################xx##H#.',
      '.##########################xx####.',
      '.#############......#############.',
      '.############........############.',
      '.....................############.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 5, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 10, x1: 20, y1: 9, t: 0.22, h: 0.5 },
      { type: 'ranke', x: 14, y: 6, w: 5, h: 3, dauer: 5.5, r: 0.6, bluete: { x: 9.5, y: 7.5 } },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.62, plaetze: [[24.0, 7.0], [30.0, 10.0]], style: 'maulwurf' },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Der Blätterwirbel', par: 3, theme: 'lehrlingsgarten',
    intro: 'Zwei Beete stehen versetzt, dazwischen geht es im Zickzack. Die Pusteblume zieht an allem, was an ihr vorbeirollt – ausgerechnet in der ersten Kehre, wo man ohnehin schon aufpassen muß. Die Sonnenblume dahinter fängt den Ball und wirft ihn immer nach unten aus; wer sie trifft, spart sich die halbe Bahn.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.#########...################.',
      '.#########...################.',
      '.##T######...################.',
      '.#########...################.',
      '.#########...######.#########.',
      '.##########.######...##xx####.',
      '.#################...##xx#H##.',
      '.#################...##xx####.',
      '.#################...########.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 18, y0: 8, x1: 19, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 8, x1: 12, y1: 9, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 15.5, y: 9.5, r: 1.5, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'magnet', x: 8.5, y: 9.5, r: 2.6, strength: 5.0, slow: 0, style: 'pollen' },
      { type: 'turntable', x: 15.5, y: 5.5, r: 1.8, speed: 1.8, exit: 90, eject: 4.5, style: 'sonnenblume' },
      { type: 'bumper', x: 22.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Lehrlingsprüfung', par: 4, theme: 'lehrlingsgarten',
    intro: 'Die Prüfung: erst die Ranke, dann zwischen dem Springkraut hindurch, dann der Bienenstand im Takt – und zum Schluß noch einmal die Hüte. Wer hier unter Par bleibt, hat den Lehrlingshut verdient.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T#############################.',
      '.##############################H#.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 10, y: 3, w: 3, h: 9, dauer: 4.2, r: 0.6, bluete: { x: 7.5, y: 7.5 } },
      { type: 'bumper', x: 14.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 14.5, y: 9.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'windmill', x: 18.5, y: 7.5, w: 7.6, gap: 1.2, speed: 0.9, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'zauberhut', takt: 2.8, phase: 0.0, r: 0.42, plaetze: [[24.0, 5.0], [24.0, 10.0], [29.0, 11.0]], style: 'maulwurf' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Die Riesenblüte', par: 6, theme: 'lehrlingsgarten', maxStrokes: 18,
    intro: 'Am Ende des Gartens steht sie: sechs Blütenblätter, und das Loch liegt in ihrer Mitte. Sie öffnet und schließt sich in einem langsamen Takt – aber wenn sie zugeht, kommt der Pollenstoß, und wer dann noch im Kelch liegt und nicht im Loch, fliegt wieder hinaus. Der Kelch glüht auf, bevor es soweit ist. Das ist die einzige Warnung, und sie reicht.',
    map: [
      '.....................................#######........',
      '...................................###########......',
      '.................................###############....',
      '.................................###############....',
      '..........####..............####.################...',
      '..........####..............#####################...',
      '..........####..............######################..',
      '.........######............#######################..',
      '.#################################################..',
      '.##T####################################H#########..',
      '.#################################################..',
      '.#################################################..',
      '..................######...#######################..',
      '...................####.....#####################...',
      '...................####.....####.################...',
      '...................####.....####.###############....',
      '.................................###############....',
      '...................................###########......',
      '.....................................#######........',
    ],
    obstacles: [
      { type: 'wall', x0: 38, y0: 0, x1: 37, y1: 1, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 0, x1: 44, y1: 1, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 1, x1: 35, y1: 2, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 45, y0: 1, x1: 46, y1: 2, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 2, x1: 33, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 47, y0: 2, x1: 48, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 48, y0: 4, x1: 49, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 49, y0: 6, x1: 50, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 7, x1: 9, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 7, x1: 15, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 7, x1: 27, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 13, x1: 18, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 13, x1: 24, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 13, x1: 27, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 49, y0: 13, x1: 50, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 48, y0: 15, x1: 49, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 17, x1: 33, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 47, y0: 17, x1: 48, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 18, x1: 35, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 45, y0: 18, x1: 46, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 19, x1: 37, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 19, x1: 44, y1: 18, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 9.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'bumper', x: 16.0, y: 9.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'windmill', x: 25.5, y: 10.0, w: 4.0, gap: 1.5, speed: 0.8, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'turntable', x: 20.5, y: 13.5, r: 1.7, speed: 1.6, exit: 270, eject: 4.5, style: 'sonnenblume' },
      { type: 'zauberkreis', x: 29.5, y: 9.5, r: 1.3, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'riesenbluete', x: 40.5, y: 9.5, r: 4.6, blaetter: 6, takt: 8.5, phase: 0.0, kraft: 26, dicke: 0.38 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];

const ZAUBER_WARTE = [
  {
    name: 'Der Aufgang', par: 3, theme: 'sternenwarte',
    intro: 'Der Mond über der Terrasse zieht, solange seine Scheibe voll ist, und stößt, solange sie dunkel ist. Beim Halbmond läßt er in Ruhe. Der Gang oben ist schmal, und unter ihm ist nichts - also: erst hinsehen, dann schlagen.',
    map: [
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##########.........#########.',
      '.##T######...........#####H##.',
      '.#########...........########.',
      '.#########...........########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 15.0, y: 4.0, r: 3.4, kraft: 9.0, takt: 7.0, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'bumper', x: 22.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Das erste Sternbild', par: 4, theme: 'sternenwarte',
    intro: 'Die drei Sterne wollen angefahren werden - alle drei, in einer Reihenfolge, die man sich vorher überlegt. Erst dann geht das Tor auf. Die Linien am Boden zeigen, was noch fehlt.',
    map: [
      '................................',
      '................................',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.##T########################H##.',
      '.##############################.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'sternbild', r: 0.5, sterne: [[7.0, 5.0], [12.0, 8.0], [16.0, 5.0]], tor: { x0: 20.0, y0: 6.0, x1: 20.0, y1: 8.0 } },
      { type: 'bumper', x: 13.5, y: 6.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Zwischen den Monden', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Monde stehen im Gegentakt: Zieht der eine, stößt der andere. Dazwischen liegen zwei Stege, die keinen Platz für Irrtümer lassen. Und am Ende schwingt das Lot des Astronomen.',
    map: [
      '..................................',
      '..................................',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.############.#########.#########.',
      '.################################.',
      '.###T#########################H##.',
      '.################################.',
      '.############.#########.#########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 12, y0: 5, x1: 13, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 5, x1: 23, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 24, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 10, x1: 13, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 10, x1: 23, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 10, x1: 24, y1: 9, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 9.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.0, core: 0.4 },
      { type: 'mondzieher', x: 19.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.5, core: 0.4 },
      { type: 'pendulum', x: 27.0, y: 4.0, len: 3.5, amp: 48, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Kartensaal', par: 4, theme: 'kartensaal',
    intro: 'Zwei Regale teilen den Saal. Wer den Gang in der Mitte nimmt, kommt am Lot des Astronomen vorbei; wer die Schanze oben trifft, fliegt über das erste Regal hinweg. Vor dem Loch wandert die Kulisse hin und her – da hilft nur der richtige Augenblick.',
    map: [
      '..............................',
      '..............................',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.################xx##########.',
      '.##T#############xx#######H##.',
      '.################xx##########.',
      '.###########xxx##xx##########.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'ramp', x: 7.5, y: 2.6, w: 3.0, h: 2.8, angle: 0, minSpeed: 2.5, speed: 5.8, land: 5.2, style: 'sternschanze' },
      { type: 'pendulum', x: 24.0, y: 3.6, len: 3.2, amp: 55, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
      { type: 'bumper', x: 18.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'wandergate', x0: 21, y0: 2, x1: 21, y1: 13, gap: 2.0, style: 'kulisse' },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Das Fernrohr', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Fernrohre stehen am Rand der Terrasse und suchen sie ab, und zwischen ihnen zieht ein Mond jeden geraden Weg krumm. Der Zickzack durch die Pfeiler ist der kurze Weg - wenn man ihn im richtigen Augenblick nimmt. Wer im Strahl liegen bleibt, wird gesehen.',
    map: [
      '................................',
      '................................',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx######xx######xx#####.',
      '.##T####xx######xx######xx#####.',
      '.#######xx######xx######xx#####.',
      '.###############xx#############.',
      '.###############xx###########H#.',
      '.###############xx#############.',
      '.###############xx#############.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'eyetower', x: 12.5, y: 15.2, r: 1.1, range: 9.0, fov: 0.6, speed: 0.4, phase: 0.0, style: 'sternenspiegel' },
      { type: 'eyetower', x: 21.0, y: -0.2, r: 1.1, range: 9.0, fov: 0.6, speed: -0.36, phase: 1.6, style: 'sternenspiegel' },
      { type: 'mondzieher', x: 20.0, y: 10.5, r: 2.8, kraft: 7.0, takt: 6.5, phase: 0.3, core: 0.4 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Die Armillarsphäre', par: 4, theme: 'sternenwarte',
    intro: 'Der Messingring fährt über den Steg und nimmt mit, wer rechtzeitig darauf liegt. Dahinter wartet ein Nebelwirbel, der alles nach außen schleudert - am besten also gar nicht erst hinein.',
    map: [
      '................................',
      '................................',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......########H##.',
      '.#############.....############.',
      '.##############################.',
      '.##T###########################.',
      '.##############################.',
      '.#############.....############.',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......###########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 5, x1: 19, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 10, x1: 19, y1: 9, t: 0.22, h: 0.5 },
      { type: 'gearfield', x0: 12.5, y0: 7.5, x1: 19.5, y1: 7.5, wait: 2.2, travel: 3.0, r: 0.9, zaehne: 10, phase: 0.0, style: 'meridian' },
      { type: 'strudel', x: 24.5, y: 9.0, r: 2.8, dreh: 1, style: 'spiralnebel' },
      { type: 'bumper', x: 9.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Der Wandelgang', par: 3, theme: 'kartensaal',
    intro: 'Das wandernde Tor läuft auf und ab, und der Mond davor zieht den Ball von der Lücke weg oder in sie hinein. Zwei Uhren, die nicht zusammenpassen - man muß sich die eine aussuchen und die andere aushalten.',
    map: [
      '..................................',
      '..................................',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'zauberkreis', x: 9.5, y: 7.0, r: 1.7, wirkung: 'wirbel', takt: 0.0, phase: 0.0, kraft: 2.2 },
      { type: 'zauberkreis', x: 26.0, y: 7.0, r: 1.6, wirkung: 'bremse', takt: 4.2, phase: 0.0 },
      { type: 'wandergate', x0: 18, y0: 3, x1: 18, y1: 11, gap: 1.9, style: 'kulisse' },
      { type: 'mondzieher', x: 13.0, y: 7.0, r: 3.0, kraft: 8.5, takt: 5.5, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 9.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Hutkammer', par: 4, theme: 'kartensaal',
    intro: 'Die Hüte aus dem Garten, eine Stufe schärfer: Wo man herauskommt, steht fest - was danach mit dem Ball geschieht, entscheidet der Mond daneben. Wer den Hut im falschen Augenblick nimmt, landet dort, wo er nicht hin wollte.',
    map: [
      '................................',
      '................................',
      '.##########xx##################.',
      '.##########xx##################.',
      '.##########xx###############H##.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##T#######xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'zauberkreis', x: 16.0, y: 8.0, r: 1.7, wirkung: 'sprung', takt: 0.0, phase: 0.0, weite: 8.4 },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.42, plaetze: [[8.0, 4.0], [16.0, 11.0], [25.0, 9.0]] },
      { type: 'mondzieher', x: 16.0, y: 4.0, r: 3.0, kraft: 8.0, takt: 6.0, phase: 0.25, core: 0.4 },
      { type: 'pendulum', x: 25.0, y: 3.0, len: 3.0, amp: 45, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Sternenprüfung', par: 4, theme: 'sternenwarte',
    intro: 'Die Prüfung der Warte: erst die Blüte anstoßen und über die Ranke, dann am Mond vorbei. Danach gibt es zwei Wege. Die Schanze zwischen den Pfeilern ist schmal, wirft aber in einem Bogen über die Kulisse hinweg; wer sie verfehlt, muß den Augenblick abpassen, in dem die Gasse vor ihm steht. Wer hier unter Par bleibt, hat den Sternenhut verdient.',
    map: [
      '....................................',
      '....................................',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.###################xx##xx#########.',
      '.##################################.',
      '.##T############################H##.',
      '.##################################.',
      '.###################xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'ranke', x: 9, y: 5, w: 4, h: 5, dauer: 4.5, r: 0.6, bluete: { x: 6.5, y: 7.5 } },
      { type: 'mondzieher', x: 16.0, y: 7.0, r: 3.2, kraft: 8.5, takt: 6.5, phase: 0.15, core: 0.4 },
      { type: 'ramp', x: 21.8, y: 6.2, w: 2.0, h: 2.6, angle: 0, minSpeed: 2.5, speed: 6.0, land: 5.4, style: 'sternschanze' },
      { type: 'wandergate', x0: 28, y0: 2, x1: 28, y1: 13, gap: 2.0, style: 'kulisse' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Die Große Armillarsphäre', par: 6, theme: 'sternenwarte', maxStrokes: 20,
    intro: 'Vier Messingringe um das Loch, jeder mit einer einzigen Gasse, jeder mit eigenem Tempo und eigener Richtung – und jeder Ring hat seine eigene Wirkung, die im Band hinter ihm gilt. Draußen zieht es zur Mitte, dahinter schiebt es, dahinter dreht es einen. Erst ganz innen ist Ruhe. Die Farbe am Boden sagt vorher, was gleich gilt; die hellen Pfosten sagen, wo die Gasse gerade steht.',
    map: [
      '............................................',
      '................###########.................',
      '.............#################..............',
      '............###################.............',
      '..........#######################...........',
      '.........#########################..........',
      '........###########################.........',
      '........###########################.........',
      '.......#############################........',
      '......###############################.......',
      '......###############################.......',
      '......###############################.......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '.....#T##############H################......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '.....#################################......',
      '......###############################.......',
      '......###############################.......',
      '......###############################.......',
      '.......#############################........',
      '........###########################.........',
      '........###########################.........',
      '.........#########################..........',
      '..........#######################...........',
      '............###################.............',
      '.............#################..............',
      '................###########.................',
      '............................................',
      '............................................',
    ],
    obstacles: [
      { type: 'wall', x0: 17, y0: 1, x1: 16, y1: 2, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 1, x1: 27, y1: 2, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 2, x1: 13, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 2, x1: 30, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 3, x1: 12, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 3, x1: 31, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 11, y0: 4, x1: 10, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 4, x1: 33, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 5, x1: 9, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 5, x1: 34, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 9, y0: 6, x1: 8, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 6, x1: 35, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 8, x1: 7, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 8, x1: 36, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 9, x1: 6, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 9, x1: 37, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 6, y0: 12, x1: 5, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 12, x1: 38, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 6, y0: 23, x1: 5, y1: 22, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 23, x1: 38, y1: 22, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 26, x1: 6, y1: 25, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 26, x1: 37, y1: 25, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 27, x1: 7, y1: 26, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 27, x1: 36, y1: 26, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 9, y0: 29, x1: 8, y1: 28, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 29, x1: 35, y1: 28, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 30, x1: 9, y1: 29, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 30, x1: 34, y1: 29, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 11, y0: 31, x1: 10, y1: 30, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 31, x1: 33, y1: 30, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 32, x1: 12, y1: 31, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 32, x1: 31, y1: 31, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 33, x1: 13, y1: 32, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 33, x1: 30, y1: 32, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 34, x1: 16, y1: 33, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 34, x1: 27, y1: 33, t: 0.22, h: 0.5 },
      { type: 'armillar', x: 21.5, y: 17.5, dicke: 0.3, ringe: [{ r: 14.0, gasse: 0.6, tempo: 0.26, phase: 0.0, wirkung: 'zug' }, { r: 10.4, gasse: 0.68, tempo: -0.4, phase: 0.33, wirkung: 'schub' }, { r: 6.9, gasse: 0.78, tempo: 0.58, phase: 0.66, wirkung: 'wirbel' }, { r: 3.4, gasse: 0.95, tempo: -0.34, phase: 0.15 }] },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];

const ZAUBER_LOGE = [
  {
    name: 'Der Winkelgang', par: 4, theme: 'erzmagierloge',
    intro: 'Drei Läufe, zwei Kehren – und in den Kehren steht keine Ecke, sondern eine Schräge. Wer mit Tempo hineinspielt, kommt um sie herum; wer zu sacht spielt, liegt davor. Das ist die Rechnung, die in dieser Welt jede Bahn verlangt.',
    map: [
      '....................................................',
      '....................................................',
      '....................................................',
      '....................................................',
      '.....................#############..................',
      '....................###############.................',
      '...................#################................',
      '..................###################...............',
      '..................######.......######...............',
      '..................#####.........#####...............',
      '.................######.........######..............',
      '..#####################.........##################..',
      '..####################...........#################..',
      '..##T################.............############H###..',
      '..##################...............###############..',
      '....................................................',
      '....................................................',
      '....................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 22, y0: 4, x1: 21, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 4, x1: 34, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 5, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 5, x1: 35, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 6, x1: 19, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 6, x1: 36, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 7, x1: 18, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 7, x1: 37, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 9, x1: 24, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 9, x1: 31, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 10, x1: 17, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 10, x1: 38, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 12, x1: 23, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 12, x1: 32, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 13, x1: 22, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 13, x1: 33, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 14, x1: 21, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 14, x1: 34, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 15, x1: 20, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 15, x1: 35, y1: 14, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 8.0, y: 13.0, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'lightning', x: 27.0, y: 5.5, w: 3.0, h: 3.2, period: 4.4, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'zauberkreis', x: 40.0, y: 13.0, r: 1.2, wirkung: 'bremse', takt: 4.2, phase: 0.0 },
      { type: 'grubenlampe', x: 46.0, y: 13.0, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Der Bannlauf', par: 5, theme: 'erzmagierloge',
    intro: 'Zweiundzwanzig Kacheln Leere, und darüber nur die Fernschleuder. Ihre drei Ringe taumeln, solange sie wartet; sobald sie einen Ball hat, richten sie sich aus – und wenn alle drei in einer Ebene stehen, fliegt er. Sie schwenkt dabei, und nicht jeder Augenblick trifft das andere Ufer: Das Fadenkreuz am Boden sagt vorher, wohin. Drüben landet man am falschen Ende – der Weg zum Loch führt ganz nach Osten, um die Schräge herum nach oben und die Galerie wieder zurück.',
    map: [
      '........................................................',
      '........................................................',
      '........................................................',
      '........................................................',
      '.....................................#############......',
      '....................................##H############.....',
      '...................................#################....',
      '..##############...................##################...',
      '..##T#######A####..............................######...',
      '..################..............................#####...',
      '..#################.............................#####...',
      '.............######.............................#####...',
      '..............######...........................######...',
      '..............#############...................#######...',
      '...............############...................######....',
      '................a##########...................#####.....',
      '.................##########...................####......',
      '........................................................',
      '........................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 38, y0: 4, x1: 37, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 49, y0: 4, x1: 50, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 5, x1: 36, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 50, y0: 5, x1: 51, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 6, x1: 35, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 51, y0: 6, x1: 52, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 7, x1: 16, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 7, x1: 53, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 8, x1: 17, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 48, y0: 9, x1: 47, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 9, x1: 18, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 10, x1: 19, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 12, x1: 13, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 12, x1: 20, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 48, y0: 12, x1: 47, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 14, x1: 14, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 14, x1: 53, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 15, x1: 15, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 51, y0: 15, x1: 52, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 50, y0: 16, x1: 51, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 17, x1: 17, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 49, y0: 17, x1: 50, y1: 16, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 8.0, y: 8.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'copperpipe', pair: 'A', angle: 0, style: 'siegelroehre' },
      { type: 'cannon', x: 24.0, y: 14.5, base: 0.0, amp: 0.13, speed: 0.5, phase: 0.0, range: 22.0, loadTime: 1.1, catchR: 0.7, flySpeed: 8, style: 'fernschleuder' },
      { type: 'zauberkreis', x: 48.5, y: 14.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'grubenlampe', x: 40.0, y: 5.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Das Bannmal', par: 5, theme: 'bannkreis',
    intro: 'Vier Sterne in vier Nischen, und das Bannmal vor dem Loch geht erst auf, wenn alle brennen. Die Nischen haben schräge Schultern – man muß nicht hineinfahren, man kann hineinspielen. In der Gruft sieht man nur, was im Licht steht.',
    map: [
      '........................................................',
      '........................................................',
      '........................................................',
      '........................................................',
      '........................................................',
      '........####................####........................',
      '.......######..............######.......................',
      '.......###A##..............######.......................',
      '......########............#######.......................',
      '..###############################xxx###############.....',
      '..#T#############################xxx###############.....',
      '..###############################################H#.....',
      '..#################################################.....',
      '................########............########............',
      '.................######..............##a###.............',
      '.................######..............######.............',
      '..................####................####..............',
      '........................................................',
      '........................................................',
      '........................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 9, y0: 5, x1: 8, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 11, y0: 5, x1: 12, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 5, x1: 28, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 5, x1: 32, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 6, x1: 7, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 6, x1: 13, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 6, x1: 27, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 6, x1: 33, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 8, x1: 6, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 8, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 8, x1: 26, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 14, x1: 16, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 14, x1: 24, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 14, x1: 36, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 14, x1: 44, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 16, x1: 17, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 16, x1: 23, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 16, x1: 37, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 16, x1: 43, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 17, x1: 18, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 17, x1: 22, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 17, x1: 38, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 17, x1: 42, y1: 16, t: 0.22, h: 0.5 },
      { type: 'copperpipe', pair: 'A', angle: 90, style: 'siegelroehre' },
      { type: 'sternbild', r: 0.5, sterne: [[9.0, 6.0], [19.0, 15.0], [29.0, 6.0], [39.0, 15.0]], tor: { x0: 45.0, y0: 9.0, x1: 45.0, y1: 13.0 } },
      { type: 'zauberkreis', x: 14.5, y: 10.5, r: 1.2, wirkung: 'schub', takt: 4.4, phase: 0.0 },
      { type: 'zauberkreis', x: 24.0, y: 10.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'zauberkreis', x: 31.0, y: 10.5, r: 1.2, wirkung: 'sprung', takt: 0.0, phase: 0.0, weite: 7.0 },
      { type: 'grubenlampe', x: 9.5, y: 6.5, r: 3.8, style: 'bannlicht' },
      { type: 'grubenlampe', x: 39.5, y: 15.5, r: 3.8, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Rat der Neun', par: 5, theme: 'erzmagierloge',
    intro: 'Der Ratssaal. In seiner Mitte steht die Raute der Neun – vier Schrägen, die nach allen Seiten abweisen, und darin brennt ein Bannkreis im Takt. Geradeaus geht hier nichts; man muß sich aussuchen, an welcher Kante man vorbeiwill. Die Fernschleuder am Eingang wirft über die Raute hinweg, aber sie schwenkt weit – wer im falschen Augenblick hineinrollt, fliegt über den Saal hinaus.',
    map: [
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................#####################...........',
      '.................#######################..........',
      '................#########################.........',
      '...............###########################........',
      '..............#############################.......',
      '.............###############################......',
      '..##########.################################.....',
      '..#T####################################H####.....',
      '..###########################################.....',
      '..##########.################################.....',
      '.............###############################......',
      '..............#############################.......',
      '...............###########################........',
      '................#########################.........',
      '.................#######################..........',
      '..................#####################...........',
      '..................................................',
      '..................................................',
      '..................................................',
      '..................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 19, y0: 4, x1: 18, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 4, x1: 39, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 5, x1: 17, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 5, x1: 40, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 6, x1: 16, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 40, y0: 6, x1: 41, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 7, x1: 15, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 7, x1: 42, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 8, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 8, x1: 43, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 9, x1: 13, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 9, x1: 44, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 44, y0: 10, x1: 45, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 44, y0: 14, x1: 45, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 15, x1: 13, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 15, x1: 44, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 16, x1: 14, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 16, x1: 43, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 17, x1: 15, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 17, x1: 42, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 18, x1: 16, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 40, y0: 18, x1: 41, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 19, x1: 17, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 19, x1: 40, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 20, x1: 18, y1: 19, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 20, x1: 39, y1: 19, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 11.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'cannon', x: 17.0, y: 11.5, base: 0.0, amp: 0.55, speed: 0.5, phase: 0.0, range: 18.0, loadTime: 1.1, catchR: 0.7, flySpeed: 8, style: 'fernschleuder' },
      { type: 'wall', x0: 23.5, y0: 11.5, x1: 28.0, y1: 7.0, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 28.0, y0: 7.0, x1: 32.5, y1: 11.5, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 32.5, y0: 11.5, x1: 28.0, y1: 16.0, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 28.0, y0: 16.0, x1: 23.5, y1: 11.5, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 20.0, y0: 5.5, x1: 24.5, y1: 10.0, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 20.0, y0: 17.5, x1: 24.5, y1: 13.0, t: 0.42, h: 0.85 },
      { type: 'zauberkreis', x: 28.0, y: 11.5, r: 1.6, wirkung: 'bann', takt: 5.0, phase: 0.0 },
      { type: 'grubenlampe', x: 40.0, y: 11.5, r: 4.2, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Die Winkelgalerie', par: 5, theme: 'erzmagierloge',
    intro: 'Sechs Kehren, alle schräg, und dazwischen zwei Banden, die frei im Gang stehen. Nichts hier hat einen Takt, auf den man warten könnte – es gibt nur Winkel. Der Mund der Siegelröhre in der dritten Kehre überspringt zwei davon, wenn man ihn trifft.',
    map: [
      '......................................................',
      '......................................................',
      '......................................................',
      '..##########..........................................',
      '..##T########.........................................',
      '..############........................................',
      '..#############......................###############..',
      '.........######.....................###########H####..',
      '..........######...................#################..',
      '..........##############..........##################..',
      '...........##############.........######..............',
      '............############A#........#####...............',
      '.............##############.......#####...............',
      '.....................######.......#####...............',
      '......................######.....######...............',
      '......................#################...............',
      '.......................############a##................',
      '........................#############.................',
      '.........................###########..................',
      '......................................................',
      '......................................................',
      '......................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 11, y0: 3, x1: 12, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 4, x1: 13, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 6, x1: 15, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 6, x1: 37, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 8, x1: 9, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 7, x1: 36, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 8, x1: 16, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 8, x1: 35, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 11, y0: 10, x1: 10, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 9, x1: 24, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 9, x1: 34, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 11, x1: 11, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 10, x1: 25, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 11, x1: 40, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 12, x1: 12, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 11, x1: 26, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 13, x1: 13, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 12, x1: 27, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 14, x1: 21, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 14, x1: 28, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 14, x1: 33, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 16, x1: 22, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 16, x1: 39, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 17, x1: 23, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 17, x1: 38, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 18, x1: 24, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 18, x1: 37, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 19, x1: 25, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 19, x1: 36, y1: 18, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 5.0, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'copperpipe', pair: 'A', angle: 0, style: 'siegelroehre' },
      { type: 'wall', x0: 17.0, y0: 9.0, x1: 19.0, y1: 11.0, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 29.0, y0: 19.0, x1: 31.0, y1: 17.0, t: 0.42, h: 0.85 },
      { type: 'zauberkreis', x: 44.0, y: 8.0, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'grubenlampe', x: 47.0, y: 8.0, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Der Bannschacht', par: 4, theme: 'erzmagierloge',
    intro: 'Die Galerie bricht über der Leere ab. Hinüber hebt nur der Bannschacht, und in den muß man mit Schwung hineinrollen – wer zu sacht spielt, liegt vor dem Stein am Ende. Dann bleibt der lange Weg am Grund, und dort zieht der Mond.',
    map: [
      '........................................................',
      '........................................................',
      '........................................................',
      '........................................................',
      '..######################x........#################......',
      '..#T####################x........################H#.....',
      '..######################x........###################....',
      '..######################x........###################....',
      '..######................................#######.........',
      '..#####..................................#####..........',
      '..#####..................................#####..........',
      '..#####..................................#####..........',
      '..#####..................................#####..........',
      '..#####..................................#####..........',
      '..######................................###a##..........',
      '..############################################..........',
      '..###########################################...........',
      '...###########################A#############............',
      '....#######################################.............',
      '........................................................',
      '........................................................',
      '........................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 49, y0: 4, x1: 50, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 50, y0: 5, x1: 51, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 51, y0: 6, x1: 52, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 9, x1: 8, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 9, x1: 40, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 46, y0: 9, x1: 47, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 7, y0: 14, x1: 8, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 14, x1: 40, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 45, y0: 16, x1: 46, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 17, x1: 2, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 44, y0: 17, x1: 45, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 18, x1: 3, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 18, x1: 44, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 19, x1: 4, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 19, x1: 43, y1: 18, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 9.0, y: 5.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'copperpipe', pair: 'A', angle: 270, style: 'siegelroehre' },
      { type: 'cannon', x: 14.0, y: 16.5, base: 0.0, amp: 0.08, speed: 0.9, phase: 0.0, range: 12.0, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'updraft', x: 20, y: 4, w: 3, h: 3, minSpeed: 2.5, land: 14.0, fly: 8.5, style: 'bannschacht' },
      { type: 'mondzieher', x: 24.0, y: 16.5, r: 3.4, kraft: 8.0, takt: 6.5, phase: 0.3, core: 0.4 },
      { type: 'zauberkreis', x: 43.0, y: 12.0, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'grubenlampe', x: 49.0, y: 5.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Das Wanderloch', par: 5, theme: 'bannkreis',
    intro: 'Das Loch wandert zwischen drei Stellen im Schacht am Ende, und man sieht immer nur die, vor der man steht. Vor dem Schacht steht eine Schräge – wer sie richtig trifft, wird hineingeworfen statt daran vorbei.',
    map: [
      '......................................................',
      '......................................................',
      '......................................................',
      '...................#############........########......',
      '..................###############.......##H#####......',
      '.................#################......########......',
      '................###################.....########......',
      '...............#######.......######.....########......',
      '..###################.........#####.....########......',
      '..#T################..........#####.....########......',
      '..#################...........#####.....########......',
      '..################............#####.....########......',
      '..............................######...#########......',
      '..............................##################......',
      '...............................################.......',
      '................................##############........',
      '.................................############.........',
      '......................................................',
      '......................................................',
      '......................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 20, y0: 3, x1: 19, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 3, x1: 32, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 4, x1: 18, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 4, x1: 33, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 5, x1: 17, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 5, x1: 34, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 6, x1: 16, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 6, x1: 35, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 7, x1: 15, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 22, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 8, x1: 29, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 9, x1: 21, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 10, x1: 20, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 11, x1: 19, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 12, x1: 18, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 12, x1: 36, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 40, y0: 12, x1: 39, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 14, x1: 30, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 47, y0: 14, x1: 48, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 15, x1: 31, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 46, y0: 15, x1: 47, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 16, x1: 32, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 45, y0: 16, x1: 46, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 17, x1: 33, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 44, y0: 17, x1: 45, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wanderloch', stellen: [[42.5, 4.5], [42.5, 9.5], [42.5, 14.5]], phase: 0.0, style: 'siegelloch' },
      { type: 'zauberkreis', x: 8.0, y: 9.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'lightning', x: 25.0, y: 4.5, w: 3.0, h: 3.2, period: 4.6, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'cannon', x: 32.0, y: 9.5, base: 0.0, amp: 0.48, speed: 0.6, phase: 0.0, range: 9.5, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'wall', x0: 35.0, y0: 16.0, x1: 39.0, y1: 12.0, t: 0.42, h: 0.85 },
      { type: 'zauberkreis', x: 42.5, y: 11.0, r: 1.2, wirkung: 'bremse', takt: 4.6, phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Siegelkammer', par: 5, theme: 'erzmagierloge',
    intro: 'Auf dieser Bahn gibt es keinen Weg zu Fuß. Jedes Stück hängt am nächsten über eine Maschine: erst die Siegelröhre nach oben, dann die zweite hinunter in die Kammer, dann die Schleuder hinüber. Drüben bringt eine Schräge den Ball um die Ecke.',
    map: [
      '..........................................................',
      '..........................................................',
      '..........................................................',
      '.......................###########........................',
      '......................a#########B#........................',
      '.....................############..........##########.....',
      '.....................###########..........##H#########....',
      '.........................................##############...',
      '.........................................###############..',
      '..#############...................................######..',
      '..#T########A##....................................#####..',
      '..#############....................................#####..',
      '..#############...###################.............######..',
      '..................###################...################..',
      '..................###################...######c########...',
      '..................####b##############...##############....',
      '...................#################....#############.....',
      '....................#############C#.......................',
      '.....................#############........................',
      '..........................................................',
      '..........................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 24, y0: 3, x1: 23, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 5, x1: 34, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 5, x1: 21, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 6, x1: 33, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 44, y0: 5, x1: 43, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 5, x1: 53, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 7, x1: 32, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 43, y0: 6, x1: 42, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 6, x1: 54, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 7, x1: 41, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 7, x1: 55, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 8, x1: 56, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 51, y0: 10, x1: 50, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 51, y0: 12, x1: 50, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 14, x1: 56, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 15, x1: 55, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 16, x1: 18, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 16, x1: 37, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 16, x1: 54, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 17, x1: 19, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 17, x1: 36, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 17, x1: 53, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 18, x1: 20, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 18, x1: 35, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 19, x1: 21, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 19, x1: 34, y1: 18, t: 0.22, h: 0.5 },
      { type: 'copperpipe', pair: 'A', angle: 0, style: 'siegelroehre' },
      { type: 'copperpipe', pair: 'B', angle: 90, style: 'siegelroehre' },
      { type: 'copperpipe', pair: 'C', angle: 0, style: 'siegelroehre' },
      { type: 'zauberkreis', x: 27.0, y: 4.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'cannon', x: 30.0, y: 14.5, base: 0.0, amp: 0.09, speed: 0.8, phase: 0.0, range: 10.5, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'wall', x0: 44.0, y0: 13.0, x1: 48.0, y1: 17.0, t: 0.42, h: 0.85 },
      { type: 'zauberkreis', x: 48.0, y: 6.5, r: 1.2, wirkung: 'bremse', takt: 4.0, phase: 0.0 },
      { type: 'grubenlampe', x: 44.0, y: 6.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Der Erzmagier', par: 5, theme: 'erzmagierloge', maxStrokes: 18,
    intro: 'Die letzte Bahn vor dem Wächter: erst der Bannschlag, dann die lange Kehre nach unten – und dort steht die Fernschleuder und wirft achtzehneinhalb Kacheln weit ans andere Ende. Auch sie schwenkt; das andere Ufer ist schmal, und daneben ist nichts. Danach die Galerie zurück nach Westen. Keine einzige rechtwinklige Ecke auf der ganzen Strecke.',
    map: [
      '............................................................',
      '............................................................',
      '............................................................',
      '...............#############................................',
      '..............###############...............................',
      '.............#################..............................',
      '............###################.............................',
      '............######.......######..........##############.....',
      '...........######.........#####.........##H#############....',
      '..###############.........#####........##################...',
      '..#T##########A#..........#####........###################..',
      '..#############...........#####.....................######..',
      '..############............#####......................#####..',
      '..........................##a##......................#####..',
      '..........................#####......................#####..',
      '..........................######....................######..',
      '..........................#################.....##########..',
      '...........................################.....#########...',
      '............................###############.....########....',
      '.............................##############.....#######.....',
      '............................................................',
      '............................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 16, y0: 3, x1: 15, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 3, x1: 28, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 4, x1: 14, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 4, x1: 29, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 5, x1: 13, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 5, x1: 30, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 6, x1: 12, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 6, x1: 31, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 8, x1: 18, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 8, x1: 25, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 42, y0: 7, x1: 41, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 7, x1: 55, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 8, x1: 11, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 41, y0: 8, x1: 40, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 8, x1: 56, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 10, x1: 17, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 40, y0: 9, x1: 39, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 56, y0: 9, x1: 57, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 11, x1: 16, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 57, y0: 10, x1: 58, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 12, x1: 15, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 12, x1: 52, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 13, x1: 14, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 15, x1: 32, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 15, x1: 52, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 17, x1: 26, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 57, y0: 17, x1: 58, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 18, x1: 27, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 56, y0: 18, x1: 57, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 19, x1: 28, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 19, x1: 56, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 20, x1: 29, y1: 19, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 20, x1: 55, y1: 19, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 10.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'copperpipe', pair: 'A', angle: 90, style: 'siegelroehre' },
      { type: 'lightning', x: 21.0, y: 4.5, w: 3.0, h: 3.2, period: 4.0, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'zauberkreis', x: 28.0, y: 12.0, r: 1.2, wirkung: 'bremse', takt: 4.4, phase: 0.0 },
      { type: 'cannon', x: 30.0, y: 17.5, base: 0.0, amp: 0.13, speed: 0.5, phase: 0.0, range: 18.5, loadTime: 1.1, catchR: 0.7, flySpeed: 8, style: 'fernschleuder' },
      { type: 'wall', x0: 44.0, y0: 10.0, x1: 48.0, y1: 14.0, t: 0.42, h: 0.85 },
      { type: 'grubenlampe', x: 42.0, y: 8.5, r: 4.2, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Der Bannwächter', par: 5, theme: 'erzmagierloge', maxStrokes: 18,
    intro: 'Am Ende der Loge steht er und sieht zu. Sein Arm dreht sich dorthin, wo der Ball liegt, dann glüht das Siegel unter ihm auf – und wer beim Einschlag im Keil steht, fliegt quer durch den Saal zurück. Vor ihm steht eine Raute, hinter der man sich wegducken kann. Der Arm ist langsamer als ein Ball; das ist alles, was man braucht.',
    map: [
      '..............................................................',
      '..............................................................',
      '.......................................##############.........',
      '......................................################........',
      '.................###########.........##################.......',
      '................#############.......####################......',
      '...............###############.....######################.....',
      '..............#################...########################....',
      '..............######.....######...#########################...',
      '.............######.......#####...##########################..',
      '..#################.......#####...##########################..',
      '..#T##############........#####...###################H######..',
      '..###############.........#####...##########################..',
      '..##############..........#####...##########################..',
      '..........................#####...##########################..',
      '..........................######.##########################...',
      '..........................################################....',
      '...........................##############################.....',
      '............................############################......',
      '.............................##########################.......',
      '.................................#####################........',
      '..................................###################.........',
      '..............................................................',
      '..............................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 40, y0: 2, x1: 39, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 2, x1: 53, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 3, x1: 38, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 3, x1: 54, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 4, x1: 17, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 4, x1: 28, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 38, y0: 4, x1: 37, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 4, x1: 55, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 5, x1: 16, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 5, x1: 29, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 5, x1: 36, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 5, x1: 56, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 6, x1: 15, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 6, x1: 30, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 6, x1: 35, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 56, y0: 6, x1: 57, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 7, x1: 14, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 7, x1: 31, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 7, x1: 34, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 57, y0: 7, x1: 58, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 9, x1: 20, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 9, x1: 25, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 58, y0: 8, x1: 59, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 9, x1: 13, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 59, y0: 9, x1: 60, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 18, y0: 11, x1: 19, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 12, x1: 18, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 13, x1: 17, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 14, x1: 16, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 59, y0: 15, x1: 60, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 15, x1: 32, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 15, x1: 33, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 58, y0: 16, x1: 59, y1: 15, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 17, x1: 26, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 57, y0: 17, x1: 58, y1: 16, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 18, x1: 27, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 56, y0: 18, x1: 57, y1: 17, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 29, y0: 19, x1: 28, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 55, y0: 19, x1: 56, y1: 18, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 30, y0: 20, x1: 29, y1: 19, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 54, y0: 20, x1: 55, y1: 19, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 21, x1: 33, y1: 20, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 53, y0: 21, x1: 54, y1: 20, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 52, y0: 22, x1: 53, y1: 21, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 11.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'lightning', x: 22.0, y: 5.5, w: 3.0, h: 3.2, period: 4.2, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'zauberkreis', x: 28.0, y: 12.0, r: 1.2, wirkung: 'bremse', takt: 4.4, phase: 0.0 },
      { type: 'cannon', x: 36.0, y: 17.0, base: 0.0, amp: 0.3, speed: 0.6, phase: 0.0, range: 8.0, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'wall', x0: 37.8, y0: 11.5, x1: 41.0, y1: 8.3, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 41.0, y0: 8.3, x1: 44.2, y1: 11.5, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 44.2, y0: 11.5, x1: 41.0, y1: 14.7, t: 0.42, h: 0.85 },
      { type: 'wall', x0: 41.0, y0: 14.7, x1: 37.8, y1: 11.5, t: 0.42, h: 0.85 },
      { type: 'bannwaechter', x: 47.0, y: 11.5, r: 2.2, weite: 13.0, keil: 0.4, takt: 5.0, phase: 0.0, folgen: 1.1, wucht: 15, warn: 1.2, schlag: 0.3 },
      { type: 'grubenlampe', x: 53.0, y: 11.5, r: 4.2, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];
