/* Schattenreich: Stufe „Legende“ – zehn Bahnen mit schmalen Wegen und Höhenstufen: Friedhöfe mit Rabenschwärmen, Knochenstege über
   Schattenfeuer, Fallbeile, verfluchte Ritter, Sargfähren über den Totensee, der Turm des Auges, das schwarze Schloss mit Thronsaal,
   die Gruft der Sensen und zuletzt das Herz der Finsternis. Neue Tiere und Geräte: Riesenfledermaus, Basilisk (Riesenarmbrust). */
const SHADOW_COURSES = [
  {
    name: 'Friedhofspforte', par: 3, theme: 'shadow', maxStrokes: 15, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 10, w: 11, h: 2, look: { x: 14, y: 10.5 } }, { x: 13, y: 6, w: 2, h: 6, look: { x: 14, y: 4.5 } }, { x: 13, y: 4, w: 14, h: 2, look: { x: 25.5, y: 4.5 } }],
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '.............############H#...',
      '.............##############...',
      '.............##...............',
      '.............##...............',
      '.............##...............',
      '.............##...............',
      '..#T###########...............',
      '..#############...............',
      '..............................',
      '..............................',
    ],
    intro: 'Durch das Friedhofstor ins Schattenreich. Der Weg ist schmal: Über die erste Gerade zieht ein Rabenschwarm hin und her und trägt den Ball mit – oder weht ihn zurück. Hinter zwei Kehren streift ein Geist umher, und im Torbogen hängt das erste Fallbeil: Nie darunter liegen bleiben, wenn es fällt.',
    obstacles: [
      { type: 'wave', style: 'ravens', x0: 4, y0: 11, x1: 12, y1: 11, w: 0.6, h: 2.4, period: 6.5, push: 12, brake: 0.55 },
      { type: 'wall', x0: 13, y0: 12, x1: 15, y1: 10, extend: 0 },
      { type: 'wall', x0: 13, y0: 6, x1: 15, y1: 4, extend: 0 },
      { type: 'mover', x0: 16, y0: 4.9, x1: 20, y1: 5.1, w: 0.8, h: 0.8, period: 4.5, style: 'ghost', e: 0.5 },
      { type: 'guillotine', x: 22.5, y: 5, w: 0.35, h: 2, period: 5, phase: 0, hold: 0.32 },
      { type: 'wall', x0: 27, y0: 4, x1: 26.4, y1: 4.5, extend: 0 },
      { type: 'wall', x0: 27, y0: 6, x1: 26.4, y1: 5.5, extend: 0 },
    ],
    decor: [
      { t: 'gravestone', x: 1.4, y: 9.4, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 5.5, y: 9.2, s: 1.2 }, { t: 'deadTree', x: 9.5, y: 8.8, s: 1.5 }, { t: 'ghostlight', x: 11.5, y: 12.6, s: 1.2, seed: 0.3 },
      { t: 'gravestone', x: 4.5, y: 12.6, s: 1.2, seed: 0.7 }, { t: 'gravestone', x: 15.5, y: 12.4, s: 1.2, seed: 0.2 }, { t: 'deadTree', x: 16.5, y: 8, s: 1.6 }, { t: 'gravecross', x: 11.5, y: 6.5, s: 1.2 },
      { t: 'pillar', x: 12.4, y: 3.4, s: 1.1 }, { t: 'torchPurple', x: 18.5, y: 3.4, s: 1.1 }, { t: 'torchPurple', x: 25.5, y: 6.6, s: 1.1 }, { t: 'skull', x: 20.5, y: 6.5 }, { t: 'bones', x: 16, y: 6.6, s: 1.2 }, { t: 'obsidian', x: 27.6, y: 3.4, s: 1.2 }, { t: 'urnDark', x: 27.6, y: 6.6, s: 1.0 },
    ],
    autoDecor: { density: 0.2, seed: 601 },
  },
  {
    name: 'Knochensteg', par: 4, theme: 'shadow', maxStrokes: 18, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 6, w: 4, h: 4, look: { x: 14, y: 7.5 } }, { x: 6, y: 7, w: 8, h: 2, look: { x: 14.5, y: 7.5 } }, { x: 14, y: 5, w: 2, h: 4, look: { x: 14.5, y: 3.5 } }, { x: 14, y: 3, w: 11, h: 2, look: { x: 26, y: 3.5 } }],
    map: [
      '..................................',
      '..................................',
      '..lllllllllllllllllllllllll#####..',
      '..lllllllllllloooooooooooll#####..',
      '..lllllllllllloooooooooooll###H#..',
      '..lllllllllllloolllllllllll#####..',
      '..####lllllllloolllllllllll#####..',
      '..#T##oooooooooollllllllllllllll..',
      '..####oooooooooollllllllllllllll..',
      '..####llllllllllllllllllllllllll..',
      '..llllllllllllllllllllllllllllll..',
      '..llllllllllllllllllllllllllllll..',
      '..llllllllllllllllllllllllllllll..',
      '..llllllllllllllllllllllllllllll..',
      '..................................',
      '..................................',
    ],
    intro: 'Zwei Kacheln breite Stege aus Knochen ohne Geländer führen über den Feuerstrom. Wer zu schnell in die Kehre geht, kippt ins Schattenfeuer. Auf dem ersten Steg fahren Knochenstacheln aus, am Ende klafft eine Lücke: Nur die Rampe bringt hinüber – und darüber jagt im Takt eine Riesenfledermaus.',
    obstacles: [
      { type: 'spikes', x: 10.5, y: 8, w: 1, h: 2, period: 4.2, up: 0.4, phase: 0 },
      { type: 'wall', x0: 14, y0: 9, x1: 16, y1: 7, extend: 0 },
      { type: 'wall', x0: 14, y0: 5, x1: 16, y1: 3, extend: 0 },
      { type: 'ramp', x: 23, y: 3, w: 2, h: 2, angle: 0, minSpeed: 2.5, speed: 4.6, land: 3.2 },
      { type: 'sharkjump', style: 'bat', x: 26, y: 4, w: 1.2, h: 2.4, period: 8, jump: 0.16, phase: 0.3, axis: 'y', height: 1.4 },
      // Geländer um die Zielinsel: nach der Landung darf der Ball nicht mehr ins Schattenfeuer rollen
      { type: 'wall', x0: 27, y0: 2, x1: 27, y1: 7, extend: 0 },
      { type: 'wall', x0: 27, y0: 7, x1: 32, y1: 7, extend: 0 },
      { type: 'bumper', x: 28.5, y: 2.6, r: 0.38, style: 'grave', kick: 7 },
      { type: 'wall', x0: 32, y0: 3, x1: 31.4, y1: 4, extend: 0 },
      { type: 'wall', x0: 32, y0: 6, x1: 31.4, y1: 5, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.6, s: 1.6 }, { t: 'gravestone', x: 1.4, y: 10.6, s: 1.2, seed: 0.4 }, { t: 'skull', x: 2.4, y: 4.6 }, { t: 'bones', x: 6, y: 14.6, s: 1.3 }, { t: 'bones', x: 20, y: 14.6, s: 1.3 },
      { t: 'pillar', x: 12.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 25.6, y: 1.4, s: 1.1 }, { t: 'skull', x: 32.5, y: 1.6 }, { t: 'gravecross', x: 32.6, y: 7.4, s: 1.2 }, { t: 'deadTree', x: 32.6, y: 12.6, s: 1.5 }, { t: 'ghostlight', x: 12, y: 14.6, s: 1.1, seed: 0.7 },
    ],
    autoDecor: { density: 0.12, seed: 603 },
  },
  {
    name: 'Fallbeilgasse', par: 4, theme: 'shadow', maxStrokes: 18, hStep: 0.5, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 5, w: 12, h: 2, look: { x: 15, y: 5.5 } }, { x: 14, y: 5, w: 10, h: 2, look: { x: 25, y: 5.5 } }, { x: 24, y: 5, w: 10, h: 2, look: { x: 32.5, y: 5.5 } }],
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '..#T################ll##########H#..',
      '..##################ll############..',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    heights: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '..00000000000011111111112222222222..',
      '..00000000000011111111112222222222..',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    intro: 'Die Gasse der Fallbeile steigt in drei Stufen an, verbunden nur über schräge Rampen. Drei Klingen hängen über dem Weg, jede in ihrem eigenen Takt: unten eine Mauer, oben eine Falle. Auf der mittleren Stufe klafft eine Feuergrube – nur mit Schwung über die Knochenrampe, und nur, wenn die Fledermaus gerade nicht quer darüber jagt.',
    obstacles: [
      { type: 'guillotine', x: 7.5, y: 6, w: 0.35, h: 2, period: 5.2, phase: 0, hold: 0.32 },
      { type: 'field', x: 12, y: 5, w: 2, h: 2, fx: -2.8, fy: 0, style: 'slope', base: 0, rise: 1 },
      { type: 'guillotine', x: 15.5, y: 6, w: 0.35, h: 2, period: 5.2, phase: 0.4, hold: 0.32 },
      { type: 'ramp', x: 17.5, y: 5, w: 2, h: 2, angle: 0, minSpeed: 2.5, speed: 4.6, land: 3.4 },
      { type: 'sharkjump', style: 'bat', x: 21, y: 5.5, w: 2.4, h: 2, period: 4.8, jump: 0.3, phase: 0.2, axis: 'y', height: 1.4 },
      { type: 'field', x: 22, y: 5, w: 2, h: 2, fx: -2.8, fy: 0, style: 'slope', base: 1, rise: 1 },
      { type: 'guillotine', x: 27.5, y: 6, w: 0.35, h: 2, period: 5.2, phase: 0.7, hold: 0.32 },
      { type: 'wall', x0: 34, y0: 5, x1: 33.4, y1: 5.5, extend: 0 },
      { type: 'wall', x0: 34, y0: 7, x1: 33.4, y1: 6.5, extend: 0 },
    ],
    decor: [
      { t: 'torchPurple', x: 5.5, y: 4.4, s: 1.1 }, { t: 'torchPurple', x: 12, y: 4.4, s: 1.1 }, { t: 'torchPurple', x: 19.5, y: 4.4, s: 1.1 }, { t: 'torchPurple', x: 26, y: 4.4, s: 1.1 }, { t: 'torchPurple', x: 31, y: 4.4, s: 1.1 },
      { t: 'skull', x: 3.5, y: 7.6 }, { t: 'bones', x: 12.5, y: 7.6, s: 1.2 }, { t: 'skull', x: 19.5, y: 7.6 }, { t: 'bones', x: 25, y: 7.6, s: 1.2 }, { t: 'pillar', x: 1.4, y: 4.4, s: 1.1 }, { t: 'pillar', x: 34.6, y: 4.4, s: 1.1 }, { t: 'urnDark', x: 34.6, y: 7.6, s: 1.1 }, { t: 'gravestone', x: 29, y: 7.8, s: 1.2, seed: 0.4 },
    ],
    autoDecor: { density: 0.15, seed: 605 },
  },
  {
    name: 'Rabenschlucht', par: 4, theme: 'shadow', maxStrokes: 18, hStep: 0.55, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 2, w: 4, h: 4, look: { x: 16, y: 4 } }, { x: 6, y: 3, w: 21, h: 3, look: { x: 28, y: 4 } }, { x: 27, y: 2, w: 6, h: 6, look: { x: 30.5, y: 3.5 } }],
    map: [
      '....................................',
      '....................................',
      '..####.....................######...',
      '..#T##oooooooooooxooooooooo###H##...',
      '..####ooooooooooooooooooooo######...',
      '..####ooooxoooooooooooooxoo######...',
      '...........................######...',
      '...........................######...',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    heights: [
      '....................................',
      '....................................',
      '..2222.....................111111...',
      '..2222222222222222222222222111111...',
      '..2222222222222222222222222111111...',
      '..2222222222222222222222222111111...',
      '...........................111111...',
      '...........................111111...',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    intro: 'Ein schmaler Grat hoch über der Schlucht, ohne Geländer. Drei Rabenschwärme fliegen quer über den Grat und schieben alles vor sich her – wer im Weg liegt, stürzt in die Tiefe. Hinter den Gruftblöcken ist man sicher. Am Ende fällt der Grat eine Stufe hinab auf die Felsplatte mit dem Loch, wo ein verfluchter Ritter wacht.',
    obstacles: [
      { type: 'wave', style: 'ravens', x0: 9, y0: 1.6, x1: 9, y1: 6.4, w: 2.6, h: 0.6, period: 6, push: 13, brake: 0.55 },
      { type: 'wave', style: 'ravens', x0: 16, y0: 6.4, x1: 16, y1: 1.6, w: 2.6, h: 0.6, period: 7, phase: 0.5, push: 13, brake: 0.55 },
      { type: 'wave', style: 'ravens', x0: 23, y0: 1.6, x1: 23, y1: 6.4, w: 2.6, h: 0.6, period: 6.5, phase: 0.25, push: 13, brake: 0.55 },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 29.5, y: 6, phase: -Math.PI / 2, slash: { period: 4.4, dur: 0.7, amp: Math.PI * 0.9, phase: 0 } },
      { type: 'wall', x0: 33, y0: 2, x1: 32.4, y1: 3, extend: 0 },
      { type: 'wall', x0: 33, y0: 5, x1: 32.4, y1: 4, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.2, s: 1.6 }, { t: 'gravestone', x: 1.4, y: 6.6, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 5.6, y: 1.4, s: 1.2 }, { t: 'skull', x: 8.5, y: 1.6 }, { t: 'bones', x: 20, y: 7.6, s: 1.2 },
      { t: 'ghostlight', x: 13, y: 8.6, s: 1.2, seed: 0.2 }, { t: 'ghostlight', x: 21, y: 0.8, s: 1.2, seed: 0.7 }, { t: 'pillar', x: 27.4, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 33.6, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 33.6, y: 8.6, s: 1.1 }, { t: 'urnDark', x: 27.4, y: 8.6, s: 1.0 }, { t: 'deadTree', x: 34.6, y: 5, s: 1.5 },
    ],
    autoDecor: { density: 0.14, seed: 607 },
  },
  {
    name: 'Ritterhalle', par: 6, theme: 'shadow', maxStrokes: 24, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 3, w: 28, h: 2, look: { x: 31, y: 4 } }, { x: 30, y: 3, w: 2, h: 5, look: { x: 31, y: 7.5 } }, { x: 6, y: 7, w: 26, h: 2, look: { x: 4, y: 7.5 } }, { x: 4, y: 7, w: 2, h: 5, look: { x: 4.5, y: 11.5 } }, { x: 4, y: 11, w: 30, h: 2, look: { x: 31.5, y: 11.5 } }],
    map: [
      '....................................',
      '....................................',
      '....................................',
      '..#T##############################..',
      '..################################..',
      '..xxxxxxxxx#xxxxxxxxx#xxxxxxxx##xx..',
      '..xxxxxxxxxxxxxxxxxxxxxxxxxxxx##xx..',
      '..################################..',
      '..################################..',
      '..xx##xxxxxxxx#xxxxxxxxx#xxxxxxxxx..',
      '..xx##xxxxxxxxxxxxxxxxxxxxxxxxxxxx..',
      '..#############################H##..',
      '..################################..',
      '....................................',
      '....................................',
      '....................................',
    ],
    intro: 'Die Ritterhalle: drei schmale Gänge zwischen den Säulenreihen, im Zickzack von oben nach unten. In den Nischen stehen verfluchte Ritterstatuen – alle paar Sekunden erwachen sie und das Schwert fährt über die nahe Hälfte des Gangs: Wer getroffen wird, trägt den Ritterfluch und rollt bis zum Loch nur noch träge – an der fernen Wand entlang ist man sicher. Im mittleren Gang rasselt ein Fallgatter, im letzten wartet das Fallbeil.',
    obstacles: [
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', len: 1.6, x: 11.5, y: 5.5, phase: Math.PI / 2, slash: { period: 4.2, dur: 0.7, amp: Math.PI * 0.9, phase: 0 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', len: 1.6, x: 21.5, y: 5.5, phase: -Math.PI / 2, slash: { period: 4.6, dur: 0.7, amp: Math.PI * 0.9, phase: 0.5 } },
      { type: 'mover', x0: 14, y0: 3.5, x1: 26, y1: 4.5, w: 0.8, h: 0.8, period: 6, style: 'ghost', e: 0.5 },
      { type: 'wall', x0: 30, y0: 3, x1: 32, y1: 5, extend: 0 },
      { type: 'wall', x0: 32, y0: 7, x1: 30, y1: 9, extend: 0 },
      { type: 'gate', x: 20, y: 8, w: 0.3, h: 2, period: 6, open: 0.45, phase: 0, axis: 'y' },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', len: 1.6, x: 14.5, y: 9.5, phase: -Math.PI / 2, slash: { period: 4.0, dur: 0.65, amp: -Math.PI * 0.9, phase: 0.25 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', len: 1.6, x: 24.5, y: 9.5, phase: Math.PI / 2, slash: { period: 4.8, dur: 0.7, amp: Math.PI * 0.9, phase: 0.7 } },
      { type: 'bumper', x: 8.5, y: 7.4, r: 0.38, style: 'eye', kick: 7 },
      { type: 'wall', x0: 6, y0: 7, x1: 4, y1: 9, extend: 0 },
      { type: 'wall', x0: 4, y0: 11, x1: 6, y1: 13, extend: 0 },
      { type: 'guillotine', x: 27.5, y: 12, w: 0.35, h: 2, period: 5.4, phase: 0.3, hold: 0.32 },
      { type: 'wall', x0: 33, y0: 11, x1: 32.4, y1: 11.5, extend: 0 },
      { type: 'wall', x0: 33, y0: 13, x1: 32.4, y1: 12.5, extend: 0 },
    ],
    decor: [
      { t: 'pillar', x: 1.4, y: 2.4, s: 1.2 }, { t: 'torchPurple', x: 8.5, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 17, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 26, y: 2.4, s: 1.1 }, { t: 'pillar', x: 34.6, y: 2.4, s: 1.2 },
      { t: 'pillar', x: 1.4, y: 13.6, s: 1.2 }, { t: 'pillar', x: 34.6, y: 13.6, s: 1.2 }, { t: 'torchPurple', x: 10, y: 13.6, s: 1.1 }, { t: 'torchPurple', x: 20, y: 13.6, s: 1.1 }, { t: 'torchPurple', x: 30, y: 13.6, s: 1.1 },
      { t: 'skull', x: 1.4, y: 7.5 }, { t: 'bones', x: 34.6, y: 7.5, s: 1.2 }, { t: 'urnDark', x: 1.4, y: 11.5, s: 1.0 }, { t: 'urnDark', x: 34.6, y: 4.5, s: 1.0 },
    ],
    autoDecor: { density: 0.1, seed: 609 },
  },
  {
    name: 'Totenfähre', par: 6, theme: 'darksea', maxStrokes: 24, cupR: 0.56, cupPull: 1.0, hazardText: { oob: 'Ins schwarze Wasser gestürzt', water: 'Im Totensee versunken' },
    views: [{ x: 2, y: 6, w: 5, h: 4, look: { x: 16, y: 7.5 } }, { x: 15, y: 5, w: 4, h: 6, look: { x: 28, y: 6.5 } }, { x: 27, y: 3, w: 5, h: 8, look: { x: 38, y: 6.5 } }, { x: 32, y: 6, w: 5, h: 2, look: { x: 38.5, y: 6.5 } }],
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '...........................#####..........',
      '...........................#####..........',
      '...............####........#####.....###..',
      '..#####........####........#####ooooo#H#..',
      '..#T###........####........#####ooooo###..',
      '..#####........####........#####.....###..',
      '..#####........####........#####..........',
      '...............####........#####..........',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    intro: 'Über den Totensee geht es nur mit den Sargfähren: Sie legen im Takt ab und an – wer noch auf dem Sarg liegt, fährt mit, wer daneben rollt, versinkt im schwarzen Wasser. Auf dem Weg kriechen dunkle Tentakel aus dem See. Zuletzt ein Steg ohne Geländer, über den ein Rabenschwarm zieht.',
    obstacles: [
      { type: 'ferry', x0: 6.6, y0: 7.5, x1: 15.4, y1: 7.5, w: 1.5, h: 1.3, wait: 2.2, travel: 2.8, style: 'coffin', flat: true },
      { type: 'rotor', x: 16.5, y: 11.6, blades: 1, len: 2.4, speed: 1.0, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 0.5 },
      { type: 'ferry', x0: 18.4, y0: 6.5, x1: 27.4, y1: 6.5, w: 1.5, h: 1.3, wait: 2.4, travel: 3.0, style: 'coffin', flat: true, phase: 0.5 },
      { type: 'rotor', x: 25.6, y: 4, blades: 1, len: 2.2, speed: -1.0, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 2.5 },
      { type: 'wave', style: 'ravens', x0: 34, y0: 4.4, x1: 34, y1: 8.6, w: 2.4, h: 0.6, period: 5.5, push: 12, brake: 0.55 },
      { type: 'wall', x0: 40, y0: 5, x1: 39.4, y1: 6, extend: 0 },
      { type: 'wall', x0: 40, y0: 8, x1: 39.4, y1: 7, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 5.2, s: 1.6 }, { t: 'gravestone', x: 4.5, y: 5.2, s: 1.3, seed: 0.4 }, { t: 'anchor', x: 6.6, y: 10.4, s: 1.3 }, { t: 'bones', x: 2.5, y: 10.6, s: 1.2 }, { t: 'bollard', x: 6.6, y: 6.4, s: 1.0 }, { t: 'bollard', x: 14.4, y: 8.6, s: 1.0 },
      { t: 'lantern', x: 15.4, y: 4.4 }, { t: 'skull', x: 18.6, y: 4.6 }, { t: 'bollard', x: 18.6, y: 5.6, s: 1.0 }, { t: 'bollard', x: 26.4, y: 7.6, s: 1.0 }, { t: 'lantern', x: 27.4, y: 2.4 }, { t: 'barrel', x: 30.6, y: 2.4, s: 1.0 }, { t: 'crate', x: 30.6, y: 10.6, s: 1.0 },
      { t: 'ghostlight', x: 34, y: 3.4, s: 1.2, seed: 0.3 }, { t: 'gravecross', x: 40.6, y: 4.4, s: 1.2 }, { t: 'gravestone', x: 40.6, y: 8.6, s: 1.2, seed: 0.8 }, { t: 'lantern', x: 36.6, y: 9.4 },
    ],
    autoDecor: { density: 0.1, seed: 611 },
  },
  {
    name: 'Turm des Auges', par: 5, theme: 'shadow', maxStrokes: 22, hStep: 0.55, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 4, y: 17, w: 24, h: 3, look: { x: 29, y: 18 } }, { x: 28, y: 8, w: 3, h: 12, look: { x: 29, y: 6 } }, { x: 8, y: 5, w: 23, h: 3, look: { x: 5, y: 6 } }, { x: 4, y: 5, w: 4, h: 3, look: { x: 5, y: 12.5 } }, { x: 4, y: 8, w: 3, h: 6, look: { x: 5, y: 12.5 } }],
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....##########x################.....',
      '....###########################.....',
      '....##################x########.....',
      '....x##.....................##x.....',
      '....###.....................###.....',
      '....###.....................x##.....',
      '....#x#.....................###.....',
      '....#H#..........#..........###.....',
      '....###.....................###.....',
      '............................###.....',
      '............................###.....',
      '............................###.....',
      '....########x##################.....',
      '....#T#########################.....',
      '....################x##########.....',
      '....................................',
      '....................................',
    ],
    heights: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....222111111111111111111111111.....',
      '....222111111111111111111111111.....',
      '....222111111111111111111111111.....',
      '....222.....................111.....',
      '....222.....................111.....',
      '....222.....................111.....',
      '....222.....................111.....',
      '....222..........0..........111.....',
      '....222.....................111.....',
      '............................111.....',
      '............................000.....',
      '............................000.....',
      '....000000000000000000000000000.....',
      '....000000000000000000000000000.....',
      '....000000000000000000000000000.....',
      '....................................',
      '....................................',
    ],
    intro: 'Mitten auf dem Felsen steht der Turm, und auf ihm brennt das Auge. Der schmale Weg windet sich in drei Stufen um den Turm hinauf, immer im Blick des Auges. Wer in seinem Lichtkegel liegen bleibt, ist verloren – nur hinter den Gruftblöcken ist man sicher. Also nie im Licht stehen bleiben. Auf der zweiten Stufe hängt ein Fallbeil, oben streift ein Geist umher.',
    obstacles: [
      { type: 'eyetower', x: 17.5, y: 12.5, r: 1.1, range: 11, fov: 0.6, speed: 0.42, phase: 0 },
      { type: 'wall', x0: 29, y0: 20, x1: 31, y1: 18, extend: 0 },
      { type: 'field', x: 28, y: 14, w: 3, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 0, rise: 1 },
      { type: 'guillotine', x: 29.5, y: 11, w: 3, h: 0.35, period: 5.4, phase: 0, hold: 0.32 },
      { type: 'wall', x0: 29, y0: 5, x1: 31, y1: 7, extend: 0 },
      { type: 'mover', x0: 24, y0: 6, x1: 12, y1: 6, w: 0.8, h: 0.8, period: 7, style: 'ghost', e: 0.5 },
      { type: 'field', x: 6, y: 5, w: 3, h: 3, fx: 2.8, fy: 0, style: 'slope', base: 1, rise: 1 },
      { type: 'wall', x0: 6, y0: 5, x1: 4, y1: 7, extend: 0 },
    ],
    decor: [
      { t: 'gravestone', x: 2.6, y: 20.6, s: 1.3, seed: 0.4 }, { t: 'deadTree', x: 10, y: 20.8, s: 1.6 }, { t: 'gravecross', x: 18, y: 20.8, s: 1.2 }, { t: 'gravestone', x: 26, y: 20.8, s: 1.2, seed: 0.7 }, { t: 'torchPurple', x: 32.6, y: 20.4, s: 1.1 },
      { t: 'ghostlight', x: 32.6, y: 12, s: 1.2, seed: 0.3 }, { t: 'skull', x: 8.5, y: 15.5 }, { t: 'bones', x: 24.5, y: 15.6, s: 1.2 }, { t: 'skull', x: 24.5, y: 9.5 }, { t: 'bones', x: 12.5, y: 9.6, s: 1.2 }, { t: 'obsidian', x: 32.6, y: 4, s: 1.1 }, { t: 'urnDark', x: 2.6, y: 15.6, s: 1.0 },
      { t: 'deadTree', x: 2.4, y: 3.4, s: 1.6 }, { t: 'gravestone', x: 10, y: 3.6, s: 1.3, seed: 0.2 }, { t: 'gravecross', x: 20, y: 3.6, s: 1.2 }, { t: 'gravestone', x: 28, y: 3.6, s: 1.2, seed: 0.9 }, { t: 'torchPurple', x: 2.6, y: 9.5, s: 1.1 },
    ],
    autoDecor: { density: 0.1, seed: 613 },
  },
  {
    name: 'Schattenschloss', par: 8, theme: 'shadow', maxStrokes: 30, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 17, w: 5, h: 4, look: { x: 12, y: 18.5 } }, { x: 10, y: 17, w: 5, h: 4, look: { x: 12, y: 12 } }, { x: 11, y: 11, w: 3, h: 6, look: { x: 20, y: 10 } }, { x: 11, y: 9, w: 16, h: 3, look: { x: 28.5, y: 10 } }, { x: 27, y: 3, w: 4, h: 9, look: { x: 28.5, y: 3 } }, { x: 15, y: 3, w: 12, h: 3, look: { x: 20.5, y: 1 } }],
    map: [
      '........................................',
      '........................................',
      '.......lll..............................',
      '.......lll.....################.........',
      '.......lll.....################.........',
      '.......lll.....################.........',
      '.......lll.....xx........#x####.........',
      '.......lll.....xx.........x####.........',
      '.......lll.............#...####.........',
      '.......lll.######ll############.........',
      '.......lll.######ll############.........',
      '.......lll.####################.........',
      '.......lll.###..........................',
      '.......lll.###..........................',
      '.......lll.###..........................',
      '.......lll.###..........................',
      '.......lll.###..........................',
      '..#####lll#####.........................',
      '..#T###lll#####.........................',
      '..#####lll#####.........................',
      '..#####lll#####.........................',
      '.......lll..............................',
      '.......lll..............................',
      '.......lll..............................',
    ],
    intro: 'Das schwarze Schloss. Vom Vorhof geht es nur mit Schwung über die Zugbrücke – wer zu langsam ist, rollt in den Feuergraben, und im Takt schießt eine Riesenfledermaus quer über den Graben. Im Torhaus rasselt das Fallgatter. Der Burghof führt einmal um den Bergfried: über die Rampe am Feuergraben (oder auf der schmalen Spur daran vorbei), an Rittern und einem Geist vorbei bis zum großen Tor. Dahinter der Thronsaal: Der Kerkergang endet vor dem Basilisken, der Riesenarmbrust des Schattenkönigs – nur sie schießt den Ball hinauf auf die Empore zum Loch.',
    obstacles: [
      { type: 'ramp', x: 4.5, y: 17, w: 2, h: 4, angle: 0, minSpeed: 3, speed: 6.5, land: 5.4 },
      { type: 'sharkjump', style: 'bat', x: 8.5, y: 18.5, w: 3, h: 4, period: 5, jump: 0.3, phase: 0.1, axis: 'y', height: 1.4 },
      { type: 'wall', x0: 13, y0: 21, x1: 15, y1: 19, extend: 0 },
      { type: 'gate', x: 12.5, y: 13.5, w: 3, h: 0.3, period: 6, open: 0.45, phase: 0, axis: 'x' },
      { type: 'wall', x0: 11, y0: 12, x1: 13, y1: 10, extend: 0 },
      { type: 'ramp', x: 14.5, y: 9, w: 2, h: 3, angle: 0, minSpeed: 2.5, speed: 4.6, land: 2.8 },
      { type: 'sharkjump', style: 'bat', x: 17.5, y: 10, w: 2, h: 3, period: 5, jump: 0.34, phase: 0.6, axis: 'y', height: 1.4 },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 23, y: 8.4, phase: Math.PI / 2, slash: { period: 4.4, dur: 0.7, amp: Math.PI * 0.9, phase: 0 } },
      { type: 'wall', x0: 29, y0: 12, x1: 31, y1: 10, extend: 0 },
      { type: 'mover', x0: 28.5, y0: 9, x1: 28.5, y1: 5.5, w: 0.8, h: 0.8, period: 5, style: 'ghost', e: 0.5 },
      { type: 'wall', x0: 31, y0: 5, x1: 29, y1: 3, extend: 0 },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 25.5, y: 6.4, phase: -Math.PI / 2, slash: { period: 4.0, dur: 0.7, amp: -Math.PI * 0.9, phase: 0.5 } },
      { type: 'wall', x0: 18.5, y0: 3, x1: 19.5, y1: 4, extend: 0 },
      { type: 'wall', x0: 22.5, y0: 3, x1: 21.5, y1: 4, extend: 0 },
      { type: 'door', x: 20.5, y: 4.4, r: 1.0, style: 'castle', px: 20.5, py: 1.6, gw: 3.6 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 16.2, s: 1.6 }, { t: 'gravestone', x: 4.5, y: 16, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 3.5, y: 21.6, s: 1.2 }, { t: 'skull', x: 6.5, y: 21.6 }, { t: 'ghostlight', x: 1.4, y: 19, s: 1.2, seed: 0.3 },
      { t: 'pillar', x: 10.4, y: 21.6, s: 1.2 }, { t: 'pillar', x: 15.6, y: 21.6, s: 1.2 }, { t: 'torchPurple', x: 10.4, y: 13.5, s: 1.1 }, { t: 'torchPurple', x: 14.6, y: 13.5, s: 1.1 }, { t: 'pillar', x: 15.6, y: 16.4, s: 1.2 },
      { t: 'torchPurple', x: 16.5, y: 12.6, s: 1.1 }, { t: 'torchPurple', x: 24, y: 12.6, s: 1.1 }, { t: 'bones', x: 20, y: 12.6, s: 1.2 }, { t: 'skull', x: 31.6, y: 7.5 }, { t: 'urnDark', x: 31.6, y: 4.5, s: 1.0 }, { t: 'obsidian', x: 31.6, y: 10.5, s: 1.1 },
      { t: 'torchPurple', x: 14, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 27, y: 2.4, s: 1.1 }, { t: 'pillar', x: 20.5, y: 7.6, s: 1.2 }, { t: 'deadTree', x: 35, y: 4, s: 1.6 }, { t: 'gravestone', x: 35, y: 10, s: 1.3, seed: 0.7 },
    ],
    autoDecor: { density: 0.1, seed: 615 },
    inner: {
      name: 'Thronsaal', theme: 'throne', hStep: 0.6, cupR: 0.56, cupPull: 1.0, look: { x: 21.4, y: 11 }, hazardText: { fell: 'In den Kerker gestürzt', beheaded: 'Im Thronsaal geköpft!' },
      views: [{ x: 2, y: 9, w: 20, h: 4, look: { x: 21.4, y: 11 } }, { x: 14, y: 1, w: 15, h: 5, look: { x: 26.5, y: 2.5 } }],
      map: [
        '..............................',
        '..............###############.',
        '..............############H##.',
        '..............###############.',
        '..............###############.',
        '..............###############.',
        '..............................',
        '..............................',
        '..............................',
        '..#####################.......',
        '..#T###################.......',
        '..#####################.......',
        '..#####################.......',
        '..............................',
      ],
      heights: [
        '..............................',
        '..............222222222222222.',
        '..............222222222222222.',
        '..............222222222222222.',
        '..............222222222222222.',
        '..............222222222222222.',
        '..............................',
        '..............................',
        '..............................',
        '..000000000000000000000.......',
        '..000000000000000000000.......',
        '..000000000000000000000.......',
        '..000000000000000000000.......',
        '..............................',
      ],
      intro: 'Der Thronsaal des Schattenkönigs. Der Kerkergang führt an Sense und Fallbeil vorbei in die Rinne des Basilisken, der Riesenarmbrust – sie spannt die Sehne und schießt den Ball hoch hinauf auf die Empore, wo das Loch liegt. Der Schaft pendelt: Wer im falschen Moment hineinrollt, fliegt schief.',
      obstacles: [
        { type: 'bumper', x: 7.5, y: 12.2, r: 0.4, style: 'grave', kick: 7 },
        { type: 'rotor', x: 10.5, y: 11, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.6 }, phase: 0, height: 0.5 },
        { type: 'guillotine', x: 15.5, y: 11, w: 0.35, h: 4, period: 5.4, phase: 0, hold: 0.32 },
        { type: 'wall', x0: 19.5, y0: 9, x1: 21, y1: 10.3, extend: 0 },
        { type: 'wall', x0: 19.5, y0: 13, x1: 21, y1: 11.7, extend: 0 },
        { type: 'cannon', style: 'ballista', x: 21.4, y: 11, base: -Math.PI / 2, amp: 0.3, speed: 0.8, range: 6.2, catchR: 0.65, loadTime: 0.9 },
        { type: 'wall', x0: 28, y0: 1, x1: 29, y1: 2, extend: 0 },
        { type: 'wall', x0: 29, y0: 5, x1: 28, y1: 4, extend: 0 },
      ],
      decor: [
        { t: 'pillar', x: 15.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 19.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 23.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 27.5, y: 0.4, s: 1.2 },
        { t: 'torchPurple', x: 13.4, y: 2.5, s: 1.1 }, { t: 'torchPurple', x: 29.6, y: 2.5, s: 1.1 }, { t: 'obsidian', x: 17.5, y: 6.4, s: 1.2 }, { t: 'obsidian', x: 25.5, y: 6.4, s: 1.2 }, { t: 'urnDark', x: 21.5, y: 6.4, s: 1.0 },
        { t: 'torchPurple', x: 1.4, y: 10.5, s: 1.1 }, { t: 'torchPurple', x: 8.5, y: 8.4, s: 1.1 }, { t: 'torchPurple', x: 14, y: 13.6, s: 1.1 }, { t: 'skull', x: 4.5, y: 13.6 }, { t: 'bones', x: 12.5, y: 8.4, s: 1.2 }, { t: 'bones', x: 18, y: 13.6, s: 1.2 }, { t: 'pillar', x: 23.4, y: 9.4, s: 1.1 }, { t: 'pillar', x: 23.4, y: 12.6, s: 1.1 },
      ],
      autoDecor: { density: 0.08, seed: 616 },
    },
  },
  {
    name: 'Gruft der Sensen', par: 5, theme: 'shadow', maxStrokes: 22, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 2, y: 3, w: 18, h: 2, look: { x: 18.5, y: 3.5 } }, { x: 3, y: 9, w: 18, h: 2, look: { x: 21.5, y: 9.5 } }, { x: 21, y: 9, w: 2, h: 6, look: { x: 21.5, y: 14.5 } }, { x: 8, y: 14, w: 13, h: 2, look: { x: 9.5, y: 14.5 } }],
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..#T################..........',
      '..##################..........',
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '...####################.......',
      '...####################.......',
      '.....................##.......',
      '.....................##.......',
      '.....................##.......',
      '........#H#############.......',
      '........###############.......',
      '..............................',
      '..............................',
    ],
    intro: 'Die Gruft der Sensen: Im ersten Gang schwingen zwei Sensen quer über den Weg, am Ende wartet ein Schattenportal. Es setzt den Ball in den zweiten Gang – Fallbeil, Knochenstacheln, dann die Druckplatte: Sie hebt das Fallgatter vor der Grabkammer für kurze Zeit. Wer trödelt, steht davor, wenn es wieder fällt.',
    obstacles: [
      { type: 'rotor', x: 8.5, y: 3.4, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.2, speed: 1.6 }, phase: 0, height: 0.5 },
      { type: 'rotor', x: 14.5, y: 4.6, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.2, speed: 1.9 }, phase: Math.PI, height: 0.5 },
      { type: 'portal', x: 18.5, y: 4, tx: 4.5, ty: 10, color: '#c58bff' },
      { type: 'portal', x: 4.5, y: 10, tx: 18.5, ty: 4, color: '#c58bff', entrance: false },
      { type: 'guillotine', x: 10.5, y: 10, w: 0.35, h: 2, period: 5.2, phase: 0, hold: 0.32 },
      { type: 'spikes', x: 15.5, y: 10, w: 1, h: 2, period: 4.2, up: 0.4, phase: 0.5 },
      { type: 'switch', x: 20, y: 10, r: 0.5, duration: 16, target: 'A' },
      { type: 'wall', x0: 21, y0: 9, x1: 23, y1: 11, extend: 0 },
      { type: 'wall', x0: 23, y0: 14, x1: 21, y1: 16, extend: 0 },
      { type: 'guillotine', x: 16, y: 15, w: 0.35, h: 2, linked: 'A', liftH: 2.2 },
      { type: 'mover', x0: 14, y0: 14.5, x1: 11, y1: 14.5, w: 0.8, h: 0.8, period: 4, style: 'ghost', e: 0.5 },
      { type: 'wall', x0: 8, y0: 14, x1: 8.6, y1: 14.5, extend: 0 },
      { type: 'wall', x0: 8, y0: 16, x1: 8.6, y1: 15.5, extend: 0 },
    ],
    decor: [
      { t: 'torchPurple', x: 6.5, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 12.5, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 18.5, y: 2.4, s: 1.1 }, { t: 'pillar', x: 1.4, y: 2.4, s: 1.1 }, { t: 'pillar', x: 20.6, y: 2.4, s: 1.1 }, { t: 'urnDark', x: 20.6, y: 5.6, s: 1.0 },
      { t: 'skull', x: 4.5, y: 5.6 }, { t: 'bones', x: 10.5, y: 5.6, s: 1.2 }, { t: 'gravestone', x: 15.5, y: 6.4, s: 1.2, seed: 0.6 }, { t: 'torchPurple', x: 2.4, y: 8.4, s: 1.1 }, { t: 'torchPurple', x: 12.5, y: 8.4, s: 1.1 }, { t: 'torchPurple', x: 23.6, y: 12, s: 1.1 },
      { t: 'skull', x: 7.5, y: 11.6 }, { t: 'bones', x: 17.5, y: 11.6, s: 1.2 }, { t: 'pillar', x: 7.4, y: 13.4, s: 1.1 }, { t: 'torchPurple', x: 12, y: 16.6, s: 1.1 }, { t: 'torchPurple', x: 19, y: 16.6, s: 1.1 }, { t: 'urnDark', x: 7.4, y: 16.6, s: 1.0 }, { t: 'obsidian', x: 23.6, y: 16.6, s: 1.1 },
    ],
    autoDecor: { density: 0.12, seed: 617 },
  },
  {
    name: 'Herz der Finsternis', par: 9, theme: 'shadow', maxStrokes: 33, hStep: 0.55, cupR: 0.56, cupPull: 1.0, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Tiefe gestürzt', spiked: 'Von Knochenstacheln aufgespießt', shark: 'Von der Riesenfledermaus gepackt!' },
    views: [{ x: 4, y: 3, w: 5, h: 4, look: { x: 20, y: 4.5 } }, { x: 9, y: 4, w: 12, h: 2, look: { x: 21.5, y: 5 } }, { x: 21, y: 6, w: 2, h: 10, look: { x: 21.5, y: 15 } }, { x: 7, y: 14, w: 14, h: 2, look: { x: 4, y: 15 } }, { x: 2, y: 13, w: 5, h: 6, look: { x: 30, y: 15 } }, { x: 28, y: 12, w: 6, h: 7, look: { x: 34, y: 15 } }],
    map: [
      '........................................',
      '........................................',
      '........................................',
      '....#####...............................',
      '....#T###oooooooooooooo.................',
      '....#####oooooooooooooo.................',
      '....#####............oo.................',
      '.....................oo.................',
      '.....................oo.................',
      '.....................oo.................',
      '.....................oo.................',
      '.....................oo.................',
      '.....................oo.....######......',
      '..#####..............oo.....######......',
      '..#####ooooollooooooooo.....######......',
      '..#####ooooollooooooooo.....######......',
      '..#####.....................######......',
      '..#####.....................######......',
      '..#####.....................######......',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
    ],
    intro: 'Das Herz der Finsternis. Von der schwarzen Zinne geht es drei Stufen hinab: über den Grat, auf dem Raben wehen, den Steg mit dem Fallbeil und die Lücke mit der Fledermaus. Ganz unten wartet der Basilisk und schießt den Ball über den Totensee ins Wrack. Drinnen schlägt das Herz: drei Gänge im Zickzack hinauf, in der Mitte das brennende Auge, Sensen, und ganz oben hebt nur die Druckplatte das Fallgatter vor dem Loch.',
    obstacles: [
      { type: 'wave', style: 'ravens', x0: 14, y0: 2.6, x1: 14, y1: 6.4, w: 2.6, h: 0.6, period: 6, push: 13, brake: 0.55 },
      { type: 'wall', x0: 21, y0: 4, x1: 23, y1: 6, extend: 0 },
      { type: 'guillotine', x: 22, y: 9.5, w: 2.4, h: 0.35, period: 5.2, phase: 0, hold: 0.32 },
      { type: 'wall', x0: 23, y0: 14, x1: 21, y1: 16, extend: 0 },
      { type: 'ramp', x: 14, y: 14, w: 2, h: 2, angle: 180, minSpeed: 2.5, speed: 4.6, land: 3.2 },
      { type: 'sharkjump', style: 'bat', x: 13, y: 15, w: 2, h: 2.4, period: 4.6, jump: 0.34, phase: 0.4, axis: 'y', height: 1.4 },
      { type: 'cannon', style: 'ballista', x: 5.0, y: 15, base: 0, amp: 0.08, speed: 0.8, range: 22.5, catchR: 1.0, loadTime: 1.0 },
      { type: 'rotor', x: 33.6, y: 13, blades: 1, len: 2.2, speed: 1.0, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 0.5 },
      { type: 'door', x: 31.2, y: 15.5, r: 1.7, style: 'wreck', px: 36.5, py: 15.5 },
    ],
    decor: [
      { t: 'obsidian', x: 3.4, y: 2.4, s: 1.3 }, { t: 'torchPurple', x: 9, y: 2.4, s: 1.1 }, { t: 'gravecross', x: 3.4, y: 7.4, s: 1.2 }, { t: 'skull', x: 12, y: 6.6 }, { t: 'bones', x: 18, y: 2.6, s: 1.2 }, { t: 'torchPurple', x: 23.6, y: 3.4, s: 1.1 },
      { t: 'ghostlight', x: 24, y: 10, s: 1.2, seed: 0.3 }, { t: 'torchPurple', x: 23.6, y: 16.6, s: 1.1 }, { t: 'bones', x: 8, y: 12.4, s: 1.2 }, { t: 'skull', x: 18, y: 16.6 }, { t: 'deadTree', x: 1.2, y: 11.2, s: 1.6 }, { t: 'gravestone', x: 1.4, y: 19.6, s: 1.3, seed: 0.4 },
      { t: 'anchor', x: 27.4, y: 20.4, s: 1.3 }, { t: 'lantern', x: 27.4, y: 13.4 }, { t: 'barrel', x: 32.6, y: 12.6, s: 1.0 }, { t: 'bones', x: 30, y: 20.6, s: 1.2 }, { t: 'ghostlight', x: 15, y: 20, s: 1.2, seed: 0.8 },
    ],
    autoDecor: { density: 0.08, seed: 619 },
    inner: {
      name: 'Im Herz der Finsternis', theme: 'throne', hStep: 0.55, cupR: 0.56, cupPull: 1.0, look: { x: 14.5, y: 10.5 }, hazardText: { fell: 'In den Abgrund gestürzt', seen: 'Vom Herz der Finsternis erblickt!', beheaded: 'Im Herz der Finsternis geköpft!' },
      views: [{ x: 3, y: 12, w: 22, h: 2, look: { x: 25.5, y: 12.5 } }, { x: 25, y: 10, w: 2, h: 4, look: { x: 25.5, y: 8.5 } }, { x: 5, y: 8, w: 22, h: 2, look: { x: 3.5, y: 8.5 } }, { x: 3, y: 6, w: 2, h: 4, look: { x: 3.5, y: 4.5 } }, { x: 3, y: 4, w: 24, h: 2, look: { x: 24.5, y: 4.5 } }],
      map: [
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '...#############x#######H##...',
        '...######x#################...',
        '...##.........................',
        '...##.........................',
        '...########x###############...',
        '...#################x######...',
        '..............#..........##...',
        '.........................##...',
        '...T####x##################...',
        '...###############x########...',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
      ],
      heights: [
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '...222222222222222222222222...',
        '...222222222222222222222222...',
        '...11.........................',
        '...11.........................',
        '...111111111111111111111111...',
        '...111111111111111111111111...',
        '..............0..........00...',
        '.........................00...',
        '...000000000000000000000000...',
        '...000000000000000000000000...',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
      ],
      intro: 'Drei Gänge im Zickzack, jeder eine Stufe höher, und in der Mitte das brennende Auge: Wer in seinem Blick liegen bleibt, fliegt zurück. Hinter den Gruftblöcken ist man sicher. Sensen im mittleren Gang, oben die Druckplatte – sie hebt das Fallgatter vor dem Loch nur für kurze Zeit.',
      obstacles: [
        { type: 'eyetower', x: 14.5, y: 10.5, r: 0.9, range: 9, fov: 0.6, speed: 0.45, phase: 0 },
        { type: 'mover', x0: 12, y0: 12.5, x1: 22, y1: 13.5, w: 0.8, h: 0.8, period: 6, style: 'ghost', e: 0.5 },
        { type: 'wall', x0: 25, y0: 14, x1: 27, y1: 12, extend: 0 },
        { type: 'field', x: 25, y: 10, w: 2, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 0, rise: 1 },
        { type: 'wall', x0: 27, y0: 10, x1: 25, y1: 8, extend: 0 },
        { type: 'rotor', x: 15.5, y: 8.4, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.2, speed: 1.7 }, phase: 0, height: 0.5 },
        { type: 'rotor', x: 7.5, y: 9.6, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.2, speed: 1.5 }, phase: Math.PI, height: 0.5 },
        { type: 'wall', x0: 3, y0: 8, x1: 5, y1: 10, extend: 0 },
        { type: 'field', x: 3, y: 6, w: 2, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 1, rise: 1 },
        { type: 'wall', x0: 3, y0: 6, x1: 5, y1: 4, extend: 0 },
        { type: 'switch', x: 6.5, y: 5, r: 0.75, duration: 22, target: 'A' },
        { type: 'guillotine', x: 20.5, y: 5, w: 0.35, h: 2, linked: 'A', liftH: 2.2 },
        { type: 'wall', x0: 27, y0: 4, x1: 26.4, y1: 4.5, extend: 0 },
        { type: 'wall', x0: 27, y0: 6, x1: 26.4, y1: 5.5, extend: 0 },
      ],
      decor: [
        { t: 'pillar', x: 2.4, y: 2.4, s: 1.2 }, { t: 'pillar', x: 27.6, y: 2.4, s: 1.2 }, { t: 'torchPurple', x: 8, y: 2.6, s: 1.1 }, { t: 'torchPurple', x: 14, y: 2.6, s: 1.1 }, { t: 'torchPurple', x: 20, y: 2.6, s: 1.1 }, { t: 'obsidian', x: 27.6, y: 6.6, s: 1.2 },
        { t: 'urnDark', x: 2.4, y: 10.6, s: 1.0 }, { t: 'skull', x: 27.6, y: 10.6 }, { t: 'bones', x: 6.5, y: 15, s: 1.2 }, { t: 'skull', x: 15.5, y: 15 }, { t: 'torchPurple', x: 22, y: 15, s: 1.1 }, { t: 'pillar', x: 2.4, y: 14.6, s: 1.2 }, { t: 'pillar', x: 27.6, y: 14.6, s: 1.2 },
        { t: 'obsidian', x: 9.5, y: 10.5, s: 1.1 }, { t: 'obsidian', x: 19.5, y: 10.5, s: 1.1 }, { t: 'torchPurple', x: 2.4, y: 6.6, s: 1.1 },
      ],
      autoDecor: { density: 0.06, seed: 620 },
    },
  },
];
