/* Das Zauberreich: ein Ereignis mit drei Orten, die einen Aufstieg erzählen.
   Erzeugt von tools/zauber.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

     'lehrling'   Lehrlingsgarten   Normal    der ummauerte Garten, in dem man es lernt
     'warte'      Sternenwarte      Profi
     'loge'       Erzmagierloge     Legende

   DIE FRAGE DIESER WELT IST: *WANN FÄNGT ES AN?*
   Jede andere Welt läuft im Takt – Fallgatter, Falltür, Stacheln, Fontäne, Wracktor gehen auf und
   zu, ohne daß jemand gefragt würde, und die Aufgabe heißt immer: den Moment abpassen. Hier
   startet der Spieler die Uhr selbst. Er stößt die Blüte an, und von da an läuft SEINE Zeit. Aus
   dem Abpassen wird eine Dosierung, und das ist es, was ein Lehrling übt.

   DIE MASCHINEN (src/obstacles_zauber.js):
     'ranke'       Die Blüte anstoßen läßt eine Ranke über die Lücke wachsen – für ein paar
                   Sekunden, dann welkt sie. Ihre Felder sind in der Karte gewöhnlicher Boden;
                   daß man ohne Ranke hindurchfällt, besorgt die Maschine. Dieselbe Umkehrung wie
                   bei der Schneebrücke, und aus demselben Grund: Boden, der zur Laufzeit
                   entsteht, müßte Wegfindung, Banden und Kamera mitziehen. Boden, der wegfällt,
                   kostet eine Abfrage.
     'zauberhut'   Drei Hüte, einer leuchtet. Wer in einen rollt, kommt aus dem leuchtenden
                   heraus; wer in den leuchtenden rollt, aus dem nächsten – es gibt keine
                   Sackgasse. Das Leuchten wandert im Takt und kündigt sich an.

   DIE OPTIK KOMMT AUS DEM BESTAND. Kein einziges neues Bild für die alten Maschinen, und trotzdem
   sieht keine aus wie im Märchenland: Das Windrad ist hier eine Ranke oder ein Besen, der
   Prellklotz ein Pilz, eine Leuchtkugel oder ein Kristall, der Magnet ein Seelenlicht, die
   Drehscheibe ein Laubwirbel.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. */

const ZAUBER_GARTEN = [
  {
    name: 'Am Gartentor', par: 3, theme: 'lehrlingsgarten',
    intro: 'Der Garten des Lehrlings, kurz vor Sonnenuntergang. Zwei Hecken stehen im Weg, und dazwischen geht es im Bogen hindurch. Die beiden Springkräuter federn den Ball zurück, sobald ihre Kapsel platzt – das lohnt sich zu wissen, bevor es schwieriger wird.',
    map: [
      '..............................',
      '..............................',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.#######....#################.',
      '.##T#####..#######..######H##.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '.################....########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 6, x1: 9, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 6, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 7, x1: 18, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 7, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 14.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 23.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Die erste Blüte', par: 3, theme: 'lehrlingsgarten',
    intro: 'Über die Lücke führt nichts – bis man die Blüte anstößt. Dann wächst eine Ranke hinüber und trägt vier Sekunden lang. Zu sacht geschlagen, und man liegt noch darauf, wenn sie welkt; zu hart, und man fliegt daran vorbei. Dazwischen liegt der Schlag.',
    map: [
      '................................',
      '................................',
      '................................',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '.##T########################H##.',
      '.##############################.',
      '.##############################.',
      '.##############################.',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'ranke', x: 14, y: 3, w: 4, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 10.5, y: 6.5 } },
      { type: 'rotor', x: 21.5, y: 6.5, blades: 3, len: 1.8, speed: 1.1, thick: 0.16, style: 'sprenger', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Der Springkrautkranz', par: 3, theme: 'lehrlingsgarten',
    intro: 'Ein Rundbeet, und mitten darin das Loch. Der Kranz aus Springkraut läßt niemanden geradewegs hinein – wer es mit Gewalt versucht, kommt weiter heraus, als er hineingekommen ist. Sanft anspielen und eine Kapsel als Wand benutzen ist der kürzere Weg.',
    map: [
      '............................',
      '............................',
      '.......##############.......',
      '....####################....',
      '...######################...',
      '..########################..',
      '..########################..',
      '..#T#########H############..',
      '..########################..',
      '..########################..',
      '..########################..',
      '...######################...',
      '....####################....',
      '.......##############.......',
      '............................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 2, x1: 7, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 2, x1: 21, y1: 3, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 3, x1: 4, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 3, x1: 24, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 4, x1: 3, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 4, x1: 25, y1: 5, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 5, x1: 2, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 26, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 3, y0: 11, x1: 2, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 11, x1: 26, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 4, y0: 12, x1: 3, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 12, x1: 25, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 5, y0: 13, x1: 4, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 13, x1: 24, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 8, y0: 14, x1: 7, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 14, x1: 21, y1: 13, t: 0.22, h: 0.5 },
      { type: 'bumper', x: 16.7, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 10.7, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 9.8, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 10.3, y: 7.5, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 11.2, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 13.5, y: 4.3, r: 0.58, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 15.8, y: 5.2, r: 0.5, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Zwei Blüten', par: 4, theme: 'lehrlingsgarten',
    intro: 'Zwei Lücken, zwei Blüten. Die zweite Blüte liegt hinter der ersten Ranke – man kommt also nur an sie heran, wenn die erste noch trägt. Ein Schlag, der beide schafft, ist möglich; zwei ruhige sind sicherer.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 11, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 8.5, y: 6.5 } },
      { type: 'ranke', x: 22, y: 3, w: 3, h: 7, dauer: 4.0, r: 0.6, bluete: { x: 18.5, y: 6.5 } },
      { type: 'bumper', x: 27.5, y: 6.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Der Maulwurfshügel', par: 3, theme: 'lehrlingsgarten',
    intro: 'Durch die erste Hecke kommt nur, wer sich untergräbt: hinein in einen Hügel, heraus aus dem, in dem der Maulwurf gerade steckt – und wer in dessen Hügel rollt, kommt aus dem nächsten. Einer der beiden Ausgänge liegt in einer Nische: Von dort muß man erst zur Seite und dann hinaus, das kostet einen Schlag. Danach ist die Bahn noch nicht zu Ende – die zweite Hecke läßt nur oben eine Gasse, und davor dreht der Sprenger.',
    map: [
      '..........................................',
      '..........................................',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx##########################.',
      '.###########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.##T########xxx#############xxx##########.',
      '.###########xxx#############xxx##########.',
      '.###########xxx##xxxxx######xxx##########.',
      '.###########xxx######x######xxx######H###.',
      '.###########xxx######x######xxx##########.',
      '.###########xxx######x######xxx##########.',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'zauberhut', takt: 2.6, phase: 0.0, r: 0.42, plaetze: [[6.0, 7.0], [18.0, 4.0], [18.0, 11.0]], style: 'maulwurf' },
      { type: 'bumper', x: 9.5, y: 10.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 7.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'rotor', x: 34.5, y: 6.5, blades: 2, len: 1.3, speed: 0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Das Treibhaus', par: 4, theme: 'lehrlingsgarten',
    intro: 'Der Bienenstand steht quer im Weg, und der Durchlaß zwischen den Körben schließt sich im Takt mit einer Wabe. Dahinter drehen zwei Rasensprenger gegeneinander – sie laufen in verschiedene Richtungen, also gibt es keinen Augenblick, in dem beide zugleich aus dem Weg sind. Einer nach dem anderen.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##T#######################H#.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'windmill', x: 15.5, y: 6.5, w: 6.8, gap: 1.5, speed: 0.85, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'rotor', x: 21.5, y: 4.5, blades: 2, len: 1.3, speed: -0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
      { type: 'rotor', x: 21.5, y: 8.5, blades: 2, len: 1.3, speed: 0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 8.5, y: 8.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Blüte und Hügel', par: 4, theme: 'lehrlingsgarten',
    intro: 'Erst die Ranke über den Steg – sie trägt hier eine halbe Sekunde länger, der Weg ist weiter. Dann steht die Hecke im Weg, und wieder helfen nur die Hügel. Wer beim Steg zu viel Kraft gibt, steht drüben zu weit oben und muß noch einmal ansetzen.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.....................######xx####.',
      '.############........######xx####.',
      '.#############......#######xx####.',
      '.##########################xx####.',
      '.##T#######################xx##H#.',
      '.##########################xx####.',
      '.#############......#############.',
      '.############........############.',
      '.....................############.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 5, x1: 20, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 10, x1: 20, y1: 9, t: 0.22, h: 0.5 },
      { type: 'ranke', x: 14, y: 6, w: 5, h: 3, dauer: 5.5, r: 0.6, bluete: { x: 9.5, y: 7.5 } },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.62, plaetze: [[24.0, 7.0], [30.0, 10.0]], style: 'maulwurf' },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Der Blätterwirbel', par: 3, theme: 'lehrlingsgarten',
    intro: 'Zwei Beete stehen versetzt, dazwischen geht es im Zickzack. Die Pusteblume zieht an allem, was an ihr vorbeirollt – ausgerechnet in der ersten Kehre, wo man ohnehin schon aufpassen muß. Die Sonnenblume dahinter fängt den Ball und wirft ihn immer nach unten aus; wer sie trifft, spart sich die halbe Bahn.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '.#########...################.',
      '.#########...################.',
      '.##T######...################.',
      '.#########...################.',
      '.#########...######.#########.',
      '.##########.######...##xx####.',
      '.#################...##xx#H##.',
      '.#################...##xx####.',
      '.#################...########.',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 18, y0: 8, x1: 19, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 8, x1: 12, y1: 9, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 15.5, y: 9.5, r: 1.5, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'magnet', x: 8.5, y: 9.5, r: 2.6, strength: 5.0, slow: 0, style: 'pollen' },
      { type: 'turntable', x: 15.5, y: 5.5, r: 1.8, speed: 1.8, exit: 90, eject: 4.5, style: 'sonnenblume' },
      { type: 'bumper', x: 22.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Lehrlingsprüfung', par: 4, theme: 'lehrlingsgarten',
    intro: 'Die Prüfung: erst die Ranke, dann zwischen dem Springkraut hindurch, dann der Bienenstand im Takt – und zum Schluß noch einmal die Hüte. Wer hier unter Par bleibt, hat den Lehrlingshut verdient.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '.################################.',
      '.################################.',
      '.################################.',
      '.################################.',
      '.##T#############################.',
      '.##############################H#.',
      '.################################.',
      '.################################.',
      '.################################.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'ranke', x: 10, y: 3, w: 3, h: 9, dauer: 4.2, r: 0.6, bluete: { x: 7.5, y: 7.5 } },
      { type: 'bumper', x: 14.5, y: 5.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'bumper', x: 14.5, y: 9.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'windmill', x: 18.5, y: 7.5, w: 7.6, gap: 1.2, speed: 0.9, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'zauberhut', takt: 2.8, phase: 0.0, r: 0.42, plaetze: [[24.0, 5.0], [24.0, 10.0], [29.0, 11.0]], style: 'maulwurf' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Die Riesenblüte', par: 6, theme: 'lehrlingsgarten', maxStrokes: 18,
    intro: 'Am Ende des Gartens steht sie: sechs Blütenblätter, und das Loch liegt in ihrer Mitte. Sie öffnet und schließt sich in einem langsamen Takt – aber wenn sie zugeht, kommt der Pollenstoß, und wer dann noch im Kelch liegt und nicht im Loch, fliegt wieder hinaus. Der Kelch glüht auf, bevor es soweit ist. Das ist die einzige Warnung, und sie reicht.',
    map: [
      '....................................................',
      '....................................................',
      '....................................................',
      '..............................#####################.',
      '..........####..............#######################.',
      '..........####..............#######################.',
      '..........####..............#######################.',
      '.........######............########################.',
      '.##################################################.',
      '.##T####################################H##########.',
      '.##################################################.',
      '.##################################################.',
      '..................######...########################.',
      '...................####.....#######################.',
      '...................####.....#######################.',
      '...................####.....#######################.',
      '..............................#####################.',
      '....................................................',
      '....................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 31, y0: 3, x1: 30, y1: 4, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 10, y0: 7, x1: 9, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 7, x1: 15, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 7, x1: 27, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 13, x1: 18, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 23, y0: 13, x1: 24, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 13, x1: 27, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 17, x1: 30, y1: 16, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 9.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'rotor', x: 11.5, y: 6.0, blades: 2, len: 1.4, speed: 0.9, thick: 0.16, style: 'sprenger', phase: 0.0 },
      { type: 'bumper', x: 16.0, y: 9.5, r: 0.55, style: 'springkraut', kick: 7.5 },
      { type: 'windmill', x: 25.5, y: 10.0, w: 4.0, gap: 1.5, speed: 0.8, blades: 4, axis: 'y', phase: 0.0, depth: 3.0, style: 'bienenstock' },
      { type: 'turntable', x: 20.5, y: 13.5, r: 1.7, speed: 1.6, exit: 270, eject: 4.5, style: 'sonnenblume' },
      { type: 'zauberkreis', x: 29.5, y: 9.5, r: 1.3, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'riesenbluete', x: 40.5, y: 9.5, r: 4.6, blaetter: 6, takt: 8.5, phase: 0.0, kraft: 26, dicke: 0.38 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];

const ZAUBER_WARTE = [
  {
    name: 'Der Aufgang', par: 3, theme: 'sternenwarte',
    intro: 'Der Mond über der Terrasse zieht, solange seine Scheibe voll ist, und stößt, solange sie dunkel ist. Beim Halbmond läßt er in Ruhe. Der Gang oben ist schmal, und unter ihm ist nichts - also: erst hinsehen, dann schlagen.',
    map: [
      '..............................',
      '..............................',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.############################.',
      '.##########.........#########.',
      '.##T######...........#####H##.',
      '.#########...........########.',
      '.#########...........########.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'wall', x0: 10, y0: 8, x1: 11, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 20, y1: 7, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 15.0, y: 4.0, r: 3.4, kraft: 9.0, takt: 7.0, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 8.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'bumper', x: 22.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Das erste Sternbild', par: 3, theme: 'sternenwarte',
    intro: 'Die drei Sterne wollen angefahren werden - alle drei, in einer Reihenfolge, die man sich vorher überlegt. Erst dann geht das Tor auf. Die Linien am Boden zeigen, was noch fehlt.',
    map: [
      '................................',
      '................................',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.##T########################H##.',
      '.##############################.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'sternbild', r: 0.5, sterne: [[6.0, 3.0], [11.0, 9.0], [16.0, 3.0]], tor: { x0: 20.0, y0: 6.0, x1: 20.0, y1: 8.0 } },
      { type: 'bumper', x: 13.5, y: 6.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Zwischen den Monden', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Monde stehen im Gegentakt: Zieht der eine, stößt der andere. Dazwischen liegen zwei Stege, die keinen Platz für Irrtümer lassen. Und am Ende schwingt das Lot des Astronomen.',
    map: [
      '..................................',
      '..................................',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.############.#########.#########.',
      '.################################.',
      '.###T#########################H##.',
      '.################################.',
      '.############.#########.#########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '.###########...#######...########.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'wall', x0: 12, y0: 5, x1: 13, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 5, x1: 23, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 5, x1: 24, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 10, x1: 13, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 15, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 10, x1: 23, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 10, x1: 24, y1: 9, t: 0.22, h: 0.5 },
      { type: 'mondzieher', x: 9.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.0, core: 0.4 },
      { type: 'mondzieher', x: 19.0, y: 7.0, r: 3.2, kraft: 8.0, takt: 6.0, phase: 0.5, core: 0.4 },
      { type: 'pendulum', x: 27.0, y: 4.0, len: 3.5, amp: 48, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Kartensaal', par: 4, theme: 'kartensaal',
    intro: 'Zwei Regale teilen den Saal. Wer den Gang in der Mitte nimmt, kommt am Lot des Astronomen vorbei; wer die Schanze oben trifft, fliegt über das erste Regal hinweg. Vor dem Loch wandert die Kulisse hin und her – da hilft nur der richtige Augenblick.',
    map: [
      '..............................',
      '..............................',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.################xx##########.',
      '.##T#############xx#######H##.',
      '.################xx##########.',
      '.###########xxx##xx##########.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '.###########xxx##############.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'ramp', x: 7.5, y: 2.6, w: 3.0, h: 2.8, angle: 0, minSpeed: 2.5, speed: 5.8, land: 5.2, style: 'sternschanze' },
      { type: 'pendulum', x: 24.0, y: 3.6, len: 3.2, amp: 55, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
      { type: 'bumper', x: 18.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'wandergate', x0: 21, y0: 2, x1: 21, y1: 13, gap: 2.0, style: 'kulisse' },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Das Fernrohr', par: 4, theme: 'sternenwarte',
    intro: 'Zwei Fernrohre stehen am Rand der Terrasse und suchen sie ab, und zwischen ihnen zieht ein Mond jeden geraden Weg krumm. Der Zickzack durch die Pfeiler ist der kurze Weg - wenn man ihn im richtigen Augenblick nimmt. Wer im Strahl liegen bleibt, wird gesehen.',
    map: [
      '................................',
      '................................',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx##############xx#####.',
      '.#######xx######xx######xx#####.',
      '.##T####xx######xx######xx#####.',
      '.#######xx######xx######xx#####.',
      '.###############xx#############.',
      '.###############xx###########H#.',
      '.###############xx#############.',
      '.###############xx#############.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'eyetower', x: 12.5, y: 15.2, r: 1.1, range: 9.0, fov: 0.6, speed: 0.4, phase: 0.0, style: 'sternenspiegel' },
      { type: 'eyetower', x: 21.0, y: -0.2, r: 1.1, range: 9.0, fov: 0.6, speed: -0.36, phase: 1.6, style: 'sternenspiegel' },
      { type: 'mondzieher', x: 20.0, y: 10.5, r: 2.8, kraft: 7.0, takt: 6.5, phase: 0.3, core: 0.4 },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Die Armillarsphäre', par: 4, theme: 'sternenwarte',
    intro: 'Der Messingring fährt über den Steg und nimmt mit, wer rechtzeitig darauf liegt. Dahinter wartet ein Nebelwirbel, der alles nach außen schleudert - am besten also gar nicht erst hinein.',
    map: [
      '................................',
      '................................',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......########H##.',
      '.#############.....############.',
      '.##############################.',
      '.##T###########################.',
      '.##############################.',
      '.#############.....############.',
      '.############.......###########.',
      '.############.......###########.',
      '.############.......###########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'wall', x0: 13, y0: 5, x1: 14, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 5, x1: 19, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 10, x1: 14, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 20, y0: 10, x1: 19, y1: 9, t: 0.22, h: 0.5 },
      { type: 'gearfield', x0: 12.5, y0: 7.5, x1: 19.5, y1: 7.5, wait: 2.2, travel: 3.0, r: 0.9, zaehne: 10, phase: 0.0, style: 'meridian' },
      { type: 'strudel', x: 24.5, y: 9.0, r: 2.8, dreh: 1, style: 'spiralnebel' },
      { type: 'bumper', x: 9.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Der Wandelgang', par: 3, theme: 'kartensaal',
    intro: 'Das wandernde Tor läuft auf und ab, und der Mond davor zieht den Ball von der Lücke weg oder in sie hinein. Zwei Uhren, die nicht zusammenpassen - man muß sich die eine aussuchen und die andere aushalten.',
    map: [
      '..................................',
      '..................................',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '.#####xx#########################.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'zauberkreis', x: 9.5, y: 7.0, r: 1.7, wirkung: 'wirbel', takt: 0.0, phase: 0.0, kraft: 2.2 },
      { type: 'zauberkreis', x: 26.0, y: 7.0, r: 1.6, wirkung: 'bremse', takt: 4.2, phase: 0.0 },
      { type: 'wandergate', x0: 18, y0: 3, x1: 18, y1: 11, gap: 1.9, style: 'kulisse' },
      { type: 'mondzieher', x: 13.0, y: 7.0, r: 3.0, kraft: 8.5, takt: 5.5, phase: 0.0, core: 0.4 },
      { type: 'bumper', x: 24.5, y: 4.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'bumper', x: 24.5, y: 9.5, r: 0.55, style: 'meteorit', kick: 7.5 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Hutkammer', par: 4, theme: 'kartensaal',
    intro: 'Die Hüte aus dem Garten, eine Stufe schärfer: Wo man herauskommt, steht fest - was danach mit dem Ball geschieht, entscheidet der Mond daneben. Wer den Hut im falschen Augenblick nimmt, landet dort, wo er nicht hin wollte.',
    map: [
      '................................',
      '................................',
      '.##########xx##################.',
      '.##########xx##################.',
      '.##########xx###############H##.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##T#######xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.##########xx#######xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '.###################xx#########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'zauberkreis', x: 16.0, y: 8.0, r: 1.7, wirkung: 'sprung', takt: 0.0, phase: 0.0, weite: 5.6 },
      { type: 'zauberhut', takt: 2.4, phase: 0.0, r: 0.42, plaetze: [[8.0, 4.0], [16.0, 11.0], [25.0, 9.0]] },
      { type: 'mondzieher', x: 16.0, y: 4.0, r: 3.0, kraft: 8.0, takt: 6.0, phase: 0.25, core: 0.4 },
      { type: 'pendulum', x: 25.0, y: 3.0, len: 3.0, amp: 45, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Die Sternenprüfung', par: 5, theme: 'sternenwarte',
    intro: 'Die Prüfung der Warte: erst die Blüte anstoßen und über die Ranke, dann am Mond vorbei. Danach gibt es zwei Wege. Die Schanze zwischen den Pfeilern ist schmal, wirft aber in einem Bogen über die Kulisse hinweg; wer sie verfehlt, muß den Augenblick abpassen, in dem die Gasse vor ihm steht. Wer hier unter Par bleibt, hat den Sternenhut verdient.',
    map: [
      '....................................',
      '....................................',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.###################xx##xx#########.',
      '.##################################.',
      '.##T############################H##.',
      '.##################################.',
      '.###################xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '.########xxxx#######xx##xx#########.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'ranke', x: 9, y: 5, w: 4, h: 5, dauer: 4.5, r: 0.6, bluete: { x: 6.5, y: 7.5 } },
      { type: 'mondzieher', x: 16.0, y: 7.0, r: 3.2, kraft: 8.5, takt: 6.5, phase: 0.15, core: 0.4 },
      { type: 'ramp', x: 21.8, y: 6.2, w: 2.0, h: 2.6, angle: 0, minSpeed: 2.5, speed: 6.0, land: 5.4, style: 'sternschanze' },
      { type: 'wandergate', x0: 28, y0: 2, x1: 28, y1: 13, gap: 2.0, style: 'kulisse' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Die Große Armillarsphäre', par: 6, theme: 'sternenwarte', maxStrokes: 18,
    intro: 'Drei Messingringe um das Loch, jeder mit einer einzigen Gasse, jeder mit eigenem Tempo und eigener Richtung. Alle drei zugleich zu erwischen ist möglich, aber selten – der ruhigere Weg ist, sich von Ring zu Ring zu arbeiten und zwischen zweien zu warten. Die hellen Pfosten zeigen, wo die Gasse gerade steht.',
    map: [
      '......................................................',
      '......................................................',
      '..........................###########################.',
      '..........................###########################.',
      '........#############.....###########################.',
      '........#############.....###########################.',
      '........#############.....###########################.',
      '........#############.....###########################.',
      '.......#####.....#####...############################.',
      '.####################################################.',
      '.##T###################################H#############.',
      '.####################################################.',
      '.####################################################.',
      '................#####..##############################.',
      '.................####################################.',
      '.................####################################.',
      '.................####################################.',
      '.................####################################.',
      '.........................############################.',
      '..........................###########################.',
      '......................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 8, y0: 8, x1: 7, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 8, x1: 22, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 8, x1: 25, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 17, y0: 14, x1: 16, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 26, y0: 19, x1: 25, y1: 18, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 6.0, y: 10.5, r: 1.3, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'bumper', x: 14.0, y: 5.5, r: 0.55, style: 'meteorit', kick: 7.5 },
      { type: 'pendulum', x: 18.5, y: 10.0, len: 3.2, amp: 55, ruhe: 90, phase: 0.0, w: 1.2, h: 1.2, style: 'foucault' },
      { type: 'zauberkreis', x: 21.5, y: 15.5, r: 1.3, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'mondzieher', x: 30.0, y: 10.5, r: 3.0, kraft: 7.5, takt: 6.0, phase: 0.2, core: 0.4 },
      { type: 'armillar', x: 39.5, y: 10.5, dicke: 0.3, ringe: [{ r: 8.2, gasse: 0.62, tempo: 0.3, phase: 0.0 }, { r: 5.6, gasse: 0.72, tempo: -0.44, phase: 0.35 }, { r: 3.1, gasse: 0.86, tempo: 0.66, phase: 0.7 }] },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];

const ZAUBER_LOGE = [
  {
    name: 'Vor der Loge', par: 4, theme: 'erzmagierloge',
    intro: 'Der Aufgang zur Loge: drei Gänge, zwei Kehren, und neben dem Weg ist nichts. In jedem Gang steht eine Sache – erst der Schubkreis, dann der Zeiger, dann der Bann. Wer zu früh zu viel Tempo mitnimmt, findet die erste Kehre nicht mehr.',
    map: [
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '...........#################............',
      '...........#################............',
      '...........#################............',
      '..........#####.........####............',
      '..############...........###............',
      '..#T##########...........###............',
      '..############...........###............',
      '.........................####...........',
      '.........................##############.',
      '.........................###########H##.',
      '.........................##############.',
      '........................................',
      '........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 11, y0: 7, x1: 10, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 8, x1: 15, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 25, y0: 8, x1: 24, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 11, x1: 29, y1: 12, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 8.0, y: 9.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'rotor', x: 12.5, y: 9.0, blades: 3, len: 1.3, speed: 0.9, thick: 0.16, style: 'bannzeiger', phase: 0.0 },
      { type: 'lightning', x: 19.0, y: 5.5, w: 3.0, h: 3.0, period: 4.4, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'zauberkreis', x: 26.5, y: 9.0, r: 1.2, wirkung: 'bremse', takt: 4.0, phase: 0.0 },
      { type: 'grubenlampe', x: 31.0, y: 13.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
  {
    name: 'Der Bannlauf', par: 4, theme: 'erzmagierloge',
    intro: 'Der Gang endet vor der Leere. Hinüber kommt nur, wer sich in den Ring aus Bannfeuer rollen läßt – er wirft immer gleich weit, und die Punkte am Boden sagen vorher, wohin. Drüben bremst ein blauer Kreis, damit man in der Kehre nicht vorbeischießt.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..............................###########.',
      '..............................########H##.',
      '..............................###########.',
      '..............................####........',
      '..##############..............###.........',
      '..#T############..............###.........',
      '..##############..............###.........',
      '............#####.............####........',
      '.............##########.......###########.',
      '.............##########.......###########.',
      '.............##########.......###########.',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 33, y0: 7, x1: 34, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 11, x1: 12, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 10, x1: 17, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 33, y0: 10, x1: 34, y1: 11, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 8.5, y: 8.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'cannon', x: 20.0, y: 12.5, base: 0.0, amp: 0.0, speed: 1.0, phase: 0.0, range: 9.5, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'zauberkreis', x: 35.0, y: 12.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'rotor', x: 31.5, y: 8.0, blades: 3, len: 1.3, speed: -0.9, thick: 0.16, style: 'bannzeiger', phase: 0.0 },
      { type: 'grubenlampe', x: 36.0, y: 4.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 29 },
  },
  {
    name: 'Das Bannmal', par: 5, theme: 'bannkreis',
    intro: 'Vier Sterne liegen in vier Sackgassen, und das Bannmal vor dem Loch geht erst auf, wenn alle brennen. In der Gruft sieht man nur, was im Licht steht. Im Hauptgang liegen drei Kreise – sie helfen beim Abbiegen und stehen im Weg beim Zurückkommen.',
    map: [
      '........................................',
      '........................................',
      '........................................',
      '......###............###................',
      '......###............###................',
      '......###............###................',
      '......###............###................',
      '.....#####..........#####...............',
      '..#####################################.',
      '..#T################################H##.',
      '..#####################################.',
      '............#####..........#####........',
      '.............###............###.........',
      '.............###............###.........',
      '.............###............###.........',
      '.............###............###.........',
      '........................................',
      '........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 6, y0: 7, x1: 5, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 9, y0: 7, x1: 10, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 21, y0: 7, x1: 20, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 7, x1: 25, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 13, y0: 12, x1: 12, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 12, x1: 17, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 12, x1: 27, y1: 11, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 31, y0: 12, x1: 32, y1: 11, t: 0.22, h: 0.5 },
      { type: 'sternbild', r: 0.5, sterne: [[7.0, 4.0], [14.0, 14.0], [22.0, 4.0], [29.0, 14.0]], tor: { x0: 33.0, y0: 8.0, x1: 33.0, y1: 11.0 } },
      { type: 'zauberkreis', x: 10.5, y: 9.5, r: 1.2, wirkung: 'sprung', takt: 0.0, phase: 0.0, weite: 4.6 },
      { type: 'zauberkreis', x: 18.0, y: 9.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'zauberkreis', x: 25.5, y: 9.5, r: 1.2, wirkung: 'schub', takt: 4.4, phase: 0.0 },
      { type: 'grubenlampe', x: 7.0, y: 4.5, r: 3.6, style: 'bannlicht' },
      { type: 'grubenlampe', x: 29.0, y: 14.5, r: 3.6, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 43 },
  },
  {
    name: 'Der Rat der Neun', par: 5, theme: 'erzmagierloge',
    intro: 'Vier Hüte, und zwischen ihnen ist nichts – kein Steg, keine Brücke. Wo man herauskommt, entscheidet der Takt, und die beiden Stücke in der Mitte sind verschieden: oben bremst es, unten schiebt es. Wer oben landet, hat Zeit; wer unten landet, muß sie sich nehmen.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '.................###########..............',
      '.................###########..............',
      '.................###########...###........',
      '...............................####.......',
      '..###########..................##########.',
      '..#T#########..................#######H##.',
      '..###########..................##########.',
      '...............................####.......',
      '.................###########...###........',
      '.................###########..............',
      '.................###########..............',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 34, y0: 6, x1: 35, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 11, x1: 35, y1: 10, t: 0.22, h: 0.5 },
      { type: 'zauberhut', takt: 2.2, phase: 0.0, r: 0.42, plaetze: [[10.0, 8.0], [19.0, 4.0], [19.0, 12.0], [32.0, 8.0]] },
      { type: 'zauberkreis', x: 24.0, y: 4.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'zauberkreis', x: 24.0, y: 12.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'mondzieher', x: 32.5, y: 8.5, r: 2.8, kraft: 7.5, takt: 5.5, phase: 0.1, core: 0.4 },
      { type: 'grubenlampe', x: 36.0, y: 8.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 57 },
  },
  {
    name: 'Die Ranken der Gruft', par: 5, theme: 'bannkreis',
    intro: 'Zwei Ranken hintereinander, und zwischen ihnen ein Stück Gang, auf dem ein Bremskreis liegt. Wer zu schnell über die erste kommt, steht beim Anstoßen der zweiten schon still – und in der Dunkelheit sieht man immer nur, was gerade im Licht liegt.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '................................#########.',
      '................................######H##.',
      '................................#########.',
      '...............................#####......',
      '..#################################.......',
      '..#T###############################.......',
      '..#################################.......',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 32, y0: 6, x1: 31, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 35, y0: 7, x1: 36, y1: 6, t: 0.22, h: 0.5 },
      { type: 'ranke', x: 12, y: 7, w: 6, h: 3, dauer: 4.2, r: 0.6, bluete: { x: 9.5, y: 8.5 } },
      { type: 'ranke', x: 24, y: 7, w: 6, h: 3, dauer: 4.2, r: 0.6, bluete: { x: 20.5, y: 8.5 } },
      { type: 'zauberkreis', x: 22.5, y: 8.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'zauberkreis', x: 37.0, y: 4.5, r: 1.2, wirkung: 'bremse', takt: 4.4, phase: 0.0 },
      { type: 'grubenlampe', x: 9.5, y: 8.5, r: 4.2, style: 'bannlicht' },
      { type: 'grubenlampe', x: 20.5, y: 8.5, r: 4.2, style: 'bannlicht' },
      { type: 'grubenlampe', x: 37.0, y: 4.5, r: 4.2, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 71 },
  },
  {
    name: 'Der Blitzgang', par: 5, theme: 'erzmagierloge',
    intro: 'Drei Bänne schlagen versetzt in denselben Gang – es gibt keinen Augenblick, in dem alle drei schweigen, also muß man zwischen ihnen durchwandern. Am Ende steht die Siegelröhre: Wer hineinrollt, kommt oben wieder heraus und spart den ganzen Rückweg.',
    map: [
      '............................................',
      '............................................',
      '............................................',
      '................###########################.',
      '................####a###################H##.',
      '................###########################.',
      '...............####.........................',
      '..#############################.............',
      '..#T###########################.............',
      '..#############################.............',
      '...............#####.......####.............',
      '................####.......####.............',
      '................###############.............',
      '................#############A#.............',
      '................###############.............',
      '............................................',
      '............................................',
    ],
    obstacles: [
      { type: 'wall', x0: 16, y0: 6, x1: 15, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 16, y0: 11, x1: 15, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 11, x1: 20, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 11, x1: 27, y1: 10, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 19, y0: 11, x1: 20, y1: 12, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 28, y0: 11, x1: 27, y1: 12, t: 0.22, h: 0.5 },
      { type: 'lightning', x: 9.0, y: 8.5, w: 3.0, h: 3.0, period: 4.0, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'lightning', x: 16.0, y: 8.5, w: 3.0, h: 3.0, period: 4.0, phase: 0.33, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'lightning', x: 23.0, y: 8.5, w: 3.0, h: 3.0, period: 4.0, phase: 0.66, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'copperpipe', pair: 'A', angle: 0, style: 'siegelroehre' },
      { type: 'zauberkreis', x: 35.0, y: 4.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'grubenlampe', x: 38.0, y: 4.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 83 },
  },
  {
    name: 'Das Wanderloch', par: 5, theme: 'bannkreis',
    intro: 'Das Loch wandert zwischen drei Stellen in einem schmalen Schacht, und man sieht immer nur die, vor der man steht. Der Bannschacht in der Mitte hebt einen über die Kehre hinweg – wenn man ihn trifft. Sonst geht es außen herum, und das dauert.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '............###############.......###.....',
      '............###############.......#H#.....',
      '............###############.......###.....',
      '............####.......####.......###.....',
      '...........####.........###.......###.....',
      '..#############.........###.......###.....',
      '..#T###########.........###.......###.....',
      '..#############.........###.......###.....',
      '........................###.......###.....',
      '........................####.....####.....',
      '........................#############.....',
      '........................#############.....',
      '........................#############.....',
      '..........................................',
      '..........................................',
    ],
    obstacles: [
      { type: 'wall', x0: 15, y0: 7, x1: 16, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 7, x1: 23, y1: 6, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 12, y0: 7, x1: 11, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 12, x1: 28, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 34, y0: 12, x1: 33, y1: 13, t: 0.22, h: 0.5 },
      { type: 'wanderloch', stellen: [[35.5, 4.5], [35.5, 9.5], [35.5, 14.5]], phase: 0.0, style: 'siegelloch' },
      { type: 'zauberkreis', x: 8.0, y: 9.5, r: 1.2, wirkung: 'sprung', takt: 0.0, phase: 0.0, weite: 4.8 },
      { type: 'updraft', x: 24, y: 8, w: 3, h: 3, minSpeed: 2.5, land: 6.5, fly: 7.5, style: 'bannschacht' },
      { type: 'rotor', x: 30.0, y: 14.5, blades: 3, len: 1.3, speed: 0.9, thick: 0.16, style: 'bannzeiger', phase: 0.0 },
      { type: 'zauberkreis', x: 35.5, y: 11.0, r: 1.2, wirkung: 'bremse', takt: 4.6, phase: 0.0 },
    ],
    autoDecor: { density: 0.09, seed: 97 },
  },
  {
    name: 'Die Siegelkammer', par: 5, theme: 'erzmagierloge',
    intro: 'Vier Stücke Gang, und keines hängt am anderen: Die erste Röhre bringt einen nach oben, die Schleuder von oben nach unten, die zweite Röhre ans Ziel. Wer eine davon verfehlt, liegt auf einem Stück, von dem aus es nur einen Weg gibt – zurück in dieselbe Maschine.',
    map: [
      '............................................',
      '............................................',
      '............................................',
      '..................###########...............',
      '..................#a#########...............',
      '..................###########.....###.......',
      '..................................###.......',
      '..................................####......',
      '..###########.....................#########.',
      '..#T#######A#.....................#b####H##.',
      '..###########.....................#########.',
      '..................................####......',
      '..................###########.....###.......',
      '..................#########B#.....###.......',
      '..................###########...............',
      '............................................',
      '............................................',
      '............................................',
    ],
    obstacles: [
      { type: 'wall', x0: 37, y0: 7, x1: 38, y1: 8, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 37, y0: 12, x1: 38, y1: 11, t: 0.22, h: 0.5 },
      { type: 'copperpipe', pair: 'A', angle: 0, style: 'siegelroehre' },
      { type: 'copperpipe', pair: 'B', angle: 0, style: 'siegelroehre' },
      { type: 'cannon', x: 26.0, y: 4.5, base: 1.571, amp: 0.0, speed: 1.0, phase: 0.0, range: 9.0, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'zauberkreis', x: 22.0, y: 13.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'zauberkreis', x: 38.0, y: 9.5, r: 1.2, wirkung: 'bann', takt: 5.0, phase: 0.0 },
      { type: 'grubenlampe', x: 41.0, y: 9.5, r: 3.8, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 109 },
  },
  {
    name: 'Der Erzmagier', par: 6, theme: 'erzmagierloge',
    intro: 'Die Prüfung der Loge: Schubkreis, Ranke, Hüte, Schleuder, Mond, Bann – sechs Gänge hintereinander, und zwischen ihnen ist nichts. Jeder einzelne ist zu schaffen. Alle sechs in einem Anlauf ist das, was den Erzmagierhut kostet.',
    map: [
      '..............................................',
      '..............................................',
      '..............................................',
      '..............................................',
      '......................###########...#########.',
      '......................###########...#########.',
      '......................###########...#########.',
      '......................####..........####......',
      '.....................####...........###.......',
      '..#######################...........###.......',
      '..#T#####################...........###.......',
      '..#######################...........###.......',
      '....................................###.......',
      '...................................####.......',
      '..............................#########.......',
      '..............................##H######.......',
      '..............................#########.......',
      '..............................................',
      '..............................................',
    ],
    obstacles: [
      { type: 'wall', x0: 25, y0: 8, x1: 26, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 39, y0: 8, x1: 40, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 22, y0: 8, x1: 21, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 36, y0: 13, x1: 35, y1: 14, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 10.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'ranke', x: 12, y: 9, w: 6, h: 3, dauer: 4.2, r: 0.6, bluete: { x: 9.5, y: 10.5 } },
      { type: 'zauberhut', takt: 2.2, phase: 0.0, r: 0.42, plaetze: [[20.0, 10.0], [23.0, 5.0], [30.0, 5.0]] },
      { type: 'cannon', x: 31.0, y: 5.5, base: 0.0, amp: 0.0, speed: 1.0, phase: 0.0, range: 9.5, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'mondzieher', x: 41.0, y: 5.5, r: 2.8, kraft: 7.5, takt: 5.0, phase: 0.2, core: 0.4 },
      { type: 'lightning', x: 37.5, y: 11.0, w: 3.0, h: 4.0, period: 4.2, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'zauberkreis', x: 34.0, y: 15.5, r: 1.2, wirkung: 'bremse', takt: 0.0, phase: 0.0 },
      { type: 'grubenlampe', x: 32.0, y: 15.5, r: 4.0, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 127 },
  },
  {
    name: 'Der Bannwächter', par: 6, theme: 'erzmagierloge', maxStrokes: 18,
    intro: 'Am Ende der Loge steht er und sieht zu. Sein Arm dreht sich dorthin, wo der Ball liegt, dann glüht das Siegel unter ihm auf – und wer beim Einschlag im Keil steht, fliegt quer durch den Saal zurück. Der Arm ist langsamer als ein Ball. Das ist alles, was man braucht, und das einzige, worauf man sich verlassen kann.',
    map: [
      '........................................................',
      '........................................................',
      '................................#######################.',
      '................................#######################.',
      '..............#############.....#######################.',
      '..............#############.....#######################.',
      '..............#############.....#######################.',
      '..............####.....####.....#######################.',
      '.............####.......###.....#######################.',
      '..###############.......###.....#######################.',
      '..#T#############.......###.....##################H####.',
      '..###############.......###.....#######################.',
      '........................###.....#######################.',
      '........................####...########################.',
      '........................###############################.',
      '........................###############################.',
      '........................###############################.',
      '...............................########################.',
      '................................#######################.',
      '................................#######################.',
      '........................................................',
    ],
    obstacles: [
      { type: 'wall', x0: 17, y0: 8, x1: 18, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 24, y0: 8, x1: 23, y1: 7, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 14, y0: 8, x1: 13, y1: 9, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 27, y0: 13, x1: 28, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 13, x1: 31, y1: 14, t: 0.22, h: 0.5 },
      { type: 'wall', x0: 32, y0: 18, x1: 31, y1: 17, t: 0.22, h: 0.5 },
      { type: 'zauberkreis', x: 7.0, y: 10.5, r: 1.2, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'lightning', x: 20.0, y: 5.5, w: 3.0, h: 3.0, period: 4.2, phase: 0.0, warn: 1.0, strike: 0.35, style: 'bannschlag' },
      { type: 'cannon', x: 28.0, y: 15.5, base: 0.0, amp: 0.0, speed: 1.0, phase: 0.0, range: 8.0, loadTime: 0.7, catchR: 0.7, flySpeed: 8, style: 'bannschleuder' },
      { type: 'zauberkreis', x: 35.0, y: 15.0, r: 1.4, wirkung: 'schub', takt: 0.0, phase: 0.0 },
      { type: 'bannwaechter', x: 42.0, y: 10.5, r: 2.2, weite: 13.0, keil: 0.4, takt: 5.0, phase: 0.0, folgen: 1.1, wucht: 15, warn: 1.2, schlag: 0.3 },
      { type: 'grubenlampe', x: 50.0, y: 10.5, r: 4.2, style: 'bannlicht' },
    ],
    autoDecor: { density: 0.09, seed: 11 },
  },
];
