/* Der Schneeberg (Weltkennung 'snow'): zwölf Bahnen, ein Aufstieg vom Fuß bis über die Wolken.

   Der rote Faden ist der Wind. Jede andere Welt fragt, wie fest oder wann man schlägt; diese fragt
   *wohin*. Der Wind dreht im Takt durch vier Richtungen, versetzt jeden rollenden Ball – und er ist
   ablesbar: Die Windfahne zeigt die nächste Richtung, bevor sie kommt, und zwischen zwei Richtungen
   ist einen Augenblick Flaute. Wer geradeaus zielt, kommt nicht an; wer danebenzielt oder wartet,
   schon. Darum steht der Wind auf fast jeder Bahn quer zum Weg und nie längs.

   Der zweite Faden ist die Höhe. Die vier Abschnitte sind vier Paletten, und sie werden nach oben
   hin kälter, schmaler und ausgesetzter:
     Bahn 1-3   'snowfoot' – Nadelwald am Fuß, breite Hänge
     Bahn 4-6   'snowrock' – Felsband, Lawine und Seilbahn
     Bahn 7-9   'glacier'  – Blankeis und Gletscherspalten
     Bahn 10-12 'summit'   – Grat und Gipfel, oben die Wolkenetagen

   Vier eigene Maschinen (src/obstacles_snow.js):
     'windfahne'      dreht den Wind und sagt die nächste Richtung an
     'lawine'         fegt im Takt durch ihren Streifen; hinter einem Block ('x') ist man gedeckt
     'seilbahn'       Gondel zwischen zwei Stationen, darf dabei die Ebene wechseln ('ziel')
     'schneebruecke'  trägt genau einen Schlag lang, dann bricht sie ein

   Die Wolkenetagen sind dieselbe Mechanik wie die Ebenen des Uhrenturms – 'map' ist die unterste
   Fläche, 'ebenen' die darüber, alle deckungsgleich. Nur gezeichnet werden sie als Wolkenbank
   statt als Steinscholle (Palette 'summit' und 'cloud' mit ebeneStil 'wolke').

   Sonst gilt dieselbe Kartenlegende wie in courses.js: 's' ist hier Tiefschnee (bremst), 'i'
   blankes Eis (rutscht), 'x' ein Felsblock (und damit Deckung vor der Lawine), 'o' eine offene
   Kante. Winkel in Grad, Zeiten in Sekunden, Koordinaten in Kacheln.

   Die Karten entstehen mit tools/schneeberg.py und werden dort schon beim Bauen geprüft. */
const SNOW_COURSES = [
  {
    name: 'Talstation', par: 3, theme: 'snowfoot', maxStrokes: 12,
    intro: 'Der Hang unter der Talstation, und die erste Lektion des Berges: Hier oben steht der Wind nicht still. Die Fahne dreht sich alle paar Sekunden weiter und zeigt schon vorher, woher es gleich kommt – und zwischen zwei Richtungen ist einen Augenblick Flaute. Wer geradeaus zielt, landet neben dem Loch; wer danebenzielt oder wartet, trifft.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##T####################H##..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..............................',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'windfahne', x: 15, y: 6.5 },
    ],
    decor: [
      { t: 'pineSnow', x: 15, y: 1.4, s: 1.4 },
      { t: 'pineSnow', x: 8, y: 11.4, s: 1.2 },
      { t: 'pineSnow', x: 22, y: 11.4, s: 1.3 },
      { t: 'rockSnow', x: 0.8, y: 6.5, s: 1 },
    ],
    autoDecor: { density: 0.3, seed: 301 },
  },
  {
    name: 'Waldschneise', par: 4, theme: 'snowfoot', maxStrokes: 14,
    intro: 'Die Schneise durch den Wald. In der Mitte bleibt nur eine Gasse zwischen den Baumgruppen frei, und quer dazu drückt der Wind. Links und rechts liegt Tiefschnee: Dort bleibt der Ball fast stehen – manchmal ist genau das die Rettung.',
    map: [
      '................................',
      '................................',
      '................................',
      '..############################..',
      '..#########xx######xx#########..',
      '..#########xx######xx#########..',
      '..##T###sss##########ssss#####..',
      '..######sss##########ssss##H##..',
      '..#########xx######xx#########..',
      '..#########xx######xx#########..',
      '..############################..',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'windfahne', x: 16, y: 6.5, phase: 0.25 },
    ],
    decor: [
      { t: 'pineSnow', x: 16, y: 1.4, s: 1.5 },
      { t: 'pineSnow', x: 6, y: 12.4, s: 1.2 },
      { t: 'pineSnow', x: 26, y: 12.4, s: 1.3 },
      { t: 'rockSnow', x: 30.8, y: 6.5, s: 1 },
    ],
    autoDecor: { density: 0.35, seed: 302 },
  },
  {
    name: 'Lawinenhang', par: 4, theme: 'snowfoot', maxStrokes: 16,
    intro: 'Über dem Hang hängt eine Wächte, und alle neun Sekunden kommt sie herunter. Vorher staubt es an der Abrisskante – das ist die Vorwarnung. Wer dann offen liegt, wird ein Stück mitgenommen; wer hinter einem Felsblock liegt, merkt nichts davon. Die hellen Keile im Schnee zeigen, wo die Deckung reicht.',
    map: [
      '................................',
      '................................',
      '................................',
      '..############################..',
      '..############################..',
      '..#########xx########xx#######..',
      '..############################..',
      '..##T######################H##..',
      '..##############xx############..',
      '..############################..',
      '..###########xx###############..',
      '..############################..',
      '................................',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'lawine', x: 8, y: 3, w: 18, h: 9, angle: 90 },
      { type: 'windfahne', x: 16, y: 10.5 },
    ],
    decor: [
      { t: 'pineSnow', x: 6, y: 1.4, s: 1.3 },
      { t: 'rockSnow', x: 30.8, y: 7.5, s: 1.1 },
      { t: 'pineSnow', x: 25, y: 1.4, s: 1.2 },
    ],
    autoDecor: { density: 0.25, seed: 303 },
  },
  {
    name: 'Felsband', par: 4, theme: 'snowrock', maxStrokes: 16,
    intro: 'Ein Band, vier Kacheln breit, und links wie rechts geht es hinunter. Der Wind steht quer dazu, und kurz vor dem Loch ist das Band vereist – dort greift nichts mehr, außer dem Wind. Hier lohnt es sich, auf die Flaute zu warten.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..##########xx##################..',
      '..##T###################iiii####..',
      '..######################iiii##H#..',
      '..#################xx###########..',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'windfahne', x: 8, y: 7.5, phase: 0.4 },
      { type: 'lawine', x: 10, y: 6, w: 12, h: 4, angle: 90, phase: 0.3 },
    ],
    decor: [
      { t: 'rockSnow', x: 17, y: 3.4, s: 1.4 },
      { t: 'rockSnow', x: 8, y: 12.4, s: 1.2 },
      { t: 'crystalBlue', x: 26, y: 3.4, s: 1 },
      { t: 'rockSnow', x: 28, y: 12.4, s: 1.1 },
    ],
    autoDecor: { density: 0.2, seed: 304 },
  },
  {
    name: 'Die Seilbahn', par: 4, theme: 'snowrock', maxStrokes: 16,
    intro: 'Zwischen den beiden Felsköpfen liegt nichts als Luft – hinüber bringt nur die Gondel. Sie wartet an der Station, fährt hinüber, wartet und kommt zurück; einsteigen kann man nur, während sie steht. Drüben liegt Tiefschnee vor dem Loch, der den Anlauf schluckt.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '.......................###########..',
      '..###########..........###########..',
      '..###########..........#####sss###..',
      '..###########..........#####sss###..',
      '..##T########..........#####sssH##..',
      '..###########..........###########..',
      '..###########..........###########..',
      '..###########..........###########..',
      '....................................',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'seilbahn', x0: 11.5, y0: 8.5, x1: 23.5, y1: 8.5, wait: 2.6, travel: 3.4 },
      { type: 'windfahne', x: 6, y: 8.5 },
    ],
    decor: [
      { t: 'rockSnow', x: 17, y: 2.4, s: 1.5 },
      { t: 'rockSnow', x: 17, y: 13.4, s: 1.4 },
      { t: 'crystalBlue', x: 34.8, y: 8.5, s: 1 },
    ],
    autoDecor: { density: 0.2, seed: 305 },
  },
  {
    name: 'Schneewächte', par: 5, theme: 'snowrock', maxStrokes: 18,
    intro: 'Die Rinne ist überschneit, und die Wächte darüber trägt – aber nur einmal. Hat der Ball sie überquert, bricht sie hinter ihm ein; im selben Schlag kommt man nicht zurück. Beim nächsten Schlag liegt sie wieder da, der Berg schneit zu. Also: erst schauen, wo man hinwill, dann hinüber.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................##############..',
      '..................####xx########..',
      '..##############################..',
      '..##############################..',
      '..##T########################H##..',
      '..##############################..',
      '..##############################..',
      '..................##############..',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'schneebruecke', x: 14, y: 6, w: 4, h: 5 },
      { type: 'windfahne', x: 25, y: 9.5, phase: 0.5 },
      { type: 'lawine', x: 19, y: 4, w: 11, h: 7, angle: 90, phase: 0.45 },
    ],
    decor: [
      { t: 'rockSnow', x: 8, y: 12.4, s: 1.3 },
      { t: 'crystalBlue', x: 16, y: 2.4, s: 1.1 },
      { t: 'rockSnow', x: 33, y: 2.4, s: 1.2 },
    ],
    autoDecor: { density: 0.2, seed: 306 },
  },
  {
    name: 'Blankeis', par: 4, theme: 'glacier', maxStrokes: 16,
    intro: 'Der Gletscher, blank gefegt. Auf dem Eis bremst nichts mehr – der Ball läuft, bis ihn etwas aufhält, und der Wind hat die ganze Zeit über Gelegenheit, ihn abzutreiben. Sanft schlagen ist hier keine Schwäche, sondern die einzige Möglichkeit.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..#######iiiiixxiiiiiiiiiii#####..',
      '..#######iiiiiiiiiiiiiiiiii#####..',
      '..##T####iiiiiiiiiiiiiiiiii#####..',
      '..#######iiiiiiiiiiiiiiiiii##H##..',
      '..#######iiiiiiiiiiiiiiiiii#####..',
      '..#######iiiiiiiiiiixxiiiii#####..',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'windfahne', x: 6, y: 7.5 },
      { type: 'lawine', x: 11, y: 5, w: 14, h: 6, angle: 90, phase: 0.35 },
    ],
    decor: [
      { t: 'crystalBlue', x: 17, y: 2.4, s: 1.5 },
      { t: 'crystalBlue', x: 12, y: 12.4, s: 1.3 },
      { t: 'rockSnow', x: 27, y: 2.4, s: 1.2 },
      { t: 'crystalBlue', x: 33, y: 12.4, s: 1.1 },
    ],
    autoDecor: { density: 0.15, seed: 307 },
  },
  {
    name: 'Gletscherspalten', par: 5, theme: 'glacier', maxStrokes: 18,
    intro: 'Zwei Spalten hintereinander, beide nur von einer Wächte überbrückt. Jede trägt genau einen Schlag – wer auf der Zwischeninsel landet, hat die erste hinter sich gelassen und muss über die zweite weiter. Zurück geht es erst im nächsten Schlag, wenn wieder Schnee darüberliegt.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '.........................#########..',
      '.........................#####xx##..',
      '..#########################iii####..',
      '..#########################iii####..',
      '..##T######################iii####..',
      '..#########################iii#H##..',
      '..################################..',
      '..################################..',
      '.........................#########..',
      '....................................',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'schneebruecke', x: 11, y: 6, w: 4, h: 6 },
      { type: 'schneebruecke', x: 21, y: 6, w: 4, h: 6 },
      { type: 'windfahne', x: 17, y: 10.5, phase: 0.3 },
      { type: 'lawine', x: 26, y: 4, w: 8, h: 8, angle: 90, phase: 0.5 },
    ],
    decor: [
      { t: 'crystalBlue', x: 18, y: 2.4, s: 1.4 },
      { t: 'crystalBlue', x: 8, y: 13.4, s: 1.2 },
      { t: 'rockSnow', x: 30, y: 14.4, s: 1.2 },
    ],
    autoDecor: { density: 0.15, seed: 308 },
  },
  {
    name: 'Eisbruch', par: 5, theme: 'glacier', maxStrokes: 18,
    intro: 'Der Bruch, wo der Gletscher über die Kante fällt. Über die erste Kluft trägt die Gondel, quer über die Mittelinsel läuft die Lawine, und auf die Kanzel kommt man nur über eine Wächte, die einmal trägt. Drei Sachen nacheinander, und jede will für sich abgepasst werden.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................########........',
      '....................########........',
      '..##########........##iiii#########.',
      '..##########........##iiii#########.',
      '..##T#######........##iiii#######H#.',
      '..##########........##iiii#########.',
      '..##########........###############.',
      '..##########........###xx##########.',
      '....................########........',
      '....................................',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'seilbahn', x0: 10.5, y0: 8.5, x1: 21.5, y1: 8.5, wait: 2.6, travel: 3.8 },
      { type: 'lawine', x: 20, y: 4, w: 8, h: 8, angle: 90, phase: 0.4 },
      { type: 'schneebruecke', x: 28, y: 6, w: 3, h: 6 },
      { type: 'windfahne', x: 6, y: 8.5, phase: 0.2 },
    ],
    decor: [
      { t: 'crystalBlue', x: 16, y: 2.4, s: 1.4 },
      { t: 'crystalBlue', x: 16, y: 14.4, s: 1.3 },
      { t: 'rockSnow', x: 33, y: 14.4, s: 1.2 },
    ],
    autoDecor: { density: 0.15, seed: 309 },
  },
  {
    name: 'Der Grat', par: 5, theme: 'summit', maxStrokes: 18,
    intro: 'Drei Kacheln breit, und rechts wie links tausend Meter Luft. Der Wind steht quer zum Grat, und er dreht: Wer im falschen Augenblick losschlägt, wird heruntergedrückt. Die beiden Felsköpfe auf dem Grat sind das Einzige, woran man sich festhalten kann.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '..................................',
      '.........................########.',
      '.........................########.',
      '..#######................##xx####.',
      '..############xx#################.',
      '..##T########################H###.',
      '..#################xx############.',
      '..#######................########.',
      '.........................########.',
      '.........................########.',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'windfahne', x: 5, y: 9.5 },
      { type: 'lawine', x: 25, y: 5, w: 8, h: 8, angle: 90, phase: 0.35 },
    ],
    decor: [
      { t: 'rockSnow', x: 16, y: 4.4, s: 1.4 },
      { t: 'rockSnow', x: 16, y: 14.4, s: 1.3 },
      { t: 'crystalBlue', x: 33, y: 2.4, s: 1.1 },
    ],
    autoDecor: { density: 0.12, seed: 310 },
  },
  {
    name: 'Über den Wolken', par: 5, theme: 'summit', maxStrokes: 18,
    intro: 'Ab hier ist der Berg zu Ende, und weiter geht es nur über die Wolken. Die Gondel hängt an einem Seil, das von der Platte hinauf in die Wolkenbank führt – man sieht schon von unten, wohin sie fährt. Oben trägt die Wolke, aber an ihrem hellen Rand hört sie auf; wer darüber hinausrollt, fällt auf den Fels zurück. Das kostet keinen Strafschlag, nur den Weg.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '..#############.....................',
      '..#############.....................',
      '..##T###xx#####.....................',
      '..#############.....................',
      '..#############.....................',
      '..#############.....................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    ebenen: [
      [
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................#############o..',
        '....................#############o..',
        '....................#########H###o..',
        '....................#############o..',
        '....................#############o..',
        '....................#############o..',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
      ],
    ],
    obstacles: [
      { type: 'seilbahn', x0: 13.5, y0: 9.5, x1: 21.5, y1: 8.5, wait: 2.6, travel: 3.8, ziel: 1 },
      { type: 'windfahne', x: 6, y: 11.5 },
      { type: 'lawine', x: 2, y: 7, w: 12, h: 6, angle: 90, phase: 0.5 },
    ],
    decor: [
      { t: 'rockSnow', x: 17, y: 14.4, s: 1.3 },
      { t: 'cloud', x: 25, y: 2.4, s: 1.6 },
      { t: 'cloud', x: 8, y: 2.4, s: 1.4 },
      { t: 'cloud', x: 30, y: 14.4, s: 1.5 },
    ],
    views: [
      { x: 0, y: 0, w: 18, h: 17, ebene: 0, look: { x: 13.5, y: 9.5 } },
    ],
    autoDecor: { density: 0.12, seed: 311 },
  },
  {
    name: 'Der Gipfel', par: 6, theme: 'summit', maxStrokes: 22,
    intro: 'Ganz oben. Von der Gipfelplatte bringt die erste Gondel auf die untere Wolke, dort trennt eine Wächte die beiden Bänke – sie trägt einmal, dann bricht sie ein –, und von der zweiten Bank führt die letzte Gondel noch eine Wolke höher. Dort liegt das Loch. Über der Platte fegt es noch einmal herunter, und der Wind hört den ganzen Weg nicht auf. Wer hier ankommt, hat den Berg gelesen und nicht bezwungen.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '..#############.....................',
      '..#############.....................',
      '..####xx#######.....................',
      '..##T##########.....................',
      '..#############.....................',
      '..#############.....................',
      '..#############.....................',
      '....................................',
      '....................................',
      '....................................',
    ],
    ebenen: [
      [
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '.................o#######...######..',
        '.................o################..',
        '.................o################..',
        '.................o################..',
        '.................o################..',
        '.................o#######...######..',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
      ],
      [
        '....................................',
        '....................................',
        '....................................',
        '.......................o##########..',
        '.......................o##########..',
        '.......................o######H###..',
        '.......................o##########..',
        '.......................o##########..',
        '.......................o##########..',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
      ],
    ],
    obstacles: [
      { type: 'seilbahn', x0: 13.5, y0: 13.5, x1: 19.5, y1: 12.5, wait: 2.6, travel: 3.8, ziel: 1 },
      { type: 'schneebruecke', x: 25, y: 10, w: 3, h: 4, ebene: 1 },
      { type: 'seilbahn', x0: 31.5, y0: 11.5, x1: 30.5, y1: 6.5, wait: 2.6, travel: 3.4, ebene: 1, ziel: 2 },
      { type: 'windfahne', x: 10, y: 15.5 },
      { type: 'lawine', x: 2, y: 10, w: 13, h: 7, angle: 90, phase: 0.4 },
    ],
    decor: [
      { t: 'cloud', x: 20, y: 2.4, s: 1.6 },
      { t: 'cloud', x: 8, y: 4.4, s: 1.4 },
      { t: 'cloud', x: 30, y: 17.4, s: 1.5 },
      { t: 'rockSnow', x: 17, y: 17.4, s: 1.3 },
    ],
    views: [
      { x: 0, y: 0, w: 17, h: 20, ebene: 0, look: { x: 13.5, y: 13.5 } },
      { x: 16, y: 0, w: 20, h: 20, ebene: 1, look: { x: 31.5, y: 11.5 } },
    ],
    autoDecor: { density: 0.1, seed: 312 },
  },
];
