/* Uhrenturm (Weltkennung 'clock'): dreizehn Bahnen in einer Stadt, die im Takt läuft.

   Der rote Faden ist die Zeit. Jede andere Welt fragt, wie fest und wohin man schlägt; diese fragt
   zuerst *wann*. Darum steht auf jeder Bahn mindestens eine Maschine vor einer Stelle, an der kein
   Weg vorbeiführt – eine Tür, eine Lücke, ein Rohr, eine Etage –, und sie gibt diese Stelle nur
   zeitweise frei. Wer zusieht und mitzählt, kommt durch; wer nur fest schlägt, nicht.

   Es ist die letzte Welt des Spiels, darum sind ihre Karten durchweg weiter gebaut als die der
   übrigen Welten: die schmalste 34 Kacheln breit, die weiten 40 bis 42, das Zifferblatt 36 auf 26.

   Aufbau: Bahn 1 bis 4 sind flach und führen je ein bis zwei Maschinen ein. Bahn 5 bringt die
   erste zweite Ebene (eine einzige Turbine, sonst nichts Neues), Bahn 6 ist eine flache Atempause,
   Bahn 7 und 8 bringen Aufzug und Zahnstange samt Luke. Bahn 9 bis 11 mischen, Bahn 12 stapelt
   drei Etagen, die nur Kupferrohre verbinden, und Bahn 13 ist der Höhepunkt. Das Kupferrohr kommt
   ab Bahn 4 vor, die Hemmung ab Bahn 6 – beide bewusst nicht auf jeder Bahn.

   Gestapelte Ebenen: 'map' ist die unterste Fläche, 'ebenen' sind die darüber, alle deckungsgleich.
   Der Ball ist immer auf genau einer und kollidiert nur mit deren Wänden. Hinauf geht es über
   Turbine, Aufzug, Zahnstange oder ein Kupferrohr mit 'ziel'; hinunter an jeder offenen Kante
   ('o' in der Karte) und durch eine offene Luke, beides ohne Strafschlag.

   Das wandernde Loch steht auf Bahn 6, 9 und 11 und - als ganzes Zifferblatt mit zwoelf
   Stundenmarken - auf Bahn 13. Es springt alle zehn Sekunden eine Stelle weiter. Was das Loch tut,
   macht das Hindernis 'wanderloch' selbst; das 'H' der Karte steht auf seiner ersten Stelle, damit
   die Bahn auch ohne laufende Uhr ein Ziel hat.

   Auf Bahn 13 gehen ausserdem die drei Zeiger des Turms ('handclock'): Sie sind keine Mauern,
   sondern fuehren Felder mit sich - der langsame Stundenzeiger bremst, der Minutenzeiger stoesst
   weg, der schnelle Sekundenzeiger zieht an.

   Die Kupferrohre stehen nicht als Koordinaten in der Hindernisliste, sondern als Buchstaben in der
   Karte: Der Großbuchstabe ist der Rohrmund, der gleiche Kleinbuchstabe das Rohrende (A/a, B/b,
   C/c). Bei einem Rohr zwischen Ebenen steht der Mund auf der Karte von 'ebene', das Ende auf der
   von 'ziel'. In der Liste steht je Paar nur, in welche Richtung es ausspuckt ('angle' in Grad).

   Die Karten dieser Datei entstehen mit tools/uhrenturm.py aus Rechtecken und Scheiben. Das Skript
   prüft schon beim Bauen, was sonst erst im Spiel auffiele: dass jeder Punkt, den eine Maschine
   braucht, auf der Bahn liegt – der Umkehrpunkt eines Pendels, das Ende eines Zahnradfelds, der
   Landepunkt einer Feder, jede Marke des Zifferblatts, der Boden über einem Aufzug.

   Sonst gilt dieselbe Kartenlegende wie in courses.js. Winkel in Grad, wo nicht anders vermerkt
   (Feder und Rohr rechnen intern im Bogenmaß), Zeiten in Sekunden, Koordinaten in Kacheln. */
const CLOCK_COURSES = [
  {
    name: 'Marktplatz', par: 3, theme: 'clocktown', maxStrokes: 12,
    intro: 'Der Platz unter der Stadtuhr. Durch die Mauer führt eine einzige Tür, und vor ihr schwingt das große Pendel. Zweimal je Schwingung gibt es die Tür frei – dann muss der Ball hindurch.',
    map: [
      '..................................',
      '..................................',
      '..................................',
      '..###############x##############..',
      '..###############x##############..',
      '..###############x##############..',
      '..##T########################H##..',
      '..###############x##############..',
      '..###############x##############..',
      '..###############x##############..',
      '..................................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 17.5, y: 3, len: 3.5, amp: 50, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 17, y: 0.5, s: 2.4 },
      { t: 'lantern', x: 4.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 29.5, y: 0.6, s: 1 },
      { t: 'barrel', x: 0.9, y: 6.5, s: 1 },
      { t: 'crate', x: 32.8, y: 4.4, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 71 },
  },
  {
    name: 'Glockengasse', par: 4, theme: 'clocktown', maxStrokes: 14,
    intro: 'Zwei Türen, zwei Pendel – und sie gehen versetzt. Wer die erste im richtigen Moment nimmt, steht vor der zweiten zur falschen Zeit. Einmal zusehen lohnt sich mehr als jeder feste Schlag.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '..##########x###########x###########..',
      '..##########x###########x###########..',
      '..##########x###########x###########..',
      '..##T###########################H###..',
      '..##########x###########x###########..',
      '..##########x###########x###########..',
      '..##########x###########x###########..',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 12.5, y: 3, len: 3.5, amp: 50, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'pendulum', x: 24.5, y: 3, len: 3.5, amp: 50, ruhe: 90, phase: 0.5, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 19, y: 0.5, s: 2.4 },
      { t: 'bell', x: 9.5, y: 11.6, s: 1.2 },
      { t: 'bell', x: 29.5, y: 11.6, s: 1.2 },
      { t: 'lantern', x: 19, y: 11.7, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 23 },
  },
  {
    name: 'Räderwerkstatt', par: 4, theme: 'clocktown', maxStrokes: 16,
    intro: 'Zwischen den Hallen liegt nichts als Luft; hinüber tragen nur die Zahnräder. Sie halten an jedem Ufer kurz an – das ist der Moment zum Einsteigen. Drüben wartet noch ein Pendel.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '..############........########x#####..',
      '..############........########x#####..',
      '..############........########x#####..',
      '..##T########o........o##########H##..',
      '..############........########x#####..',
      '..############........########x#####..',
      '..############........########x#####..',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'gearfield', x0: 13.5, y0: 6.5, x1: 22.5, y1: 6.5, wait: 2.8, travel: 3.6, r: 0.9, zaehne: 10, phase: 0 },
      { type: 'pendulum', x: 30.5, y: 2.5, len: 4, amp: 60, ruhe: 90, phase: 0.35, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 18, y: 0.5, s: 2.2 },
      { t: 'lantern', x: 5.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 32.5, y: 0.6, s: 1 },
      { t: 'gearFlat', x: 18, y: 11.5, s: 1.8 },
      { t: 'crate', x: 0.9, y: 6.5, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 44 },
  },
  {
    name: 'Rohrpost', par: 4, theme: 'boiler', maxStrokes: 16,
    intro: 'Die Wand hat kein Tor. Hinüber führt nur das Kupferrohr – und in das kommt man immer, auch ganz sacht. Die Leitung läuft über die Wand hinweg, man sieht den Ball darin fahren und weiß schon vorher, wo er ankommt. Hinter der Wand wirft ihn das Rohrende in die Kesselhalle, wo wieder ein Pendel vor der Tür steht.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '..#############x########a#####x#####..',
      '..#############x##############x#####..',
      '..#############x##############x#####..',
      '..##T#########Ax#################H##..',
      '..#############x##############x#####..',
      '..#############x##############x#####..',
      '..#############x##############x#####..',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'pendulum', x: 30.5, y: 2.5, len: 4, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 0.6, s: 1 },
      { t: 'lantern', x: 25.5, y: 11.6, s: 1 },
      { t: 'barrel', x: 36.8, y: 6.5, s: 1 },
      { t: 'gearFlat', x: 9.5, y: 11.5, s: 1.4 },
    ],
    autoDecor: { density: 0.12, seed: 88 },
  },
  {
    name: 'Turbinenhalle', par: 4, theme: 'boiler', maxStrokes: 16,
    intro: 'Hier geht es zum ersten Mal nach oben. Das Loch liegt auf der Galerie, und hinauf bringt nur die Turbine: Wer über ihr Gitter rollt, wird mit einem Windstoß eine Etage höher gesetzt – mit derselben Richtung und demselben Tempo. Oben hält die Brüstung, nur die gestrichelte Südkante ist offen: Von dort geht es ohne Strafschlag zurück nach unten, wenn man sich verschätzt hat.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '......................................',
      '..##################x###############..',
      '..##################x###############..',
      '..##################x###############..',
      '..##T###############################..',
      '..##################x###############..',
      '..##################x###############..',
      '..##################x###############..',
      '..##################x###############..',
      '......................................',
      '......................................',
      '......................................',
    ],
    ebenen: [
      [
        '......................................',
        '......................................',
        '......................................',
        '......................................',
        '......................................',
        '......................................',
        '........................###########...',
        '........................########H##...',
        '........................###########...',
        '........................###########...',
        '........................ooooooooooo...',
        '......................................',
        '......................................',
        '......................................',
        '......................................',
      ],
    ],
    obstacles: [
      { type: 'pendulum', x: 20.5, y: 3.5, len: 4, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'turbine', x: 26.5, y: 7.5, w: 1.4, h: 1.4 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 1.5, s: 1 },
      { t: 'lantern', x: 15.5, y: 13.5, s: 1 },
      { t: 'barrel', x: 36.8, y: 7.5, s: 1 },
      { t: 'gearFlat', x: 10, y: 13.4, s: 1.5 },
    ],
    autoDecor: { density: 0.12, seed: 105 },
  },
  {
    name: 'Hemmwerk', par: 4, theme: 'escapement', maxStrokes: 16,
    intro: 'Die Hemmung sperrt immer eine Hälfte des Ganges und gibt die andere frei; alle paar Sekunden wechselt sie. Beim Umschlagen sind beide Klinken kurz unten. Dahinter steht das Pendel vor der Tür – und hinter der Tür bleibt das Loch nicht liegen: Es springt alle zehn Sekunden eine Stelle weiter. Der leuchtende Ring sagt, wohin als Nächstes.',
    map: [
      '......................................',
      '......................................',
      '......................................',
      '..#########################x########..',
      '..#########################x####H###..',
      '..#########################x########..',
      '..##T###############################..',
      '..#########################x########..',
      '..#########################x########..',
      '..#########################x########..',
      '......................................',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'escapement', x: 15.5, y: 6.5, w: 0.45, h: 7, phase: 0 },
      { type: 'pendulum', x: 27.5, y: 3, len: 3.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'wanderloch', stellen: [[32.5, 4.5], [32.5, 6.5], [32.5, 8.5]] },
    ],
    decor: [
      { t: 'gearFlat', x: 19, y: 1.4, s: 1.8 },
      { t: 'lantern', x: 9.5, y: 11.5, s: 1 },
      { t: 'lantern', x: 29.5, y: 11.5, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 12 },
  },
  {
    name: 'Federkammer', par: 5, theme: 'boiler', maxStrokes: 18,
    intro: 'Über die Kluft kommt nur, wer sich einspannen lässt; der leuchtende Punkt zeigt, wo der Ball landen wird. Drüben steht der Aufzug: Die Kabine wartet unten, und wer hineinrollt, fährt mit – hier muss man nichts abpassen. Oben liegt dafür die Luke im Weg: zu ist sie Boden, offen ein Loch. Und hinter ihr wartet das Ziel.',
    map: [
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '.......................###############..',
      '..#############........###############..',
      '..#############........###############..',
      '..#############........###############..',
      '..##T##########........###############..',
      '..#############........###############..',
      '..#############........###############..',
      '..#############........###############..',
      '..#############........###############..',
      '.......................###############..',
      '........................................',
      '........................................',
      '........................................',
    ],
    ebenen: [
      [
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '..........................o###########..',
        '..........................o#########H#..',
        '..........................o###########..',
        '..........................o###########..',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
      ],
    ],
    obstacles: [
      { type: 'springwork', x: 10.5, y: 8.5, base: 0, amp: 0.22, speed: 0.8, range: 12, catchR: 0.7, loadTime: 0.9 },
      { type: 'aufzug', x: 30.5, y: 8.5, angle: 0 },
      { type: 'luke', x: 33.5, y: 8.5, w: 1.6, h: 1.6, ebene: 1 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 2.5, s: 1 },
      { t: 'lantern', x: 30.5, y: 1.5, s: 1 },
      { t: 'barrel', x: 18, y: 2.5, s: 1 },
      { t: 'crate', x: 18, y: 15.4, s: 1 },
      { t: 'gearFlat', x: 20, y: 15.4, s: 1.5 },
    ],
    autoDecor: { density: 0.12, seed: 61 },
  },
  {
    name: 'Zeigerhof', par: 5, theme: 'clocktown', maxStrokes: 18,
    intro: 'Der runde Hof unter dem großen Zeiger. Er braucht zwölf Sekunden für eine Runde und schiebt alles vor sich her, was auf dem Pflaster liegt – hinüber kommt man nur hinter ihm her. Am Vorplatz steht die Zahnstange: Ihre Schaufel wartet unten, fährt hoch und kommt zurück, und sie nimmt mit, wer beim Losfahren daraufsteht. Oben liegt das Loch.',
    map: [
      '........................................',
      '........................................',
      '........................................',
      '................########................',
      '...............##########...............',
      '..............############..............',
      '..............############..............',
      '.............#########################..',
      '..####################################..',
      '..####################################..',
      '..##T#################################..',
      '..####################################..',
      '..###########.############.###########..',
      '..............############..............',
      '...............##########...............',
      '................########................',
      '........................................',
      '........................................',
      '........................................',
    ],
    ebenen: [
      [
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '...............................######o..',
        '...............................####H#o..',
        '...............................######o..',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '........................................',
      ],
    ],
    obstacles: [
      { type: 'sweephand', x: 20, y: 9.5, r: 5.5, thick: 0.24, phase: 0 },
      { type: 'zahnstange', x: 33.5, y: 10.5, angle: 0 },
    ],
    decor: [
      { t: 'clock', x: 20, y: 0.6, s: 2.6 },
      { t: 'lantern', x: 5.5, y: 5.5, s: 1 },
      { t: 'lantern', x: 31.5, y: 4.5, s: 1 },
      { t: 'gearFlat', x: 20, y: 17.4, s: 1.8 },
      { t: 'crate', x: 0.9, y: 10.5, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 5 },
  },
  {
    name: 'Kesselhaus', par: 5, theme: 'boiler', maxStrokes: 18,
    intro: 'Erst durch die Tür, dann ins Rohr – die Tür will abgepasst sein, das Rohr nimmt einen immer. In der Kesselhalle wartet die Feder, die als Einzige über die Glut auf das Podest wirft. Und auf dem Podest wandert das Loch zwischen drei Stellen: Die helle ist die nächste.',
    map: [
      '........................................',
      '........................................',
      '...............######a######............',
      '...............#############............',
      '..######x#####x#############...#######..',
      '..######x#####x#############...####H##..',
      '..######x#####x#############...#######..',
      '..#T#########Ax#############...#######..',
      '..######x#####x#############...#######..',
      '..######x#####x#############...#######..',
      '..######x#####x#############...#######..',
      '..######x#####x#############...#######..',
      '...............#############............',
      '........................................',
      '........................................',
    ],
    obstacles: [
      { type: 'pendulum', x: 8.5, y: 4, len: 3.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'springwork', x: 25.5, y: 7.5, base: 0, amp: 0.2, speed: 0.75, range: 9, catchR: 0.7, loadTime: 0.9 },
      { type: 'wanderloch', stellen: [[35.5, 5.5], [35.5, 7.5], [35.5, 9.5]] },
    ],
    decor: [
      { t: 'lantern', x: 4.5, y: 2.5, s: 1 },
      { t: 'barrel', x: 29, y: 7.5, s: 1 },
      { t: 'crate', x: 29, y: 10.5, s: 1 },
      { t: 'gearFlat', x: 21, y: 13.4, s: 1.6 },
    ],
    autoDecor: { density: 0.12, seed: 93 },
  },
  {
    name: 'Glockenturm', par: 5, theme: 'clocktown', maxStrokes: 20,
    intro: 'Die Glockenstube liegt eine Etage höher. Unten stehen erst das Pendel vor der Tür und dann die Hemmung quer durch die Halle; hinauf bringt der Aufzug, und oben liegt die Luke zwischen der Kabine und dem Loch. Drei Takte, und keiner passt zum anderen – hier gewinnt, wer wartet, nicht wer fest schlägt.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '..#############x########################..',
      '..#############x########################..',
      '..#############x########################..',
      '..#############x########################..',
      '..##T###################################..',
      '..#############x########################..',
      '..#############x########################..',
      '..#############x########################..',
      '..#############x########################..',
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    ebenen: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '...........................############o..',
        '...........................##########H#o..',
        '...........................############o..',
        '...........................############o..',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
    ],
    obstacles: [
      { type: 'pendulum', x: 15.5, y: 4, len: 4.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'escapement', x: 24.5, y: 8.5, w: 0.45, h: 9, phase: 0.5 },
      { type: 'aufzug', x: 30.5, y: 8.5, angle: 0 },
      { type: 'luke', x: 34.5, y: 8.5, w: 1.6, h: 1.6, ebene: 1, phase: 0.35 },
    ],
    decor: [
      { t: 'bell', x: 7.5, y: 1.4, s: 1.4 },
      { t: 'bell', x: 33.5, y: 1.4, s: 1.4 },
      { t: 'clock', x: 20, y: 0.8, s: 2.4 },
      { t: 'lantern', x: 20, y: 15.4, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 145 },
  },
  {
    name: 'Räderschacht', par: 6, theme: 'escapement', maxStrokes: 22,
    intro: 'In die Endkammer führt unten keine Tür. Erst über die Zahnräder auf die Scheibe, dort am Zeiger vorbei auf die Zahnstange – und oben über den schmalen Steg ohne Geländer. Wer zu weit rollt, fällt seitlich hinunter; wer weit genug kommt, fällt am Ende genau in die Kammer. Dort wandert das Loch zwischen drei Stellen.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..................######..................',
      '.................########.................',
      '................##########......########..',
      '..##########...############.....########..',
      '..##########...############.....###H####..',
      '..##########...############.....########..',
      '..##T######o..#o############....########..',
      '..##########...############.....########..',
      '..##########...############.....########..',
      '..##########...############.....########..',
      '................##########......########..',
      '.................########.................',
      '..................######..................',
      '..........................................',
    ],
    ebenen: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '....................#####ooooooooooo......',
        '....................#####ooooooooooo......',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
    ],
    obstacles: [
      { type: 'gearfield', x0: 11.5, y0: 9.5, x1: 15.5, y1: 9.5, wait: 2.2, travel: 2.6, r: 0.9, zaehne: 10, phase: 0 },
      { type: 'sweephand', x: 21, y: 9.5, r: 5, thick: 0.24, phase: 0.25 },
      { type: 'zahnstange', x: 21.5, y: 9.5, angle: 0 },
      { type: 'wanderloch', stellen: [[35.5, 7.5], [35.5, 9.5], [35.5, 11.5]] },
    ],
    decor: [
      { t: 'gearFlat', x: 21, y: 1.4, s: 1.8 },
      { t: 'gearFlat', x: 13.5, y: 15.4, s: 1.6 },
      { t: 'lantern', x: 5.5, y: 3.5, s: 1 },
      { t: 'lantern', x: 35.5, y: 2.5, s: 1 },
      { t: 'crate', x: 29, y: 15.4, s: 1 },
    ],
    autoDecor: { density: 0.1, seed: 207 },
  },
  {
    name: 'Kupferlabyrinth', par: 6, theme: 'boiler', maxStrokes: 22,
    intro: 'Drei Kammern übereinander, und zwischen ihnen führt kein Weg – nur die Rohre. Hinein kommt man immer, auch ganz sacht; man sieht den Ball außen an der Halle entlangfahren und weiß schon, wo er ankommt. Schwer ist, was dazwischen liegt: Zwischen dem ersten und dem zweiten Rohrmund steht die Hemmung, und die offenen Kanten oben verzeihen keinen zu festen Schlag.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '................######a######.............',
      '..###########...#############.............',
      '..###########...#############.............',
      '..###########...#############.............',
      '..##T#######A...############B.............',
      '..###########...#############.............',
      '..###########...#############.............',
      '..###########...#############.............',
      '..###########...#############.............',
      '................#############.............',
      '..........................................',
      '..........................................',
      '..........................................',
    ],
    ebenen: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '....................#################o....',
        '....................#################o....',
        '....................####b#########C##o....',
        '....................#################o....',
        '....................#################o....',
        '....................#################o....',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................#############o..',
        '..........................##c########H#o..',
        '..........................#############o..',
        '..........................#############o..',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'escapement', x: 25, y: 8.5, w: 0.45, h: 10, phase: 0 },
      { type: 'copperpipe', pair: 'B', angle: 0, ziel: 1 },
      { type: 'copperpipe', pair: 'C', angle: 0, ebene: 1, ziel: 2 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 2.5, s: 1 },
      { t: 'lantern', x: 22, y: 15.4, s: 1 },
      { t: 'barrel', x: 32.5, y: 15.4, s: 1 },
      { t: 'crate', x: 14, y: 2.5, s: 1 },
    ],
    autoDecor: { density: 0.12, seed: 311 },
  },
  {
    name: 'Der Rohrturm', par: 6, theme: 'boiler', maxStrokes: 22,
    intro: 'Hier stehen die Etagen weit auseinander, und dazwischen ist nichts als Luft – nur das Kupferrohr steigt hindurch, und man kann ihm mit den Augen folgen. Drei Leitungen, sonst kein Weg: Die erste bringt quer in die Kesselhalle, die zweite von dort in einem Zug bis ganz nach oben auf den Steg. Das Loch aber liegt auf der mittleren Etage, und hinauf führt dorthin nichts – man kommt nur von oben hinein, durch die Luke im Steg. Wer unten auf der Galerie am Loch vorbeirollt, nimmt die dritte Leitung und ist wieder oben.',
    map: [
      '..........................................',
      '..........................................',
      '..........................................',
      '..........................................',
      '....................######a#######........',
      '....................##############........',
      '..###############...##############........',
      '..###############...##############........',
      '..###############...##############........',
      '..###############...##############........',
      '..##T###########A...#############B........',
      '..###############...##############........',
      '..###############...##############........',
      '..###############...##############........',
      '..###############...##############........',
      '..###############...##############........',
      '....................##############........',
      '..........................................',
      '..........................................',
    ],
    ebeneZ: 4.2,
    ebenen: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '......................#############.......',
        '......................#############.......',
        '......................##########H#C.......',
        '......................#############.......',
        '......................#############.......',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '........................#############.....',
        '........................#b##########c.....',
        '........................#############.....',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
      ],
    ],
    obstacles: [
      { type: 'copperpipe', pair: 'A', angle: 90 },
      { type: 'copperpipe', pair: 'B', angle: 0, ziel: 2 },
      { type: 'luke', x: 30.5, y: 10.5, w: 1.6, h: 1.6, ebene: 2 },
      { type: 'copperpipe', pair: 'C', angle: 180, ebene: 1, ziel: 2 },
    ],
    decor: [
      { t: 'lantern', x: 5.5, y: 3.5, s: 1 },
      { t: 'lantern', x: 36.5, y: 2.5, s: 1 },
      { t: 'barrel', x: 18, y: 17.4, s: 1 },
      { t: 'crate', x: 22, y: 17.4, s: 1 },
      { t: 'gearFlat', x: 10, y: 17.4, s: 1.6 },
    ],
    autoDecor: { density: 0.12, seed: 417 },
  },
  {
    name: 'Das große Zifferblatt', par: 6, theme: 'escapement', maxStrokes: 26,
    intro: 'Die Schlussbahn. Unten läuft der Werkgang am Rand entlang, und vom Blatt trennt ihn die Leere – hinüber kommt nur, wer die Turbine nimmt und oben über den Steg fährt. Der Steg hat über dem Blatt kein Geländer: Dort lässt man sich fallen, und wo man sich fallen lässt, entscheidet alles. Denn auf dem Blatt bleibt das Loch nicht liegen – alle zehn Sekunden springt es eine Stundenmarke weiter, immer im Uhrzeigersinn, und der leuchtende Ring zeigt, wohin als Nächstes. Über die Marken streicht der große Zeiger und schiebt alles vor sich her. Darunter gehen die drei Zeiger des Werks – der blaue Stundenzeiger bremst, der grüne Minutenzeiger drückt weg, der rote Sekundenzeiger reißt mit sich herum. Dazu zwei Pendel über dem Blatt. Hier zählt nur eines: im richtigen Moment am richtigen Ort zu sein.',
    map: [
      '....................................',
      '....................................',
      '..########x#######################..',
      '..##T#############################..',
      '..########x#######################..',
      '....................................',
      '...............######...............',
      '.............##########.............',
      '............######H#####............',
      '...........##############...........',
      '..........################..........',
      '..........################..........',
      '.........##################.........',
      '.........##################.........',
      '.........##################.........',
      '.........##################.........',
      '.........##################.........',
      '.........##################.........',
      '..........################..........',
      '..........################..........',
      '...........##############...........',
      '............############............',
      '.............##########.............',
      '...............######...............',
      '....................................',
      '....................................',
    ],
    ebenen: [
      [
        '....................................',
        '....................................',
        '........................####........',
        '........................####........',
        '........................####........',
        '........................####........',
        '........................####........',
        '........................####........',
        '........................####........',
        '........................####........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '.........................oo.........',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
        '....................................',
      ],
    ],
    obstacles: [
      { type: 'pendulum', x: 10.5, y: 1, len: 2.5, amp: 60, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'turbine', x: 25.5, y: 3.5, w: 1.4, h: 1.4 },
      { type: 'wanderloch', x: 18, y: 15, r: 6.5, marken: 12 },
      { type: 'sweephand', x: 18, y: 15, r: 7.2, thick: 0.24, phase: 0 },
      { type: 'handclock', x: 18, y: 15, r: 8.4, phase: 0 },
      { type: 'pendulum', x: 14, y: 10, len: 5, amp: 30, ruhe: 90, phase: 0, w: 1.2, h: 1.2 },
      { type: 'pendulum', x: 22, y: 10, len: 5, amp: 30, ruhe: 90, phase: 0.5, w: 1.2, h: 1.2 },
    ],
    decor: [
      { t: 'clock', x: 18, y: 0.6, s: 2.6 },
      { t: 'bell', x: 4.5, y: 7.5, s: 1.3 },
      { t: 'bell', x: 31.5, y: 7.5, s: 1.3 },
      { t: 'lantern', x: 2.5, y: 21.5, s: 1 },
      { t: 'lantern', x: 33.5, y: 21.5, s: 1 },
    ],
    autoDecor: { density: 0.08, seed: 1200 },
  },
];
