/* Die Zwergenmine (Weltkennung 'mine'): zehn Bahnen, ein Abstieg unter den Berg.
   Erzeugt von tools/mine.py – dort steht auch, warum sie so aussehen, wie sie aussehen.

   DER ABSTIEG IST WÖRTLICH GEMEINT. Vier der zehn Bahnen haben zwei Sohlen: Man schlägt auf der
   oberen ab und kommt nach unten, indem man über eine Kante rollt und fällt. Das kostet keinen
   Strafschlag, und genau darum ist es hier das richtige Mittel – in jeder anderen Welt braucht ein
   Stockwerkwechsel eine Maschine, die trägt. Nach unten braucht man keine. Ein 'o' in der Karte
   ist so eine offene Kante; an einem gewöhnlichen Bodenrand stünde eine Bande.

   Der rote Faden bleibt die Dunkelheit. Jede andere Welt fragt, wie fest, wann oder wohin man
   schlägt; diese fragt, *was da vorn überhaupt liegt*. Ab Bahn 2 trägt jede Bahn einen Schleier
   ('dunkel'), der sich nur um den Ball und um die Grubenlampen öffnet. Die Lampen sind darum kein
   Schmuck, sondern das Wertvollste auf der Bahn – und jede dunkle Bahn ist so gebaut, dass der Weg
   mit ihnen allein lesbar bleibt (tools/mine.py prüft das, Sohle für Sohle).

   Die vier Abschnitte sind vier Paletten und zugleich der Weg nach unten:
     Bahn 1      'mundloch'  Tageslicht vor dem Berg
     Bahn 2-5    'stollen'   Grubenholz und Lampenschein
     Bahn 6-7    'kristall'  der Fels leuchtet selbst
     Bahn 8-10   'schmelze'  die unterste Sohle, wo das Erz flüssig wird

   Die Maschinen der Welt (src/obstacles_mine.js):
     'sprengladung'  wirft im Takt alles im Umkreis nach außen, je näher desto weiter; die
                     brennende Lunte sagt es vorher an. Keine Strafe – man kann sich tragen lassen.
     'bruchwand'     stehengebliebener Fels, den eine Zündung in der Nähe wegsprengt. Danach bleibt
                     der Gang offen – die einzige Maschine im Spiel, die die Bahn selbst ändert.
     'kippbuehne'    Bohle über dem Schacht, die zu der Seite kippt, auf der der Ball liegt:
                     über die Mitte hinaus wirft sie hinüber, davor schickt sie zurück.
     'grubenlampe'   leuchtet ein Stück Bahn aus.

   Sonst gilt dieselbe Kartenlegende wie in courses.js: 's' ist hier Geröll (bremst), 'x' ein
   Block (Grubenholz oder Fels), 'l' die Glut in den Spalten, '.' der offene Schacht. */
const MINE_COURSES = [
  {
    name: 'Mundloch', par: 3, theme: 'mundloch',
    intro: 'Vor dem Berg: Halde, Grubenholz, und hinten das Mundloch. Zwischen den Holzstapeln geht es hindurch – das Geröll bremst, wer zu weit ausholt. Ab hier wird es dunkel.',
    map: [
      '..............................',
      '..............................',
      '.############xx##############.',
      '.############xx##############.',
      '.#####sssss##xx##############.',
      '.#####sssss##xx##############.',
      '.#####sssss##################.',
      '.#T#######################H##.',
      '.############################.',
      '.################sssss#######.',
      '.############xx##sssss#######.',
      '.############xx##sssss#######.',
      '.############xx##############.',
      '..............................',
      '..............................',
    ],
    obstacles: [
      { type: 'bumper', x: 9.5, y: 9.5, r: 0.65, style: 'fass' },
      { type: 'bumper', x: 21.5, y: 4.5, r: 0.65, style: 'fass' },
      { type: 'grubenlampe', x: 25.5, y: 10.5, r: 3.0 },
    ],
  },
  {
    name: 'Erster Stollen', par: 3, theme: 'stollen', dunkel: 0.62, lampe: 3.0,
    intro: 'Unter Tage sieht man nur, was im Licht steht. Der Schleier öffnet sich um den Ball und um jede Grubenlampe – dazwischen muss man sich merken, was man beim Hinweg gesehen hat. Den Lampen nach, dann findet man auch das Loch.',
    map: [
      '................................',
      '..........###############.......',
      '..........###############.......',
      '..........###############.......',
      '..........###############.......',
      '.###############.....####.......',
      '.#T#############.....####.......',
      '.###############.....####.......',
      '.###############.....##########.',
      '.....................#######H##.',
      '.....................##########.',
      '.....................##########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'grubenlampe', x: 12.5, y: 6.5, r: 3.8 },
      { type: 'grubenlampe', x: 12.5, y: 2.5, r: 3.4 },
      { type: 'grubenlampe', x: 22.5, y: 2.5, r: 3.8 },
      { type: 'grubenlampe', x: 22.5, y: 9.5, r: 3.6 },
      { type: 'grubenlampe', x: 27.5, y: 9.5, r: 3.2 },
    ],
  },
  {
    name: 'Der Schacht', par: 3, theme: 'stollen', dunkel: 0.58, lampe: 3.0,
    intro: 'Ab hier geht es nach unten. Die Strecke bricht vorn einfach ab – über die Kante rollen und fallen lassen, das ist der Weg. Es kostet keinen Schlag; im Berg ist nach unten die bequemste Richtung. Unten liegt die Sohle mit dem Loch.',
    map: [
      '..............................',
      '..............................',
      '..............................',
      '..............................',
      '..............##############..',
      '..............##############..',
      '..............##############..',
      '..............##############..',
      '..............##########H###..',
      '..............##############..',
      '..............##############..',
      '..............##############..',
      '..............##############..',
      '..............................',
      '..............................',
      '..............................',
    ],
    ebenen: [
      [
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '..################oo..........',
        '..#T##############oo..........',
        '..################oo..........',
        '..################oo..........',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
      ],
    ],
    obstacles: [
      { type: 'grubenlampe', x: 6.5, y: 7.5, r: 3.8, ebene: 1 },
      { type: 'grubenlampe', x: 13.5, y: 7.5, r: 4.0, ebene: 1 },
      { type: 'grubenlampe', x: 18.5, y: 7.5, r: 3.4, ebene: 1 },
      { type: 'grubenlampe', x: 17.5, y: 8.0, r: 4.0 },
      { type: 'grubenlampe', x: 23.5, y: 8.0, r: 4.0 },
      { type: 'grubenlampe', x: 26.5, y: 5.0, r: 3.2 },
    ],
  },
  {
    name: 'Sprengfeld', par: 4, theme: 'stollen', maxStrokes: 14, dunkel: 0.6, lampe: 3.0,
    intro: 'Zwei Ladungen liegen mitten im Gang. Der rote Kreis ist ihre Reichweite, die brennende Lunte ihre Uhr: Wer im Kreis liegt, wenn sie durchgebrannt ist, fliegt nach außen – umso weiter, je näher er lag. Das ist keine Strafe. Wer sich richtig hinlegt, lässt sich tragen. Rechts und links steht allerdings nichts mehr.',
    map: [
      '..................................',
      '..................................',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '.################################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.################################.',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '........#####.......#####.........',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'sprengladung', x: 10.0, y: 8.0, phase: 0.0, weite: 3.4 },
      { type: 'sprengladung', x: 22.0, y: 8.0, phase: 0.45, weite: 3.4 },
      { type: 'grubenlampe', x: 5.5, y: 8.5, r: 3.4 },
      { type: 'grubenlampe', x: 10.0, y: 8.0, r: 4.4 },
      { type: 'grubenlampe', x: 16.0, y: 8.5, r: 3.6 },
      { type: 'grubenlampe', x: 22.0, y: 8.0, r: 4.4 },
      { type: 'grubenlampe', x: 28.5, y: 8.5, r: 3.4 },
    ],
  },
  {
    name: 'Die Bruchwand', par: 4, theme: 'stollen', maxStrokes: 14, dunkel: 0.58, lampe: 3.0,
    intro: 'Vorn steht der Berg. Der Pfeiler mit dem Bohrloch und dem Kreidekreuz ist stehengebliebener Fels – dagegen hilft kein Schlag. Daneben liegt eine Ladung, und wenn die zündet, ist der Pfeiler weg. Für den Rest der Bahn. Hier muss man nicht treffen, sondern abwarten.',
    map: [
      '..................................',
      '..................................',
      '............#####.................',
      '............#####.................',
      '............#####.................',
      '.################################.',
      '.################################.',
      '.##T##########################H##.',
      '.################################.',
      '.################################.',
      '............#####.................',
      '............#####.................',
      '............#####.................',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'bruchwand', x: 17.0, y: 7.0, w: 1.6, h: 5.0 },
      { type: 'sprengladung', x: 14.0, y: 11.0, phase: 0.0, weite: 3.0 },
      { type: 'bumper', x: 8.0, y: 7.0, r: 0.6, style: 'fass' },
      { type: 'grubenlampe', x: 6.0, y: 7.5, r: 3.6 },
      { type: 'grubenlampe', x: 13.5, y: 7.5, r: 4.2 },
      { type: 'grubenlampe', x: 14.0, y: 11.0, r: 3.4 },
      { type: 'grubenlampe', x: 21.0, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 28.0, y: 7.5, r: 3.6 },
    ],
  },
  {
    name: 'Kippbohle', par: 3, theme: 'stollen', dunkel: 0.6, lampe: 3.0,
    intro: 'Über den Schacht führt eine Bohle, die auf einer Achse ruht. Sie kippt zu der Seite, auf der der Ball liegt: Wer über die Mitte kommt, wird hinübergeworfen – wer davor liegenbleibt, rutscht zurück. Also nicht zaghaft.',
    map: [
      '................................',
      '................................',
      '..#######..............########.',
      '..#######..............########.',
      '..#######..............########.',
      '.##########.........###########.',
      '.##############################.',
      '.###T######################H###.',
      '.##############################.',
      '.##########.........###########.',
      '..#######..............########.',
      '..#######..............########.',
      '..#######..............########.',
      '................................',
      '................................',
    ],
    obstacles: [
      { type: 'kippbuehne', x: 11.0, y: 6.0, w: 8.0, h: 2.0, angle: 0 },
      { type: 'grubenlampe', x: 6.0, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 11.0, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 15.0, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 19.0, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 26.0, y: 7.5, r: 4.0 },
    ],
  },
  {
    name: 'Lorensohle', par: 4, theme: 'stollen', maxStrokes: 14, dunkel: 0.62, lampe: 3.0,
    intro: 'Auf dieser Strecke fahren die Hunte. Zwei Loren queren sie im eigenen Takt – man wartet sie ab oder schlägt zwischen ihnen hindurch. Ganz vorn bricht die Strecke ab, und darunter liegt die Sohle mit dem Loch.',
    map: [
      '....................................',
      '....................................',
      '....................................',
      '....................###############.',
      '....................###############.',
      '....................###############.',
      '....................####ssssss#####.',
      '....................####ssssss#####.',
      '....................####ssssss##H##.',
      '....................####ssssss#####.',
      '....................####ssssss#####.',
      '....................###############.',
      '....................###############.',
      '....................###############.',
      '....................................',
      '....................................',
    ],
    ebenen: [
      [
        '....................................',
        '....................................',
        '...........###.....###..............',
        '...........###.....###..............',
        '...........###.....###..............',
        '..#######################oo.........',
        '..#######################oo.........',
        '..##T####################oo.........',
        '..#######################oo.........',
        '..#######################oo.........',
        '..#######################oo.........',
        '...........###.....###..............',
        '...........###.....###..............',
        '...........###.....###..............',
        '....................................',
        '....................................',
      ],
    ],
    obstacles: [
      { type: 'rail', x0: 12.0, y0: 2.4, x1: 12.0, y1: 13.6, ebene: 1 },
      { type: 'mover', style: 'cart', x0: 12.0, y0: 3.0, x1: 12.0, y1: 13.0, period: 4.2, r: 0.62, ebene: 1 },
      { type: 'rail', x0: 20.0, y0: 2.4, x1: 20.0, y1: 13.6, ebene: 1 },
      { type: 'mover', style: 'cart', x0: 20.0, y0: 13.0, x1: 20.0, y1: 3.0, period: 3.4, r: 0.62, ebene: 1 },
      { type: 'grubenlampe', x: 7.0, y: 7.5, r: 3.8, ebene: 1 },
      { type: 'grubenlampe', x: 12.0, y: 7.5, r: 4.2, ebene: 1 },
      { type: 'grubenlampe', x: 16.0, y: 7.5, r: 3.8, ebene: 1 },
      { type: 'grubenlampe', x: 20.0, y: 7.5, r: 4.2, ebene: 1 },
      { type: 'grubenlampe', x: 25.0, y: 7.5, r: 3.6, ebene: 1 },
      { type: 'grubenlampe', x: 24.0, y: 8.0, r: 4.2 },
      { type: 'grubenlampe', x: 31.0, y: 8.0, r: 4.0 },
      { type: 'grubenlampe', x: 30.0, y: 4.5, r: 3.4 },
    ],
  },
  {
    name: 'Kristallkammer', par: 4, theme: 'kristall', maxStrokes: 14, dunkel: 0.5, lampe: 3.0,
    intro: 'Die Kammer ist ausgesprengt, nicht gemauert. Oben auf der Galerie sitzt ein Magnetit, der den Ball von sich wegdrückt, und die Kristalle werfen ihn zurück – wer geradeaus zielt, kommt nie an. Unten versperrt ein Felspfeiler den Weg in die große Kammer; die Ladung daneben macht ihn auf.',
    map: [
      '..................................',
      '..................................',
      '......................#...........',
      '.................###########......',
      '................#############.....',
      '..............#################...',
      '.............###################..',
      '............####################..',
      '............####################..',
      '............################H####.',
      '............####################..',
      '............####################..',
      '.............###################..',
      '..............#################...',
      '................#############.....',
      '.................###########......',
      '......................#...........',
      '..................................',
    ],
    ebenen: [
      [
        '..................................',
        '..................................',
        '..................................',
        '..................................',
        '..................................',
        '......#######.....................',
        '....###########...................',
        '..############oo..................',
        '..############oo..................',
        '..##T#########oo#.................',
        '..############oo..................',
        '..############oo..................',
        '....###########...................',
        '......#######.....................',
        '..................................',
        '..................................',
        '..................................',
        '..................................',
      ],
    ],
    obstacles: [
      { type: 'magnet', x: 9.0, y: 9.0, r: 3.2, core: 0.4, push: true, ebene: 1 },
      { type: 'bumper', x: 6.0, y: 6.0, r: 0.7, style: 'crystal', ebene: 1 },
      { type: 'bumper', x: 6.0, y: 12.0, r: 0.7, style: 'crystal', ebene: 1 },
      { type: 'bruchwand', x: 19.0, y: 9.0, w: 1.6, h: 4.4 },
      { type: 'sprengladung', x: 16.5, y: 12.0, phase: 0.2, weite: 3.0 },
      { type: 'bumper', x: 25.0, y: 5.5, r: 0.8, style: 'crystal' },
      { type: 'bumper', x: 25.0, y: 12.5, r: 0.8, style: 'crystal' },
      { type: 'grubenlampe', x: 6.0, y: 9.5, r: 4.0, ebene: 1 },
      { type: 'grubenlampe', x: 11.0, y: 9.5, r: 4.2, ebene: 1 },
      { type: 'grubenlampe', x: 14.5, y: 9.5, r: 3.4, ebene: 1 },
      { type: 'grubenlampe', x: 15.0, y: 9.5, r: 4.2 },
      { type: 'grubenlampe', x: 16.5, y: 12.0, r: 3.4 },
      { type: 'grubenlampe', x: 22.0, y: 9.5, r: 4.4 },
      { type: 'grubenlampe', x: 27.0, y: 9.5, r: 4.0 },
    ],
  },
  {
    name: 'Sohle Neun', par: 5, theme: 'schmelze', maxStrokes: 16, dunkel: 0.48, lampe: 3.0,
    intro: 'Die unterste Sohle: In den Spalten steht die Glut. Über den ersten Spalt führt ein schmaler Steg, über den zweiten eine Bohle – und die Ladung dazwischen kann beides sein, Gefahr oder Abkürzung.',
    map: [
      '....................................',
      '....................................',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####################H##.',
      '............#######################.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '............####lllll#####llll#####.',
      '....................................',
      '....................................',
    ],
    ebenen: [
      [
        '....................................',
        '....................................',
        '....................................',
        '........#####.......................',
        '........#####.......................',
        '........#####.......................',
        '..###########oo.....................',
        '..###########oo.....................',
        '..##T########oo.....................',
        '..###########oo.....................',
        '..###########oo.....................',
        '........#####.......................',
        '........#####.......................',
        '........#####.......................',
        '....................................',
        '....................................',
      ],
    ],
    obstacles: [
      { type: 'kippbuehne', x: 26.0, y: 7.0, w: 4.0, h: 2.0, angle: 0 },
      { type: 'sprengladung', x: 22.5, y: 11.0, phase: 0.3, weite: 3.2 },
      { type: 'grubenlampe', x: 6.0, y: 8.5, r: 3.8, ebene: 1 },
      { type: 'grubenlampe', x: 11.0, y: 8.5, r: 4.2, ebene: 1 },
      { type: 'grubenlampe', x: 13.5, y: 8.5, r: 3.4, ebene: 1 },
      { type: 'grubenlampe', x: 14.5, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 18.0, y: 7.5, r: 3.6 },
      { type: 'grubenlampe', x: 23.0, y: 7.5, r: 4.2 },
      { type: 'grubenlampe', x: 27.5, y: 7.5, r: 3.6 },
      { type: 'grubenlampe', x: 32.0, y: 7.5, r: 3.8 },
    ],
  },
  {
    name: 'Die Gießhalle', par: 4, theme: 'schmelze', maxStrokes: 16, dunkel: 0.45, lampe: 3.0,
    intro: 'Quer durch die Halle steht die Glut, und hinüber führt nichts. Am Rand hängt der Gießlöffel: Jedes Mal, wenn er kippt, läuft das Erz ein Feld weiter und erstarrt – so baut sich die Brücke selbst. Nur läuft jeder neue Guss über das schon Erstarrte hinweg. Warten, bis es kalt ist, und dann hinüber.',
    map: [
      '..................................',
      '..................................',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.##T##########lllll###########H##.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '.#############lllll##############.',
      '..................................',
      '..................................',
    ],
    obstacles: [
      { type: 'giessloeffel', x: 13.0, y: 7.5, takt: 2.2, glut: 0.9, kipp: 0.7, phase: 0.0, rinne: {'x': 14, 'y': 7, 'len': 5, 'dx': 1, 'dy': 0} },
      { type: 'bumper', x: 8.0, y: 4.0, r: 0.7, style: 'fass' },
      { type: 'bumper', x: 8.0, y: 11.0, r: 0.7, style: 'fass' },
      { type: 'bumper', x: 25.0, y: 4.0, r: 0.7, style: 'fass' },
      { type: 'bumper', x: 25.0, y: 11.0, r: 0.7, style: 'fass' },
      { type: 'grubenlampe', x: 4.0, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 9.5, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 13.0, y: 7.5, r: 4.4 },
      { type: 'grubenlampe', x: 20.5, y: 7.5, r: 4.2 },
      { type: 'grubenlampe', x: 26.0, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 30.5, y: 7.5, r: 3.8 },
    ],
  },
  {
    name: 'Die zerbrochene Brücke', par: 4, theme: 'schmelze', maxStrokes: 16, dunkel: 0.45, lampe: 3.0,
    intro: 'Über den See führte einmal eine Brücke; in der Mitte fehlt ein Stück. Genau dort steht eine Spalte, aus der im Takt die Lava hochschiesst – und die erwischt den Ball auch in der Luft. Die Rampe bringt hinüber, aber nur, wenn der Strahl gerade unten ist. Warten hilft nicht: Die Ruhe dauert eine Sekunde.',
    map: [
      '....................................',
      '....................................',
      '.llllllllllllllllllllllllllllllllll.',
      '.llllllllllllllllllllllllllllllllll.',
      '.llllllllllllllllllllllllll#######l.',
      '.#########lllllllllllllllll#######l.',
      '.################lll##############l.',
      '.###T############lll###########H##l.',
      '.################lll##############l.',
      '.#########lllllllllllllllll#######l.',
      '.llllllllllllllllllllllllll#######l.',
      '.llllllllllllllllllllllllllllllllll.',
      '.llllllllllllllllllllllllllllllllll.',
      '....................................',
      '....................................',
    ],
    obstacles: [
      { type: 'lavafontaene', x: 18.0, y: 7.5, r: 1.1, takt: 2.1, droht: 0.5, oben: 0.55, phase: 0.0, hoehe: 4.2 },
      { type: 'ramp', x: 13.0, y: 6.0, w: 2.0, h: 3.0, angle: 0, minSpeed: 2.5, speed: 5.0, land: 5.2 },
      { type: 'lavafontaene', x: 11.5, y: 7.5, r: 0.7, takt: 2.1, droht: 0.5, oben: 0.55, phase: 0.33, hoehe: 3.4 },
      { type: 'lavafontaene', x: 24.0, y: 7.5, r: 0.7, takt: 2.1, droht: 0.5, oben: 0.55, phase: 0.66, hoehe: 3.4 },
      { type: 'bumper', x: 5.5, y: 5.5, r: 0.6, style: 'fass' },
      { type: 'bumper', x: 5.5, y: 8.5, r: 0.6, style: 'fass' },
      { type: 'grubenlampe', x: 4.0, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 10.0, y: 7.5, r: 3.6 },
      { type: 'grubenlampe', x: 14.5, y: 7.5, r: 4.0 },
      { type: 'grubenlampe', x: 21.5, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 26.5, y: 7.5, r: 3.8 },
      { type: 'grubenlampe', x: 31.0, y: 7.5, r: 4.0 },
    ],
  },
  {
    name: 'Die Schmelze', par: 5, theme: 'schmelze', maxStrokes: 18, dunkel: 0.45, lampe: 3.0,
    intro: 'Ganz unten steht das Erz flüssig. Mitten im See liegt die Insel mit dem Loch, und nur ein schmaler Damm führt hinüber – am Anfang zugemauert, in der Mitte bewacht von einer Ladung, die im Takt alles hinunterfegt. Wer den Augenblick nach dem Knall erwischt, hat freie Bahn.',
    map: [
      '......................................',
      '......................................',
      '.##################l#################.',
      '.############lllllllllllll###########.',
      '.##########lllllllllllllllll#########.',
      '.########lllllllllllllllllll#########.',
      '.#######lllllllllllllllllll##########.',
      '.####################################.',
      '.##T###l#######################H#####.',
      '.####################################.',
      '.#######lllllllllllllllllll##########.',
      '.########lllllllllllllllllll#########.',
      '.##########lllllllllllllllll#########.',
      '.############lllllllllllll###########.',
      '.##################l#################.',
      '.####################################.',
      '......................................',
      '......................................',
    ],
    obstacles: [
      { type: 'bruchwand', x: 13.0, y: 8.5, w: 1.4, h: 3.0 },
      { type: 'sprengladung', x: 10.5, y: 8.5, phase: 0.0, weite: 3.2 },
      { type: 'windmill', x: 18.0, y: 8.5, w: 3.0, gap: 0.95, speed: 1.0, blades: 4, axis: 'y', phase: 0.0, style: 'ofen', len: 1.1, height: 1.8, depth: 1.3 },
      { type: 'sprengladung', x: 23.0, y: 8.5, phase: 0.5, weite: 3.4 },
      { type: 'bumper', x: 5.0, y: 5.0, r: 0.7, style: 'fass' },
      { type: 'bumper', x: 5.0, y: 11.0, r: 0.7, style: 'fass' },
      { type: 'grubenlampe', x: 4.5, y: 8.5, r: 3.8 },
      { type: 'grubenlampe', x: 10.5, y: 8.5, r: 4.2 },
      { type: 'grubenlampe', x: 16.0, y: 8.5, r: 4.0 },
      { type: 'grubenlampe', x: 23.0, y: 8.5, r: 4.4 },
      { type: 'grubenlampe', x: 29.5, y: 8.5, r: 4.2 },
    ],
  },
];
