/* Die Flut (Weltkennung 'flut'): die versunkene Stadt.
   Erzeugt von tools/flut.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

   NOCH NICHT FERTIG. Zurzeit stehen hier zwei Probebahnen, an denen die Maschinen angesehen und
   gespielt werden können, bevor neun Bahnen darauf gebaut werden. Die Welt trägt darum in
   src/courses_pro.js die Kennzeichnung 'nurVorschau'; im Spiel taucht sie nicht auf.

   DAS FLUTBECKEN ist ein Hindernis wie das Wandertor oder die Falltür: Es läuft im Takt von außen
   nach innen voll und wieder leer, und solange es leer ist, geht der Weg hindurch. Ringsum bleibt
   die Bahn trocken und immer spielbar – **es gibt auf jeder Bahn einen Weg, der auch bei vollem
   Becken zum Loch führt** (tools/flut.py prüft das). Das Becken ist die Abkürzung, nicht die
   einzige Möglichkeit; warten muß man nie.

   Zuerst war die Flut eine Weltregel und stieg über die ganze Bahn. Das war gut gedacht und
   schlecht zu spielen: Wer den Augenblick verpaßte, konnte nur zusehen. Siehe src/obstacles_flut.js.

   Kartenlegende wie in courses.js: '#' Boden, '.' offenes Wasser, 'x' Block, 's' Schlick (bremst),
   'T' Abschlag, 'H' Loch. */
const FLUT_COURSES = [
  {
    name: 'Das Hafenbecken', par: 3, theme: 'wasserlinie',
    intro: 'Dicht unter der Oberfläche. Der Steg führt geradeaus durch das Becken – steht es leer, ist es kurz; steht es voll, geht es oben herum. Neben dem Steg ist nichts.',
    map: [
      '................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww############wwwwwwwww.',
      '.wwwwwwww##############wwwwwwww.',
      '.wwwwwwww##############wwwwwwww.',
      '.wwwwwwww###wwwwwwww###wwwwwwww.',
      '.wwwwwwww###wwwwwwww###wwwwwwww.',
      '.ww##########ssssss##########ww.',
      '.ww#T########ssssss########H#ww.',
      '.ww##########ssssss##########ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '................................',
    ],
    obstacles: [
      { type: 'flut', x: 16.0, y: 9.5, w: 6, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Der Priel', par: 3, theme: 'wasserlinie',
    intro: 'Ein Priel zieht quer über den Steg, und neben dem Steg ist nichts. Wer darin liegenbleibt, wird heruntergespült und zahlt dafür. Aber er ist eine Dünung – er schwillt an und wieder ab, und der Augenblick dazwischen ist der, in dem man spielt.',
    map: [
      '..................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww############################ww.',
      '.ww#T########################H#ww.',
      '.ww############################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 15.5, y: 8.0, w: 3, h: 12, angle: 90, tempo: 5.0, puls: 1.25, phase: 0.0 },
      { type: 'bumper', x: 10.5, y: 7.5, r: 0.65, style: 'fass' },
      { type: 'bumper', x: 20.5, y: 7.5, r: 0.65, style: 'fass' },
    ],
  },
  {
    name: 'Die Mole', par: 4, theme: 'wasserlinie',
    intro: 'Unten schiebt die Strömung nach rechts – wer sie mitnimmt, ist schnell am Aufgang. Der Aufgang ist ein Becken. Ist es voll, bleibt nur der lange Weg ganz links zurück.',
    map: [
      '..................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwww########################w.',
      '.wwwwwww###################H#####.',
      '.wwwwwww#########################.',
      '.wwwwwwwwwwwwwwwwwwww###wwwwww###.',
      '.wwwwwwwwwwwwwwwwwwww###wwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.wwwwwwwwwwwwwwwwwwwwssswwwwww###.',
      '.ww##############################.',
      '.ww#T############################.',
      '.ww#############################w.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 15.5, y: 15.5, w: 11, h: 3, angle: 0, tempo: 7.0 },
      { type: 'flut', x: 22.5, y: 11.0, w: 3, h: 6, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Sandbank', par: 4, theme: 'flachwasser',
    intro: 'Zwei Becken hintereinander auf einem Steg. Der Umweg unten herum ist lang – aber auf ihm liegt das Pumpwerk, und das hält beide Becken vier Sekunden lang leer.',
    map: [
      '....................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########ssssss####ssssss######ww.',
      '.ww#T######ssssss####ssssss####H#ww.',
      '.ww########ssssss####ssssss######ww.',
      '.wwwwww###wwwwwwwwwwwwwwwww###wwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwww###wwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwww###wwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwww###wwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwww###wwwww.',
      '.wwwwww#######################wwwww.',
      '.wwwwww#######################wwwww.',
      '.wwwwwww#####################wwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '....................................',
    ],
    obstacles: [
      { type: 'flut', x: 14.0, y: 8.5, w: 6, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'flut', x: 24.0, y: 8.5, w: 6, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'pumpwerk', x: 18.5, y: 16.5, r: 0.8, dauer: 4 },
    ],
  },
  {
    name: 'Der Seegraswald', par: 3, theme: 'flachwasser',
    intro: 'Zwischen den Halmen liegt eine Kammer, und darin dreht sich das Wasser. Der Strudel hält niemanden fest – er wirft nur woandershin, als man wollte, und der Ausgang ist schmal.',
    map: [
      '..................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.ww############################ww.',
      '.ww#T########################H#ww.',
      '.ww############################ww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwww#########wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..................................',
    ],
    obstacles: [
      { type: 'strudel', x: 17.0, y: 9.5, r: 3.6, dreh: 1 },
      { type: 'angler', x0: 22.5, y0: 9.5, x1: 29.5, y1: 9.5, tempo: 2.0 },
    ],
  },
  {
    name: 'Die Rinne', par: 4, theme: 'flachwasser',
    intro: 'Die Rinne trägt weit – man muß sie nur treffen und darf nicht zu früh liegenbleiben. Am Ende liegt ein Becken quer vor dem Loch; drumherum geht es unten lang.',
    map: [
      '......................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########################ssss####ww.',
      '.ww#T######################ssss##H#ww.',
      '.ww########################ssss####ww.',
      '.wwwwwwwwwwwwwwwwwwwwww###wwwwww###ww.',
      '.wwwwwwwwwwwwwwwwwwwwww###wwwwww###ww.',
      '.wwwwwwwwwwwwwwwwwwwwww###wwwwww###ww.',
      '.wwwwwwwwwwwwwwwwwwwwww###wwwwww###ww.',
      '.wwwwwwwwwwwwwwwwwwwwww###wwwwww###ww.',
      '.wwwwwwwwwwwwwwwwwwwwww############ww.',
      '.wwwwwwwwwwwwwwwwwwwwww############ww.',
      '.wwwwwwwwwwwwwwwwwwwwwww##########www.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '......................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 15.5, y: 7.5, w: 15, h: 3, angle: 0, tempo: 7.5 },
      { type: 'flut', x: 29.0, y: 7.5, w: 4, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Gassen', par: 4, theme: 'daemmerzone',
    intro: 'Das Haus in der Mitte versperrt den geraden Weg. Links und rechts daran vorbei laufen zwei Gassen, und beide saufen im Takt voll – versetzt, damit immer eine offen ist.',
    map: [
      '..................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwww###sssssss###wwwwwwwww.',
      '.wwwwwwwww####sssssss####wwwwwwww.',
      '.wwwwwwwww####sssssss####wwwwwwww.',
      '.wwwwwwwww###wwwwwwwww###wwwwwwww.',
      '.ww##########wwwwwwwww#########ww.',
      '.ww#T########wwwwwwwww#######H#ww.',
      '.ww##########wwwwwwwww#########ww.',
      '.wwwww###w###wwwwwwwww###w###wwww.',
      '.wwwww###w####sssssss####w###wwww.',
      '.wwwww###w####sssssss####w###wwww.',
      '.wwwww###ww###sssssss###ww###wwww.',
      '.wwwww###wwwwwwwwwwwwwwwww###wwww.',
      '.wwwww#######################wwww.',
      '.wwwww#######################wwww.',
      '.wwwwww#####################wwwww.',
      '..................................',
    ],
    obstacles: [
      { type: 'flut', x: 17.5, y: 6.5, w: 7, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'flut', x: 17.5, y: 14.5, w: 7, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Der Marktplatz', par: 4, theme: 'daemmerzone',
    intro: 'Über dem alten Brunnen dreht sich das Wasser, und in den Platz hinein und heraus führt je ein Becken. Wer beide im richtigen Augenblick nimmt, wird trotzdem noch versetzt.',
    map: [
      '......................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwww#############wwwwwwwwwww.',
      '.wwwwwwwwwwww#############wwwwwwwwwww.',
      '.wwwwwwwwwwww#############wwwwwwwwwww.',
      '.wwwwwwwwwwww#############wwwwwwwwwww.',
      '.ww##########ssss#####ssss#########ww.',
      '.ww#T########ssss#####ssss#######H#ww.',
      '.ww##########ssss#####ssss#########ww.',
      '.wwwwwww###ww#############ww###wwwwww.',
      '.wwwwwww###ww#############ww###wwwwww.',
      '.wwwwwww###ww#############ww###wwwwww.',
      '.wwwwwww###ww#############ww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww#######################wwwwww.',
      '.wwwwwww#######################wwwwww.',
      '.wwwwwwww#####################wwwwwww.',
      '......................................',
    ],
    obstacles: [
      { type: 'flut', x: 15.0, y: 10.5, w: 4, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'strudel', x: 19.0, y: 10.5, r: 3.6, dreh: -1 },
      { type: 'flut', x: 24.0, y: 10.5, w: 4, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Kaimauer', par: 4, theme: 'daemmerzone',
    intro: 'Unter der Kaimauer geht es hin, oben wieder zurück. Der kurze Aufgang ist ein Becken; oben zieht es dann kräftig aufs Loch zu – zu kräftig, um dort stehenzubleiben. Das Pumpwerk liegt am Anfang des langen Wegs.',
    map: [
      '........................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww############################w.',
      '.wwwwwwwww#######################H#####.',
      '.wwwwwwwww#############################.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwwwssswwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwwwssswwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwwwssswwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwwwssswwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwwwssswwwwwwwwwwwwww###.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwww###.',
      '.ww####################################.',
      '.ww#T##################################.',
      '.ww###################################w.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '........................................',
    ],
    obstacles: [
      { type: 'flut', x: 20.5, y: 11.5, w: 3, h: 5, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'stroemung', x: 27.0, y: 5.5, w: 10, h: 3, angle: 0, tempo: 7.5 },
      { type: 'pumpwerk', x: 10.5, y: 16.5, r: 0.8, dauer: 4 },
    ],
  },
  {
    name: 'Der Grund', par: 3, theme: 'meeresgrund',
    intro: 'Ganz unten. Von oben kommt kein Licht mehr – was leuchtet, leuchtet selbst. Quer über den Steg liegt ein langes Becken; der Umweg unten herum ist weit, und auf ihm schwimmt ein Anglerfisch. Seine Laterne ist hier das hellste Licht: Man sieht ihn kommen, bevor man ihn sieht.',
    map: [
      '......................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww##########ssssssssssss##########ww.',
      '.ww#T########ssssssssssss########H#ww.',
      '.ww##########ssssssssssss##########ww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww###wwwwwwwwwwwwwwwww###wwwwww.',
      '.wwwwwww#######################wwwwww.',
      '.wwwwwww#######################wwwwww.',
      '.wwwwwwww#####################wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '......................................',
    ],
    obstacles: [
      { type: 'flut', x: 19.0, y: 8.5, w: 12, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'pumpwerk', x: 19.5, y: 17.5, r: 0.8, dauer: 4 },
      { type: 'angler', x0: 12.5, y0: 17.5, x1: 27.5, y1: 17.5, tempo: 2.4 },
    ],
  },
  {
    name: 'Das Kaltwasserfeld', par: 5, theme: 'meeresgrund',
    intro: 'Zwei Stege, auf beiden zieht es – oben nach rechts, unten nach links, und beide als Dünung. Verbunden sind sie nur in der Mitte, und mitten in der Verbindung dreht sich das Wasser. Stehenbleiben geht nirgends.',
    map: [
      '........................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww##################################ww.',
      '.ww################################H#ww.',
      '.ww##################################ww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwww.',
      '.ww##################################ww.',
      '.ww#T################################ww.',
      '.ww##################################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '........................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 13.5, y: 6.5, w: 9, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 0.0 },
      { type: 'stroemung', x: 28.5, y: 6.5, w: 9, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 1.6 },
      { type: 'stroemung', x: 13.5, y: 15.5, w: 9, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 3.14 },
      { type: 'stroemung', x: 28.5, y: 15.5, w: 9, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 4.7 },
      { type: 'strudel', x: 20.5, y: 10.5, r: 2.6, dreh: 1 },
    ],
  },
  {
    name: 'Der Schlund', par: 5, theme: 'meeresgrund',
    intro: 'Das Ende. Zwei Äste, in jedem ein Becken, und beide münden in eine Kammer, in der es zieht und sich alles dreht. Wer dort liegenbleibt, bleibt nicht liegen.',
    map: [
      '..........................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww###sssss###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwww####sssss####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwww####sssss####wwwwwwwwwwwwwwwwwww.',
      '.wwwwwwww###wwwwwww############wwwwwwwwww.',
      '.wwwwwwww###wwwwwwww###########wwwwwwwwww.',
      '.wwwwwwww###wwwwwwww###########wwwwwwwwww.',
      '.ww#########wwwwwwww###################ww.',
      '.ww#T#######wwwwwwww#################H#ww.',
      '.ww#########wwwwwwww###################ww.',
      '.wwwwwwww###wwwwwwww############wwwwwwwww.',
      '.wwwwwwww###wwwwwwww############wwwwwwwww.',
      '.wwwwwwww###wwwwwww#############wwwwwwwww.',
      '.wwwwwwww####sssss####wwwwwww###wwwwwwwww.',
      '.wwwwwwww####sssss####wwwwwww###wwwwwwwww.',
      '.wwwwwwww####sssss###wwwwwwww###wwwwwwwww.',
      '.wwwwwwww#######################wwwwwwwww.',
      '.wwwwwwww#######################wwwwwwwww.',
      '.wwwwwwwww#####################wwwwwwwwww.',
      '..........................................',
    ],
    obstacles: [
      { type: 'flut', x: 15.5, y: 5.5, w: 5, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'flut', x: 15.5, y: 17.5, w: 5, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'stroemung', x: 25.5, y: 11.5, w: 11, h: 9, angle: 0, tempo: 6.0, puls: 1.15, phase: 0.0 },
      { type: 'strudel', x: 25.0, y: 11.5, r: 3.2, dreh: -1 },
      { type: 'angler', x0: 21.5, y0: 8.5, x1: 29.5, y1: 14.5, tempo: 2.2 },
      { type: 'pumpwerk', x: 6.5, y: 11.5, r: 0.8, dauer: 4 },
    ],
  },
];
