/* Dschungeltempel: zweite Profi-Welt – neun Bahnen durch den Urwald bis zur verlorenen Stadt.
   Neue Hindernisse: Stachelfallen, Krokodil, Lianen, Kokosnüsse, Steingötzen, Tempeltor mit Tempelhalle.
   Gleiche Kartenlegende wie in courses.js. */
const JUNGLE_COURSES = [
  {
    name: 'Urwaldpfad', par: 4, theme: 'jungle', maxStrokes: 15, friction: { s: 26 }, hazardText: { water: 'Platsch! In den Fluss' },
    intro: 'Ein schmaler Pfad durch den Urwald. Eine Liane pendelt über den Weg, im Treibsand bleibt der Ball fast stehen, und ein Steingötze wacht vor dem Loch.',
    map: [
      '......................',
      '..T#####..............',
      '..######..............',
      '.....####.............',
      '.....####.............',
      '.....#######..........',
      '.....###ss######......',
      '.......#########......',
      '.......#####...###....',
      '.......#####...#H#....',
      '......................',
    ],
    obstacles: [
      { type: 'rotor', x: 6.5, y: 3.4, blades: 1, len: 1.25, thick: 0.16, hubR: 0.1, style: 'vine', e: 0.6, swing: { amp: Math.PI / 2.6, speed: 1.6 }, phase: Math.PI / 2, height: 0.5 },
      { type: 'bumper', x: 12.6, y: 6.5, r: 0.38, style: 'idol' },
      { type: 'wall', x0: 14.8, y0: 8, x1: 16, y1: 9.2, extend: 0 },
    ],
    decor: [
      { t: 'jungleTree', x: 1.0, y: 0.6, s: 1.5, seed: 0.7 }, { t: 'jungleTree', x: 12.5, y: 3.5, s: 1.6, seed: 0.3 }, { t: 'jungleTree', x: 19.5, y: 6.5, s: 1.4, seed: 0.8 }, { t: 'fern', x: 3.5, y: 4.4, s: 1.3, seed: 0.2 },
      { t: 'fern', x: 10.5, y: 3.6, s: 1.2, seed: 0.6 }, { t: 'fern', x: 13.5, y: 10.4, s: 1.4, seed: 0.9 }, { t: 'idol', x: 18.5, y: 9.5, s: 1.3 }, { t: 'totem', x: 1.2, y: 6.5, s: 1.2, seed: 0.4 },
      { t: 'rock', x: 4.5, y: 8.5, s: 1.3 }, { t: 'flowerbush', x: 9.5, y: 1.5 }, { t: 'flowerbush', x: 16.5, y: 5.4 }, { t: 'monkey', x: 12.3, y: 3.3, s: 1.1, seed: 0.5 },
    ],
    autoDecor: { density: 0.4, seed: 301 },
  },
  {
    name: 'Affenbrücke', par: 5, theme: 'jungle', maxStrokes: 18, hazardText: { water: 'Platsch! In den Fluss' },
    views: [{ x: 2, y: 1, w: 6, h: 6, look: { x: 20, y: 4.5 } }],
    intro: 'Eine Hängebrücke ohne Geländer führt über den Fluss. Drüben werfen zwei Affen Kokosnüsse quer über den Platz – wer sich anrempeln lässt, landet im Wasser.',
    map: [
      '..........................',
      '..######wwwwwwwwww........',
      '..######wwwwwwwwww######..',
      '..#T####wwwwwwwwww######..',
      '..######oooooooooo######..',
      '..######wwwwwwwwww######..',
      '..######wwwwwwwwww###H##..',
      '........wwwwwwwwww######..',
      '..........................',
    ],
    obstacles: [
      { type: 'mover', x0: 18.6, y0: 3.5, x1: 23.4, y1: 3.5, w: 0.5, h: 0.5, period: 4, style: 'coconut', e: 0.7 },
      { type: 'mover', x0: 23.4, y0: 5.4, x1: 18.6, y1: 5.4, w: 0.5, h: 0.5, period: 5, phase: 0.4, style: 'coconut', e: 0.7 },
      { type: 'wall', x0: 2, y0: 5.2, x1: 3.2, y1: 6.4, extend: 0 },
    ],
    decor: [
      { t: 'ropepost', x: 7.85, y: 3.55, s: 1.1 }, { t: 'ropepost', x: 7.85, y: 5.45, s: 1.1 }, { t: 'ropepost', x: 18.15, y: 3.55, s: 1.1 }, { t: 'ropepost', x: 18.15, y: 5.45, s: 1.1 },
      { t: 'jungleTree', x: 19.4, y: 0.9, s: 1.5, seed: 0.5 }, { t: 'monkey', x: 19.2, y: 0.9, s: 1.2, seed: 0.2 }, { t: 'jungleTree', x: 24.6, y: 1.4, s: 1.4, seed: 0.9 }, { t: 'monkey', x: 24.4, y: 1.4, s: 1.2, seed: 0.8 },
      { t: 'jungleTree', x: 1.0, y: 0.8, s: 1.5, seed: 0.3 }, { t: 'fern', x: 1.2, y: 4.5, s: 1.3, seed: 0.6 }, { t: 'fern', x: 24.6, y: 6.5, s: 1.3, seed: 0.1 }, { t: 'idol', x: 4.5, y: 7.6, s: 1.2 },
      { t: 'rock', x: 12.5, y: 8.4, s: 1.4 }, { t: 'rock', x: 9.5, y: 0.5, s: 1.2 }, { t: 'flowerbush', x: 21.5, y: 8.5 },
    ],
    autoDecor: { density: 0.3, seed: 303 },
  },
  {
    name: 'Krokodilfluss', par: 3, theme: 'jungle', maxStrokes: 18, friction: { s: 26 }, hazardText: { water: 'Platsch! In den Krokodilfluss', shark: 'Vom Krokodil geschnappt!' },
    views: [{ x: 2, y: 1, w: 8, h: 3, look: { x: 17, y: 2.5 } }],
    intro: 'Über die Rampe hinweg über den Fluss – doch das Krokodil schnappt im Takt nach allem, was über ihm fliegt. Drüben lauert Treibsand, und ein Götze steht vor dem Loch.',
    map: [
      '........................',
      '..########wwww########..',
      '..#T######wwww######H#..',
      '..########wwww##sss###..',
      '........................',
      '........................',
    ],
    obstacles: [
      { type: 'ramp', x: 8, y: 1, w: 2, h: 3, angle: 0, minSpeed: 3, speed: 6.5, land: 5.6 },
      { type: 'sharkjump', x: 12, y: 2.5, w: 4, h: 3, period: 3.8, jump: 0.34, phase: 0.1, axis: 'y', height: 1.2, style: 'croc' },
      { type: 'bumper', x: 18.6, y: 1.6, r: 0.38, style: 'idol' },
    ],
    decor: [
      { t: 'jungleTree', x: 5.5, y: 0.4, s: 1.5, seed: 0.4 }, { t: 'jungleTree', x: 17.5, y: 0.3, s: 1.4, seed: 0.8 }, { t: 'fern', x: 1.2, y: 3.6, s: 1.3, seed: 0.3 }, { t: 'fern', x: 22.6, y: 3.6, s: 1.3, seed: 0.7 },
      { t: 'ropepost', x: 9.8, y: 0.6, s: 1.0 }, { t: 'ropepost', x: 14.2, y: 0.6, s: 1.0 }, { t: 'idol', x: 22.6, y: 1.0, s: 1.2 }, { t: 'totem', x: 1.0, y: 1.2, s: 1.1, seed: 0.6 },
      { t: 'rock', x: 11.5, y: 4.6, s: 1.3 }, { t: 'rock', x: 12.6, y: 0.3, s: 1.1 }, { t: 'flowerbush', x: 6.5, y: 4.5 },
    ],
    autoDecor: { density: 0.32, seed: 305 },
  },
  {
    name: 'Stachelpfad', par: 4, theme: 'jungle', maxStrokes: 18, hazardText: { water: 'Platsch! In den Fluss', spiked: 'Aufgespießt! Zurück zum Schlagstart' },
    views: [{ x: 2, y: 1, w: 14, h: 2, look: { x: 16.5, y: 1.5 } }, { x: 16, y: 1, w: 2, h: 4, look: { x: 16.5, y: 6 } }],
    intro: 'Drei Stachelfallen im Takt: Die Platten schießen ihre Spitzen aus und versperren den Weg, kurz darauf fahren sie wieder ein. Wer auf einer Platte liegen bleibt, wird aufgespießt. Mit dem richtigen Moment passt ein Schlag an beiden Platten der ersten Geraden vorbei.',
    map: [
      '......................',
      '..T###############....',
      '..################....',
      '................##....',
      '................##....',
      '......#H##########....',
      '......############....',
      '......................',
    ],
    obstacles: [
      { type: 'spikes', x: 7, y: 2, w: 1, h: 2, period: 4, up: 0.45, phase: 0 },
      { type: 'spikes', x: 12, y: 2, w: 1, h: 2, period: 4, up: 0.45, phase: 0.1 }, // fährt 0,4 s nach der ersten Platte ein
      { type: 'spikes', x: 12, y: 6, w: 1, h: 2, period: 3.4, up: 0.45, phase: 0.25 },
      { type: 'wall', x0: 16.8, y0: 1, x1: 18, y1: 2.2, extend: 0 },
      { type: 'wall', x0: 18, y0: 5.8, x1: 16.8, y1: 7, extend: 0 },
    ],
    decor: [
      { t: 'jungleTree', x: 9.5, y: 4.2, s: 1.5, seed: 0.5 }, { t: 'jungleTree', x: 20.5, y: 1.2, s: 1.4, seed: 0.2 }, { t: 'fern', x: 3.5, y: 4.4, s: 1.3, seed: 0.6 }, { t: 'fern', x: 14.5, y: 0.4, s: 1.2, seed: 0.9 },
      { t: 'idol', x: 4.5, y: 6.5, s: 1.3 }, { t: 'totem', x: 20.6, y: 6.2, s: 1.2, seed: 0.3 }, { t: 'skull', x: 8.5, y: 0.5 }, { t: 'bones', x: 13.5, y: 4.2, s: 1.1 }, { t: 'rock', x: 1.0, y: 3.2, s: 1.2 },
    ],
    autoDecor: { density: 0.34, seed: 307 },
  },
  {
    name: 'Felskugelschlucht', par: 4, theme: 'jungle', maxStrokes: 22, hazardText: { water: 'Platsch! In den Fluss' },
    intro: 'Eine enge Schlucht, in der eine riesige Felskugel hin und her rollt. Nur die Nischen links und rechts bieten Schutz – warten, bis sie vorbei ist, dann weiter.',
    map: [
      '..........................',
      '......#....#....#....#....',
      '..T####################H..',
      '........#....#....#.......',
      '..........................',
    ],
    obstacles: [
      { type: 'mover', x0: 6.5, y0: 2.5, x1: 22.5, y1: 2.5, w: 0.85, h: 0.85, period: 10, style: 'boulder', e: 0.6 },
    ],
    decor: [
      { t: 'jungleTree', x: 4.5, y: 0.2, s: 1.6, seed: 0.4 }, { t: 'jungleTree', x: 14.5, y: 0.1, s: 1.5, seed: 0.8 }, { t: 'jungleTree', x: 24.5, y: 0.2, s: 1.5, seed: 0.2 },
      { t: 'rock', x: 3.5, y: 0.8, s: 1.5 }, { t: 'rock', x: 9.5, y: 0.6, s: 1.4 }, { t: 'rock', x: 19.5, y: 0.7, s: 1.5 }, { t: 'rock', x: 5.5, y: 4.3, s: 1.4 }, { t: 'rock', x: 11.5, y: 4.4, s: 1.5 }, { t: 'rock', x: 16.5, y: 4.3, s: 1.4 }, { t: 'rock', x: 22.5, y: 4.4, s: 1.5 },
      { t: 'fern', x: 1.2, y: 1.2, s: 1.3, seed: 0.5 }, { t: 'fern', x: 24.8, y: 3.8, s: 1.3, seed: 0.1 }, { t: 'skull', x: 7.5, y: 4.4 }, { t: 'bones', x: 15.5, y: 0.6, s: 1.1 }, { t: 'idol', x: 1.0, y: 3.4, s: 1.2 },
    ],
    autoDecor: { density: 0.3, seed: 309 },
  },
  {
    name: 'Treibsandbecken', par: 4, theme: 'jungle', maxStrokes: 18, friction: { s: 26 }, hazardText: { water: 'Platsch! In den Fluss' },
    intro: 'Ein Becken voller Treibsand, nur ein schmaler Steinpfad führt hindurch. Wer vom Pfad rollt, kommt im Sand kaum noch vom Fleck. Eine Liane pendelt über den Pfad, eine Kokosnuss rollt quer.',
    map: [
      '....................',
      '..ssssssssssssssss..',
      '..T#######ssssssss..',
      '..sssssss#ssssssss..',
      '..sssssss#ssssssss..',
      '..sssssss#ssssssss..',
      '..sssssss########s..',
      '..ssssssssssssss#s..',
      '..ssssssssssssssHs..',
      '....................',
    ],
    obstacles: [
      { type: 'rotor', x: 9.5, y: 4.2, blades: 1, len: 1.1, thick: 0.15, hubR: 0.1, style: 'vine', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.4 }, phase: 0, height: 0.5 },
      { type: 'mover', x0: 10.2, y0: 6.5, x1: 15.6, y1: 6.5, w: 0.5, h: 0.5, period: 5, style: 'coconut', e: 0.7 },
      { type: 'wall', x0: 8.8, y0: 2, x1: 10, y1: 3.2, extend: 0 },
      { type: 'wall', x0: 8.8, y0: 7, x1: 10, y1: 5.8, extend: 0 },
      { type: 'wall', x0: 15.8, y0: 6, x1: 17, y1: 7.2, extend: 0 },
    ],
    decor: [
      { t: 'idol', x: 5.5, y: 5.0, s: 1.4 }, { t: 'idol', x: 13.5, y: 3.5, s: 1.3 }, { t: 'totem', x: 3.5, y: 7.2, s: 1.2, seed: 0.7 }, { t: 'bones', x: 12.5, y: 1.6, s: 1.1 }, { t: 'skull', x: 6.5, y: 7.6 },
      { t: 'jungleTree', x: 1.0, y: 0.5, s: 1.5, seed: 0.3 }, { t: 'jungleTree', x: 18.8, y: 1.0, s: 1.5, seed: 0.9 }, { t: 'fern', x: 1.2, y: 8.6, s: 1.3, seed: 0.5 }, { t: 'fern', x: 18.6, y: 8.8, s: 1.3, seed: 0.2 },
      { t: 'monkey', x: 18.6, y: 1.0, s: 1.2, seed: 0.4 },
    ],
    autoDecor: { density: 0.3, seed: 311 },
  },
  {
    name: 'Totemplatz', par: 4, theme: 'jungle', maxStrokes: 22, friction: { s: 26 }, hazardText: { water: 'Platsch! In den Fluss' },
    views: [{ x: 2, y: 8, w: 6, h: 3, look: { x: 19, y: 5.5 } }],
    intro: 'Auf dem Platz drehen sich zwei Totempfähle mit vier Armen. Die Druckplatte unten links öffnet das Steintor zur Kammer mit dem Loch – aber nur für kurze Zeit.',
    map: [
      '.......................',
      '..T################....',
      '..#########ss######....',
      '..#################....',
      '..######s############..',
      '..##################H..',
      '..###################..',
      '..###ss##############..',
      '..#############ss##....',
      '..#################....',
      '..#################....',
      '.......................',
    ],
    obstacles: [
      { type: 'rotor', x: 7, y: 5.5, blades: 4, len: 2.0, thick: 0.18, hubR: 0.4, speed: 1.0, height: 0.6, style: 'stone' },
      { type: 'rotor', x: 14, y: 5.5, blades: 4, len: 2.0, thick: 0.18, hubR: 0.4, speed: -1.2, phase: 0.6, height: 0.6, style: 'stone' },
      { type: 'switch', x: 3.5, y: 9.5, r: 0.55, duration: 14, target: 'A' },
      { type: 'gate', x: 19, y: 6, w: 0.3, h: 4, linked: 'A', liftH: 1.4, barH: 1.0 },
      { type: 'bumper', x: 17.5, y: 2.2, r: 0.36, style: 'idol' },
    ],
    decor: [
      { t: 'totem', x: 1.0, y: 3.0, s: 1.3, seed: 0.1 }, { t: 'totem', x: 1.0, y: 8.0, s: 1.3, seed: 0.5 }, { t: 'totem', x: 19.6, y: 1.2, s: 1.3, seed: 0.9 }, { t: 'totem', x: 21.6, y: 9.4, s: 1.2, seed: 0.3 },
      { t: 'idol', x: 21.6, y: 3.2, s: 1.3 }, { t: 'idol', x: 21.6, y: 8.0, s: 1.3 }, { t: 'jungleTree', x: 10.5, y: 0.2, s: 1.5, seed: 0.6 }, { t: 'jungleTree', x: 4.5, y: 11.4, s: 1.4, seed: 0.2 },
      { t: 'fern', x: 15.5, y: 11.4, s: 1.3, seed: 0.8 }, { t: 'fern', x: 17.5, y: 0.5, s: 1.2, seed: 0.4 }, { t: 'brazier', x: 20.5, y: 3.4, s: 1.0 }, { t: 'brazier', x: 20.5, y: 8.6, s: 1.0 },
    ],
    autoDecor: { density: 0.3, seed: 313 },
  },
  {
    name: 'Wasserfallterrassen', par: 4, theme: 'jungle', maxStrokes: 22, hStep: 0.45, hazardText: { water: 'Platsch! In den Wasserfall', oob: 'Über die Kante gestürzt' },
    intro: 'Drei Terrassen, durch Wasserfälle getrennt, führen bergab. Schräge Banden lenken um die Kehren, auf der mittleren Terrasse rollt eine Kokosnuss quer.',
    map: [
      '........................',
      '..########.ww...........',
      '..T#######.ww...........',
      '..########.ww...........',
      '........##..............',
      '........##..............',
      '....############.ww.....',
      '....############.ww.....',
      '....############.ww.....',
      '..............##........',
      '..............##........',
      '..........##########H#..',
      '..........############..',
      '........................',
    ],
    heights: [
      '........................',
      '..22222222.22...........',
      '..22222222.22...........',
      '..22222222.22...........',
      '........11..............',
      '........11..............',
      '....111111111111.11.....',
      '....111111111111.11.....',
      '....111111111111.11.....',
      '..............00........',
      '..............00........',
      '..........000000000000..',
      '..........000000000000..',
      '........................',
    ],
    obstacles: [
      { type: 'field', x: 8, y: 4, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 1, rise: 1 },
      { type: 'field', x: 14, y: 9, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 0, rise: 1 },
      { type: 'wall', x0: 8.8, y0: 1, x1: 10, y1: 2.2, extend: 0 },
      { type: 'wall', x0: 7.8, y0: 9, x1: 9, y1: 7.8, extend: 0 },
      { type: 'wall', x0: 14.8, y0: 6, x1: 16, y1: 7.2, extend: 0 },
      { type: 'wall', x0: 13.8, y0: 13, x1: 15, y1: 11.8, extend: 0 },
      { type: 'mover', x0: 5, y0: 7.5, x1: 13, y1: 7.5, w: 0.5, h: 0.5, period: 6, style: 'coconut', e: 0.7 },
      { type: 'bumper', x: 18.5, y: 12.5, r: 0.36, style: 'idol' },
    ],
    decor: [
      { t: 'jungleTree', x: 1.0, y: 0.4, s: 1.6, seed: 0.2 }, { t: 'jungleTree', x: 20.5, y: 5.5, s: 1.5, seed: 0.7 }, { t: 'jungleTree', x: 6.5, y: 10.5, s: 1.4, seed: 0.5 },
      { t: 'fern', x: 3.5, y: 4.6, z: 0.9, s: 1.3, seed: 0.3 }, { t: 'fern', x: 22.6, y: 12.6, s: 1.3, seed: 0.8 }, { t: 'idol', x: 5.5, y: 0.5, z: 0.9, s: 1.2 }, { t: 'totem', x: 16.6, y: 5.5, z: 0.45, s: 1.2, seed: 0.6 },
      { t: 'rock', x: 10.5, y: 4.5, z: 0.9, s: 1.3 }, { t: 'rock', x: 16.5, y: 9.5, z: 0.45, s: 1.3 }, { t: 'rock', x: 12.5, y: 13.3, s: 1.2 }, { t: 'monkey', x: 20.3, y: 5.5, s: 1.1, seed: 0.3 },
    ],
    autoDecor: { density: 0.3, seed: 315 },
  },
  {
    name: 'Der Tempel', par: 8, theme: 'jungle', maxStrokes: 30, hazardText: { water: 'Platsch! In den Fluss', oob: 'In die Schlucht gestürzt' },
    views: [{ x: 2, y: 2, w: 7, h: 2, look: { x: 17, y: 3 } }, { x: 15, y: 1, w: 6, h: 5, look: { x: 18.5, y: 11 } }, { x: 18, y: 6, w: 2, h: 6, look: { x: 22.5, y: 12.6 } }, { x: 10, y: 12, w: 14, h: 2, look: { x: 22.5, y: 12.6 } }],
    intro: 'Die verlorene Stadt: über die Hängebrücke, vorbei an Stachelfallen, durch die Schlucht mit der Felskugel bis zum Tempeltor. Drinnen wartet die Tempelhalle mit Feuergruben, Steinscheibe, Druckplatte und dem goldenen Götzen.',
    map: [
      '..............................',
      '.........wwwwww######.........',
      '..#T#####wwwwww######.........',
      '..#######oooooo######.........',
      '.........wwwwww######.........',
      '.........wwwwww######.........',
      '..................##..........',
      '..................##..........',
      '..................##..........',
      '..................##..........',
      '..................##..........',
      '..................##..........',
      '..........###########ooo......',
      '..........###########ooo......',
      '..............................',
    ],
    obstacles: [
      { type: 'spikes', x: 17.5, y: 2.5, w: 1, h: 1, period: 3.6, up: 0.45, phase: 0 },
      { type: 'spikes', x: 16.5, y: 4.5, w: 1, h: 1, period: 3.6, up: 0.45, phase: 0.5 },
      { type: 'spikes', x: 19.5, y: 3.5, w: 1, h: 1, period: 4.2, up: 0.45, phase: 0.25 },
      { type: 'wall', x0: 19.8, y0: 5.2, x1: 21, y1: 4, extend: 0 },
      { type: 'mover', x0: 18.9, y0: 6.6, x1: 18.9, y1: 11.3, w: 0.85, h: 0.85, period: 7, style: 'boulder', e: 0.6 },
      { type: 'wall', x0: 18, y0: 12.8, x1: 19.2, y1: 14, extend: 0 },
      { type: 'door', x: 22.5, y: 12.6, r: 0.95, style: 'temple', px: 22.5, py: 11.5, gw: 3.2 },
    ],
    decor: [
      { t: 'ropepost', x: 8.85, y: 2.55, s: 1.1 }, { t: 'ropepost', x: 8.85, y: 4.45, s: 1.1 }, { t: 'ropepost', x: 15.15, y: 2.55, s: 1.1 }, { t: 'ropepost', x: 15.15, y: 4.45, s: 1.1 },
      { t: 'jungleTree', x: 1.0, y: 0.8, s: 1.6, seed: 0.3 }, { t: 'jungleTree', x: 5.5, y: 6.5, s: 1.5, seed: 0.8 }, { t: 'jungleTree', x: 24.5, y: 2.5, s: 1.6, seed: 0.5 }, { t: 'jungleTree', x: 12.5, y: 9.5, s: 1.5, seed: 0.1 },
      { t: 'monkey', x: 24.3, y: 2.5, s: 1.2, seed: 0.6 }, { t: 'fern', x: 4.5, y: 4.6, s: 1.3, seed: 0.2 }, { t: 'fern', x: 21.5, y: 7.5, s: 1.3, seed: 0.9 }, { t: 'fern', x: 8.5, y: 13.5, s: 1.3, seed: 0.4 },
      { t: 'idol', x: 16.5, y: 8.5, s: 1.3 }, { t: 'idol', x: 26.5, y: 13.5, s: 1.4 }, { t: 'totem', x: 15.5, y: 12.4, s: 1.2, seed: 0.2 }, { t: 'totem', x: 9.0, y: 11.6, s: 1.2, seed: 0.7 },
      { t: 'rock', x: 16.6, y: 6.6, s: 1.4 }, { t: 'rock', x: 21.4, y: 9.6, s: 1.4 }, { t: 'rock', x: 12.5, y: 0.4, s: 1.2 }, { t: 'skull', x: 20.5, y: 9.4 }, { t: 'bones', x: 17.0, y: 10.6, s: 1.1 },
    ],
    autoDecor: { density: 0.3, seed: 317 },
    inner: {
      name: 'Tempelhalle', theme: 'temple', look: { x: 11.5, y: 5.5 }, hazardText: { lava: 'Ins Feuer gefallen!', oob: 'In den Abgrund gestürzt' },
      views: [{ x: 2, y: 1, w: 11, h: 3, look: { x: 11.5, y: 6 } }, { x: 4, y: 8, w: 17, h: 4, look: { x: 21, y: 9.5 } }],
      map: [
        '..............................',
        '..###########.................',
        '..T###ll#####.................',
        '..###########.................',
        '...........##.................',
        '...........##.................',
        '...........##.................',
        '...........##.................',
        '....####################l###..',
        '....######################H#..',
        '....########################..',
        '....####################l###..',
        '..............................',
        '..............................',
        '..............................',
        '..............................',
      ],
      obstacles: [
        { type: 'spikes', x: 9.5, y: 2.5, w: 1, h: 3, period: 4, up: 0.45, phase: 0.2 },
        { type: 'wall', x0: 11.8, y0: 1, x1: 13, y1: 2.2, extend: 0 },
        { type: 'wall', x0: 10.8, y0: 8, x1: 12, y1: 6.8, extend: 0 },
        { type: 'turntable', x: 15, y: 9.5, r: 1.4, speed: 1.6, exit: 0 },
        { type: 'mover', x0: 5, y0: 10.6, x1: 19.5, y1: 10.6, w: 0.8, h: 0.8, period: 9, phase: 0.3, style: 'boulder', e: 0.6 },
        { type: 'switch', x: 5.5, y: 8.8, r: 0.55, duration: 16, target: 'A' },
        { type: 'gate', x: 21, y: 10, w: 0.3, h: 4, linked: 'A', liftH: 1.6, barH: 1.2 },
        { type: 'bumper', x: 19.5, y: 8.6, r: 0.34, style: 'idol' },
      ],
      decor: [
        { t: 'brazier', x: 1.3, y: 1.4, s: 1.1 }, { t: 'brazier', x: 13.5, y: 0.6, s: 1.1 }, { t: 'brazier', x: 3.4, y: 11.6, s: 1.1 }, { t: 'brazier', x: 21.5, y: 7.4, s: 1.1 }, { t: 'brazier', x: 28.5, y: 8.4, s: 1.1 }, { t: 'brazier', x: 28.5, y: 11.6, s: 1.1 },
        { t: 'idol', x: 22.6, y: 12.6, s: 1.4 }, { t: 'idol', x: 13.6, y: 4.6, s: 1.3 }, { t: 'urn', x: 8.5, y: 0.5, s: 1.1 }, { t: 'urn', x: 9.5, y: 12.4, s: 1.1 }, { t: 'urn', x: 25.5, y: 7.4, s: 1.1 },
        { t: 'skull', x: 4.5, y: 4.4 }, { t: 'bones', x: 16.5, y: 12.5, s: 1.2 }, { t: 'chest', x: 26.5, y: 12.6, s: 1.3 }, { t: 'totem', x: 2.4, y: 7.5, s: 1.2, seed: 0.4 },
      ],
      autoDecor: { density: 0.18, seed: 319 },
    },
  },
];
