/* Die Flut (Weltkennung 'flut'): die versunkene Stadt.
   Erzeugt von tools/flut.py – dort steht auch, warum die Bahnen so aussehen, wie sie aussehen.

   NOCH NICHT FERTIG. Zurzeit stehen hier zwei Probebahnen, an denen die Maschinen angesehen und
   gespielt werden können, bevor neun Bahnen darauf gebaut werden. Die Welt trägt darum in
   src/courses_pro.js die Kennzeichnung 'nurVorschau'; im Spiel taucht sie nicht auf.

   DAS FLUTBECKEN ist ein Hindernis wie das Wandertor oder die Falltür: Es läuft im Takt von außen
   nach innen voll und wieder leer, und solange es leer ist, geht der Weg hindurch. Ringsum bleibt
   die Bahn trocken und immer spielbar – **es gibt auf jeder Bahn einen Weg, der auch bei vollem
   Becken zum Loch führt** (tools/flut.py prüft das). Das Becken ist die Abkürzung, nicht die
   einzige Möglichkeit; warten muß man nie.

   Zuerst war die Flut eine Weltregel und stieg über die ganze Bahn. Das war gut gedacht und
   schlecht zu spielen: Wer den Augenblick verpaßte, konnte nur zusehen. Siehe src/obstacles_flut.js.

   Kartenlegende wie in courses.js: '#' Boden, '.' offenes Wasser, 'x' Block, 's' Schlick (bremst),
   'T' Abschlag, 'H' Loch. */
const FLUT_COURSES = [
  {
    name: 'Die Hafenmole', par: 4, theme: 'wasserlinie', tiefe: 0.12,
    intro: 'Die Mole läuft nach rechts und knickt am Ende nach oben ab. Mittendrin läuft sie im Takt voll: Zwei Wege, im richtigen Augenblick hindurch – oder unten herum, immer, aber weiter.',
    autoDecor: { density: 0.13, seed: 17 },
    map: [
      '........................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwww#######ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww######H#ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww########ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.ww#############################wwwwwww.',
      '.ww#T###########################wwwwwww.',
      '.ww############################wwwwwwww.',
      '.wwwwwwwwwww###wwwwwwwww###wwwwwwwwwwww.',
      '.wwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwww###############wwwwwwwwwwww.',
      '.............#############..............',
    ],
    obstacles: [
      { type: 'flut', x: 20.5, y: 15.5, w: 7, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Der Priel', par: 5, theme: 'wasserlinie', tiefe: 0.2,
    intro: 'Zwei Becken hintereinander, versetzt getaktet – nacheinander kommt man nie durch beide. Am Anfang liegt das Pumpwerk: Wer darüberrollt, legt beide für vier Sekunden trocken.',
    autoDecor: { density: 0.13, seed: 29 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########################wwwwwwwwwwwwwwww.',
      '.ww#T#######################wwwwwwwwwwwwwww.',
      '.ww#########################wwwwwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwww###ww###wwwwwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwww###ww###wwwwwwwwwwwwwww.',
      '.wwwwwwwww#############ww###wwwwwwwwwwwwwww.',
      '.wwwwwwwww#############ww###wwwwwwwwwwwwwww.',
      '.wwwwwwwwww###########www###wwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwww##############H#ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwww###############ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwww###www.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###########www.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwww###########www.',
      '..............................#########.....',
    ],
    obstacles: [
      { type: 'pumpwerk', x: 8.5, y: 5.5, r: 0.8, dauer: 4 },
      { type: 'flut', x: 16.5, y: 5.5, w: 5, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'flut', x: 34.5, y: 17.5, w: 5, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Buhnen', par: 5, theme: 'wasserlinie', tiefe: 0.28,
    intro: 'Zwischen den Buhnen drückt das Wasser zurück – wer zu sacht spielt, kommt nicht durch. Und vor dem Loch hängt eine Luke aus einem Schiffsrumpf: langsam auf, blitzschnell zu.',
    autoDecor: { density: 0.13, seed: 43 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwww#####################ww.',
      '.wwwwwwwwwwwwwwwwwww###################H#ww.',
      '.wwwwwwwwwwwwwwwwwww#####################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwww.',
      '.ww#################################wwwwwww.',
      '.ww#T###############################wwwwwww.',
      '.ww################################wwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 22.0, y: 16.5, w: 8, h: 3, angle: 180, tempo: 4.6 },
      { type: 'wracktor', x: 28.5, y: 4.15, len: 2.8, zuWinkel: 90, takt: 6.0, gegen: true },
    ],
  },
  {
    name: 'Der Kessel', par: 4, theme: 'flachwasser', tiefe: 0.36,
    intro: 'Mitten im Kessel dreht sich das Wasser. Es hält niemanden fest – es schleudert nach außen, und wohin, entscheidet, wo man hineingerät.',
    autoDecor: { density: 0.13, seed: 59 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww#########################ww.',
      '.wwwwwwwwwwwwwww#######################H#ww.',
      '.wwwwwwwwwwwwwww#########################ww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.ww#T##########################wwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'strudel', x: 23.0, y: 10.5, r: 3.8, dreh: 1 },
    ],
  },
  {
    name: 'Der Seegraswald', par: 5, theme: 'flachwasser', tiefe: 0.44,
    intro: 'Hin und um die Ecke wieder zurück – das Loch liegt fast neben dem Abschlag, nur eben auf der anderen Seite. Auf beiden Läufen liegt ein Tangfeld quer. Es hält niemanden auf, es nimmt den Schwung; durch jedes läuft eine Gasse, und die wandert.',
    autoDecor: { density: 0.13, seed: 71 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww##############################wwwwwwwwwwww.',
      '.ww#T#############################wwwwwwwwwww.',
      '.ww###############################wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwww###w###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwww###w###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###wwwww###w###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###########w###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwww###########w###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwww#########ww###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww################wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww#H##############wwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'tangwald', x: 16.5, y: 5.5, w: 3, h: 5, takt: 3.4 },
      { type: 'flut', x: 23.5, y: 5.5, w: 5, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
    ],
  },
  {
    name: 'Die Austernbank', par: 5, theme: 'flachwasser', tiefe: 0.52,
    intro: 'Oben oder unten herum – und in beiden Ästen sitzt eine Riesenmuschel. Geschlossen ist sie ein Klotz, offen ein Maul: Sie schluckt, hält kurz und spuckt in ihre Richtung wieder aus. Wer den Takt trifft, spart den halben Weg.',
    autoDecor: { density: 0.13, seed: 89 },
    map: [
      '............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww#############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww#############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww#################wwwwwwwwww.',
      '.wwwwwwwwwwwwwww#################wwwwwwwwww.',
      '.wwwwwwwwwwwwwww#################wwwwwwwwww.',
      '.wwwwwwwwwwwwwww#####wwwwwww#####wwwwwwwwww.',
      '.wwwwwwwwwwwwwww#####wwwwwww#####wwwwwwwwww.',
      '.ww##################wwwwwww#############ww.',
      '.ww#T################wwwwwww###########H#ww.',
      '.ww##################wwwwwwwww###########ww.',
      '.wwwwwwwwwwwwwww#####wwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww#####wwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww#############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwww#############wwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '............................................',
    ],
    obstacles: [
      { type: 'muschel', x: 24.5, y: 5.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45 },
      { type: 'muschel', x: 24.5, y: 17.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45, phase: 0.5 },
    ],
  },
  {
    name: 'Die Kanalisation', par: 4, theme: 'daemmerzone', tiefe: 0.6,
    intro: 'Im Platz dreht sich das Wasser, und in seiner Ecke liegt ein Abflußgitter. Man spielt nicht hinein – man landet darin, wenn einen der Strudel dorthin schleudert. Unter dem Grund läuft die Leitung schnurgerade hinter den Platz; man sieht die Naht.',
    autoDecor: { density: 0.13, seed: 101 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwwwww.',
      '.ww#T##########################wwwwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwww###########################ww.',
      '.wwwwwwwwwwwwwww###A##############a######H#ww.',
      '.wwwwwwwwwwwwwww###########################ww.',
      '.wwwwwwwwwwwwwww###############wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'strudel', x: 23.0, y: 11.0, r: 3.8, dreh: -1 },
      { type: 'abflussrohr', pair: 'A', angle: 0 },
    ],
  },
  {
    name: 'Die Kaimauer', par: 5, theme: 'daemmerzone', tiefe: 0.68,
    intro: 'Unten hin, oben zurück – oder andersherum. Über beiden Stegen schwingt ein Anker an seiner Kette. Er ist langsamer als jedes Pendel der Uhrwerkstadt, und das ist auch nötig: Ein Stoß auf drei Kacheln Steg schickt einen ins Meer.',
    autoDecor: { density: 0.13, seed: 113 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########################################ww.',
      '.ww######################################H##w.',
      '.ww#########################################w.',
      '.ww#########################################w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww####wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww####w.',
      '.ww#########################################w.',
      '.ww#T#######################################w.',
      '.ww########################################ww.',
      '.ww########################################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'ankerkette', x: 20.5, y: 12.5, len: 5.0, amp: 48, ruhe: 90, takt: 5.2 },
      { type: 'ankerkette', x: 30.5, y: 11.5, len: 5.0, amp: 48, ruhe: 270, takt: 5.2, phase: 0.5 },
      { type: 'wracktor', x: 12.5, y: 16.1, len: 2.8, zuWinkel: 90, takt: 6.0, gegen: true },
    ],
  },
  {
    name: 'Der Marktplatz', par: 5, theme: 'daemmerzone', tiefe: 0.76,
    intro: 'Am Eingang ein Becken, im Platz der Brunnen, in dem sich alles dreht, und davor und dahinter Schlick, der den Schwung frißt. In der Ecke wartet das Abflußgitter, über dem Ausgang hängt der Anker. Wer hier in fünf Schlägen durchkommt, hat alles getroffen.',
    autoDecor: { density: 0.13, seed: 131 },
    map: [
      '................................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwww###################wwwwwwwwwwwwww.',
      '.ww##############################wwwwwwwwwwwwww.',
      '.ww#T############################wwwwwwwwwwwwww.',
      '.ww##############################wwwwwwwwwwwwww.',
      '.www###www###w###################wwwwwwwwwwwwww.',
      '.www###www###w####ssss####ssss###wwwwwwwwwwwwww.',
      '.www#########w####ssss####ssss###wwwwwwwwwwwwww.',
      '.www#########w####ssss####ssss###wwwwwwwwwwwwww.',
      '.wwww#######ww####ssss####ssss###wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwww####ssss####ssss###wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwww###################wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwww################################w.',
      '.wwwwwwwwwwwww######################b#######H#w.',
      '.wwwwwwwwwwwww##B#############################w.',
      '.wwwwwwwwwwwww###################wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '................................................',
    ],
    obstacles: [
      { type: 'flut', x: 8.5, y: 6.5, w: 3, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'strudel', x: 23.5, y: 11.0, r: 3.2, dreh: -1 },
      { type: 'abflussrohr', pair: 'B', angle: 0 },
      { type: 'ankerkette', x: 40.5, y: 12.5, len: 4.0, amp: 48, ruhe: 90, takt: 5.2 },
    ],
  },
  {
    name: 'Die Schlotebene', par: 4, theme: 'meeresgrund', tiefe: 0.84,
    intro: 'Aus dem Grund stößt eine heiße Quelle. Sie wirft auch einen Ball, der nur daliegt – und sie wirft ihn weit. Kurz vorher flimmert der Boden: Das ist die ganze Warnung, die man bekommt.',
    autoDecor: { density: 0.13, seed: 149 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwww#################################wwww.',
      '.wwwwww################################H#wwww.',
      '.wwwwww##################################wwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwww###wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwwwww.',
      '.ww#T##########################wwwwwwwwwwwwww.',
      '.ww############################wwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'raucher', x: 26.5, y: 17.5, r: 1.0, angle: 270, weite: 11.0, takt: 4.6 },
      { type: 'tangwald', x: 31.5, y: 6.5, w: 3, h: 5, takt: 3.4 },
    ],
  },
  {
    name: 'Das Kaltwasserfeld', par: 5, theme: 'meeresgrund', tiefe: 0.92,
    intro: 'Zwei Stege, auf beiden zieht es – oben nach rechts, unten nach links, und beide als Dünung: Sie kommt und geht. Verbunden sind sie nur in der Mitte, und mitten in der Verbindung dreht sich das Wasser. Stehenbleiben geht nirgends.',
    autoDecor: { density: 0.13, seed: 163 },
    map: [
      '..............................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.ww########################################ww.',
      '.ww######################################H#ww.',
      '.ww########################################ww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwww###wwwwwwwwwwwwwwwwwwww.',
      '.ww########################################ww.',
      '.ww#T######################################ww.',
      '.ww########################################ww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '..............................................',
    ],
    obstacles: [
      { type: 'stroemung', x: 15.0, y: 7.5, w: 10, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 0.0 },
      { type: 'stroemung', x: 32.0, y: 7.5, w: 10, h: 3, angle: 0, tempo: 6.0, puls: 1.25, phase: 1.6 },
      { type: 'stroemung', x: 15.0, y: 16.5, w: 10, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 3.14 },
      { type: 'stroemung', x: 32.0, y: 16.5, w: 10, h: 3, angle: 180, tempo: 6.0, puls: 1.25, phase: 4.7 },
      { type: 'strudel', x: 23.5, y: 11.5, r: 2.8, dreh: 1 },
      { type: 'muschel', x: 23.5, y: 6.5, r: 1.05, angle: 0, takt: 5.5, offen: 0.45, phase: 0.3 },
    ],
  },
  {
    name: 'Der Schlund', par: 5, theme: 'meeresgrund', tiefe: 1.0,
    intro: 'Das Ende. Zwei Äste, in jedem ein Becken, und beide münden in die Kammer, in der es zieht, sich alles dreht – und in der ein Anglerfisch seine Bahn zieht. Wen seine Laterne erreicht, der spielt den letzten Schlag noch einmal.',
    autoDecor: { density: 0.13, seed: 181 },
    map: [
      '................................................',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwwww###sssss####wwwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww####sssss#####wwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww####sssss#####wwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwww###wwwwwwwwwwwwwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwww##############wwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwwww#############wwwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwwww#############wwwwwwwwwwww.',
      '.ww##########wwwwwwwww#######################ww.',
      '.ww#T########wwwwwwwww#####################H#ww.',
      '.ww##########wwwwwwwww#######################ww.',
      '.wwwwwwwww###wwwwwwwww##############wwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwwww##############wwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwww###############wwwwwwwwwww.',
      '.wwwwwwwww###wwwwwwww###wwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwww####sssss#####wwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwww####sssss#####wwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwww####sssss####wwwwwwwwww###wwwwwwwwwww.',
      '.wwwwwwwww##########################wwwwwwwwwww.',
      '.wwwwwwwww##########################wwwwwwwwwww.',
      '.wwwwwwwwww########################wwwwwwwwwwww.',
      '................................................',
    ],
    obstacles: [
      { type: 'flut', x: 16.5, y: 5.5, w: 5, h: 3, start: 2.5, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'flut', x: 16.5, y: 19.5, w: 5, h: 3, start: 4.4, takt: 1.2, halt: 1.0, leer: 5.0 },
      { type: 'stroemung', x: 28.5, y: 12.5, w: 9, h: 5, angle: 0, tempo: 5.0, puls: 1.15, phase: 0.0 },
      { type: 'strudel', x: 28.0, y: 12.5, r: 2.6, dreh: -1 },
      { type: 'angler', x0: 23.5, y0: 9.5, x1: 33.5, y1: 15.5, tempo: 2.2 },
      { type: 'raucher', x: 37.5, y: 12.5, r: 1.0, angle: 0, weite: 6.0, takt: 5.2 },
      { type: 'pumpwerk', x: 7.0, y: 12.5, r: 0.8, dauer: 4 },
    ],
  },
];
