/* Uhrwerkstadt: neun Bahnen in einer Stadt, die im Takt läuft.

   Die Idee, die diese Welt von allen anderen trennt: Auf jeder Bahn geht alles auf denselben Takt.
   Pendel, Zeiger, Tore, Aufzüge und Dampfventile teilen sich eine Grundzeit; was nicht darauf läuft,
   läuft auf ihrer Hälfte oder ihrem Doppelten. Dadurch ist keine Bahn ein Ratespiel: Man sieht einmal
   zu, zählt mit, und schlägt auf den Schlag. Der Takt steht in jeder Einleitung.

   Gebaut ist alles aus Teilen, die es schon gab – das Pendel ist ein Rotor mit swing, das Dampfventil
   ein Feld mit gust, der Zahnradaufzug eine Fähre. Neu sind nur ihre Gesichter (Stile 'pendel' und
   'steam') und die drei Farbpaletten. Ein Hindernis dazuzuerfinden, das sich am Ende doch wie ein
   Rotor benimmt, hätte der Welt nichts gegeben und dem Spiel eine Klasse mehr zu warten.

   Kartenlegende wie in courses.js. Winkel in Grad, Zeiten in Sekunden, Koordinaten in Kacheln.
   Beim Pendel gilt: phase 1.5708 (= 90°) lässt die Stange nach unten hängen, amp ist der Ausschlag
   im Bogenmaß, speed = 2π / Takt. */
const CLOCK_COURSES = [
  {
    name: 'Marktplatz', par: 2, theme: 'clocktown', maxStrokes: 12,
    intro: 'Der Platz unter der Stadtuhr, Takt 4 Sekunden. Ein einziges Pendel streicht über das Pflaster – warte, bis es zur Seite ausschwingt, und schieb den Ball darunter durch.',
    map: [
      '..........................',
      '....##################....',
      '..######################..',
      '..######################..',
      '..T#####################..',
      '..#####################H..',
      '..######################..',
      '..######################..',
      '....##################....',
      '..........................',
    ],
    obstacles: [
      { type: 'rotor', x: 13, y: 1.2, blades: 1, len: 4.2, thick: 0.16, hubR: 0.4, style: 'pendel',
        phase: 1.5708, swing: { amp: 0.85, speed: 1.5708 } },
    ],
    decor: [
      { t: 'clock', x: 13, y: 0.4, s: 2.4 },
      { t: 'lantern', x: 4.5, y: 1.6 }, { t: 'lantern', x: 21.5, y: 1.6 },
      { t: 'lantern', x: 4.5, y: 8.4 }, { t: 'lantern', x: 21.5, y: 8.4 },
      { t: 'barrel', x: 1.2, y: 5.5 }, { t: 'crate', x: 24.6, y: 3.4 },
      { t: 'gearFlat', x: 8.5, y: 0.5, s: 1.4, speed: 0.4, seed: 0.2 },
      { t: 'gearFlat', x: 17.5, y: 0.5, s: 1.3, speed: -0.5, seed: 0.7 },
    ],
    autoDecor: { density: 0.14, seed: 71 },
  },
  {
    name: 'Zeigergasse', par: 3, theme: 'clocktown', maxStrokes: 14,
    intro: 'Zwei große Zeiger drehen sich gegenläufig über der Gasse, Takt 4 Sekunden – einmal herum je Takt, dazwischen ein Tor: zwei Sekunden offen, zwei zu. Der zweite Zeiger nimmt einen langsamen Ball mit und schleudert ihn am Ende der Stange davon; wer mit Schwung kommt, prallt einfach ab. Wer den ersten Zeiger richtig erwischt, hat auch den zweiten.',
    map: [
      '............................',
      '...######################...',
      '...######################...',
      '..T######################...',
      '...######################...',
      '...#####################H...',
      '...######################...',
      '...######################...',
      '............................',
    ],
    obstacles: [
      { type: 'rotor', x: 9.5, y: 4.5, blades: 2, len: 3.2, thick: 0.15, speed: 1.5708, style: 'stone' },
      { type: 'hand', x: 18.5, y: 4.5, len: 3.2, thick: 0.16, speed: -1.5708, phase: 1.5708, schub: 1.6, fang: 5 },
      { type: 'gate', x: 14, y: 4.5, w: 0.32, h: 3.6, period: 4, open: 0.5, phase: 0.25, axis: 'y' },
    ],
    decor: [
      { t: 'clock', x: 6.5, y: 0.4, s: 1.8 }, { t: 'clock', x: 21.5, y: 0.4, s: 1.8 },
      { t: 'lantern', x: 14, y: 0.5 }, { t: 'lantern', x: 14, y: 8.4 },
      { t: 'pipe', x: 1.4, y: 2.5, s: 1.2, seed: 0.3 }, { t: 'pipe', x: 26.4, y: 6.5, s: 1.1, seed: 0.8 },
      { t: 'weight', x: 2.4, y: 7.6, seed: 0.2 }, { t: 'weight', x: 25.6, y: 1.6, seed: 0.65 },
    ],
    autoDecor: { density: 0.13, seed: 73 },
  },
  {
    name: 'Dampfgasse', par: 3, theme: 'clocktown', maxStrokes: 16,
    intro: 'Takt 3 Sekunden. Das erste Ventil bläst quer über die Gasse und drückt jeden Ball an die Mauer, der zur falschen Zeit rollt. Das zweite bläst um die Ecke – das ist keine Falle, das ist die Abkürzung.',
    map: [
      '..............................',
      '..########....................',
      '..T#######....................',
      '..########....................',
      '.....#####....................',
      '.....#####....................',
      '.....##############...........',
      '.....##############...........',
      '.....##############...........',
      '..............#####...........',
      '..............#####...........',
      '..........#############.......',
      '..........######H######.......',
      '..........#############.......',
      '..............................',
    ],
    obstacles: [
      // quer über den ersten Schenkel: wer zum falschen Takt kommt, wird nach unten weggedrückt
      { type: 'field', x: 5, y: 1, w: 4.5, h: 3, fx: 0, fy: 7, style: 'steam', gust: 2.0944 },
      // in der Ecke: schiebt den Ball nach rechts in den langen Schenkel
      { type: 'field', x: 5.2, y: 6.2, w: 3.6, h: 2.6, fx: 7.5, fy: 0, style: 'steam', gust: 2.0944, phase: 3.1416 },
      // vor dem Loch: bremst den Anlauf, damit der letzte Schlag gelegt und nicht gedroschen wird
      { type: 'bumper', x: 16, y: 10, r: 0.5, style: 'feder' },
    ],
    decor: [
      { t: 'pipe', x: 4.3, y: 0.6, s: 1.4, seed: 0.2 }, { t: 'pipe', x: 10.3, y: 0.6, s: 1.2, seed: 0.5 },
      { t: 'pipe', x: 4.3, y: 9.4, s: 1.3, seed: 0.8 }, { t: 'pipe', x: 20.4, y: 6.4, s: 1.2, seed: 0.35 },
      { t: 'lantern', x: 12.5, y: 5.5 }, { t: 'lantern', x: 23.5, y: 12.5 },
      { t: 'barrel', x: 1.3, y: 3.5 }, { t: 'crate', x: 8.5, y: 10.5 },
      { t: 'gear', x: 25.5, y: 9.5, s: 1.3, seed: 0.4 },
    ],
    autoDecor: { density: 0.13, seed: 77 },
  },
  {
    name: 'Zahnradbrücke', par: 5, theme: 'clocktown', maxStrokes: 20,
    intro: 'Der Stadtkanal, Takt 5 Sekunden. Zwei Zahnradfähren pendeln versetzt hinüber: Die erste wartet, wenn die zweite fährt. Drüben streicht ein Pendel über den Anleger – erst aufsteigen, dann durchschlüpfen.',
    map: [
      '..............................',
      '..#########wwww###############',
      '..#########wwww###############',
      '..T########wwww###############',
      '..#########wwww###############',
      '..#########wwww###############',
      '..#########wwww#####wwww######',
      '..#########wwww#####wwww######',
      '..#########wwww#####wwww##H###',
      '..#########wwww#####wwww######',
      '..#########wwww###############',
      '..............................',
    ],
    obstacles: [
      { type: 'rail', y: 3.5, x0: 10, x1: 16 },
      { type: 'ferry', x0: 10.5, y0: 3.5, x1: 15.5, y1: 3.5, w: 1.2, h: 1.2, wait: 1.8, travel: 2.5, style: 'cart' },
      { type: 'rail', y: 7.5, x0: 19, x1: 25 },
      { type: 'ferry', x0: 19.5, y0: 7.5, x1: 24.5, y1: 7.5, w: 1.2, h: 1.2, wait: 1.8, travel: 2.5, phase: 0.5, style: 'cart' },
      { type: 'rotor', x: 27.5, y: 4.6, blades: 1, len: 3, thick: 0.15, hubR: 0.35, style: 'pendel',
        phase: 1.5708, swing: { amp: 0.7, speed: 1.2566 } },
    ],
    decor: [
      { t: 'gear', x: 9.2, y: 0.6, s: 1.6, seed: 0.25 }, { t: 'gear', x: 15.8, y: 0.6, s: 1.6, seed: 0.75 },
      { t: 'gear', x: 18.2, y: 10.4, s: 1.4, seed: 0.4 }, { t: 'gear', x: 25.4, y: 10.4, s: 1.4, seed: 0.9 },
      { t: 'bollard', x: 9.4, y: 5.5 }, { t: 'bollard', x: 16.4, y: 5.5 },
      { t: 'lantern', x: 9.4, y: 1.5 }, { t: 'lantern', x: 16.4, y: 9.5 },
      { t: 'clock', x: 22, y: 0.4, s: 2 },
    ],
    autoDecor: { density: 0.16, seed: 79 },
  },
  {
    name: 'Glockenturm', par: 4, theme: 'clocktown', maxStrokes: 20,
    intro: 'Im Turmstuhl, Takt 6 Sekunden. Eine Wand teilt die Kammer, nur zwei Läden führen hindurch – und sie öffnen gegengleich: Ist der obere offen, ist der untere zu. In jeder Hälfte gleitet ein Laufgewicht quer durch den Weg – die Glocken hängen darüber im Stuhl.',
    map: [
      '..............................',
      '..############x#############..',
      '..############################',
      '..T###########x#############..',
      '..############x#############..',
      '..############x#############..',
      '..############x#############..',
      '..############x#############..',
      '..############################',
      '..############x#############..',
      '..############x######H######..',
      '..############x#############..',
      '..............................',
    ],
    obstacles: [
      // Die beiden Läden sitzen in den Durchlässen und laufen im selben Takt, aber gegengleich
      { type: 'gate', x: 14.5, y: 2.5, w: 0.32, h: 1.1, period: 6, open: 0.45, phase: 0, axis: 'y' },
      { type: 'gate', x: 14.5, y: 8.5, w: 0.32, h: 1.1, period: 6, open: 0.45, phase: 0.5, axis: 'y' },
      // je Hälfte ein Laufgewicht, das quer durch den Weg gleitet
      { type: 'mover', x0: 8.5, y0: 1.5, x1: 8.5, y1: 10.5, w: 1.3, h: 1.3, period: 6, style: 'cart' },
      { type: 'mover', x0: 20.5, y0: 10.5, x1: 20.5, y1: 1.5, w: 1.3, h: 1.3, period: 6, phase: 0.5, style: 'cart' },
    ],
    decor: [
      { t: 'bell', x: 5.5, y: 0.5, s: 1.5, seed: 0.2 }, { t: 'bell', x: 11.5, y: 0.5, s: 1.4, seed: 0.55 },
      { t: 'bell', x: 20.5, y: 0.5, s: 1.5, seed: 0.85 },
      { t: 'weight', x: 1.3, y: 6.5, seed: 0.1 }, { t: 'weight', x: 28.6, y: 4.5, seed: 0.6 },
      { t: 'lantern', x: 16.5, y: 5.5 }, { t: 'lantern', x: 12.5, y: 5.5 },
      { t: 'gearFlat', x: 24.6, y: 8.5, s: 1.8, speed: -0.35, seed: 0.3 },
    ],
    autoDecor: { density: 0.16, seed: 83 },
  },
  {
    name: 'Rohrpost', par: 4, theme: 'boiler', maxStrokes: 20,
    intro: 'Im Kesselhaus, Takt 4 Sekunden. Die Wand hat kein Tor – hinüber führen nur die beiden Rohre, und beide setzen einen weit weg vom Loch ab: das blaue oben links, das rote unten rechts. Vor den Öffnungen bläst je ein Ventil, aber nie beide zugleich, und über dem Loch dreht sich ein Rad.',
    map: [
      '..............................',
      '..###########x##############..',
      '..T##########x##############..',
      '..###########x##############..',
      '..#####lll###x##############..',
      '..#####lll###x######H#######..',
      '..#####lll###x##############..',
      '..###########x##############..',
      '..###########x##############..',
      '..###########x##############..',
      '..............................',
    ],
    obstacles: [
      // Beide Rohre setzen in einer Ecke ab, nicht am Loch – sonst waere die Bahn nach einem Schlag vorbei
      { type: 'portal', x: 4.5, y: 2.5, tx: 15.5, ty: 1.5, color: '#4fd0ff' },
      { type: 'portal', x: 4.5, y: 7.5, tx: 27.5, ty: 9.5, color: '#ff7a4f' },
      // die beiden Ventile blasen abwechselnd: phase 0 gegen phase π
      { type: 'field', x: 3, y: 3.4, w: 3, h: 2.2, fx: 0, fy: -7, style: 'steam', gust: 1.5708 },
      { type: 'field', x: 3, y: 5.6, w: 3, h: 2.2, fx: 0, fy: 7, style: 'steam', gust: 1.5708, phase: 3.1416 },
      // das Rad ueber dem Loch dreht sich einmal je Takt – zwischen seinen Armen muss der Ball hindurch
      { type: 'rotor', x: 20.5, y: 3.4, blades: 3, len: 1.8, thick: 0.15, speed: 1.5708, style: 'stone' },
      { type: 'bumper', x: 25.5, y: 5.5, r: 0.5, style: 'feder' },
    ],
    decor: [
      { t: 'pipe', x: 4.4, y: 0.6, s: 1.5, seed: 0.15 }, { t: 'pipe', x: 9.4, y: 0.6, s: 1.3, seed: 0.45 },
      { t: 'pipe', x: 17.4, y: 0.6, s: 1.4, seed: 0.7 }, { t: 'pipe', x: 24.4, y: 0.6, s: 1.3, seed: 0.9 },
      { t: 'barrel', x: 1.3, y: 8.5 }, { t: 'crate', x: 28.5, y: 8.5 }, { t: 'crate', x: 7.5, y: 9.5 },
      { t: 'brazier', x: 8.5, y: 1.5 }, { t: 'gear', x: 28.5, y: 2.5, s: 1.4, seed: 0.5 },
    ],
    autoDecor: { density: 0.16, seed: 89 },
  },
  {
    name: 'Federwerk', par: 4, theme: 'boiler', maxStrokes: 20,
    intro: 'Die Federkammer, Takt 3 Sekunden. Sechs Spannfedern werfen den Ball zurück, zwei Pendel streichen gegengleich durch die Mitte. Hier hilft kein harter Schlag – hier hilft der richtige Winkel.',
    map: [
      '..............................',
      '..######################......',
      '..######################......',
      '..T#####################......',
      '..######################......',
      '..######################......',
      '..######################......',
      '..######################......',
      '..#####sss######sss#####......',
      '..#####sss######sss#####......',
      '..###################H##......',
      '..######################......',
      '..............................',
    ],
    obstacles: [
      { type: 'rotor', x: 9, y: 1.4, blades: 1, len: 3.4, thick: 0.15, hubR: 0.35, style: 'pendel',
        phase: 1.5708, swing: { amp: 0.8, speed: 2.0944 } },
      { type: 'rotor', x: 16.5, y: 1.4, blades: 1, len: 3.4, thick: 0.15, hubR: 0.35, style: 'pendel',
        phase: 1.5708, swing: { amp: -0.8, speed: 2.0944 } },
      { type: 'bumper', x: 5.5, y: 5.5, r: 0.55, style: 'feder' }, { type: 'bumper', x: 12.5, y: 4.5, r: 0.6, style: 'feder' },
      { type: 'bumper', x: 19.5, y: 5.5, r: 0.55, style: 'feder' }, { type: 'bumper', x: 8.5, y: 7.5, r: 0.5, style: 'feder' },
      { type: 'bumper', x: 15.5, y: 7.5, r: 0.5, style: 'feder' }, { type: 'bumper', x: 21.5, y: 8.5, r: 0.5, style: 'feder' },
      /* Das Loch liegt in einer Tasche: links und oben zu, offen bleibt nur der Schlitz bei x 22–23.
         Ohne sie war die Kammer ein Raum mit Federn darin, und der Ball rollte quer hindurch. */
      { type: 'wall', x0: 20, y0: 9.6, x1: 20, y1: 12, extend: 0, h: 0.7 },
      { type: 'wall', x0: 20, y0: 9.6, x1: 22, y1: 9.6, extend: 0, h: 0.7 },
    ],
    decor: [
      { t: 'gear', x: 1.3, y: 2.5, s: 1.5, seed: 0.2 }, { t: 'gear', x: 24.6, y: 3.5, s: 1.5, seed: 0.6 },
      { t: 'gearFlat', x: 12.7, y: 0.5, s: 2.2, speed: 0.5, seed: 0.4 },
      { t: 'pipe', x: 5.4, y: 0.6, s: 1.3, seed: 0.25 }, { t: 'pipe', x: 20.4, y: 0.6, s: 1.2, seed: 0.85 },
      { t: 'brazier', x: 1.3, y: 9.5 }, { t: 'barrel', x: 24.5, y: 9.5 },
      { t: 'weight', x: 24.4, y: 6.5, seed: 0.35 },
    ],
    autoDecor: { density: 0.16, seed: 97 },
  },
  {
    name: 'Kesselhaus', par: 5, theme: 'boiler', maxStrokes: 24,
    intro: 'Über der Glut, Takt 5 Sekunden. Ein Zahnradaufzug trägt über die erste Rinne, ein Drehteller wirft nach oben aus, und über der zweiten Rinne schlägt ein Dampfkolben aus der Wand. Alles drei hängt zusammen – wer den Aufzug richtig erwischt, ist auch am Kolben vorbei, bevor er kommt.',
    map: [
      '..............................',
      '..###########lll##############',
      '..###########lll##############',
      '..T##########lll##############',
      '..###########lll##############',
      '..###########lll##############',
      '..###########lll##############',
      '..######################lll###',
      '..######################lll###',
      '..###################lllll#H##',
      '..######################lll###',
      '..###########lll##############',
      '..............................',
    ],
    obstacles: [
      { type: 'rail', y: 3.5, x0: 11, x1: 18 },
      { type: 'ferry', x0: 11.5, y0: 3.5, x1: 17.5, y1: 3.5, w: 1.2, h: 1.2, wait: 1.9, travel: 2.6, style: 'cart' },
      { type: 'turntable', x: 20.5, y: 4.5, r: 1.6, speed: 1.2566, exit: -90 },
      { type: 'piston', x: 22.6, y: 6.5, w: 1.2, h: 1.4, angle: 0, hub: 3, period: 5, phase: 0.15 },
      { type: 'bumper', x: 20.5, y: 10.5, r: 0.5, style: 'feder' },
    ],
    decor: [
      { t: 'brazier', x: 12.5, y: 0.5 }, { t: 'brazier', x: 14.5, y: 11.5 },
      { t: 'pipe', x: 10.4, y: 0.6, s: 1.4, seed: 0.3 }, { t: 'pipe', x: 18.4, y: 0.6, s: 1.4, seed: 0.7 },
      { t: 'pipe', x: 25.4, y: 3.5, s: 1.3, seed: 0.5 },
      { t: 'gear', x: 1.3, y: 6.5, s: 1.6, seed: 0.15 }, { t: 'gear', x: 28.6, y: 6.5, s: 1.5, seed: 0.8 },
      { t: 'barrel', x: 6.5, y: 9.5 }, { t: 'crate', x: 4.5, y: 10.5 },
      { t: 'weight', x: 8.4, y: 1.6, seed: 0.55 },
    ],
    autoDecor: { density: 0.16, seed: 101 },
  },
  {
    name: 'Der große Turm', par: 6, theme: 'clocktown', maxStrokes: 30, hStep: 0.45,
    intro: 'Die Schlussbahn, Takt 6 Sekunden. Zwei Schöpfräder stehen vor den Stufen und drehen sich. Spiel den Ball in eine Zahnlücke am Fuß des Rades: Dann fährt er außen mit hinauf, und oben wirft ihn das Rad über die Wand. Gegen einen Zahn prallt er ab und muss auf die nächste Lücke warten. Oben ein Pendel, dann durch das Turmtor.',
    map: [
      '..................................',
      '..############....................',
      '..T###########....................',
      '..############....................',
      '..############....................',
      '.....#########################....',
      '.....#########################....',
      '.....#########################....',
      '.....#########################....',
      '..................................',
      '..................................',
    ],
    heights: [
      '..................................',
      '..000000000000....................',
      '..000000000000....................',
      '..000000000000....................',
      '..000000000000....................',
      '.....11111111222222222222222......',
      '.....11111111222222222222222......',
      '.....11111111222222222222222......',
      '.....11111111222222222222222......',
      '..................................',
      '..................................',
    ],
    obstacles: [
      /* Zwei Aufzüge statt zweier Rampen: Auf so engem Raum bekommt man den Anlauf für eine Rampe
         nicht zusammen – der Bot lief hier in sechs von sechs Runden ins Schlaglimit. Der Aufzug
         nimmt einen ruhenden Ball mit, verlangt dafür aber den richtigen Augenblick. */
      { type: 'gearlift', x: 6.5, y: 4.6, r: 1.8, angle: 90, speed: 1.0472, zaehne: 8 },
      { type: 'gearlift', x: 12.6, y: 6.5, r: 1.8, angle: 0, speed: 1.0472, zaehne: 8, phase: 0.5 },
      { type: 'rotor', x: 19, y: 5.4, blades: 1, len: 2.6, thick: 0.14, hubR: 0.32, style: 'pendel',
        phase: 1.5708, swing: { amp: 0.75, speed: 1.0472 } },
      { type: 'door', x: 28.5, y: 6.5, r: 0.7, s: 3.6 },
    ],
    decor: [
      { t: 'clock', x: 28.5, y: 3.2, s: 3 },
      { t: 'obelisk', x: 32, y: 2.5, s: 1.4 }, { t: 'pipe', x: 1.2, y: 8.5, s: 1.4, seed: 0.4 },
      { t: 'lantern', x: 4.4, y: 2.5 }, { t: 'lantern', x: 4.4, y: 8.4 }, { t: 'lantern', x: 26.5, y: 9.4 },
      { t: 'gear', x: 15.5, y: 9.5, s: 1.5, seed: 0.3 }, { t: 'gear', x: 22.5, y: 9.5, s: 1.4, seed: 0.7 },
      { t: 'weight', x: 26.4, y: 4.6, seed: 0.4 }, { t: 'bell', x: 24.5, y: 0.6, s: 1.4, seed: 0.5 },
    ],
    autoDecor: { density: 0.16, seed: 103 },
    inner: {
      name: 'Turmkammer', theme: 'escapement', look: { x: 8.5, y: 5.5 },
      intro: 'Die Hemmung: zwei Pendel, spiegelbildlich zueinander – schlägt das eine nach links, schlägt das andere nach rechts. Dahinter dreht sich der große Zeiger einmal je Takt: Er nimmt einen langsamen Ball mit, schiebt ihn nach außen und schleudert ihn am Ende der Stange davon.',
      map: [
        '....................',
        '..T###############..',
        '..################..',
        '..################..',
        '..################..',
        '..################..',
        '..############H###..',
        '..################..',
        '..################..',
        '....................',
      ],
      obstacles: [
        { type: 'rotor', x: 6, y: 1.4, blades: 1, len: 3.2, thick: 0.16, hubR: 0.35, style: 'pendel',
          phase: 1.5708, swing: { amp: 0.9, speed: 1.0472 } },
        { type: 'rotor', x: 13, y: 1.4, blades: 1, len: 3.2, thick: 0.16, hubR: 0.35, style: 'pendel',
          phase: 1.5708, swing: { amp: -0.9, speed: 1.0472 } },
        // Das grosse Rad nimmt einen langsamen Ball mit und wirft ihn an der Rinne zum Loch aus
        { type: 'hand', x: 9.5, y: 6.5, len: 2.6, thick: 0.17, speed: 1.0472, schub: 1.4, fang: 5 },
      ],
      decor: [
        { t: 'gearFlat', x: 4.5, y: 4.5, s: 2.2, speed: 0.35, seed: 0.2 },
        { t: 'gearFlat', x: 15.5, y: 3.5, s: 2, speed: -0.4, seed: 0.6 },
        { t: 'gearFlat', x: 9.5, y: 8.6, s: 2.6, speed: 0.3, seed: 0.8 },
        { t: 'clock', x: 10, y: 0.3, s: 2.6 },
        { t: 'weight', x: 1.4, y: 6.5, seed: 0.25 }, { t: 'weight', x: 18.5, y: 6.5, seed: 0.75 },
        { t: 'lantern', x: 1.4, y: 2.5 }, { t: 'lantern', x: 18.5, y: 2.5 },
      ],
      autoDecor: { density: 0.14, seed: 107 },
    },
  },
];
