/* Schattenreich: Stufe „Legende“ – neun extra große Bahnen im Reich der Schatten: Friedhöfe, Schattenfeuer,
   Falltüren, Schattenzonen (der Ball wird unsichtbar), Geister, Fledermäuse, Sensen, Seelenlichter,
   Schattenspiegel; die Neunte führt in den Thronsaal mit eigener Innen-Map. */
const SHADOW_COURSES = [
  {
    name: 'Friedhofspforte', par: 4, theme: 'shadow', maxStrokes: 18, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 10, h: 3, look: { x: 13, y: 3 } }, { x: 12, y: 2, w: 3, h: 5, look: { x: 13, y: 8 } }],
    map: [
      '....................................',
      '....................................',
      '..#############.....................',
      '..#T###########.....................',
      '..#############.....................',
      '............###.....................',
      '............###.....................',
      '............######################..',
      '............###################H##..',
      '............######################..',
      '....................................',
      '....................................',
    ],
    intro: 'Durch das Friedhofstor ins Schattenreich. Grabsteine federn den Ball zurück, an der Kehre schwingt eine Sense, und vor dem Loch schwebt ein Geist über den Weg, der alles wegschiebt, was er berührt.',
    obstacles: [
      { type: 'bumper', x: 6.5, y: 2.6, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 9.5, y: 4.4, r: 0.4, style: 'grave', kick: 7 },
      { type: 'rotor', x: 13, y: 5.5, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.7 }, phase: 0, height: 0.5 },
      { type: 'wall', x0: 12, y0: 2, x1: 14, y1: 2, extend: 0 },
      { type: 'wall', x0: 15, y0: 3, x1: 15, y1: 5, extend: 0 },
      { type: 'wall', x0: 12, y0: 8, x1: 14, y1: 10, extend: 0 },
      { type: 'mover', x0: 20, y0: 7.5, x1: 28, y1: 8.5, w: 0.9, h: 0.9, period: 6, style: 'ghost', e: 0.5 },
      { type: 'bumper', x: 24.5, y: 9.4, r: 0.38, style: 'grave', kick: 7 },
      { type: 'wall', x0: 34, y0: 7, x1: 35, y1: 8, extend: 0 },
      { type: 'wall', x0: 35, y0: 9, x1: 34, y1: 10, extend: 0 },
    ],
    decor: [
      { t: 'gravestone', x: 1.4, y: 1.4, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 5.5, y: 1.2, s: 1.2 }, { t: 'deadTree', x: 9.5, y: 0.8, s: 1.5 }, { t: 'ghostlight', x: 8.5, y: 5.6, s: 1.2, seed: 0.3 },
      { t: 'gravestone', x: 16.5, y: 6.4, s: 1.2, seed: 0.7 }, { t: 'gravestone', x: 20.5, y: 10.5, s: 1.2, seed: 0.2 }, { t: 'deadTree', x: 27, y: 5.4, s: 1.6 }, { t: 'ghostlight', x: 33.6, y: 6.4, s: 1.2, seed: 0.8 },
      { t: 'gravecross', x: 30.5, y: 10.6, s: 1.2 }, { t: 'bones', x: 11, y: 10.6, s: 1.2 }, { t: 'skull', x: 3.5, y: 5.4 }, { t: 'obsidian', x: 35.4, y: 10.8, s: 1.2 },
    ],
    autoDecor: { density: 0.18, seed: 501 },
  },
  {
    name: 'Irrlichtsumpf', par: 6, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 34, h: 10, look: { x: 33, y: 6.5 } }],
    map: [
      '......................................',
      '......................................',
      '..######www#########www#######www###..',
      '..######www#########www#######www###..',
      '..######www#########www#############..',
      '..############www#########www#######..',
      '..#T##########www#########www####H##..',
      '..############www#########www#######..',
      '..############www###################..',
      '..######www#########wwww############..',
      '..######www#########wwww######www###..',
      '..######www#########wwww######www###..',
      '......................................',
      '......................................',
    ],
    intro: 'Ein weites Moor voller Schattenwasser. Seelenlichter locken den Ball an – und genau neben ihnen liegen die Tümpel. In der Mitte schluckt eine Schattenzone den Ball: Dort rollt er unsichtbar weiter.',
    obstacles: [
      { type: 'magnet', x: 11.5, y: 6.5, r: 3.2, strength: 10, style: 'soul' },
      { type: 'magnet', x: 24.5, y: 6.5, r: 3.0, strength: 10, style: 'soul' },
      { type: 'field', x: 17, y: 3, w: 4, h: 8, fx: 0, fy: 0, style: 'dark' },
      { type: 'mover', x0: 27.5, y0: 3.5, x1: 27.5, y1: 10, w: 0.6, h: 0.6, period: 4, style: 'bat', e: 0.7 },
      { type: 'bumper', x: 29.5, y: 6.5, r: 0.38, style: 'grave', kick: 7 },
      { type: 'bumper', x: 5.5, y: 9.5, r: 0.38, style: 'grave', kick: 7 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.2, s: 1.6 }, { t: 'deadTree', x: 13.5, y: 0.8, s: 1.5 }, { t: 'deadTree', x: 25, y: 12.8, s: 1.6 }, { t: 'deadTree', x: 36.6, y: 1.4, s: 1.5 },
      { t: 'ghostlight', x: 9.5, y: 6.5, s: 1.1, seed: 0.2 }, { t: 'ghostlight', x: 15.5, y: 12.6, s: 1.1, seed: 0.6 }, { t: 'ghostlight', x: 28.5, y: 0.8, s: 1.1, seed: 0.9 },
      { t: 'gravestone', x: 4.5, y: 12.6, s: 1.2, seed: 0.5 }, { t: 'gravecross', x: 36.6, y: 12.6, s: 1.2 }, { t: 'bones', x: 19.5, y: 12.6, s: 1.2 }, { t: 'skull', x: 1.4, y: 8.5 },
    ],
    autoDecor: { density: 0.18, seed: 503 },
  },
  {
    name: 'Falltürgang', par: 6, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 23, h: 3, look: { x: 26, y: 3 } }, { x: 25, y: 2, w: 3, h: 3, look: { x: 26, y: 7 } }],
    map: [
      '........................................',
      '........................................',
      '..##########################............',
      '..#T########################............',
      '..##########################............',
      '.........................#############..',
      '.........................##########H##..',
      '.........................#############..',
      '........................................',
      '........................................',
    ],
    intro: 'Vier Falltüren im Gruftgang, jede klappt zu ihrer eigenen Zeit auf. Zu ist die Platte fester Boden, offen wartet der Schacht – wer zum falschen Moment darüberrollt oder darauf liegen bleibt, stürzt in die Gruft.',
    obstacles: [
      { type: 'trapdoor', x: 8, y: 3.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0 },
      { type: 'trapdoor', x: 13, y: 3.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.3 },
      { type: 'trapdoor', x: 18, y: 3.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.6 },
      { type: 'trapdoor', x: 23, y: 3.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.9 },
      { type: 'wall', x0: 26, y0: 2, x1: 28, y1: 4, extend: 0 },
      { type: 'wall', x0: 25, y0: 8, x1: 27, y1: 6, extend: 0 },
      { type: 'rotor', x: 31.5, y: 6, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.6, speed: 1.6 }, phase: Math.PI / 2, height: 0.5 },
      { type: 'wall', x0: 37, y0: 5, x1: 38, y1: 6, extend: 0 },
      { type: 'wall', x0: 38, y0: 7, x1: 37, y1: 8, extend: 0 },
    ],
    decor: [
      { t: 'torchPurple', x: 5.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 15.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 10.5, y: 5.6, s: 1.1 }, { t: 'torchPurple', x: 20.5, y: 5.6, s: 1.1 },
      { t: 'skull', x: 3.5, y: 5.5 }, { t: 'bones', x: 16.5, y: 5.6, s: 1.2 }, { t: 'pillar', x: 28.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 28.6, y: 8.6, s: 1.1 }, { t: 'urnDark', x: 38.6, y: 4.4, s: 1.1 }, { t: 'gravestone', x: 33.5, y: 8.6, s: 1.2, seed: 0.4 },
    ],
    autoDecor: { density: 0.17, seed: 505 },
  },
  {
    name: 'Schattenspiegel', par: 4, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 12, h: 12, look: { x: 8, y: 3.5 } }],
    map: [
      '....................................',
      '....................................',
      '..############......................',
      '..############........############..',
      '..############........############..',
      '..############........#########H##..',
      '..############........############..',
      '..#T##########........############..',
      '..############........#####lll####..',
      '..############........#####lll####..',
      '..############........#####lll####..',
      '..############........############..',
      '..############........############..',
      '..############......................',
      '....................................',
      '....................................',
    ],
    intro: 'Kein Weg führt hinüber – nur drei Schattenspiegel. Einer setzt den Ball vor dem Loch ab, einer mitten ins Schattenfeuer, einer wirft ihn zurück zum Anfang. Drüben flattern Fledermäuse durch den Saal.',
    obstacles: [
      { type: 'portal', x: 8.5, y: 3.5, tx: 24.5, ty: 10.5, color: '#c58bff' },
      { type: 'portal', x: 11.5, y: 8.5, tx: 28, ty: 9, color: '#c58bff' },
      { type: 'portal', x: 6.5, y: 12.5, tx: 3.5, ty: 3.5, color: '#c58bff' },
      { type: 'bumper', x: 7.5, y: 8.0, r: 0.4, style: 'eye', kick: 7 },
      { type: 'mover', x0: 23, y0: 5, x1: 32, y1: 6.5, w: 0.6, h: 0.6, period: 4.5, style: 'bat', e: 0.7 },
      { type: 'mover', x0: 32, y0: 11, x1: 23, y1: 12, w: 0.6, h: 0.6, period: 5.5, phase: 0.4, style: 'bat', e: 0.7 },
      { type: 'bumper', x: 27.5, y: 5.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'wall', x0: 33, y0: 3, x1: 34, y1: 4, extend: 0 },
      { type: 'wall', x0: 34, y0: 12, x1: 33, y1: 13, extend: 0 },
    ],
    decor: [
      { t: 'pillar', x: 1.4, y: 1.4, s: 1.1 }, { t: 'pillar', x: 14.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 1.4, y: 14.6, s: 1.1 }, { t: 'pillar', x: 14.6, y: 14.6, s: 1.1 },
      { t: 'deadTree', x: 18, y: 4, s: 1.6 }, { t: 'deadTree', x: 18, y: 12, s: 1.5 }, { t: 'ghostlight', x: 17.5, y: 8, s: 1.2, seed: 0.5 },
      { t: 'torchPurple', x: 21.4, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 34.6, y: 2.4, s: 1.1 }, { t: 'torchPurple', x: 21.4, y: 13.6, s: 1.1 }, { t: 'torchPurple', x: 34.6, y: 13.6, s: 1.1 }, { t: 'skull', x: 25.5, y: 13.5 }, { t: 'urnDark', x: 22.6, y: 8.6, s: 1.0 },
    ],
    autoDecor: { density: 0.16, seed: 507 },
  },
  {
    name: 'Knochenbrücke', par: 6, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 3, w: 6, h: 6, look: { x: 20, y: 5.5 } }, { x: 8, y: 5, w: 14, h: 2, look: { x: 24, y: 5.5 } }, { x: 22, y: 2, w: 6, h: 8, look: { x: 38, y: 5.5 } }, { x: 28, y: 5, w: 8, h: 2, look: { x: 39, y: 5.5 } }],
    map: [
      '............................................',
      '............................................',
      '......................######................',
      '..######llllllllllllll######llllllll######..',
      '..######llllllllllllll######llllllll######..',
      '..#T####oooooooooooooo######oooooooo###H##..',
      '..######oooooooooooooo######oooooooo######..',
      '..######llllllllllllll######llllllll######..',
      '..######llllllllllllll######llllllll######..',
      '......................######................',
      '............................................',
      '............................................',
    ],
    intro: 'Eine Brücke aus Knochen ohne Geländer über einen Strom aus Schattenfeuer. Mitten auf der Brücke fahren Knochenstacheln aus dem Boden, auf der Felsinsel schwingt eine Sense, und der zweite Steg ist kürzer, aber schmal.',
    obstacles: [
      { type: 'spikes', x: 14.5, y: 6, w: 1, h: 2, period: 4.4, up: 0.36, phase: 0 },
      { type: 'spikes', x: 18.5, y: 6, w: 1, h: 2, period: 4.4, up: 0.36, phase: 0.1 },
      { type: 'rotor', x: 24.5, y: 5.5, blades: 1, len: 1.8, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.2, speed: 1.5 }, phase: 0, height: 0.5 },
      { type: 'bumper', x: 26.5, y: 2.8, r: 0.38, style: 'grave', kick: 7 },
      { type: 'bumper', x: 26.5, y: 8.2, r: 0.38, style: 'grave', kick: 7 },
      { type: 'spikes', x: 32.5, y: 6, w: 1, h: 2, period: 4, up: 0.36, phase: 0.5 },
      { type: 'wall', x0: 41, y0: 3, x1: 42, y1: 4, extend: 0 },
      { type: 'wall', x0: 42, y0: 8, x1: 41, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.6, s: 1.6 }, { t: 'gravestone', x: 5.5, y: 1.6, s: 1.2, seed: 0.4 }, { t: 'skull', x: 2.4, y: 9.6 }, { t: 'bones', x: 10, y: 1.6, s: 1.3 }, { t: 'bones', x: 16, y: 10.4, s: 1.3 },
      { t: 'pillar', x: 21.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 27.6, y: 10.6, s: 1.1 }, { t: 'skull', x: 30.5, y: 1.6 }, { t: 'bones', x: 33, y: 10.4, s: 1.2 }, { t: 'deadTree', x: 42.6, y: 1.6, s: 1.5 }, { t: 'ghostlight', x: 38.5, y: 10.6, s: 1.1, seed: 0.7 },
    ],
    autoDecor: { density: 0.13, seed: 509 },
  },
  {
    name: 'Geisterreigen', par: 6, theme: 'shadow', maxStrokes: 24, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 4, w: 26, h: 18, look: { x: 14.5, y: 2.5 } }],
    map: [
      '..............................',
      '............######............',
      '............##H###............',
      '............######............',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##########################..',
      '..##T#######################..',
      '..##########################..',
      '..##########################..',
      '..............................',
      '..............................',
    ],
    intro: 'Auf dem großen Platz tanzen drei Geister ihren Reigen. In der Mitte liegt eine Schattenzone, in der der Ball unsichtbar rollt, und ein Schattenstrudel schleudert langsame Bälle nach Osten. Das Loch liegt in einer Nische im Norden, zwei Grabsteine bewachen den Eingang.',
    obstacles: [
      { type: 'mover', x0: 4, y0: 8, x1: 25, y1: 8, w: 1.0, h: 1.0, period: 8, style: 'ghost', e: 0.5 },
      { type: 'mover', x0: 25, y0: 14, x1: 4, y1: 14, w: 1.0, h: 1.0, period: 9, phase: 0.4, style: 'ghost', e: 0.5 },
      { type: 'mover', x0: 8, y0: 20, x1: 21, y1: 6, w: 1.0, h: 1.0, period: 11, phase: 0.7, style: 'ghost', e: 0.5 },
      { type: 'field', x: 11, y: 10, w: 8, h: 5, fx: 0, fy: 0, style: 'dark' },
      { type: 'turntable', x: 14.5, y: 12.5, r: 1.6, speed: 1.8, exit: 0, style: 'void', captureSpeed: 8, eject: 7 },
      { type: 'bumper', x: 13.5, y: 5.2, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 15.5, y: 5.2, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 8.5, y: 5.8, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 20.5, y: 5.8, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 5.5, y: 18.5, r: 0.4, style: 'eye', kick: 7 },
      { type: 'bumper', x: 23.5, y: 18.5, r: 0.4, style: 'eye', kick: 7 },
      { type: 'wall', x0: 11, y0: 4, x1: 12, y1: 5, extend: 0 },
      { type: 'wall', x0: 18, y0: 5, x1: 17, y1: 4, extend: 0 },
    ],
    decor: [
      { t: 'pillar', x: 1.4, y: 3.4, s: 1.2 }, { t: 'pillar', x: 28.6, y: 3.4, s: 1.2 }, { t: 'pillar', x: 1.4, y: 22.6, s: 1.2 }, { t: 'pillar', x: 28.6, y: 22.6, s: 1.2 },
      { t: 'gravestone', x: 6, y: 2.4, s: 1.3, seed: 0.3 }, { t: 'gravestone', x: 23, y: 2.4, s: 1.3, seed: 0.8 }, { t: 'deadTree', x: 9.5, y: 0.6, s: 1.6 }, { t: 'deadTree', x: 20, y: 0.6, s: 1.6 },
      { t: 'torchPurple', x: 11.5, y: 0.5, s: 1.1 }, { t: 'torchPurple', x: 17.6, y: 0.5, s: 1.1 }, { t: 'ghostlight', x: 1.2, y: 12, s: 1.2, seed: 0.4 }, { t: 'ghostlight', x: 28.8, y: 12, s: 1.2, seed: 0.9 }, { t: 'skull', x: 14.5, y: 22.6 },
    ],
    autoDecor: { density: 0.16, seed: 511 },
  },
  {
    name: 'Gruftlabyrinth', par: 7, theme: 'shadow', maxStrokes: 26, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 29, h: 3, look: { x: 32, y: 3 } }, { x: 31, y: 2, w: 3, h: 13, look: { x: 32, y: 16 } }, { x: 5, y: 15, w: 26, h: 3, look: { x: 3, y: 16 } }, { x: 2, y: 11, w: 3, h: 7, look: { x: 3, y: 9 } }, { x: 2, y: 8, w: 8, h: 3, look: { x: 11, y: 9 } }, { x: 10, y: 8, w: 3, h: 5, look: { x: 20, y: 11 } }],
    map: [
      '....................................',
      '....................................',
      '..################################..',
      '..#T##############################..',
      '..################################..',
      '...............................###..',
      '..............#############....###..',
      '..............#############....###..',
      '..###########.######H######....###..',
      '..###########.#############....###..',
      '..#########################....###..',
      '..###.....#################....###..',
      '..###.....#################....###..',
      '..###..........................###..',
      '..###..........................###..',
      '..################################..',
      '..################################..',
      '..################################..',
      '....................................',
      '....................................',
    ],
    intro: 'Das Labyrinth der Gruft: einmal außen herum bis zur Druckplatte, die das Steintor zur Grabkammer öffnet – nur für kurze Zeit. Falltüren im Gang, Fledermäuse und eine Schattenzone vor der Kammer.',
    obstacles: [
      { type: 'trapdoor', x: 12, y: 3, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0 },
      { type: 'trapdoor', x: 24, y: 3, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.5 },
      { type: 'wall', x0: 31, y0: 2, x1: 34, y1: 4, extend: 0 },
      { type: 'wall', x0: 34, y0: 16, x1: 32, y1: 18, extend: 0 },
      { type: 'mover', x0: 6, y0: 16, x1: 29, y1: 16, w: 0.6, h: 0.6, period: 7, style: 'bat', e: 0.7 },
      { type: 'trapdoor', x: 16, y: 16, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.25 },
      { type: 'switch', x: 3.5, y: 12.5, r: 0.55, duration: 20, target: 'A' },
      { type: 'wall', x0: 2, y0: 17, x1: 4, y1: 18, extend: 0 },
      { type: 'wall', x0: 2, y0: 9, x1: 4, y1: 8, extend: 0 },
      { type: 'gate', x: 13, y: 11, w: 0.3, h: 2, linked: 'A', liftH: 1.4, barH: 1.0 },
      { type: 'field', x: 14, y: 10, w: 4, h: 3, fx: 0, fy: 0, style: 'dark' },
      { type: 'bumper', x: 20.5, y: 10.5, r: 0.4, style: 'eye', kick: 7 },
      { type: 'rotor', x: 17.5, y: 7.5, blades: 1, len: 1.4, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.6 }, phase: 0, height: 0.5 },
    ],
    decor: [
      { t: 'torchPurple', x: 8.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 20.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 34.6, y: 9.5, s: 1.1 }, { t: 'torchPurple', x: 14.5, y: 18.6, s: 1.1 }, { t: 'torchPurple', x: 1.4, y: 12.5, s: 1.1 },
      { t: 'pillar', x: 8, y: 6.4, s: 1.1 }, { t: 'pillar', x: 28.6, y: 7, s: 1.1 }, { t: 'pillar', x: 28.6, y: 13.6, s: 1.1 }, { t: 'skull', x: 6.5, y: 13 }, { t: 'bones', x: 23, y: 13.6, s: 1.2 }, { t: 'urnDark', x: 15.5, y: 5.4, s: 1.0 }, { t: 'urnDark', x: 24.5, y: 5.4, s: 1.0 }, { t: 'gravestone', x: 6.5, y: 6.6, s: 1.2, seed: 0.6 },
    ],
    autoDecor: { density: 0.14, seed: 513 },
  },
  {
    name: 'Schattenwald', par: 6, theme: 'shadow', maxStrokes: 24, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 36, h: 12, look: { x: 35.5, y: 7.5 } }],
    map: [
      '........................................',
      '........................................',
      '..####################################..',
      '..#############x###############x######..',
      '..#####x###############x##############..',
      '..####################################..',
      '..####################################..',
      '..#T#######x#######x#######x#####x#H##..',
      '..#################x##################..',
      '..####################################..',
      '..#####x###############x##############..',
      '..#############x###############x######..',
      '..####################################..',
      '..####################################..',
      '........................................',
      '........................................',
    ],
    intro: 'Ein Wald aus toten Stämmen quer über den Weg. Zwischen den Stämmen schwingen Sensen, Fledermäuse jagen hindurch, zwei Schattenzonen schlucken den Ball, und vor dem Loch wacht das Schattenauge.',
    obstacles: [
      { type: 'rotor', x: 11.5, y: 4.5, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.5 }, phase: 0, height: 0.5 },
      { type: 'rotor', x: 11.5, y: 10.5, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.5 }, phase: Math.PI, height: 0.5 },
      { type: 'field', x: 14, y: 5, w: 4, h: 6, fx: 0, fy: 0, style: 'dark' },
      { type: 'mover', x0: 20, y0: 3, x1: 30, y1: 12, w: 0.6, h: 0.6, period: 6, style: 'bat', e: 0.7 },
      { type: 'mover', x0: 30, y0: 3, x1: 20, y1: 12, w: 0.6, h: 0.6, period: 7, phase: 0.5, style: 'bat', e: 0.7 },
      { type: 'rotor', x: 27.5, y: 4.5, blades: 2, len: 1.5, thick: 0.14, hubR: 0.3, speed: 1.6, style: 'scythe', e: 0.6, height: 0.5 },
      { type: 'rotor', x: 27.5, y: 11.5, blades: 2, len: 1.5, thick: 0.14, hubR: 0.3, speed: -1.6, style: 'scythe', e: 0.6, height: 0.5 },
      { type: 'field', x: 29, y: 5, w: 3, h: 6, fx: 0, fy: 0, style: 'dark' },
      { type: 'bumper', x: 34.5, y: 5.6, r: 0.42, style: 'eye', kick: 7 },
      { type: 'bumper', x: 34.5, y: 9.4, r: 0.42, style: 'eye', kick: 7 },
      { type: 'wall', x0: 37, y0: 2, x1: 38, y1: 3, extend: 0 },
      { type: 'wall', x0: 38, y0: 13, x1: 37, y1: 14, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.4, s: 1.7 }, { t: 'deadTree', x: 10, y: 0.8, s: 1.6 }, { t: 'deadTree', x: 21, y: 0.6, s: 1.7 }, { t: 'deadTree', x: 30, y: 0.8, s: 1.6 }, { t: 'deadTree', x: 38.6, y: 1.4, s: 1.6 },
      { t: 'deadTree', x: 5, y: 14.8, s: 1.6 }, { t: 'deadTree', x: 16, y: 15, s: 1.7 }, { t: 'deadTree', x: 26, y: 14.8, s: 1.6 }, { t: 'deadTree', x: 36, y: 15, s: 1.6 },
      { t: 'ghostlight', x: 1.4, y: 7.5, s: 1.2, seed: 0.2 }, { t: 'ghostlight', x: 38.6, y: 7.5, s: 1.2, seed: 0.7 }, { t: 'skull', x: 9.5, y: 14.6 }, { t: 'bones', x: 32, y: 14.6, s: 1.2 }, { t: 'gravestone', x: 25.5, y: 0.6, s: 1.2, seed: 0.5 },
    ],
    autoDecor: { density: 0.17, seed: 515 },
  },
  {
    name: 'Schattenthron', par: 8, theme: 'shadow', maxStrokes: 32, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 16, w: 14, h: 5, look: { x: 24, y: 17.5 } }, { x: 16, y: 17, w: 10, h: 2, look: { x: 30, y: 17 } }, { x: 26, y: 14, w: 8, h: 7, look: { x: 31.5, y: 5 } }, { x: 30, y: 8, w: 4, h: 6, look: { x: 31.5, y: 5 } }, { x: 30, y: 4, w: 10, h: 4, look: { x: 37, y: 2 } }],
    map: [
      '..........................................',
      '....................................ooo...',
      '....................................ooo...',
      '....................................ooo...',
      '..............................##########..',
      '..............................##########..',
      '..............................##########..',
      '..............................##########..',
      '..............................####........',
      '..............................####........',
      '..............................####........',
      '..............................####........',
      '..............llllllllllllll..####........',
      '..............llllllllllllll..####........',
      '..............llllllllllll########........',
      '..............llllllllllll########........',
      '..##############llllllllll########........',
      '..##############oooooooooo########........',
      '..#T############oooooooooo########........',
      '..##############llllllllll########........',
      '..##############llllllllll########........',
      '..............llllllllllllll..............',
    ],
    intro: 'Der Weg zum Schattenthron: über den Friedhof, auf dem Knochensteg über den Feuerstrom, an Geist und Falltüren vorbei zur Gruft. Drinnen der Thronsaal: Geister, Falltüren, Schattenzone, das Auge, die Druckplatte zum Thron – und zuletzt das Loch auf dem Thronpodest.',
    obstacles: [
      { type: 'bumper', x: 7.5, y: 16.6, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 10.5, y: 19.4, r: 0.4, style: 'grave', kick: 7 },
      { type: 'rotor', x: 12.5, y: 18, blades: 1, len: 1.5, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.6 }, phase: 0, height: 0.5 },
      { type: 'spikes', x: 20.5, y: 18, w: 1, h: 2, period: 4, up: 0.45, phase: 0.2 },
      { type: 'mover', x0: 27, y0: 15, x1: 32, y1: 19.5, w: 0.9, h: 0.9, period: 6, style: 'ghost', e: 0.5 },
      { type: 'wall', x0: 33, y0: 21, x1: 34, y1: 20, extend: 0 },
      { type: 'wall', x0: 34, y0: 14, x1: 33, y1: 13, extend: 0 },
      { type: 'trapdoor', x: 31.5, y: 11, w: 3, h: 2.2, period: 5.5, open: 0.32, phase: 0 },
      { type: 'trapdoor', x: 31.5, y: 8, w: 3, h: 2.2, period: 5.5, open: 0.32, phase: 0.5 },
      { type: 'wall', x0: 30, y0: 4, x1: 32, y1: 4, extend: 0 },
      { type: 'bumper', x: 35.5, y: 5.5, r: 0.4, style: 'eye', kick: 7 },
      { type: 'door', x: 37, y: 2, r: 1.0, style: 'crypt', px: 37, py: 0.6, gw: 3.2 },
    ],
    decor: [
      { t: 'gravestone', x: 1.4, y: 15.4, s: 1.3, seed: 0.2 }, { t: 'gravecross', x: 5.5, y: 15.2, s: 1.2 }, { t: 'gravestone', x: 9.5, y: 21.6, s: 1.2, seed: 0.7 }, { t: 'deadTree', x: 2.5, y: 21.8, s: 1.6 }, { t: 'deadTree', x: 14.5, y: 15.2, s: 1.6 },
      { t: 'skull', x: 18, y: 15.4 }, { t: 'bones', x: 23, y: 20.6, s: 1.3 }, { t: 'pillar', x: 25.6, y: 13.4, s: 1.1 }, { t: 'ghostlight', x: 28.5, y: 21.6, s: 1.2, seed: 0.5 }, { t: 'torchPurple', x: 29.4, y: 9.5, s: 1.1 }, { t: 'torchPurple', x: 34.6, y: 9.5, s: 1.1 },
      { t: 'deadTree', x: 28.5, y: 2.5, s: 1.6 }, { t: 'gravestone', x: 40.6, y: 4.5, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 40.6, y: 8.6, s: 1.2 }, { t: 'ghostlight', x: 34.5, y: 1.6, s: 1.2, seed: 0.9 }, { t: 'ghostlight', x: 39.6, y: 1.6, s: 1.2, seed: 0.1 },
    ],
    autoDecor: { density: 0.16, seed: 517 },
    inner: {
      name: 'Thronsaal', theme: 'throne', look: { x: 12, y: 4.5 }, hazardText: { lava: 'Vom Schattenfeuer verschlungen', oob: 'In den Schattenschacht gestürzt', fell: 'In die Gruft gestürzt' },
      views: [{ x: 2, y: 2, w: 22, h: 5, look: { x: 26, y: 4.5 } }, { x: 24, y: 2, w: 8, h: 5, look: { x: 27.5, y: 11 } }, { x: 24, y: 7, w: 8, h: 5, look: { x: 12, y: 15 } }, { x: 2, y: 12, w: 30, h: 6, look: { x: 4, y: 15 } }],
      map: [
        '..................................',
        '..................................',
        '..##############################..',
        '..#####l#######l################..',
        '..#T############################..',
        '..#####l#######l################..',
        '..##############################..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '..##############################..',
        '..################ll############..',
        '..##H#############ll############..',
        '..################ll############..',
        '..##############################..',
        '..................................',
        '..................................',
      ],
      obstacles: [
        { type: 'mover', x0: 5, y0: 3, x1: 22, y1: 6, w: 0.9, h: 0.9, period: 8, style: 'ghost', e: 0.5 },
        { type: 'trapdoor', x: 12, y: 4.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0 },
        { type: 'trapdoor', x: 19, y: 4.5, w: 2.2, h: 3, period: 5.5, open: 0.32, phase: 0.5 },
        { type: 'switch', x: 27.5, y: 4.5, r: 0.55, duration: 20, target: 'A' },
        { type: 'wall', x0: 30, y0: 2, x1: 32, y1: 4, extend: 0 },
        { type: 'field', x: 24, y: 7, w: 8, h: 4, fx: 0, fy: 0, style: 'dark' },
        { type: 'gate', x: 27.5, y: 12, w: 4, h: 0.3, linked: 'A', liftH: 1.5, barH: 1.1 },
        { type: 'mover', x0: 22, y0: 15.5, x1: 6, y1: 15.5, w: 0.9, h: 0.9, period: 8, phase: 0.3, style: 'ghost', e: 0.5 },
        { type: 'rotor', x: 15.5, y: 15, blades: 2, len: 1.5, thick: 0.14, hubR: 0.3, speed: 1.5, style: 'scythe', e: 0.6, height: 0.5 },
        { type: 'bumper', x: 8.5, y: 13.6, r: 0.42, style: 'eye', kick: 7 },
        { type: 'bumper', x: 8.5, y: 16.4, r: 0.42, style: 'eye', kick: 7 },
        { type: 'wall', x0: 2, y0: 13, x1: 3, y1: 14, extend: 0 },
        { type: 'wall', x0: 3, y0: 17, x1: 2, y1: 16, extend: 0 },
      ],
      decor: [
        { t: 'torchPurple', x: 1.4, y: 1.4, s: 1.2 }, { t: 'torchPurple', x: 12.5, y: 0.6, s: 1.1 }, { t: 'torchPurple', x: 24.5, y: 0.6, s: 1.1 }, { t: 'pillar', x: 32.6, y: 2.5, s: 1.2 }, { t: 'pillar', x: 32.6, y: 11.5, s: 1.2 },
        { t: 'skull', x: 22.5, y: 8.4 }, { t: 'bones', x: 23.5, y: 9.6, s: 1.1 }, { t: 'torchPurple', x: 1.4, y: 12.4, s: 1.2 }, { t: 'torchPurple', x: 1.4, y: 17.6, s: 1.2 }, { t: 'pillar', x: 14.5, y: 11.4, s: 1.2 }, { t: 'urnDark', x: 32.6, y: 18.5, s: 1.1 }, { t: 'gravestone', x: 6.5, y: 18.6, s: 1.2, seed: 0.5 },
      ],
      autoDecor: { density: 0.1, seed: 519 },
    },
  },
];
