/* Schattenreich: Stufe „Legende“ – neun extra große Bahnen im Reich der Schatten: Friedhöfe mit Rabenschwärmen,
   Fallbeile, verfluchte Ritterstatuen, Knochenrampen, Geister, Sensen, der Basilisk, das schwarze Schloss mit Zugbrücke, Fallgatter und Thronsaal,
   der Turm mit dem brennenden Auge; die Neunte führt über den Totensee ins Totenschiff und zurück ans Totenufer. */
const SHADOW_COURSES = [
  {
    name: 'Friedhofspforte', par: 4, theme: 'shadow', maxStrokes: 18, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 5, w: 16, h: 4, look: { x: 19.5, y: 7 } }, { x: 18, y: 2, w: 3, h: 7, look: { x: 19.5, y: 3.5 } }],
    map: [
      '....................................',
      '....................................',
      '..................################..',
      '..................#############H##..',
      '..................################..',
      '..###################...............',
      '..#T#################...............',
      '..###################...............',
      '..###################...............',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
      '....................................',
    ],
    intro: 'Durch das Friedhofstor ins Schattenreich. Über den Hof zieht ein Rabenschwarm hin und her – wer im richtigen Moment abschlägt, wird von ihm mitgetragen, wer falsch liegt, zurückgeweht. Im Torgang wartet das erste Fallbeil: Nie darunter liegen bleiben, wenn es fällt.',
    obstacles: [
      { type: 'wave', style: 'ravens', x0: 5, y0: 7, x1: 17, y1: 7, w: 0.6, h: 3.6, period: 7, push: 14, brake: 0.55 },
      { type: 'bumper', x: 8.5, y: 5.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 13.5, y: 8.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'wall', x0: 19, y0: 9, x1: 21, y1: 7, extend: 0 },
      { type: 'wall', x0: 18, y0: 4, x1: 20, y1: 2, extend: 0 },
      { type: 'mover', x0: 21.5, y0: 2.6, x1: 24, y1: 4.4, w: 0.9, h: 0.9, period: 5, style: 'ghost', e: 0.5 },
      { type: 'guillotine', x: 27.5, y: 3.5, w: 0.35, h: 3, period: 5, phase: 0, hold: 0.32 },
      { type: 'wall', x0: 33, y0: 2, x1: 34, y1: 3, extend: 0 },
      { type: 'wall', x0: 34, y0: 4, x1: 33, y1: 5, extend: 0 },
    ],
    decor: [
      { t: 'gravestone', x: 1.4, y: 4.4, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 5.5, y: 4.2, s: 1.2 }, { t: 'deadTree', x: 9.5, y: 3.8, s: 1.5 }, { t: 'ghostlight', x: 14.5, y: 4.4, s: 1.2, seed: 0.3 },
      { t: 'gravestone', x: 4.5, y: 9.6, s: 1.2, seed: 0.7 }, { t: 'gravestone', x: 11.5, y: 9.6, s: 1.2, seed: 0.2 }, { t: 'deadTree', x: 16.5, y: 10, s: 1.6 }, { t: 'gravecross', x: 22, y: 9.6, s: 1.2 },
      { t: 'pillar', x: 17.4, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 24.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 30.5, y: 1.4, s: 1.1 }, { t: 'skull', x: 25.5, y: 5.5 }, { t: 'bones', x: 30, y: 5.6, s: 1.2 }, { t: 'obsidian', x: 35.4, y: 5.8, s: 1.2 }, { t: 'urnDark', x: 34.6, y: 1.4, s: 1.0 },
    ],
    autoDecor: { density: 0.18, seed: 501 },
  },
  {
    name: 'Rabenfriedhof', par: 4, theme: 'shadow', maxStrokes: 20, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 3, w: 36, h: 8, look: { x: 35.5, y: 6.5 } }],
    map: [
      '........................................',
      '........................................',
      '..llllllllllllllllllllllllllllllllllll..',
      '..####################################..',
      '..####################################..',
      '..##############x#############x#######..',
      '..#T###############################H##..',
      '..####################################..',
      '..#######x#############x##############..',
      '..####################################..',
      '..####################################..',
      '..llllllllllllllllllllllllllllllllllll..',
      '........................................',
      '........................................',
    ],
    intro: 'Ein weites Gräberfeld, oben und unten von Schattenfeuer gesäumt. Drei Rabenschwärme fliegen quer über den Friedhof und schieben alles vor sich her – wer im Weg liegt, landet im Feuer. Gruftblöcke geben Deckung, am Ende schwingt die Sense.',
    obstacles: [
      { type: 'wave', style: 'ravens', x0: 11, y0: 3.6, x1: 11, y1: 10.4, w: 3.2, h: 0.6, period: 6.5, push: 14, brake: 0.55 },
      { type: 'wave', style: 'ravens', x0: 19, y0: 10.4, x1: 19, y1: 3.6, w: 3.2, h: 0.6, period: 7.5, phase: 0.5, push: 14, brake: 0.55 },
      { type: 'wave', style: 'ravens', x0: 27, y0: 3.6, x1: 27, y1: 10.4, w: 3.2, h: 0.6, period: 6, phase: 0.3, push: 14, brake: 0.55 },
      { type: 'bumper', x: 5.5, y: 8.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 33.5, y: 4.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'rotor', x: 32.5, y: 6.5, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.6 }, phase: Math.PI / 2, height: 0.5 },
      { type: 'wall', x0: 36, y0: 3, x1: 38, y1: 5, extend: 0 },
      { type: 'wall', x0: 36, y0: 11, x1: 38, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.2, s: 1.6 }, { t: 'gravestone', x: 7.5, y: 0.8, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 14.5, y: 0.8, s: 1.2 }, { t: 'gravestone', x: 21.5, y: 0.8, s: 1.2, seed: 0.9 }, { t: 'deadTree', x: 29, y: 0.8, s: 1.6 }, { t: 'gravestone', x: 36.5, y: 0.8, s: 1.3, seed: 0.1 },
      { t: 'gravecross', x: 4.5, y: 13, s: 1.2 }, { t: 'deadTree', x: 12, y: 13.2, s: 1.6 }, { t: 'gravestone', x: 19.5, y: 13, s: 1.3, seed: 0.6 }, { t: 'gravestone', x: 26.5, y: 13, s: 1.2, seed: 0.3 }, { t: 'gravecross', x: 33.5, y: 13, s: 1.2 },
      { t: 'ghostlight', x: 1.4, y: 6.5, s: 1.2, seed: 0.2 }, { t: 'ghostlight', x: 38.6, y: 6.5, s: 1.2, seed: 0.7 }, { t: 'skull', x: 13.5, y: 9.5 }, { t: 'bones', x: 24.5, y: 4.5, s: 1.2 },
    ],
    autoDecor: { density: 0.12, seed: 503 },
  },
  {
    name: 'Fallbeilgasse', par: 5, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 26, h: 3, look: { x: 29.5, y: 3.5 } }, { x: 28, y: 2, w: 3, h: 5, look: { x: 29.5, y: 8.5 } }],
    map: [
      '........................................',
      '........................................',
      '..##################ll#########.........',
      '..#T################ll#########.........',
      '..##################ll#########.........',
      '............................###.........',
      '............................###.........',
      '............................##########..',
      '............................#######H##..',
      '............................##########..',
      '........................................',
      '........................................',
    ],
    intro: 'Die Gasse der Fallbeile: Zwei Klingen hängen über dem Gruftgang, jede in ihrem eigenen Takt. Unten sind sie eine Mauer, oben eine Falle – wer beim Fall darunter liegt, wird geköpft. Dann klafft eine Grube voller Schattenfeuer: Nur mit Schwung über die Knochenrampe kommt man hinüber. Hinter der Kehre wartet das letzte Beil.',
    obstacles: [
      { type: 'guillotine', x: 8.5, y: 3.5, w: 0.35, h: 3, period: 5.2, phase: 0, hold: 0.32 },
      { type: 'guillotine', x: 14.5, y: 3.5, w: 0.35, h: 3, period: 5.2, phase: 0.4, hold: 0.32 },
      { type: 'ramp', x: 17.5, y: 2, w: 2, h: 3, angle: 0, minSpeed: 2.5, speed: 4.6, land: 3.4 },
      { type: 'guillotine', x: 25.5, y: 3.5, w: 0.35, h: 3, period: 5.2, phase: 0.7, hold: 0.32 },
      { type: 'wall', x0: 29, y0: 2, x1: 31, y1: 4, extend: 0 },
      { type: 'wall', x0: 28, y0: 8, x1: 30, y1: 10, extend: 0 },
      { type: 'guillotine', x: 33, y: 8.5, w: 0.35, h: 3, period: 5.2, phase: 0.5, hold: 0.32 },
      { type: 'wall', x0: 37, y0: 7, x1: 38, y1: 8, extend: 0 },
      { type: 'wall', x0: 38, y0: 9, x1: 37, y1: 10, extend: 0 },
    ],
    decor: [
      { t: 'torchPurple', x: 5.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 12, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 20.5, y: 1.4, s: 1.1 }, { t: 'torchPurple', x: 27, y: 1.4, s: 1.1 },
      { t: 'skull', x: 3.5, y: 5.5 }, { t: 'bones', x: 12.5, y: 5.6, s: 1.2 }, { t: 'skull', x: 19.5, y: 5.5 }, { t: 'bones', x: 23, y: 5.6, s: 1.2 }, { t: 'pillar', x: 31.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 27.4, y: 10.6, s: 1.1 }, { t: 'urnDark', x: 38.6, y: 6.4, s: 1.1 }, { t: 'gravestone', x: 35, y: 10.6, s: 1.2, seed: 0.4 }, { t: 'torchPurple', x: 31.5, y: 10.6, s: 1.1 },
    ],
    autoDecor: { density: 0.15, seed: 505 },
  },
  {
    name: 'Irrlichtsumpf', par: 6, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 34, h: 10, look: { x: 33, y: 6.5 } }],
    map: [
      '......................................',
      '......................................',
      '..######www#########www#######www###..',
      '..######www#########www#######www###..',
      '..######www#########www#############..',
      '..############www#########www#######..',
      '..#T##########www#########www####H##..',
      '..############www#########www#######..',
      '..############www###################..',
      '..######www#########wwww############..',
      '..######www#########wwww######www###..',
      '..######www#########wwww######www###..',
      '......................................',
      '......................................',
    ],
    intro: 'Ein weites Moor voller Schattenwasser. Seelenlichter locken den Ball an – und genau neben ihnen liegen die Tümpel. Unten führt eine Knochenrampe mit Schwung über den großen Tümpel hinweg. Ein Rabenschwarm zieht am Ende quer über den Weg.',
    obstacles: [
      { type: 'magnet', x: 11.5, y: 6.5, r: 3.2, strength: 10, style: 'soul' },
      { type: 'magnet', x: 24.5, y: 6.5, r: 3.0, strength: 10, style: 'soul' },
      { type: 'wave', style: 'ravens', x0: 29, y0: 4.6, x1: 29, y1: 9.4, w: 2.4, h: 0.6, period: 5.5, push: 12, brake: 0.55 },
      { type: 'bumper', x: 29.5, y: 6.5, r: 0.38, style: 'grave', kick: 7 },
      { type: 'bumper', x: 5.5, y: 9.5, r: 0.38, style: 'grave', kick: 7 },
      { type: 'ramp', x: 17.5, y: 9, w: 2, h: 3, angle: 0, minSpeed: 2.5, speed: 6.5, land: 5.2 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.2, s: 1.6 }, { t: 'deadTree', x: 13.5, y: 0.8, s: 1.5 }, { t: 'deadTree', x: 25, y: 12.8, s: 1.6 }, { t: 'deadTree', x: 36.6, y: 1.4, s: 1.5 },
      { t: 'ghostlight', x: 9.5, y: 6.5, s: 1.1, seed: 0.2 }, { t: 'ghostlight', x: 15.5, y: 12.6, s: 1.1, seed: 0.6 }, { t: 'ghostlight', x: 28.5, y: 0.8, s: 1.1, seed: 0.9 },
      { t: 'gravestone', x: 4.5, y: 12.6, s: 1.2, seed: 0.5 }, { t: 'gravecross', x: 36.6, y: 12.6, s: 1.2 }, { t: 'bones', x: 19.5, y: 12.6, s: 1.2 }, { t: 'skull', x: 1.4, y: 8.5 },
    ],
    autoDecor: { density: 0.18, seed: 507 },
  },
  {
    name: 'Ritterhalle', par: 5, theme: 'shadow', maxStrokes: 24, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 2, w: 31, h: 12, look: { x: 33.5, y: 7.5 } }],
    map: [
      '........................................',
      '........................................',
      '..###############################x####..',
      '..######x########x########x######x####..',
      '..###############################x####..',
      '..###############################x####..',
      '..####################################..',
      '..#T###############################H##..',
      '..####################################..',
      '..###############################x####..',
      '..###############################x####..',
      '..###############################x####..',
      '..######x########x########x######x####..',
      '..###############################x####..',
      '........................................',
      '........................................',
    ],
    intro: 'In der Ritterhalle stehen vier verfluchte Statuen. Alle paar Sekunden erwachen sie, die Augen glühen, und das Schwert fährt blitzschnell über den Boden – wer getroffen wird, trägt den Ritterfluch und rollt bis zum Loch nur noch träge. Die Steinwand am Ende hat nur eine Lücke: unter dem Fallbeil.',
    obstacles: [
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 12, y: 5, phase: 0, slash: { period: 4.2, dur: 0.7, amp: Math.PI * 0.9, phase: 0 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 12, y: 10.5, phase: Math.PI, slash: { period: 4.2, dur: 0.7, amp: Math.PI * 0.9, phase: 0.5 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 21.5, y: 7.5, phase: -Math.PI / 2, slash: { period: 3.8, dur: 0.65, amp: Math.PI * 0.95, phase: 0.25 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 29.5, y: 4.5, phase: Math.PI / 2, slash: { period: 4.6, dur: 0.7, amp: Math.PI * 0.9, phase: 0.6 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 29.5, y: 10.5, phase: -Math.PI / 2, slash: { period: 4.6, dur: 0.7, amp: -Math.PI * 0.9, phase: 0.1 } },
      { type: 'mover', x0: 5, y0: 3, x1: 7.5, y1: 11.5, w: 0.6, h: 0.6, period: 5, style: 'bat', e: 0.7 },
      { type: 'bumper', x: 5.5, y: 12.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 24.5, y: 3.0, r: 0.4, style: 'eye', kick: 7 },
      { type: 'guillotine', x: 33.5, y: 7.5, w: 0.35, h: 3, period: 5.5, phase: 0, hold: 0.3 },
      { type: 'wall', x0: 37, y0: 6, x1: 38, y1: 7, extend: 0 },
      { type: 'wall', x0: 38, y0: 8, x1: 37, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'pillar', x: 1.4, y: 1.4, s: 1.2 }, { t: 'pillar', x: 12.5, y: 0.8, s: 1.1 }, { t: 'pillar', x: 21.5, y: 0.8, s: 1.1 }, { t: 'pillar', x: 30.5, y: 0.8, s: 1.1 }, { t: 'pillar', x: 38.6, y: 1.4, s: 1.2 },
      { t: 'torchPurple', x: 5.5, y: 0.8, s: 1.1 }, { t: 'torchPurple', x: 17, y: 0.8, s: 1.1 }, { t: 'torchPurple', x: 26, y: 0.8, s: 1.1 }, { t: 'torchPurple', x: 35.5, y: 0.8, s: 1.1 },
      { t: 'pillar', x: 1.4, y: 14.6, s: 1.2 }, { t: 'pillar', x: 38.6, y: 14.6, s: 1.2 }, { t: 'torchPurple', x: 8.5, y: 15, s: 1.1 }, { t: 'torchPurple', x: 17, y: 15, s: 1.1 }, { t: 'torchPurple', x: 26, y: 15, s: 1.1 }, { t: 'torchPurple', x: 34.5, y: 15, s: 1.1 },
      { t: 'skull', x: 15.5, y: 15 }, { t: 'bones', x: 23, y: 15, s: 1.2 }, { t: 'urnDark', x: 38.6, y: 5.4, s: 1.0 }, { t: 'urnDark', x: 38.6, y: 9.6, s: 1.0 },
    ],
    autoDecor: { density: 0.1, seed: 509 },
  },
  {
    name: 'Knochenbrücke', par: 5, theme: 'shadow', maxStrokes: 22, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 3, w: 6, h: 6, look: { x: 20, y: 5.5 } }, { x: 8, y: 5, w: 14, h: 3, look: { x: 24, y: 6 } }, { x: 22, y: 2, w: 6, h: 8, look: { x: 38, y: 5.5 } }, { x: 28, y: 5, w: 8, h: 2, look: { x: 39, y: 5.5 } }],
    map: [
      '............................................',
      '............................................',
      '......................######................',
      '..######llllllllllllll######llllllll######..',
      '..######llllllllllllll######llllllll######..',
      '..#T####oooooooooooooo######oooooooo###H##..',
      '..######oooooooooooooo######oooooooo######..',
      '..######oooooooooooooo######llllllll######..',
      '..######llllllllllllll######llllllll######..',
      '......................######................',
      '............................................',
      '............................................',
    ],
    intro: 'Eine Brücke aus Knochen ohne Geländer über einen Strom aus Schattenfeuer. Am Ufer lauert der Basilisk: Wer ihm in den Rachen rollt, wird verschluckt und weit über das Feuer bis auf die Felsinsel gespuckt – sein Kopf pendelt aber. Mitten auf der Brücke fährt eine Reihe Knochenstacheln aus dem Boden, über die ganze Felsinsel spannt sich ein riesiges Fallbeil, und der zweite Steg ist kürzer, aber schmaler – und hat seine eigenen Stacheln.',
    obstacles: [
      { type: 'cannon', style: 'basilisk', x: 5.5, y: 6, base: 0, amp: 0.14, speed: 0.8, range: 17.5, catchR: 0.6, loadTime: 0.9 },
      { type: 'spikes', x: 15.5, y: 6.5, w: 1, h: 3, period: 4.4, up: 0.36, phase: 0 },
      { type: 'guillotine', x: 24.5, y: 6, w: 0.4, h: 7.8, period: 6, phase: 0, hold: 0.3, liftH: 2.6, bladeH: 1.0 },
      { type: 'bumper', x: 26.5, y: 2.8, r: 0.38, style: 'grave', kick: 7 },
      { type: 'bumper', x: 26.5, y: 8.2, r: 0.38, style: 'grave', kick: 7 },
      { type: 'spikes', x: 32.5, y: 6, w: 1, h: 2, period: 4, up: 0.36, phase: 0.5 },
      { type: 'wall', x0: 41, y0: 3, x1: 42, y1: 4, extend: 0 },
      { type: 'wall', x0: 42, y0: 8, x1: 41, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 1.6, s: 1.6 }, { t: 'gravestone', x: 5.5, y: 1.6, s: 1.2, seed: 0.4 }, { t: 'skull', x: 2.4, y: 9.6 }, { t: 'bones', x: 10, y: 1.6, s: 1.3 }, { t: 'bones', x: 16, y: 10.4, s: 1.3 },
      { t: 'pillar', x: 21.6, y: 1.4, s: 1.1 }, { t: 'pillar', x: 27.6, y: 10.6, s: 1.1 }, { t: 'skull', x: 30.5, y: 1.6 }, { t: 'bones', x: 33, y: 10.4, s: 1.2 }, { t: 'deadTree', x: 42.6, y: 1.6, s: 1.5 }, { t: 'ghostlight', x: 38.5, y: 10.6, s: 1.1, seed: 0.7 },
    ],
    autoDecor: { density: 0.13, seed: 511 },
  },
  {
    name: 'Schattenschloss', par: 8, theme: 'shadow', maxStrokes: 30, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 16, w: 6, h: 6, look: { x: 13.5, y: 18.5 } }, { x: 11, y: 16, w: 6, h: 6, look: { x: 14, y: 12 } }, { x: 12, y: 10, w: 4, h: 6, look: { x: 22, y: 6 } }, { x: 11, y: 2, w: 13, h: 8, look: { x: 28.5, y: 3 } }, { x: 24, y: 2, w: 11, h: 8, look: { x: 28.5, y: -2 } }],
    map: [
      '............................................',
      '............................................',
      '........lllxx######ll############xx.........',
      '........lllxx######ll############xx.........',
      '........lll########ll##############.........',
      '........lll########ll##############.........',
      '........lll########ll##############.........',
      '........lll########ll##############.........',
      '........lll########################.........',
      '........lll######################xx.........',
      '........lll######################xx.........',
      '........lll.####............................',
      '........lll.####............................',
      '........lll.####............................',
      '........lll.####............................',
      '........lll.####............................',
      '..######lll######...........................',
      '..######lll######...........................',
      '..#T####lll######...........................',
      '..######lll######...........................',
      '..######lll######...........................',
      '..######lll######...........................',
      '........lll.................................',
      '........lll.................................',
    ],
    intro: 'Das schwarze Schloss. Vom Vorhof geht es nur mit Schwung über die Zugbrücke – wer zu langsam ist, rollt in den Feuergraben. Im Torhaus rasselt das Fallgatter auf und ab. Im Burghof wachen verfluchte Ritter und ein Geist, eine Rampe führt über den Feuergraben. Hinter dem großen Tor liegt der Thronsaal: Der Kerkergang endet im Rachen des Basilisken, und nur er spuckt den Ball hinauf auf die Empore zum Loch.',
    obstacles: [
      { type: 'ramp', x: 5.5, y: 16.5, w: 2, h: 4, angle: 0, minSpeed: 3, speed: 6.5, land: 5.6 },
      { type: 'gate', x: 14, y: 12.5, w: 4, h: 0.3, period: 6, open: 0.45, phase: 0, axis: 'x' },
      { type: 'bumper', x: 14.5, y: 5.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'ramp', x: 16.5, y: 3, w: 2, h: 4, angle: 0, minSpeed: 2.5, speed: 4.6, land: 2.8 },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 23, y: 8.5, phase: 0, slash: { period: 4.4, dur: 0.7, amp: Math.PI * 0.9, phase: 0 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 25.5, y: 4.5, phase: Math.PI, slash: { period: 4.0, dur: 0.7, amp: Math.PI * 0.9, phase: 0.5 } },
      { type: 'rotor', style: 'knight', blades: 1, len: 2.1, thick: 0.16, hubR: 0.5, e: 0.7, height: 0.3, curse: 2.0, curseLabel: 'Ritterfluch! Der Ball bleibt bis zum Loch träge.', x: 31, y: 6.5, phase: -Math.PI / 2, slash: { period: 4.8, dur: 0.7, amp: Math.PI * 0.9, phase: 0.25 } },
      { type: 'mover', x0: 24, y0: 9.3, x1: 32, y1: 9.3, w: 0.9, h: 0.9, period: 6, style: 'ghost', e: 0.5 },
      { type: 'bumper', x: 26, y: 9.2, r: 0.4, style: 'eye', kick: 7 },
      { type: 'wall', x0: 26.5, y0: 2, x1: 27.5, y1: 3, extend: 0 },
      { type: 'wall', x0: 30.5, y0: 2, x1: 29.5, y1: 3, extend: 0 },
      { type: 'door', x: 28.5, y: 4.0, r: 1.0, style: 'castle', px: 28.5, py: 1.5, gw: 3.6 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 15.2, s: 1.6 }, { t: 'gravestone', x: 5.5, y: 15.2, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 3.5, y: 22.8, s: 1.2 }, { t: 'skull', x: 6.5, y: 22.6 }, { t: 'ghostlight', x: 1.4, y: 19, s: 1.2, seed: 0.3 },
      { t: 'pillar', x: 11.4, y: 22.6, s: 1.2 }, { t: 'pillar', x: 16.6, y: 22.6, s: 1.2 }, { t: 'torchPurple', x: 11.4, y: 12.5, s: 1.1 }, { t: 'torchPurple', x: 15.6, y: 12.5, s: 1.1 }, { t: 'pillar', x: 16.6, y: 15.4, s: 1.2 },
      { t: 'torchPurple', x: 16.5, y: 10.6, s: 1.1 }, { t: 'torchPurple', x: 22, y: 10.6, s: 1.1 }, { t: 'torchPurple', x: 30, y: 10.6, s: 1.1 }, { t: 'bones', x: 20, y: 9.2, s: 1.2 }, { t: 'skull', x: 14.5, y: 8.5 }, { t: 'urnDark', x: 35.4, y: 6.5, s: 1.0 }, { t: 'obsidian', x: 35.4, y: 4, s: 1.1 },
      { t: 'torchPurple', x: 13.5, y: 1.2, s: 1.1 }, { t: 'torchPurple', x: 22, y: 1.2, s: 1.1 }, { t: 'torchPurple', x: 35.6, y: 1.2, s: 1.1 }, { t: 'deadTree', x: 40, y: 3, s: 1.6 }, { t: 'gravestone', x: 39, y: 9, s: 1.3, seed: 0.7 },
    ],
    autoDecor: { density: 0.1, seed: 513 },
    inner: {
      name: 'Thronsaal', theme: 'throne', look: { x: 21.4, y: 11 }, hazardText: { fell: 'In den Kerker gestürzt', beheaded: 'Im Thronsaal geköpft!' },
      views: [{ x: 2, y: 9, w: 20, h: 4, look: { x: 21.4, y: 11 } }, { x: 14, y: 1, w: 15, h: 5, look: { x: 26.5, y: 3.5 } }],
      map: [
        '..............................',
        '..............###############.',
        '..............###############.',
        '..............############H##.',
        '..............###############.',
        '..............###############.',
        '..............................',
        '..............................',
        '..............................',
        '..#####################.......',
        '..#T###################.......',
        '..#####################.......',
        '..#####################.......',
        '..............................',
      ],
      intro: 'Der Thronsaal des Schattenkönigs. Der Kerkergang führt an Sense und Fallbeil vorbei in den Rachen des Basilisken – er verschluckt den Ball, kaut kurz und spuckt ihn hinauf auf die Empore, wo das Loch liegt. Sein Kopf pendelt: Wer im falschen Moment hineinrollt, fliegt schief.',
      obstacles: [
        { type: 'bumper', x: 7.5, y: 12.2, r: 0.4, style: 'grave', kick: 7 },
        { type: 'rotor', x: 10.5, y: 11, blades: 1, len: 1.6, thick: 0.14, hubR: 0.22, style: 'scythe', e: 0.6, swing: { amp: Math.PI / 2.4, speed: 1.6 }, phase: 0, height: 0.5 },
        { type: 'guillotine', x: 15.5, y: 11, w: 0.35, h: 4, period: 5.4, phase: 0, hold: 0.32 },
        { type: 'wall', x0: 19.5, y0: 9, x1: 21, y1: 10.3, extend: 0 },
        { type: 'wall', x0: 19.5, y0: 13, x1: 21, y1: 11.7, extend: 0 },
        { type: 'cannon', style: 'basilisk', x: 21.4, y: 11, base: -Math.PI / 2, amp: 0.3, speed: 0.8, range: 6.2, catchR: 0.65, loadTime: 0.9 },
        { type: 'wall', x0: 28, y0: 1, x1: 29, y1: 2.5, extend: 0 },
        { type: 'wall', x0: 29, y0: 4.5, x1: 28, y1: 6, extend: 0 },
      ],
      decor: [
        { t: 'pillar', x: 15.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 19.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 23.5, y: 0.4, s: 1.2 }, { t: 'pillar', x: 27.5, y: 0.4, s: 1.2 },
        { t: 'torchPurple', x: 13.4, y: 2.5, s: 1.1 }, { t: 'torchPurple', x: 29.6, y: 2.5, s: 1.1 }, { t: 'obsidian', x: 17.5, y: 6.4, s: 1.2 }, { t: 'obsidian', x: 25.5, y: 6.4, s: 1.2 }, { t: 'urnDark', x: 21.5, y: 6.4, s: 1.0 },
        { t: 'torchPurple', x: 1.4, y: 10.5, s: 1.1 }, { t: 'torchPurple', x: 8.5, y: 8.4, s: 1.1 }, { t: 'torchPurple', x: 14, y: 13.6, s: 1.1 }, { t: 'skull', x: 4.5, y: 13.6 }, { t: 'bones', x: 12.5, y: 8.4, s: 1.2 }, { t: 'bones', x: 18, y: 13.6, s: 1.2 }, { t: 'pillar', x: 23.4, y: 9.4, s: 1.1 }, { t: 'pillar', x: 23.4, y: 12.6, s: 1.1 },
      ],
      autoDecor: { density: 0.08, seed: 514 },
    },
  },
  {
    name: 'Turm des Auges', par: 5, theme: 'shadow', maxStrokes: 24, hazardText: { lava: 'Vom Schattenfeuer verschlungen', water: 'Im Schattenwasser versunken', oob: 'In die Finsternis gestürzt', fell: 'In die Gruft gestürzt', spiked: 'Von Knochenstacheln aufgespießt' },
    views: [{ x: 2, y: 11, w: 18, h: 9, look: { x: 19.5, y: 10.5 } }, { x: 2, y: 2, w: 18, h: 9, look: { x: 35.5, y: 3.5 } }, { x: 20, y: 2, w: 18, h: 18, look: { x: 35.5, y: 3.5 } }],
    map: [
      '........................................',
      '........................................',
      '..############################l#######..',
      '..#########x##################l####H##..',
      '..####################x#######l#######..',
      '..############################l#######..',
      '..##########################x#l#######..',
      '..###########x##############x#l#######..',
      '..###x#######x################l#######..',
      '..####################################..',
      '..###############################x####..',
      '..###############################x####..',
      '..####################################..',
      '..######xx############################..',
      '..######################xx############..',
      '..####################################..',
      '..###############x####################..',
      '..#T##################################..',
      '..####################################..',
      '..####################################..',
      '........................................',
      '........................................',
    ],
    intro: 'Mitten auf dem Platz steht der Turm, und auf ihm brennt das Auge. Langsam dreht es seinen Blick über den Boden. Wer in seinem Lichtkegel liegen bleibt, ist verloren – nur hinter den Gruftblöcken ist man sicher. Ein rollender Ball ist zu schnell für das Auge: Also nie im Licht stehen bleiben. Vor dem Loch zieht sich ein Feuergraben über den Platz – über die Knochenrampe springt man hinüber, oder man geht unten herum.',
    obstacles: [
      { type: 'eyetower', x: 19.5, y: 10.5, r: 1.1, range: 9.5, fov: 0.62, speed: 0.45, phase: 0 },
      { type: 'bumper', x: 11.5, y: 17.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 27.5, y: 3.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'ramp', x: 27.5, y: 2, w: 2, h: 4, angle: 0, minSpeed: 2.5, speed: 4.6, land: 2.6 },
      { type: 'mover', x0: 4, y0: 4, x1: 15, y1: 13, w: 0.6, h: 0.6, period: 7, style: 'bat', e: 0.7 },
      { type: 'wall', x0: 34, y0: 2, x1: 36, y1: 2, extend: 0 },
    ],
    decor: [
      { t: 'gravestone', x: 1.4, y: 1.4, s: 1.3, seed: 0.4 }, { t: 'deadTree', x: 8, y: 0.8, s: 1.6 }, { t: 'gravecross', x: 16, y: 0.8, s: 1.2 }, { t: 'deadTree', x: 24, y: 0.8, s: 1.6 }, { t: 'gravestone', x: 31, y: 0.8, s: 1.2, seed: 0.7 }, { t: 'torchPurple', x: 38.6, y: 1.4, s: 1.1 },
      { t: 'ghostlight', x: 1.2, y: 10.5, s: 1.2, seed: 0.3 }, { t: 'ghostlight', x: 38.8, y: 10.5, s: 1.2, seed: 0.8 }, { t: 'skull', x: 8.5, y: 14.5 }, { t: 'bones', x: 24.5, y: 15.6, s: 1.2 }, { t: 'skull', x: 28.5, y: 8.5 }, { t: 'bones', x: 13.5, y: 9.6, s: 1.2 },
      { t: 'deadTree', x: 1.2, y: 20.8, s: 1.6 }, { t: 'gravestone', x: 10, y: 21, s: 1.3, seed: 0.2 }, { t: 'gravecross', x: 20, y: 21, s: 1.2 }, { t: 'gravestone', x: 30, y: 21, s: 1.2, seed: 0.9 }, { t: 'deadTree', x: 38.6, y: 20.8, s: 1.6 }, { t: 'obsidian', x: 22.5, y: 5.6, s: 1.1 }, { t: 'urnDark', x: 5.5, y: 9.6, s: 1.0 },
    ],
    autoDecor: { density: 0.12, seed: 515 },
  },
  {
    name: 'Totenschiff', par: 10, theme: 'darksea', maxStrokes: 34, hazardText: { oob: 'Ins schwarze Wasser gestürzt', water: 'Im Totensee versunken' },
    views: [{ x: 2, y: 6, w: 11, h: 8, look: { x: 18, y: 10 } }, { x: 13, y: 9, w: 12, h: 2, look: { x: 30.5, y: 9.5 } }],
    map: [
      '............................................',
      '............................................',
      '............................................',
      '............................................',
      '.........................#########..........',
      '.........................#########..........',
      '..###########............#########..........',
      '..###########............#########..........',
      '..###########............#########..........',
      '..#T#########oooooooooooo#########..........',
      '..###########oooooooooooo#########..........',
      '..###########............#########..........',
      '..###########............#########..........',
      '..###########............#########..........',
      '.........................#########..........',
      '.........................#########..........',
      '............................................',
      '............................................',
      '............................................',
      '............................................',
    ],
    intro: 'Am Totensee liegt das Wrack eines alten Schiffs. Über den Steg ohne Geländer – ein Rabenschwarm zieht darüber hin und her – zur Plattform am Rumpf, wo dunkle Tentakel aus dem Leck kriechen. Drinnen gibt es noch kein Loch: Erst durch den Laderaum – mitten im Deck klafft ein Leck, das man umrollt oder über die Planke überspringt – in die sichere Kammer, dann durch die Luke zurück an Land – am Totenufer wartet das letzte Loch.',
    obstacles: [
      { type: 'bumper', x: 7.5, y: 7.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'bumper', x: 9.5, y: 11.5, r: 0.4, style: 'grave', kick: 7 },
      { type: 'wave', style: 'ravens', x0: 14, y0: 10, x1: 23, y1: 10, w: 0.6, h: 2.2, period: 6, push: 12, brake: 0.55 },
      { type: 'rotor', x: 34.2, y: 6.5, blades: 2, len: 2.6, speed: 0.9, thick: 0.18, hubR: 0.4, style: 'darktentacle', e: 0.7, height: 0.4 },
      { type: 'rotor', x: 34.2, y: 12.5, blades: 2, len: 2.6, speed: -1.1, thick: 0.18, hubR: 0.4, style: 'darktentacle', e: 0.7, height: 0.4, phase: 1 },
      { type: 'door', x: 30.5, y: 9.5, r: 1.2, style: 'wreck', px: 37, py: 9.5 },
    ],
    decor: [
      { t: 'deadTree', x: 1.2, y: 5.2, s: 1.6 }, { t: 'gravestone', x: 5.5, y: 5.2, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 10.5, y: 5.2, s: 1.2 }, { t: 'anchor', x: 12.6, y: 13.6, s: 1.3 }, { t: 'bones', x: 3.5, y: 13.8, s: 1.2 }, { t: 'skull', x: 8.5, y: 13.6 },
      { t: 'ghostlight', x: 1.4, y: 9.5, s: 1.2, seed: 0.3 }, { t: 'bollard', x: 13.4, y: 8.6, s: 1.0 }, { t: 'bollard', x: 24.6, y: 11.4, s: 1.0 }, { t: 'lantern', x: 26.5, y: 3.6 }, { t: 'lantern', x: 26.5, y: 15.4 }, { t: 'barrel', x: 32.4, y: 4.6, s: 1.0 }, { t: 'crate', x: 32.4, y: 14.6, s: 1.0 }, { t: 'bones', x: 28.5, y: 14.6, s: 1.2 },
    ],
    autoDecor: { density: 0.1, seed: 517 },
    inner: {
      name: 'Im Totenschiff', theme: 'ghostship', look: { x: 16, y: 5.5 }, hazardText: { fell: 'In den Kielraum gestürzt', oob: 'Durch das Leck gespült' },
      views: [{ x: 2, y: 4, w: 10, h: 4, look: { x: 16, y: 5.5 } }, { x: 12, y: 2, w: 8, h: 8, look: { x: 23.5, y: 5.5 } }],
      map: [
        '............................',
        '............................',
        '............#########.......',
        '............#########.......',
        '..############ooooo#######..',
        '..#T##########o...o#######..',
        '..############o...o#######..',
        '..############o...o#######..',
        '............##ooooo##.......',
        '............#########.......',
        '............................',
        '............................',
      ],
      obstacles: [
        { type: 'rotor', x: 7.5, y: 4.4, blades: 1, len: 2.4, speed: 1.0, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 0.5 },
        { type: 'rotor', x: 10.5, y: 7.6, blades: 1, len: 2.4, speed: -1.0, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 3.6 },
        { type: 'mover', x0: 13.5, y0: 3.5, x1: 18.5, y1: 3.5, w: 0.7, h: 0.7, period: 3.6, style: 'barrel' },
        { type: 'mover', x0: 18.5, y0: 8.5, x1: 13.5, y1: 8.5, w: 0.7, h: 0.7, period: 4.4, phase: 0.3, style: 'barrel' },
        { type: 'ramp', x: 12.5, y: 5, w: 1.5, h: 3, angle: 0, minSpeed: 2.5, speed: 5, land: 4.8 },
        { type: 'rotor', x: 19.6, y: 6, blades: 2, len: 2.0, speed: 0.9, thick: 0.17, hubR: 0.35, style: 'darktentacle', e: 0.7, height: 0.4, phase: 1 },
        { type: 'door', x: 23.5, y: 5.5, r: 0.9, style: 'hatch' },
      ],
      decor: [
        { t: 'lantern', x: 1.4, y: 3.6 }, { t: 'barrel', x: 4.5, y: 3.4, s: 1.0 }, { t: 'crate', x: 9.5, y: 8.6, s: 1.0 }, { t: 'bones', x: 5.5, y: 8.6, s: 1.2 }, { t: 'skull', x: 12.5, y: 1.4 },
        { t: 'chest', x: 21.5, y: 1.4, s: 1.2 }, { t: 'barrel', x: 13.5, y: 10.6, s: 1.0 }, { t: 'seaweed', x: 18.5, y: 10.6, s: 1.2, seed: 0.5 }, { t: 'lantern', x: 21.4, y: 3.4 }, { t: 'lantern', x: 21.4, y: 7.6 }, { t: 'ghostlight', x: 25.6, y: 5.5, s: 1.1, seed: 0.4 },
      ],
      autoDecor: { density: 0.1, seed: 519 },
      inner: {
        name: 'Totenufer', theme: 'shadow', look: { x: 12, y: 6 }, hazardText: { lava: 'Vom Schattenfeuer verschlungen', beheaded: 'Am Totenufer geköpft!' },
        views: [{ x: 2, y: 4, w: 28, h: 4, look: { x: 27.5, y: 5.5 } }],
        map: [
          '................................',
          '................................',
          '................................',
          '..llllllllllllllllllllllllllll..',
          '..############################..',
          '..#T#######################H##..',
          '..############################..',
          '..############################..',
          '..llllllllllllllllllllllllllll..',
          '................................',
          '................................',
          '................................',
        ],
        obstacles: [
          { type: 'wave', style: 'ravens', x0: 9, y0: 4.6, x1: 9, y1: 7.4, w: 3, h: 0.6, period: 5.5, push: 13, brake: 0.55 },
          { type: 'bumper', x: 13.5, y: 4.6, r: 0.4, style: 'grave', kick: 7 },
          { type: 'guillotine', x: 17.5, y: 6, w: 0.35, h: 4, period: 5.2, phase: 0, hold: 0.32 },
          { type: 'bumper', x: 22.5, y: 7.4, r: 0.4, style: 'grave', kick: 7 },
          { type: 'wall', x0: 28, y0: 4, x1: 29, y1: 5, extend: 0 },
          { type: 'wall', x0: 28, y0: 8, x1: 29, y1: 7, extend: 0 },
        ],
        decor: [
          { t: 'anchor', x: 1.4, y: 3.2, s: 1.3 }, { t: 'deadTree', x: 6, y: 1.6, s: 1.6 }, { t: 'gravestone', x: 12.5, y: 1.8, s: 1.3, seed: 0.4 }, { t: 'gravecross', x: 20.5, y: 1.8, s: 1.2 }, { t: 'deadTree', x: 27, y: 1.6, s: 1.6 },
          { t: 'bones', x: 4.5, y: 10, s: 1.2 }, { t: 'skull', x: 15.5, y: 10 }, { t: 'gravestone', x: 24.5, y: 10, s: 1.2, seed: 0.8 }, { t: 'ghostlight', x: 30.6, y: 5.5, s: 1.2, seed: 0.6 }, { t: 'torchPurple', x: 16.5, y: 1.8, s: 1.1 },
        ],
        autoDecor: { density: 0.14, seed: 521 },
      },
    },
  },
];
