/* Meereswelt: neun Bahnen abwechselnd auf See und am Meeresgrund – Strand, Riff, Stege, Krake,
   Piratendeck, Leuchtturmfelsen, Schiffswrack (mit Innen-Map), Perlengrotte und Sturmsee.
   Gleiche Kartenlegende wie in courses.js. */
const SEA_COURSES = [
  {
    name: 'Strandbucht', par: 3, theme: 'harbor', maxStrokes: 15, hazardText: { water: 'Platsch! In den Gezeitentümpel', oob: 'Platsch! Ins Meer' },
    intro: 'Vom Sandstrand auf den hölzernen Steg. Zwei Felsen federn den Ball zurück, der Gezeitentümpel vor dem Loch kostet einen Schlag.',
    map: [
      '......................',
      '..ssss#######.........',
      '..sTss#######.........',
      '..ssss#######.........',
      '..........###.........',
      '..........###.........',
      '..........####ww###...',
      '..........#########...',
      '..........####..#H#...',
      '......................',
    ],
    obstacles: [
      { type: 'bumper', x: 8.5, y: 1.7, r: 0.42, style: 'rock' },
      { type: 'bumper', x: 10.6, y: 3.3, r: 0.42, style: 'rock' },
    ],
    decor: [
      { t: 'palm', x: 1.2, y: 1.2, s: 1.5, seed: 0.3 }, { t: 'palm', x: 5.6, y: 4.3, s: 1.3, seed: 0.8 }, { t: 'shell', x: 3.2, y: 4.4, s: 1.2, seed: 0.6 }, { t: 'starfish', x: 4.6, y: 0.6, s: 1.1, seed: 0.2 },
      { t: 'bollard', x: 13.3, y: 1.15, s: 1.1 }, { t: 'bollard', x: 13.3, y: 3.85, s: 1.1 }, { t: 'bollard', x: 9.7, y: 6.6, s: 1.1 }, { t: 'lantern', x: 13.4, y: 5.0 },
      { t: 'crate', x: 19.6, y: 6.4, s: 1.0 }, { t: 'barrel', x: 19.5, y: 8.6, s: 1.0 }, { t: 'anchor', x: 8.6, y: 8.4, s: 1.2 }, { t: 'buoy', x: 16.5, y: 4.2, s: 1.1 }, { t: 'buoy', x: 5.5, y: 6.4, s: 1.0 },
      { t: 'lighthouse', x: 20.8, y: 1.2, s: 1.4 }, { t: 'rock', x: 20.9, y: 1.9, s: 1.5 },
    ],
    autoDecor: { density: 0.14, seed: 201 },
  },
  {
    name: 'Muschelriff', par: 3, theme: 'reef', maxStrokes: 15, hazardText: { water: 'Hinab in die Tiefseeschlucht' },
    intro: 'Zwei Schluchten, dazwischen ein schmaler Grat. Die Strömung schiebt den Ball erst nach oben, dann nach unten – wer zu zaghaft schlägt, treibt in die Tiefe.',
    map: [
      '.........................',
      '..######wwww#########....',
      '..T#####wwww##########...',
      '..#####################..',
      '..######wwww########H#...',
      '..######wwww#########....',
      '.........................',
    ],
    obstacles: [
      { type: 'field', x: 5, y: 1, w: 5, h: 5, fx: 0, fy: -3.2, style: 'current' },
      { type: 'field', x: 13, y: 1, w: 5, h: 5, fx: 0, fy: 3.2, style: 'current' },
      { type: 'bumper', x: 15.5, y: 2.3, r: 0.4, style: 'coral' },
      { type: 'bumper', x: 18.5, y: 4.2, r: 0.4, style: 'coral' },
    ],
    decor: [
      { t: 'coral', x: 1.0, y: 3.5, s: 1.6, seed: 0.4 }, { t: 'coral', x: 23.5, y: 2.6, s: 1.5, seed: 0.9 }, { t: 'seaweed', x: 22.6, y: 5.6, s: 1.4, seed: 0.2 }, { t: 'seaweed', x: 4.5, y: 6.5, s: 1.3, seed: 0.7 },
      { t: 'shell', x: 12.5, y: 0.6, s: 1.2, seed: 0.6 }, { t: 'starfish', x: 19.5, y: 6.5, s: 1.2, seed: 0.3 }, { t: 'fish', x: 9.5, y: 0.2, s: 1.1, seed: 0.5 }, { t: 'fish', x: 14.5, y: 6.7, s: 1.0, seed: 0.1 },
      { t: 'jelly', x: 2.5, y: 0.3, s: 1.2, seed: 0.4 },
    ],
    autoDecor: { density: 0.4, seed: 203 },
  },
  {
    name: 'Fischerpier', par: 4, theme: 'harbor', maxStrokes: 18, hazardText: { oob: 'Platsch! Ins Hafenbecken' },
    views: [{ x: 5, y: 6, w: 4, h: 2, look: { x: 16, y: 7 } }],
    intro: 'Über den Fischersteg zum Ruderboot – es pendelt zwischen den Stegen. Drüben rollt ein Fass hin und her, dahinter wartet das Loch.',
    map: [
      '..........................',
      '..######..................',
      '..T#####..................',
      '..######..................',
      '.....##...................',
      '.....##...................',
      '.....####......#########..',
      '.....####......####H####..',
      '..........................',
    ],
    obstacles: [
      { type: 'ferry', x0: 8.6, y0: 7, x1: 14.4, y1: 7, w: 1.6, h: 1.0, wait: 1.8, travel: 2.4, style: 'boat', flat: true },
      { type: 'mover', x0: 16.5, y0: 6.7, x1: 22.5, y1: 6.7, w: 0.7, h: 0.7, period: 5, phase: 0.25, style: 'barrel' },
      { type: 'bumper', x: 4.3, y: 2.5, r: 0.38, style: 'rock' },
    ],
    decor: [
      { t: 'bollard', x: 8.4, y: 6.4, s: 1.1 }, { t: 'bollard', x: 8.4, y: 7.7, s: 1.1 }, { t: 'bollard', x: 15.4, y: 6.4, s: 1.1 }, { t: 'bollard', x: 15.4, y: 7.7, s: 1.1 },
      { t: 'lantern', x: 5.5, y: 3.5 }, { t: 'lantern', x: 23.5, y: 5.6 }, { t: 'crate', x: 1.2, y: 1.4, s: 1.1 }, { t: 'crate', x: 1.3, y: 3.6, s: 1.0 }, { t: 'barrel', x: 7.4, y: 0.6, s: 1.0 },
      { t: 'anchor', x: 24.5, y: 8.5, s: 1.2 }, { t: 'buoy', x: 11.5, y: 4.2, s: 1.1 }, { t: 'buoy', x: 12.5, y: 9.4, s: 1.0 }, { t: 'rock', x: 20.5, y: 9.6, s: 1.4 },
    ],
    autoDecor: { density: 0.12, seed: 205 },
  },
  {
    name: 'Krakengrotte', par: 3, theme: 'reef', maxStrokes: 18, hazardText: { water: 'Hinab in die Tiefseeschlucht' },
    intro: 'In der Grotte haust die Krake. Ihre drei Fangarme kreisen langsam – wer den Takt findet, rollt zwischen ihnen hindurch zum Loch.',
    map: [
      '....................',
      '..T#####............',
      '..######............',
      '....############....',
      '....############....',
      '....############....',
      '....############....',
      '....############....',
      '....############....',
      '..........#####H#...',
      '..........#######...',
      '....................',
    ],
    obstacles: [
      { type: 'rotor', x: 10, y: 6, blades: 3, len: 3.4, speed: 0.75, thick: 0.24, hubR: 0.75, style: 'tentacle', e: 0.7, height: 0.5 },
      { type: 'magnet', x: 14.5, y: 8.6, r: 2.4, slow: 3.2, style: 'coral' },
      { type: 'bumper', x: 5.2, y: 4.2, r: 0.4, style: 'rock' },
    ],
    decor: [
      { t: 'bones', x: 1.3, y: 4.0, s: 1.3 }, { t: 'chest', x: 18.5, y: 3.5, s: 1.2 }, { t: 'coral', x: 16.8, y: 1.6, s: 1.5, seed: 0.5 }, { t: 'coral', x: 2.2, y: 8.5, s: 1.4, seed: 0.9 },
      { t: 'seaweed', x: 8.5, y: 11.2, s: 1.4, seed: 0.3 }, { t: 'seaweed', x: 17.6, y: 6.8, s: 1.3, seed: 0.6 }, { t: 'starfish', x: 5.5, y: 9.6, s: 1.1, seed: 0.7 }, { t: 'shell', x: 12.5, y: 2.4, s: 1.2, seed: 0.2 },
      { t: 'fish', x: 3.5, y: 0.4, s: 1.1, seed: 0.3 }, { t: 'fish', x: 17.5, y: 9.8, s: 1.0, seed: 0.8 }, { t: 'jelly', x: 14.5, y: 0.5, s: 1.3, seed: 0.2 },
    ],
    autoDecor: { density: 0.38, seed: 207 },
  },
  {
    name: 'Piratendeck', par: 3, theme: 'deck', maxStrokes: 18, hStep: 0.6, hazardText: { oob: 'Platsch! Über Bord' },
    views: [{ x: 2, y: 2, w: 10, h: 5, look: { x: 10.4, y: 4.5 } }],
    intro: 'Zwei Schiffe, dazwischen offenes Meer. Über die Planken hinauf zum Bug – die Kanone schießt den Ball aufs Nachbarschiff. Dort schwingt die Rah quer über das Deck.',
    map: [
      '............................',
      '............................',
      '..####x#####.....#####x####.',
      '..T#########.....##########.',
      '..##########.....##########.',
      '..##########.....#######H##.',
      '..##########.....##########.',
      '............................',
      '............................',
    ],
    heights: [
      '............................',
      '............................',
      '..1111111222.....1111111111.',
      '..1111111222.....1111111111.',
      '..1111111222.....1111111111.',
      '..1111111222.....1111111111.',
      '..1111111222.....1111111111.',
      '............................',
      '............................',
    ],
    obstacles: [
      { type: 'field', x: 7, y: 2, w: 2, h: 5, fx: -2.2, fy: 0, style: 'slope', base: 1, rise: 1 },
      { type: 'cannon', x: 10.4, y: 4.5, base: 0, amp: 0.22, speed: 0.8, range: 8.2, catchR: 0.6, loadTime: 0.7 },
      { type: 'mover', x0: 3.5, y0: 5.5, x1: 6.3, y1: 5.5, w: 0.7, h: 0.7, period: 4, style: 'barrel' },
      { type: 'rotor', x: 21, y: 4.5, blades: 1, len: 1.9, thick: 0.18, hubR: 0.3, style: 'log', e: 0.6, swing: { amp: Math.PI / 3, speed: 1.4 }, phase: Math.PI / 2, height: 0.5 },
      { type: 'mover', x0: 12.5, y0: 8.6, x1: 16.5, y1: 8.6, w: 1.6, h: 0.8, period: 7, style: 'shark' },
    ],
    decor: [
      { t: 'mast', x: 6.5, y: 2.5, z: 1.0, s: 1.6, seed: 0.3 }, { t: 'mast', x: 22.5, y: 2.5, z: 1.0, s: 1.6, seed: 0.7 },
      { t: 'barrel', x: 3.0, y: 2.5, z: 0.6, s: 0.9 }, { t: 'crate', x: 4.0, y: 2.5, z: 0.6, s: 0.9 }, { t: 'crate', x: 18.0, y: 6.5, z: 0.6, s: 0.9 }, { t: 'barrel', x: 25.5, y: 6.5, z: 0.6, s: 0.9 },
      { t: 'lantern', x: 11.5, y: 2.4, z: 1.2 }, { t: 'lantern', x: 26.5, y: 2.4, z: 0.6 }, { t: 'anchor', x: 2.4, y: 6.5, z: 0.6, s: 1.0 },
      { t: 'buoy', x: 14.5, y: 0.8, s: 1.0 }, { t: 'buoy', x: 9.5, y: 8.3, s: 1.0 },
    ],
    autoDecor: { density: 0.05, seed: 209 },
  },
  {
    name: 'Leuchtturmfelsen', par: 5, theme: 'harbor', maxStrokes: 22, hStep: 0.4, hazardText: { oob: 'Von der Klippe ins Meer' },
    intro: 'Serpentinen den Felsen hinauf zum Leuchtturm. Schräge Banden lenken den Ball um die Kehren. Auf der zweiten Kehre bläst der Wind entgegen, ganz oben drückt er den Ball vom Geländer weg zur Klippe.',
    map: [
      '................',
      '..#H##########..',
      '..##oooooooo##..',
      '............##..',
      '..############..',
      '..##............',
      '..##............',
      '..############..',
      '............##..',
      '............##..',
      '..T###########..',
      '................',
    ],
    heights: [
      '................',
      '..333333333333..',
      '..333333333322..',
      '............22..',
      '..222222222222..',
      '..11............',
      '..11............',
      '..111111111111..',
      '............00..',
      '............00..',
      '..000000000000..',
      '................',
    ],
    obstacles: [
      { type: 'field', x: 12, y: 8, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 0, rise: 1 },
      { type: 'field', x: 2, y: 5, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 1, rise: 1 },
      { type: 'field', x: 12, y: 2, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 2, rise: 1 },
      { type: 'field', x: 4, y: 4, w: 8, h: 1, fx: -2.4, fy: 0, style: 'wind' },
      { type: 'field', x: 4, y: 1, w: 8, h: 2, fx: 0, fy: 0.9, style: 'wind' },
      // schräge Banden in allen sechs Kehren: der Ball wird um die Ecke gelenkt
      { type: 'wall', x0: 12.8, y0: 11, x1: 14, y1: 9.8, extend: 0 },
      { type: 'wall', x0: 14, y0: 8.2, x1: 12.8, y1: 7, extend: 0 },
      { type: 'wall', x0: 3.2, y0: 8, x1: 2, y1: 6.8, extend: 0 },
      { type: 'wall', x0: 2, y0: 5.2, x1: 3.2, y1: 4, extend: 0 },
      { type: 'wall', x0: 12.8, y0: 5, x1: 14, y1: 3.8, extend: 0 },
      { type: 'wall', x0: 14, y0: 2.2, x1: 12.8, y1: 1, extend: 0 },
      { type: 'wall', x0: 2, y0: 2.2, x1: 3.2, y1: 3, extend: 0 },
    ],
    decor: [
      { t: 'lighthouse', x: 1.1, y: 1.6, z: 1.2, s: 1.7 }, { t: 'rock', x: 1.2, y: 2.3, z: 1.2, s: 1.4 }, { t: 'rock', x: 14.8, y: 1.2, z: 1.2, s: 1.2 },
      { t: 'rock', x: 15.0, y: 6.0, s: 1.6 }, { t: 'rock', x: 0.9, y: 8.8, s: 1.5 },
      { t: 'buoy', x: 15.5, y: 10.3, s: 1.0 }, { t: 'buoy', x: 0.5, y: 5.6, s: 1.0 }, { t: 'lantern', x: 14.5, y: 4.5, z: 0.8 }, { t: 'lantern', x: 1.4, y: 7.5, z: 0.4 }, { t: 'anchor', x: 5.0, y: 11.4, s: 1.1 },
    ],
    autoDecor: { density: 0.1, seed: 211 },
  },
  {
    name: 'Schiffswrack', par: 6, theme: 'reef', maxStrokes: 24, hazardText: { water: 'Hinab in die Tiefseeschlucht', oob: 'In den Schlick gesunken' },
    views: [{ x: 7, y: 5, w: 11, h: 2, look: { x: 16, y: 5.4 } }],
    intro: 'Am Meeresgrund liegt ein altes Piratenschiff. Durch das breite Leck im Rumpf geht es hinein – drinnen hängt das Deck schief, Fässer rollen, und die Luke schließt sich alle paar Sekunden.',
    map: [
      '......................',
      '..T#######............',
      '..########............',
      '.......###............',
      '.......###............',
      '.......########oo#....',
      '.......###########....',
      '......................',
    ],
    obstacles: [
      { type: 'door', x: 16, y: 5.4, r: 1.25, style: 'wreck', px: 16.8, py: 3.6 },
      { type: 'bumper', x: 5.5, y: 1.5, r: 0.4, style: 'coral' },
      { type: 'bumper', x: 9.2, y: 3.2, r: 0.4, style: 'coral' },
      { type: 'field', x: 10, y: 5, w: 5, h: 2, fx: 0, fy: -2.2, style: 'current' },
      { type: 'mover', x0: 11, y0: 3.6, x1: 20, y1: 3.6, w: 1.6, h: 0.8, period: 8, style: 'shark' },
    ],
    decor: [
      { t: 'anchor', x: 3.5, y: 4.5, s: 1.3 }, { t: 'bones', x: 12.5, y: 7.6, s: 1.2 }, { t: 'coral', x: 1.2, y: 3.8, s: 1.5, seed: 0.3 }, { t: 'seaweed', x: 5.5, y: 6.6, s: 1.5, seed: 0.6 },
      { t: 'seaweed', x: 11.5, y: 1.8, s: 1.3, seed: 0.1 }, { t: 'shell', x: 9.5, y: 0.6, s: 1.2, seed: 0.8 }, { t: 'starfish', x: 4.5, y: 3.4, s: 1.1, seed: 0.4 },
      { t: 'fish', x: 14.5, y: 1.2, s: 1.1, seed: 0.6 }, { t: 'fish', x: 6.5, y: 0.5, s: 1.0, seed: 0.2 }, { t: 'jelly', x: 20.5, y: 7.5, s: 1.3, seed: 0.5 },
    ],
    autoDecor: { density: 0.36, seed: 213 },
    inner: {
      name: 'Im Wrack', theme: 'wreck', hStep: 0.5, look: { x: 15.5, y: 7.5 }, hazardText: { oob: 'Durch das Leck gespült' },
      map: [
        '....................',
        '..T#######..........',
        '..########..........',
        '..######............',
        '.......########.....',
        '.......########.....',
        '.......###..#######.',
        '.......###..###H###.',
        '....................',
      ],
      heights: [
        '....................',
        '..00000000..........',
        '..00000000..........',
        '..000000............',
        '.......00000000.....',
        '.......00000000.....',
        '.......000..0000000.',
        '.......000..0000000.',
        '....................',
      ],
      obstacles: [
        { type: 'field', x: 2, y: 1, w: 17, h: 7, fx: 1.5, fy: 0, style: 'slope', base: 0, rise: 1 },
        { type: 'mover', x0: 7.6, y0: 4.5, x1: 12.4, y1: 4.5, w: 0.7, h: 0.7, period: 3.6, style: 'barrel' },
        { type: 'mover', x0: 12.4, y0: 5.5, x1: 7.6, y1: 5.5, w: 0.7, h: 0.7, period: 4.4, phase: 0.3, style: 'barrel' },
        { type: 'gate', x: 13.5, y: 6.0, w: 3, h: 0.3, period: 9, open: 0.62, phase: 0.2 },
        { type: 'rotor', x: 16.6, y: 6.6, blades: 2, len: 1.0, speed: -1.2, thick: 0.15, hubR: 0.33, style: 'tentacle', e: 0.7, height: 0.4 },
      ],
      decor: [
        { t: 'chest', x: 4.5, y: 0.4, s: 1.3 }, { t: 'barrel', x: 1.2, y: 2.5, s: 1.0 }, { t: 'barrel', x: 9.5, y: 1.5, s: 1.0 }, { t: 'crate', x: 9.4, y: 2.6, s: 1.0 }, { t: 'bones', x: 5.5, y: 4.5, s: 1.2 },
        { t: 'skull', x: 13.5, y: 4.4 }, { t: 'seaweed', x: 6.4, y: 7.6, s: 1.2, seed: 0.5 }, { t: 'coral', x: 19.5, y: 5.6, s: 1.2, seed: 0.3 }, { t: 'fish', x: 11.0, y: 7.4, s: 0.9, seed: 0.7 },
        { t: 'lantern', x: 2.5, y: 3.6 }, { t: 'lantern', x: 18.5, y: 8.4 },
      ],
      autoDecor: { density: 0.22, seed: 215 },
    },
  },
  {
    name: 'Perlengrotte', par: 5, theme: 'reef', maxStrokes: 22, hazardText: { water: 'Hinab in die Tiefseeschlucht' },
    intro: 'Ein langer Weg über den Meeresgrund, an Korallen vorbei. Am Ende treibt die Strömung alles in den Strudel, und der Strudel wirft den Ball geradewegs in die Zauberperle. Wer sie berührt, trägt den Perlenfluch: Der Ball bleibt für den Rest der Bahn träge.',
    map: [
      '................................',
      '..#########################.....',
      '..T########################.....',
      '..#########################.....',
      '....................#######.....',
      '....................###..###....',
      '....................###..#H#....',
      '....................###..###....',
      '....................#######.....',
      '................................',
    ],
    obstacles: [
      { type: 'field', x: 16, y: 1, w: 4, h: 3, fx: 2.6, fy: 0, style: 'current' },
      { type: 'turntable', x: 21.6, y: 2.5, r: 1.6, speed: 1.7, exit: 90, style: 'whirl', captureSpeed: 13, eject: 7.5 },
      { type: 'magnet', x: 21.6, y: 7.3, r: 3.0, strength: 12, style: 'pearl', curse: 2.0 },
      { type: 'magnet', x: 26.5, y: 8.4, r: 2.2, slow: 3.4, style: 'coral' },
      { type: 'bumper', x: 5.5, y: 3.4, r: 0.38, style: 'coral' },
      { type: 'bumper', x: 9.5, y: 1.7, r: 0.38, style: 'coral' },
      { type: 'bumper', x: 13.8, y: 3.2, r: 0.36, style: 'rock' },
      { type: 'bumper', x: 17.6, y: 1.5, r: 0.38, style: 'coral' },
    ],
    decor: [
      { t: 'pearl', x: 23.5, y: 5.6, s: 1.2, seed: 0.3 }, { t: 'pearl', x: 24.4, y: 6.8, s: 1.0, seed: 0.7 }, { t: 'pearl', x: 27.6, y: 1.4, s: 1.0, seed: 0.5 }, { t: 'shell', x: 1.2, y: 1.5, s: 1.3, seed: 0.2 }, { t: 'shell', x: 28.5, y: 3.5, s: 1.2, seed: 0.8 },
      { t: 'coral', x: 17.5, y: 4.6, s: 1.5, seed: 0.5 }, { t: 'coral', x: 28.4, y: 7.5, s: 1.3, seed: 0.1 }, { t: 'seaweed', x: 18.5, y: 8.5, s: 1.4, seed: 0.9 }, { t: 'starfish', x: 4.5, y: 4.6, s: 1.1, seed: 0.4 },
      { t: 'jelly', x: 16.5, y: 0.4, s: 1.3, seed: 0.6 }, { t: 'fish', x: 29.5, y: 1.5, s: 1.0, seed: 0.3 }, { t: 'fish', x: 18.5, y: 6.5, s: 1.0, seed: 0.9 },
    ],
    autoDecor: { density: 0.36, seed: 217 },
  },
  {
    name: 'Sturmsee', par: 5, theme: 'harbor', maxStrokes: 24, hazardText: { oob: 'Platsch! In die Sturmsee' },
    views: [{ x: 7, y: 1, w: 3, h: 3, look: { x: 11, y: 5.7 } }, { x: 10, y: 5, w: 8, h: 3, look: { x: 20.8, y: 10.2 } }],
    intro: 'Drei Inseln in tobender See. Das Ruderboot bringt den Ball zur Mittelinsel, wo die Welle über die Planken rollt und alles mitspült, was auf ihr liegt – wer schneller ist als die Welle, rollt hindurch. Das Schiff setzt zum Leuchtturmfelsen über.',
    map: [
      '............................',
      '..sss#####..................',
      '..#T######..................',
      '..sss#####..................',
      '............................',
      '..........########..........',
      '..........########..........',
      '..........########..........',
      '............................',
      '....................#######.',
      '....................###H###.',
      '....................#######.',
      '............................',
    ],
    obstacles: [
      { type: 'ferry', x0: 9.3, y0: 2.5, x1: 11.0, y1: 5.7, w: 1.6, h: 1.0, wait: 1.8, travel: 2.6, style: 'boat', flat: true },
      { type: 'wave', x0: 10.6, y0: 6.5, x1: 17.4, y1: 6.5, w: 0.6, h: 3, period: 6.5, push: 16 },
      { type: 'field', x: 10, y: 5, w: 8, h: 3, fx: 0, fy: -1.4, style: 'wind' },
      { type: 'ferry', x0: 17.3, y0: 6.5, x1: 20.8, y1: 10.2, w: 2.6, h: 1.4, wait: 2.0, travel: 3.4, phase: 0.45, style: 'ship', flat: true },
      { type: 'bumper', x: 22.5, y: 9.6, r: 0.36, style: 'rock' },
    ],
    decor: [
      { t: 'lighthouse', x: 26.4, y: 8.6, s: 1.7 }, { t: 'rock', x: 26.5, y: 9.3, s: 1.5 }, { t: 'rock', x: 19.4, y: 12.0, s: 1.4 }, { t: 'rock', x: 8.5, y: 8.6, s: 1.3 },
      { t: 'palm', x: 1.0, y: 0.8, s: 1.4, seed: 0.4 }, { t: 'palm', x: 4.5, y: 4.4, s: 1.2, seed: 0.9 }, { t: 'bollard', x: 9.7, y: 1.4, s: 1.1 }, { t: 'bollard', x: 9.7, y: 3.6, s: 1.1 },
      { t: 'bollard', x: 17.6, y: 5.4, s: 1.1 }, { t: 'bollard', x: 17.6, y: 7.6, s: 1.1 }, { t: 'lantern', x: 14.0, y: 4.5 }, { t: 'lantern', x: 20.5, y: 12.4 },
      { t: 'buoy', x: 14.5, y: 2.5, s: 1.1 }, { t: 'buoy', x: 5.5, y: 7.5, s: 1.0 }, { t: 'buoy', x: 23.5, y: 5.5, s: 1.0 }, { t: 'anchor', x: 1.3, y: 4.6, s: 1.1 }, { t: 'crate', x: 24.5, y: 12.4, s: 1.0 },
    ],
    autoDecor: { density: 0.12, seed: 219 },
  },
  {
    name: 'Haifischbucht', par: 8, theme: 'harbor', maxStrokes: 32, hazardText: { oob: 'Platsch! Ins Meer', water: 'Platsch! In die Haibucht', shark: 'Vom Hai gefressen!' },
    views: [
      { x: 8, y: 1, w: 4, h: 3, look: { x: 13.8, y: 6.5 } },
      { x: 13, y: 5, w: 12, h: 5, look: { x: 31, y: 7.5 } },
      { x: 29, y: 5, w: 9, h: 5, look: { x: 34, y: 12.5 } },
      { x: 33, y: 10, w: 2, h: 5, look: { x: 27.5, y: 17.5 } },
    ],
    intro: 'Die große Überfahrt: Vom Hafensteg mit dem Ruderboot zum Windsteg, wo Böen den Ball quer schieben. Dann über die Rampe hinweg über die Haibucht – der Hai springt im Takt, wer im falschen Moment fliegt, wird gefressen. Weiter über die Welleninsel, den Steg mit dem Fallgatter und das Piratenschiff zum Leuchtturm.',
    map: [
      '........................................',
      '..##########............................',
      '..#T########............................',
      '..##########............................',
      '........................................',
      '.............############wwww#########..',
      '.............############wwww#########..',
      '.............############wwww#########..',
      '.............############wwww#########..',
      '.............############wwww#########..',
      '.................................##.....',
      '.................................##.....',
      '.................................##.....',
      '.................................##.....',
      '.................................##.....',
      '........................................',
      '....................###########.........',
      '....................###########.........',
      '....................##H########.........',
      '....................###########.........',
      '....................###########.........',
      '........................................',
    ],
    obstacles: [
      { type: 'mover', x0: 5.5, y0: 2.5, x1: 10, y1: 2.5, w: 0.7, h: 0.7, period: 5, style: 'barrel' },
      { type: 'bumper', x: 7.5, y: 1.5, r: 0.36, style: 'rock' },
      { type: 'ferry', x0: 11.3, y0: 2.5, x1: 13.8, y1: 6.5, w: 1.6, h: 1.0, wait: 1.8, travel: 2.6, style: 'boat', flat: true },
      { type: 'field', x: 15, y: 5, w: 3, h: 5, fx: 0, fy: 4.5, style: 'wind', gust: 1.1, phase: 0 },
      { type: 'field', x: 18.5, y: 5, w: 3, h: 5, fx: 0, fy: -4.5, style: 'wind', gust: 0.9, phase: 2.1 },
      { type: 'bumper', x: 21.6, y: 5.9, r: 0.34, style: 'rock' },
      { type: 'bumper', x: 21.6, y: 9.1, r: 0.34, style: 'rock' },
      { type: 'ramp', x: 22.4, y: 6.5, w: 1.6, h: 2, angle: 0, minSpeed: 3, speed: 6.5, land: 5.8 },
      { type: 'sharkjump', x: 27, y: 7.5, w: 4, h: 5, period: 3.6, jump: 0.42, phase: 0.2, axis: 'y', height: 1.7 },
      { type: 'wall', x0: 29, y0: 5, x1: 29, y1: 10, extend: 0, h: 0.5 },
      { type: 'wave', x0: 29.8, y0: 7.5, x1: 37.4, y1: 7.5, w: 0.6, h: 5, period: 7, push: 14 },
      { type: 'field', x: 29, y: 5, w: 9, h: 5, fx: 0, fy: 1.2, style: 'wind' },
      { type: 'gate', x: 34, y: 12.5, w: 2, h: 0.3, period: 6, open: 0.55, phase: 0.3 },
      { type: 'ferry', x0: 33.8, y0: 14.3, x1: 27.5, y1: 17.5, w: 2.6, h: 1.4, wait: 2.2, travel: 3.6, phase: 0.4, style: 'ship', flat: true },
      { type: 'rotor', x: 24.5, y: 18.5, blades: 1, len: 1.7, thick: 0.18, hubR: 0.3, style: 'log', e: 0.6, swing: { amp: Math.PI / 3, speed: 1.3 }, phase: Math.PI / 2, height: 0.5 },
      { type: 'bumper', x: 28.2, y: 16.8, r: 0.36, style: 'rock' },
      { type: 'bumper', x: 21.2, y: 19.6, r: 0.36, style: 'rock' },
      { type: 'mover', x0: 14, y0: 3.6, x1: 29, y1: 3.6, w: 1.6, h: 0.8, period: 11, style: 'shark' },
      { type: 'mover', x0: 31, y0: 21.6, x1: 19, y1: 21.6, w: 1.6, h: 0.8, period: 9, phase: 0.3, style: 'shark' },
      { type: 'mover', x0: 39, y0: 16.5, x1: 32, y1: 16.5, w: 1.6, h: 0.8, period: 9, phase: 0.6, style: 'shark' },
    ],
    decor: [
      { t: 'bollard', x: 11.4, y: 1.4, s: 1.1 }, { t: 'bollard', x: 11.4, y: 3.6, s: 1.1 }, { t: 'bollard', x: 13.4, y: 5.4, s: 1.1 }, { t: 'bollard', x: 13.4, y: 9.6, s: 1.1 },
      { t: 'crate', x: 2.6, y: 1.4, s: 1.0 }, { t: 'barrel', x: 2.5, y: 3.6, s: 1.0 }, { t: 'lantern', x: 5.5, y: 0.6 }, { t: 'anchor', x: 12.5, y: 0.8, s: 1.2 },
      { t: 'palm', x: 12.4, y: 10.4, s: 1.2, seed: 0.8 }, { t: 'starfish', x: 12.6, y: 4.6, s: 1.1, seed: 0.2 }, { t: 'buoy', x: 27, y: 4.2, s: 1.1 }, { t: 'buoy', x: 27, y: 10.8, s: 1.1 },
      { t: 'lantern', x: 24.5, y: 4.6 }, { t: 'lantern', x: 38.5, y: 4.6 }, { t: 'crate', x: 38.4, y: 9.5, s: 1.0 }, { t: 'barrel', x: 29.6, y: 4.5, s: 1.0 },
      { t: 'bollard', x: 32.6, y: 14.6, s: 1.1 }, { t: 'bollard', x: 35.4, y: 14.6, s: 1.1 }, { t: 'lantern', x: 35.5, y: 10.4 }, { t: 'buoy', x: 31.5, y: 12.5, s: 1.0 }, { t: 'buoy', x: 37.5, y: 13.5, s: 1.0 },
      { t: 'lighthouse', x: 19.0, y: 16.4, s: 1.7 }, { t: 'rock', x: 19.2, y: 17.2, s: 1.5 }, { t: 'rock', x: 31.5, y: 20.5, s: 1.4 }, { t: 'rock', x: 18.6, y: 20.8, s: 1.3 },
      { t: 'bollard', x: 30.6, y: 16.4, s: 1.1 }, { t: 'lantern', x: 20.5, y: 21.4 }, { t: 'anchor', x: 30.5, y: 21.5, s: 1.2 }, { t: 'crate', x: 29.5, y: 15.5, s: 1.0 },
      { t: 'buoy', x: 8.5, y: 5.5, s: 1.0 }, { t: 'buoy', x: 16.5, y: 12.5, s: 1.0 }, { t: 'buoy', x: 4.5, y: 12.5, s: 1.0 }, { t: 'palm', x: 25.6, y: 3.2, s: 1.3, seed: 0.4 },
    ],
    autoDecor: { density: 0.1, seed: 221 },
    inner: { // Wer vom Hai gefressen wird, landet hier – kurzer Weg, mit ein bis zwei Schlägen ist die Bahn zu Ende
      name: 'Haimagen', theme: 'belly', stomach: true, look: { x: 11.5, y: 2.5 }, hazardText: { lava: 'Zischhh! Magensäure', oob: 'In die Speiseröhre gerutscht' },
      map: [
        '..............',
        '..T#########..',
        '..##########..',
        '..ll#######H..',
        '..............',
      ],
      obstacles: [],
      decor: [
        { t: 'chest', x: 13.2, y: 1.2, s: 1.3 }, { t: 'anchor', x: 0.8, y: 1.6, s: 1.2 }, { t: 'bones', x: 5.5, y: 0.4, s: 1.3 }, { t: 'skull', x: 9.5, y: 0.5 }, { t: 'barrel', x: 13.3, y: 3.5, s: 1.0 },
        { t: 'crate', x: 6.5, y: 4.5, s: 1.0 }, { t: 'bones', x: 10.5, y: 4.6, s: 1.2 }, { t: 'skull', x: 1.2, y: 3.4 }, { t: 'lantern', x: 7.5, y: 0.5 },
      ],
      autoDecor: { density: 0.2, seed: 223 },
    },
  },
];
