/* Profi-Welt: acht Bahnen mit eigenen Mechaniken – Windmühlen, Kanone, Magnete, Drehscheiben,
   Schrumpftrank, Schalter und Zaubertor. Gleiche Kartenlegende wie in courses.js. */
const PRO_COURSES = [
  {
    name: 'Mühlenwiese', par: 3, theme: 'meadow', maxStrokes: 15,
    intro: 'Eine Windmühle versperrt den Weg. Nur durch die schmale Tür geht es weiter – und die Flügel streichen daran vorbei.',
    map: [
      '........................',
      '..###ss####.............',
      '..T##ss####.............',
      '..###ss####.............',
      '........###.............',
      '........###.............',
      '........#############...',
      '........###########H#...',
      '........#############...',
      '........................',
    ],
    obstacles: [
      { type: 'windmill', x: 14, y: 7.5, axis: 'y', w: 3, depth: 1.2, gap: 0.8, speed: 1.2 },
      { type: 'bumper', x: 9.5, y: 3.3, r: 0.4 },
    ],
    decor: [{ t: 'tower', x: 1, y: 6, s: 1.2 }, { t: 'flowerbush', x: 12, y: 9.5 }, { t: 'flowerbush', x: 4, y: 5.2 }],
    autoDecor: { density: 0.4, seed: 101 },
  },
  {
    name: 'Nebelmoor', par: 4, theme: 'forest', maxStrokes: 18,
    intro: 'Ein breiter Fluss ohne Brücke – nur die kleine Rampe am Ufer bringt den Ball hinüber. Dahinter wacht die Mühle über das Loch.',
    map: [
      '........................',
      '..######wwww##########..',
      '..T#####wwww##########..',
      '..######wwww####ii####..',
      '..######wwww####ii####..',
      '..######wwww##########..',
      '..######wwww######wwww..',
      '..######wwww###########.',
      '..######wwww######H###..',
      '........................',
    ],
    obstacles: [
      { type: 'ramp', x: 6.5, y: 3.5, w: 1.5, h: 2, angle: 0, minSpeed: 3, speed: 4.5, land: 4.6 },
      { type: 'windmill', x: 15, y: 6, axis: 'x', w: 6, depth: 1.2, gap: 1.5, speed: 1.0 },
    ],
    atmo: 'fog',
    decor: [{ t: 'tree', x: 9.5, y: 0.3, s: 1.3, glow: true }, { t: 'crystal', x: 22.5, y: 3 }, { t: 'lantern', x: 8.4, y: 9.4 }, { t: 'lantern', x: 11.6, y: 9.4 }],
    autoDecor: { density: 0.5, seed: 103 },
  },
  {
    name: 'Zwergenkanone', par: 3, theme: 'forge', maxStrokes: 18,
    intro: 'Über den Lavasee führt kein Weg – nur die schwenkende Kanone der Zwerge. Rollt der Ball hinein, wird er abgefeuert: in die Richtung, in die das Rohr gerade zeigt.',
    map: [
      '..........................',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..T#####xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsssH#..',
      '..######xxlllllllllsss##..',
      '..######xxlllllllllsss##..',
      '..........................',
    ],
    obstacles: [
      { type: 'cannon', x: 6.9, y: 4.5, base: 0, amp: 0.5, speed: 0.9, range: 12.5, catchR: 0.6, loadTime: 0.7 },
      { type: 'rotor', x: 4.5, y: 2.2, blades: 1, len: 1.2, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.1, speed: 2.2 }, phase: 0 },
      { type: 'rotor', x: 4.5, y: 6.8, blades: 1, len: 1.2, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.1, speed: 2.2 }, phase: Math.PI },
    ],
    decor: [{ t: 'brazier', x: 8.5, y: 0.4 }, { t: 'brazier', x: 8.5, y: 8.6 }, { t: 'anvil', x: 1, y: 6.5 }, { t: 'gold', x: 24.5, y: 2 }],
    autoDecor: { density: 0.35, seed: 107 },
  },
  {
    name: 'Korallenriff', par: 4, theme: 'reef', maxStrokes: 18, hazardText: { water: 'Hinab in die Tiefseeschlucht' },
    intro: 'Drei Zauberkorallen am Meeresgrund: Die rote zieht den Ball an, die grüne stößt ihn ab, die blaue bremst ihn aus. Wer stur aufs Loch zielt, rutscht in die Tiefseeschlucht.',
    map: [
      '........................',
      '..###################...',
      '..T##################...',
      '..#######w#####w#####...',
      '..#######w#####w#####...',
      '..###################...',
      '..###################...',
      '..###ww############H#...',
      '..###ww##############...',
      '........................',
    ],
    obstacles: [
      { type: 'magnet', x: 12.5, y: 2.4, r: 3.4, strength: 11, style: 'coral' },
      { type: 'magnet', x: 16, y: 6.8, r: 3.2, strength: -13, style: 'coral' },
      { type: 'magnet', x: 8.5, y: 6.5, r: 3, slow: 3.6, style: 'coral' },
    ],
    decor: [{ t: 'chest', x: 1, y: 3, s: 1.3 }, { t: 'coral', x: 22.5, y: 3, s: 1.6, seed: 0.9 }, { t: 'seaweed', x: 22.3, y: 8.5, s: 1.5, seed: 0.2 }, { t: 'coral', x: 0.8, y: 8.6, s: 1.4, seed: 0.5 }],
    autoDecor: { density: 0.45, seed: 109 },
  },
  {
    name: 'Uhrwerk', par: 4, theme: 'clockwork', maxStrokes: 18,
    intro: 'Im Inneren des großen Uhrturms. Zwei Zahnräder nehmen einen langsamen Ball mit und werfen ihn an der Rinne wieder aus – zu schnelle Bälle rollen einfach darüber hinweg.',
    map: [
      '..........................',
      '..######..........#####...',
      '..T#####..........##H##...',
      '..######..........#####...',
      '.....#..............#.....',
      '.....#..............#.....',
      '...#####..........#####...',
      '...#####..........#####...',
      '...####################...',
      '...#####..........#####...',
      '...#####..........#####...',
      '..........................',
    ],
    obstacles: [
      { type: 'turntable', x: 5.5, y: 8.5, r: 2, speed: 1.6, exit: 0 },
      { type: 'turntable', x: 20.5, y: 8.5, r: 2, speed: -1.6, exit: -90 },
      { type: 'gate', x: 13, y: 8.5, w: 0.3, h: 1, period: 5, open: 0.5, phase: 0, axis: 'y' },
    ],
    decor: [
      { t: 'clock', x: 13, y: 0.6, s: 2.2 },
      { t: 'gearFlat', x: 12.5, y: 4.3, s: 2.6, speed: 0.35, seed: 0.3 }, { t: 'gearFlat', x: 9.2, y: 2.2, s: 1.6, speed: -0.55, seed: 0.7 }, { t: 'gearFlat', x: 16.2, y: 2.4, s: 1.5, speed: -0.5, seed: 0.2 },
      { t: 'gearFlat', x: 12.5, y: 10.4, s: 2.2, speed: -0.4, seed: 0.6 }, { t: 'gearFlat', x: 1.2, y: 9.6, s: 1.3, speed: 0.6, seed: 0.1 }, { t: 'gearFlat', x: 24.6, y: 5.2, s: 1.4, speed: 0.5, seed: 0.9 },
      { t: 'gear', x: 1.2, y: 4.6, s: 1.5, seed: 0.35 }, { t: 'gear', x: 24.5, y: 1.2, s: 1.4, seed: 0.8 },
      { t: 'pipe', x: 9.3, y: 0.6, s: 1.3, seed: 0.2 }, { t: 'pipe', x: 16.7, y: 0.6, s: 1.3, seed: 0.6 }, { t: 'pipe', x: 17.2, y: 5.4, s: 1.1, seed: 0.4 },
    ],
    autoDecor: { density: 0.12, seed: 113 },
  },
  {
    name: 'Piratenbucht', par: 5, theme: 'harbor', maxStrokes: 22, hStep: 0.35, hazardText: { oob: 'Platsch! Ins Meer' },
    views: [{ x: 2, y: 13.5, w: 9.5, h: 4, look: { x: 17.5, y: 15 } }, { x: 17, y: 12.5, w: 7.5, h: 5, look: { x: 20.5, y: 9.5 } }, { x: 17, y: 6.5, w: 7.5, h: 4.5, look: { x: 8, y: 8 } }],
    intro: 'Vom Strand über den Steg ins Ruderboot, hinüber zur Felseninsel und die Rampe hinauf zur Festung – dort rollt eine Kanonenkugel. Das Piratenschiff bringt den Ball über die Bucht zum Leuchtturmfelsen, wo es noch einmal hinaufgeht zum Loch.',
    map: [
      '..........................',
      '..........................',
      '..######..................',
      '..##H###..................',
      '..######..................',
      '....##....................',
      '....##....................',
      '..######.........#######..',
      '..######.........#######..',
      '..######.........#######..',
      '..######.........#######..',
      '....................##....',
      '....................##....',
      '.................#######..',
      '..sssss####......#######..',
      '..sTsss####......#######..',
      '..sssss..........#######..',
      '..........................',
    ],
    heights: [
      '..........................',
      '..........................',
      '..333333..................',
      '..333333..................',
      '..333333..................',
      '....22....................',
      '....22....................',
      '..222222.........2222222..',
      '..222222.........2222222..',
      '..222222.........2222222..',
      '..222222.........2222222..',
      '....................11....',
      '....................11....',
      '.................1111111..',
      '..111111111......1111111..',
      '..111111111......1111111..',
      '..11111..........1111111..',
      '..........................',
    ],
    obstacles: [
      { type: 'ferry', x0: 10.6, y0: 15, x1: 17.4, y1: 15, w: 1.6, h: 1.0, wait: 1.6, travel: 2.6, style: 'boat', flat: true },
      { type: 'field', x: 20, y: 11, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 1, rise: 1 },
      { type: 'mover', x0: 17.6, y0: 9.6, x1: 22.4, y1: 9.6, w: 0.7, h: 0.7, period: 4.5, phase: 0, style: 'cannonball' },
      { type: 'ferry', x0: 17.3, y0: 8, x1: 6.7, y1: 8, w: 2.6, h: 1.4, wait: 2.0, travel: 4.0, phase: 0.4, style: 'ship', flat: true },
      { type: 'field', x: 2, y: 7, w: 6, h: 4, fx: 2.4, fy: 0, style: 'wind' },
      { type: 'field', x: 4, y: 5, w: 2, h: 2, fx: 0, fy: 2.2, style: 'slope', base: 2, rise: 1 },
    ],
    decor: [
      { t: 'lighthouse', x: 1.2, y: 2.6, s: 1.6 }, { t: 'rock', x: 1.4, y: 3.2, s: 1.6 },
      { t: 'barrel', x: 22.6, y: 7.5, s: 1.1 }, { t: 'barrel', x: 23.4, y: 7.6, s: 1.0 }, { t: 'crate', x: 22.6, y: 13.5, s: 1.1 }, { t: 'anchor', x: 23.5, y: 15.6, s: 1.2 },
      { t: 'bollard', x: 10.7, y: 14.15, s: 1.1 }, { t: 'bollard', x: 17.3, y: 13.4, s: 1.1 }, { t: 'bollard', x: 7.4, y: 7.3, s: 1.1 }, { t: 'bollard', x: 17.4, y: 7.3, s: 1.1 },
      { t: 'crate', x: 2.5, y: 14.5, s: 1.0 }, { t: 'barrel', x: 2.5, y: 16.5, s: 1.0 }, { t: 'lantern', x: 7.5, y: 14.2 }, { t: 'lantern', x: 22.5, y: 10.6 }, { t: 'lantern', x: 6.6, y: 2.4 },
    ],
    autoDecor: { density: 0.14, seed: 127 },
  },
  {
    name: 'Hexenküche', par: 5, theme: 'witch', maxStrokes: 20, atmo: 'mist',
    intro: 'Durch den Hexengarten bis zur Hütte – und hinein! Drinnen wartet der Hexentopf: Wer über die Rampe hineintrifft, wird geschrumpft und passt kurz durch den Spalt zum Loch.',
    map: [
      '......................',
      '..######..............',
      '..T#####..............',
      '..######..............',
      '.....###..............',
      '.....###..............',
      '.....##########.......',
      '.....##########.......',
      '.....##########.......',
      '.............##.......',
      '.............##.......',
      '......................',
    ],
    obstacles: [
      { type: 'door', x: 14, y: 10.3, r: 0.6, s: 3.4 },
      { type: 'rotor', x: 10, y: 7.5, blades: 2, len: 1.2, speed: 2, style: 'broom' },
      { type: 'bumper', x: 6.5, y: 4.5, r: 0.4, style: 'mushroom' },
    ],
    decor: [
      { t: 'deadTree', x: 9.5, y: 2.5, s: 1.6 }, { t: 'deadTree', x: 18, y: 8.5, s: 1.4 }, { t: 'pumpkin', x: 1, y: 6 }, { t: 'pumpkin', x: 11.5, y: 10 }, { t: 'pumpkin', x: 16.5, y: 5.6 },
      { t: 'skull', x: 4.2, y: 9.6 }, { t: 'mushroom', x: 3, y: 5.2, s: 1.2, seed: 0.7 }, { t: 'lantern', x: 12.2, y: 5.4 }, { t: 'broom', x: 16.4, y: 9.6, seed: 0.8 },
    ],
    autoDecor: { density: 0.4, seed: 131 },
    inner: {
      name: 'Hexenhütte', theme: 'hut', atmo: 'mist', look: { x: 3.5, y: 5.8 },
      map: [
        '................',
        '..T######.#####.',
        '..#######.#####.',
        '..#######.##H##.',
        '..#######.#####.',
        '..#######.#####.',
        '..#############.',
        '..#############.',
        '................',
      ],
      obstacles: [
        { type: 'ramp', x: 2.5, y: 2.5, w: 2, h: 1.5, angle: 90, minSpeed: 2.5, speed: 4.2, land: 1.7 },
        { type: 'cauldron', x: 3.5, y: 5.8, r: 0.75, duration: 20, scale: 0.45, exit: 0 },
        { type: 'wall', x0: 10, y0: 5.9, x1: 10, y1: 6.74, extend: 0, h: 0.8 },
        { type: 'wall', x0: 10, y0: 7.26, x1: 10, y1: 8.1, extend: 0, h: 0.8 },
        { type: 'rotor', x: 12.5, y: 5.6, blades: 2, len: 1, speed: -2.2, style: 'broom' },
      ],
      decor: [
        { t: 'shelf', x: 5.5, y: 0.5, s: 1.3, seed: 0.2 }, { t: 'shelf', x: 12.5, y: 0.4, s: 1.2, seed: 0.6 }, { t: 'candle', x: 1.4, y: 3.5, s: 1.2 }, { t: 'candle', x: 15.4, y: 2.5, s: 1.2 },
        { t: 'candle', x: 9.5, y: 4.6, s: 1.1 }, { t: 'skull', x: 8.3, y: 8.5 }, { t: 'broom', x: 1.3, y: 6.5, seed: 0.3 }, { t: 'bottle', x: 15.4, y: 6.4, s: 1.3, seed: 0.1 }, { t: 'bottle', x: 9.5, y: 1.6, s: 1.2, seed: 0.55 },
      ],
      autoDecor: { density: 0.25, seed: 133 },
    },
  },
  {
    name: 'Sultanspalast', par: 5, theme: 'palace', maxStrokes: 25, hStep: 0.5,
    views: [{ x: 18, y: 0.5, w: 4.5, h: 4.4, look: { x: 21, y: 9.5 } }, { x: 20, y: 6.5, w: 2.5, h: 4, look: { x: 17, y: 9.5 } }],
    intro: 'Die Zikkurat des Sultans: Drei Terrassen, jede eine Stufe höher, verbunden nur über Rampen. Ganz oben wartet das Loch – bewacht von Palastwachen, Wüstenwind und einem Tor, das sich im Takt öffnet und schließt.',
    map: [
      '........................',
      '..####################..',
      '..T###################..',
      '..##................##..',
      '..##................##..',
      '..##..############..##..',
      '..##..############..##..',
      '..##..##........##..##..',
      '..##..##........##..##..',
      '..##..######H#..######..',
      '..##..########..######..',
      '..##..##........##..##..',
      '..##..##........##..##..',
      '..##..############..##..',
      '..##..############..##..',
      '..##................##..',
      '..##................##..',
      '..####################..',
      '..####################..',
      '........................',
    ],
    heights: [
      '........................',
      '..00000000000000000000..',
      '..00000000000000000000..',
      '..00................00..',
      '..00................00..',
      '..00..111111111111..00..',
      '..00..111111111111..00..',
      '..00..11........11..00..',
      '..00..11........11..00..',
      '..00..11112222..110000..',
      '..00..11112222..110000..',
      '..00..11........11..00..',
      '..00..11........11..00..',
      '..00..111111111111..00..',
      '..00..111111111111..00..',
      '..00................00..',
      '..00................00..',
      '..00000000000000000000..',
      '..00000000000000000000..',
      '........................',
    ],
    obstacles: [
      // Rampen: fx/fy zeigen bergab, base = untere Stufe, rise = Stufen aufwärts
      { type: 'field', x: 18, y: 9, w: 2, h: 2, fx: 2.8, fy: 0, style: 'slope', base: 0, rise: 1 },
      { type: 'field', x: 8, y: 9, w: 2, h: 2, fx: -2.8, fy: 0, style: 'slope', base: 1, rise: 1 },
      { type: 'field', x: 8, y: 5, w: 8, h: 2, fx: -3, fy: 0, style: 'wind' },
      { type: 'field', x: 20, y: 11, w: 2, h: 5, fx: 0, fy: 2.2, style: 'wind' },
      { type: 'windmill', x: 21, y: 5.5, axis: 'x', w: 2, depth: 1.2, gap: 0.8, speed: 1.2 },
      { type: 'gate', x: 10, y: 10, w: 0.3, h: 2, period: 6, open: 0.5, phase: 0, axis: 'y' },
      { type: 'mover', x0: 7, y0: 2, x1: 19.5, y1: 2, w: 0.7, h: 0.7, period: 9, phase: 0.3, style: 'guard' },
      { type: 'mover', x0: 8, y0: 6, x1: 15.5, y1: 6, w: 0.7, h: 0.7, period: 6, phase: 0, style: 'guard' },
      { type: 'mover', x0: 7, y0: 13, x1: 16.5, y1: 13, w: 0.7, h: 0.7, period: 7, phase: 0.5, style: 'guard' },
    ],
    decor: [
      { t: 'tower', x: 8.6, y: 7.4, s: 1.6, dome: '#2fb8c9' }, { t: 'tower', x: 15.4, y: 7.4, s: 1.6, dome: '#2fb8c9' },
      { t: 'tower', x: 8.6, y: 12.4, s: 1.6, dome: '#2fb8c9' }, { t: 'tower', x: 15.4, y: 12.4, s: 1.6, dome: '#2fb8c9' },
      { t: 'palm', x: 4.6, y: 3.6, s: 1.3, seed: 0.3 }, { t: 'palm', x: 19.5, y: 3.6, s: 1.3, seed: 0.7 }, { t: 'palm', x: 4.6, y: 15.4, s: 1.3, seed: 0.5 }, { t: 'palm', x: 19.5, y: 15.4, s: 1.3, seed: 0.2 },
      { t: 'urn', x: 12, y: 3.6, s: 1.2 }, { t: 'urn', x: 12, y: 15.5, s: 1.2 }, { t: 'cactus', x: 4.5, y: 12, s: 1.2, seed: 0.7 }, { t: 'cactus', x: 19.5, y: 7.5, s: 1.1, seed: 0.3 },
    ],
    autoDecor: { density: 0.28, seed: 137 },
  },
  {
    name: 'Pyramide', par: 6, theme: 'desert', maxStrokes: 30, hazardText: { water: 'Platsch! In die Oase', oob: 'Aus! In den Wüstensand' },
    views: [{ x: 1.5, y: 0.5, w: 3.5, h: 15, look: { x: 3.5, y: 18 } }, { x: 1.5, y: 15.5, w: 5, h: 4, look: { x: 9, y: 17.5 } }, { x: 5.5, y: 7, w: 4.5, h: 9, look: { x: 8, y: 3 } }, { x: 5.5, y: 0.5, w: 9.5, h: 6.5, look: { x: 13, y: 9 } }],
    intro: 'Der Weg zur Pyramide des Pharaos: ein Serpentinenweg durch die Wüste, an der Oase vorbei, gegen den Wüstenwind – bis zum Eingang. Drinnen wartet die große Grabkammer mit Rampen, einem Katapult über den Grabschacht und der Kammer ganz oben.',
    map: [
      '.........................',
      '..#T#.#########..........',
      '..###.#########..........',
      '..###.##www####..........',
      '..###.##www####..........',
      '..###.#########..........',
      '..###.#########..........',
      '..###.####.####..........',
      '..###.####.####..........',
      '..###.####.####..........',
      '..###.####.####..........',
      '..###.####.#oo#..........',
      '..###.####...............',
      '..###.####...............',
      '..###.####...............',
      '..###.####...............',
      '..########...............',
      '..########...............',
      '..########...............',
      '.........................',
      '.........................',
      '.........................',
      '.........................',
      '.........................',
      '.........................',
    ],
    obstacles: [
      { type: 'door', x: 13, y: 11.6, r: 0.95, style: 'pyramid', px: 16.5, py: 17.6, base: 11 },
      // schräge Banden in den Kurven (wie in der Skizze)
      { type: 'wall', x0: 2, y0: 16.6, x1: 4.3, y1: 19 },
      { type: 'wall', x0: 7.2, y0: 19, x1: 10, y1: 16.2 },
      { type: 'wall', x0: 6, y0: 2.3, x1: 7.5, y1: 1 },
      // Trennwand links der Oase (bis ans Wasser hoch): schmaler Windstreifen links, Spur rechts direkt auf das Wasser zu
      { type: 'wall', x0: 8, y0: 3, x1: 8, y1: 9.5, extend: 0 },
      // Mauer an der Unterkante der Oase: die Spur endet unter dem Wasser
      { type: 'wall', x0: 8, y0: 5, x1: 10, y1: 5, extend: 0.1 },
      // rechte Kante der Oase geschlossen – ins Wasser geht es nur von unten aus der Spur
      { type: 'wall', x0: 11, y0: 3, x1: 11, y1: 5, extend: 0.1 },
      // Bande in der oberen rechten Ecke: lenkt den Sturm-Ball aus dem Windkanal hinunter in den rechten Gang
      { type: 'wall', x0: 12.6, y0: 1, x1: 14, y1: 2.4 },
      // Mauer an der Oberkante der Oase: die obere Reihe wird zum Windkanal über das Wasser
      { type: 'wall', x0: 8, y0: 3, x1: 11, y1: 3, extend: 0.1 },
      // Wüstenwind (Pfeile aus der Skizze): im mittleren Gang hinauf zur Oase, über der Oase nach rechts, rechts kräftig hinunter zum Eingang
      // Streifen: Sturm hinauf (stärker als die Reibung – der Ball wird bis zur Pyramide durchgepustet), Spur: mäßiger Wind zur Oase
      { type: 'field', x: 6, y: 5, w: 2, h: 9, fx: 0, fy: -6.5, style: 'wind' },
      { type: 'field', x: 8, y: 5, w: 2, h: 9, fx: 0.5, fy: -3.4, style: 'wind' },
      { type: 'field', x: 6, y: 1, w: 5, h: 2, fx: 6.5, fy: 0, style: 'wind' },
      { type: 'field', x: 11, y: 1, w: 4, h: 10.5, fx: 0, fy: 6.5, style: 'wind' },
      // Trichter vor dem Pyramidentor
      { type: 'wall', x0: 11, y0: 10.1, x1: 12.2, y1: 11.9, extend: 0.1 },
      { type: 'wall', x0: 15, y0: 10.1, x1: 13.8, y1: 11.9, extend: 0.1 },
      // Steinweiche an der Gabelung: schräger Balken am Ende der Trennwand, schwenkt im Takt und lenkt den Ball in den offenen Weg
      { type: 'rotor', x: 8, y: 9.25, blades: 1, len: 3.6, thick: 0.2, hubR: 0.12, style: 'stone', e: 0.3, swing: { amp: Math.PI / 6, speed: 1.6 }, phase: Math.PI / 2 },
    ],
    decor: [
      { t: 'obelisk', x: 5.5, y: 0.4, s: 1.4 }, { t: 'obelisk', x: 15.6, y: 0.4, s: 1.4 }, { t: 'obelisk', x: 0.8, y: 19.6, s: 1.3 }, { t: 'obelisk', x: 10.6, y: 15.5, s: 1.2 },
      { t: 'palm', x: 5.5, y: 11, s: 1.3, seed: 0.4 }, { t: 'palm', x: 1, y: 10, s: 1.2, seed: 0.8 }, { t: 'palm', x: 10.5, y: 8.5, s: 1.1, seed: 0.2 }, { t: 'palm', x: 15.8, y: 7, s: 1.3, seed: 0.6 },
      { t: 'bones', x: 5.4, y: 14.5 }, { t: 'urn', x: 10.5, y: 12.6, s: 1.1 }, { t: 'cactus', x: 15.7, y: 10.4, s: 1.2, seed: 0.7 }, { t: 'rock', x: 1, y: 3, s: 1.3 },
    ],
    autoDecor: { density: 0.22, seed: 139 },
    inner: {
      name: 'Grabkammer', theme: 'tomb', hStep: 0.5, look: { x: 3.5, y: 21 }, hazardText: { oob: 'In den Grabschacht gestürzt' },
      views: [{ x: 1.5, y: 21.5, w: 33, h: 6, look: { x: 3.5, y: 20 } }, { x: 1.5, y: 9.5, w: 6, h: 12, look: { x: 11.5, y: 9.5 } }, { x: 27.5, y: 13.5, w: 7, h: 8.5, look: { x: 30.5, y: 8 } }, { x: 27.5, y: 5.5, w: 7, h: 8, look: { x: 24, y: 8.5 } }],
      map: [
        '....................................',
        '..............########..............',
        '..............###H####..............',
        '..............########..............',
        '..............########..............',
        '................####................',
        '................####........######..',
        '..........################..######..',
        '..........ssss####################..',
        '..........ssss####################..',
        '..#####...ssss############..######..',
        '..#####...ssss############..######..',
        '..#####.............................',
        '..#####.............................',
        '..#####.....................######..',
        '..#####.....................######..',
        '..#####.....................######..',
        '..#####.....................######..',
        '..#####.....................######..',
        '..#####.....................######..',
        '...##..........................##...',
        '...##..........................##...',
        '..########ss############ss########..',
        '..########ss############ss########..',
        '..######x####x########x####x######..',
        '..###############T################..',
        '..################################..',
        '....................................',
      ],
      heights: [
        '....................................',
        '..............33333333..............',
        '..............33333333..............',
        '..............33333333..............',
        '..............33333333..............',
        '................2222................',
        '................2222........111111..',
        '..........2222222222222222..111111..',
        '..........222222222222222211111111..',
        '..........222222222222222211111111..',
        '..11111...2222222222222222..111111..',
        '..11111...2222222222222222..111111..',
        '..11111.............................',
        '..11111.............................',
        '..11111.....................111111..',
        '..11111.....................111111..',
        '..11111.....................111111..',
        '..11111.....................111111..',
        '..11111.....................111111..',
        '..11111.....................111111..',
        '...00..........................00...',
        '...00..........................00...',
        '..00000000000000000000000000000000..',
        '..00000000000000000000000000000000..',
        '..00000000000000000000000000000000..',
        '..00000000000000000000000000000000..',
        '..00000000000000000000000000000000..',
        '....................................',
      ],
      obstacles: [
        // Treppen (Rampen) aus der Halle auf die Galerien
        { type: 'field', x: 3, y: 20, w: 2, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 0, rise: 1 },
        { type: 'field', x: 31, y: 20, w: 2, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 0, rise: 1 },
        // Katapult auf der linken Galerie: wirft über den Grabschacht auf die Sand-Landezone der Plattform
        { type: 'cannon', style: 'catapult', x: 4.5, y: 12.5, base: -0.405, amp: 0.45, speed: 0.9, range: 6.7, catchR: 0.6, loadTime: 0.8 },
        // rechte Galerie: Sprung über den Spalt, Pendelbalken, Rampe hinauf zur Plattform
        { type: 'ramp', x: 28, y: 14, w: 6, h: 2, angle: -90, minSpeed: 2.5, speed: 4.5, land: 2.6 },
        { type: 'rotor', x: 30.5, y: 17.5, blades: 1, len: 1.6, thick: 0.14, hubR: 0.25, style: 'log', swing: { amp: 1.2, speed: 2.0 }, phase: 0 },
        { type: 'field', x: 26, y: 8, w: 2, h: 2, fx: 2.8, fy: 0, style: 'slope', base: 1, rise: 1 },
        // Plattform: rollender Felsbrocken, Steintor vor der letzten Rampe
        { type: 'mover', x0: 11, y0: 10.2, x1: 24.5, y1: 10.2, w: 0.8, h: 0.8, period: 8, phase: 0.2, style: 'boulder' },
        { type: 'gate', x: 18, y: 7.35, w: 4, h: 0.3, period: 6, open: 0.5, phase: 0, axis: 'x' },
        { type: 'field', x: 16, y: 5, w: 4, h: 2, fx: 0, fy: 2.8, style: 'slope', base: 2, rise: 1 },
      ],
      decor: [
        { t: 'sarcophagus', x: 17.5, y: 0.6, s: 1.5 }, { t: 'brazier', x: 13.5, y: 0.6 }, { t: 'brazier', x: 21.5, y: 0.6 },
        { t: 'sarcophagus', x: 4.5, y: 9.6, s: 1.2, seed: 0.3 }, { t: 'sarcophagus', x: 30.5, y: 5.6, s: 1.2, seed: 0.7 },
        { t: 'brazier', x: 9.5, y: 6.6 }, { t: 'brazier', x: 25.5, y: 6.6 }, { t: 'brazier', x: 1.4, y: 21.5 }, { t: 'brazier', x: 34.6, y: 21.5 },
        { t: 'obelisk', x: 8.5, y: 27.4, s: 1.2 }, { t: 'obelisk', x: 26.5, y: 27.4, s: 1.2 },
        { t: 'urn', x: 8.5, y: 20.5, s: 1.1 }, { t: 'urn', x: 27.5, y: 20.5, s: 1.1 }, { t: 'skull', x: 12, y: 27.3 }, { t: 'bones', x: 22.5, y: 27.4 },
        { t: 'urn', x: 9.5, y: 12.6, s: 1.0 }, { t: 'urn', x: 27.5, y: 12.6, s: 1.0 },
      ],
      autoDecor: { density: 0.16, seed: 141 },
    },
  },
];

/* Welten: jede mit eigener Bahnliste. Neue Welten hier anhängen. */
const WORLDS = [
  { id: 'normal', name: 'Normal-Welt', short: 'Normal', courses: COURSES },
  { id: 'pro', name: 'Profi-Welt', short: 'Profi', courses: PRO_COURSES },
];
