/* Sturmhimmel: Stufe „Legende“ – neun extra große Bahnen über den Wolken: schwebende Felsinseln,
   Aufwinde, Heißluftballons und Luftschiffe, Böen, Blitzfelder, Gewitterwolken, Propeller; die Neunte
   führt in die Sturmfestung mit eigener Innen-Map. Gleiche Kartenlegende wie in courses.js. */
const STORM_COURSES = [
  {
    name: 'Inselsprung', par: 4, theme: 'storm', maxStrokes: 18, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 2, w: 8, h: 5, look: { x: 16, y: 4.5 } }, { x: 13, y: 2, w: 8, h: 5, look: { x: 28, y: 4.5 } }],
    map: [
      '..................................',
      '..................................',
      '..########...########....########.',
      '..########...########....########.',
      '..#T######...########....#####H##.',
      '..########...########....########.',
      '..########...########....########.',
      '..................................',
      '..................................',
    ],
    intro: 'Drei Inseln im Sturm. Aufwinde tragen den Ball über die Wolkenschlucht – genau in Rollrichtung, also gerade anrollen. Auf der Mittelinsel schlägt im Takt ein Blitz ein; wer dann dort steht, wird getroffen. Vor dem Loch dreht ein Propeller.',
    obstacles: [
      { type: 'updraft', x: 8, y: 3, w: 2, h: 3, minSpeed: 2.5, land: 6, fly: 7 },
      { type: 'rotor', x: 29.5, y: 5.9, blades: 3, len: 0.9, thick: 0.12, hubR: 0.26, speed: 2.4, height: 0.4, style: 'propeller', e: 0.7 },
      { type: 'lightning', x: 17.5, y: 4.5, w: 2, h: 5, period: 4.5, phase: 0, warn: 1.0, strike: 0.35 },
      { type: 'updraft', x: 19, y: 3, w: 2, h: 3, minSpeed: 2.5, land: 6.5, fly: 7 },
      { type: 'bumper', x: 27.5, y: 3.2, r: 0.4, style: 'orb', kick: 8 },
      { type: 'wall', x0: 32, y0: 5.8, x1: 33, y1: 4.8, extend: 0 },
      { type: 'wall', x0: 33, y0: 3.2, x1: 32, y1: 2.2, extend: 0 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.6, y: 1.4, s: 1.1 }, { t: 'windsock', x: 9.5, y: 7.6, s: 1.1, seed: 0.8 }, { t: 'cloudDark', x: 11, y: 1.0, s: 1.4 }, { t: 'cloudDark', x: 23, y: 8.4, s: 1.3 },
      { t: 'rock', x: 14.4, y: 7.4, s: 1.2 }, { t: 'lightningrod', x: 21.4, y: 1.5, s: 1.1 }, { t: 'windsock', x: 25.5, y: 7.6, s: 1.0, seed: 0.2 }, { t: 'pine', x: 33.4, y: 7.2, s: 1.2 },
    ],
    autoDecor: { density: 0.14, seed: 401 },
  },
  {
    name: 'Ballonfahrt', par: 5, theme: 'storm', maxStrokes: 20, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 4, w: 8, h: 5, look: { x: 14, y: 6 } }, { x: 18, y: 2, w: 10, h: 8, look: { x: 32, y: 6 } }],
    map: [
      '........................................',
      '........................................',
      '..................##########............',
      '..................##########............',
      '..########........##########.......####.',
      '..########........##########.......####.',
      '..#T######........##########.......##H#.',
      '..########........##########.......####.',
      '..########........##########.......####.',
      '..................##########............',
      '........................................',
      '........................................',
    ],
    intro: 'Ein Heißluftballon pendelt zur Mittelinsel, wo Böen den Ball quer schieben und eine Gewitterwolke patrouilliert. Der zweite Ballon bringt ihn zur Zielinsel – wer den Korb verfehlt, fällt in die Wolken.',
    obstacles: [
      { type: 'ferry', x0: 9.4, y0: 6, x1: 17.6, y1: 6, w: 1.3, h: 1.3, wait: 2.6, travel: 3.6, style: 'balloon', flat: true },
      { type: 'field', x: 19, y: 2, w: 3, h: 8, fx: 0, fy: 4.2, style: 'wind', gust: 1.0, phase: 0 },
      { type: 'field', x: 24, y: 2, w: 3, h: 8, fx: 0, fy: -4.2, style: 'wind', gust: 0.8, phase: 2.0 },
      { type: 'mover', x0: 19.2, y0: 6, x1: 26.8, y1: 6, w: 1.4, h: 1.0, period: 7, style: 'stormcloud', e: 0.6 },
      { type: 'bumper', x: 22.5, y: 3.0, r: 0.38, style: 'orb', kick: 8 },
      { type: 'bumper', x: 22.5, y: 9.0, r: 0.38, style: 'orb', kick: 8 },
      { type: 'ferry', x0: 27.6, y0: 6, x1: 34.4, y1: 6, w: 1.3, h: 1.3, wait: 2.4, travel: 3.2, phase: 0.5, style: 'balloon', flat: true },
      { type: 'wall', x0: 38, y0: 4, x1: 39, y1: 5, extend: 0 },
      { type: 'wall', x0: 39, y0: 8, x1: 38, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'windsock', x: 2.6, y: 3.4, s: 1.1, seed: 0.7 }, { t: 'lightningrod', x: 8.5, y: 9.5, s: 1.0 }, { t: 'cloudDark', x: 13.5, y: 2.5, s: 1.5 }, { t: 'cloudDark', x: 13, y: 10.5, s: 1.3 },
      { t: 'rock', x: 18.4, y: 10.4, s: 1.2 }, { t: 'lightningrod', x: 27.4, y: 1.4, s: 1.1 }, { t: 'cloudDark', x: 31, y: 2.5, s: 1.4 }, { t: 'cloudDark', x: 31.5, y: 10.5, s: 1.2 }, { t: 'pine', x: 35.4, y: 3.4, s: 1.2 }, { t: 'windsock', x: 38.6, y: 9.6, s: 1.0, seed: 0.2 },
    ],
    autoDecor: { density: 0.12, seed: 403 },
  },
  {
    name: 'Blitzfeld', par: 5, theme: 'storm', maxStrokes: 20, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 2, w: 18, h: 5, look: { x: 22, y: 4 } }, { x: 20, y: 6, w: 4, h: 4, look: { x: 30, y: 8.5 } }],
    map: [
      '......................................',
      '......................................',
      '..####################................',
      '..####################................',
      '..#T##################................',
      '..####################................',
      '..######################..............',
      '....................################..',
      '....................#############H##..',
      '....................################..',
      '......................##############..',
      '......................................',
    ],
    intro: 'Vier Blitzfelder hintereinander, jedes schlägt zu einem anderen Zeitpunkt ein. Der Boden knistert eine Sekunde vorher – dann heißt es warten oder durchrollen. Nach dem Knick wacht ein Propeller vor dem Loch.',
    obstacles: [
      { type: 'lightning', x: 7.5, y: 4.5, w: 2, h: 5, period: 5, phase: 0, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 11.5, y: 4.5, w: 2, h: 5, period: 5, phase: 0.3, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 15.5, y: 4.5, w: 2, h: 5, period: 5, phase: 0.6, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 19.5, y: 4.5, w: 2, h: 5, period: 5, phase: 0.9, warn: 1.0, strike: 0.35 },
      { type: 'wall', x0: 20, y0: 2, x1: 22, y1: 4, extend: 0 },
      { type: 'wall', x0: 20, y0: 10, x1: 22, y1: 8, extend: 0.2 },
      { type: 'rotor', x: 29.5, y: 8.5, blades: 3, len: 1.5, thick: 0.12, hubR: 0.3, speed: 2.0, height: 0.4, style: 'propeller', e: 0.7 },
      { type: 'bumper', x: 25.5, y: 7.6, r: 0.36, style: 'orb', kick: 8 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.4, y: 1.4, s: 1.2 }, { t: 'lightningrod', x: 12.5, y: 1.3, s: 1.1 }, { t: 'lightningrod', x: 12.5, y: 7.6, s: 1.1 }, { t: 'cloudDark', x: 7, y: 9.5, s: 1.5 }, { t: 'cloudDark', x: 28, y: 3.5, s: 1.4 },
      { t: 'windsock', x: 24.5, y: 6.4, s: 1.0, seed: 0.6 }, { t: 'rock', x: 36.4, y: 10.6, s: 1.2 }, { t: 'pine', x: 30.5, y: 11.4, s: 1.2 }, { t: 'windsock', x: 36.4, y: 6.4, s: 1.0, seed: 0.3 },
    ],
    autoDecor: { density: 0.14, seed: 405 },
  },
  {
    name: 'Windbrücke', par: 5, theme: 'storm', maxStrokes: 22, hazardText: { oob: 'Vom Steg in die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 2, w: 6, h: 5, look: { x: 14, y: 3.5 } }, { x: 8, y: 3, w: 8, h: 2, look: { x: 18, y: 3.5 } }, { x: 16, y: 1, w: 6, h: 9, look: { x: 26, y: 6.5 } }, { x: 22, y: 6, w: 8, h: 2, look: { x: 33, y: 6.5 } }],
    map: [
      '......................................',
      '................######................',
      '..######........######................',
      '..######oooooooo######................',
      '..#T####oooooooo######........######..',
      '..######........######........######..',
      '..######........######oooooooo###H##..',
      '................######oooooooo######..',
      '................######........######..',
      '................######........######..',
      '......................................',
      '......................................',
      '......................................',
      '......................................',
    ],
    intro: 'Zwei Hängestege ohne Geländer führen über die Schlucht, und der Sturm bläst in Böen quer über die Planken. Wer zu langsam ist, wird über die Kante geschoben; wer zu schnell ist, fliegt am Ende vorbei.',
    obstacles: [
      { type: 'field', x: 9, y: 3, w: 6, h: 2, fx: 0, fy: 2.6, style: 'wind', gust: 1.1, phase: 0 },
      { type: 'field', x: 23, y: 6, w: 6, h: 2, fx: 0, fy: -2.6, style: 'wind', gust: 0.9, phase: 1.5 },
      { type: 'bumper', x: 18.5, y: 3.2, r: 0.36, style: 'orb', kick: 8 },
      { type: 'lightning', x: 18.5, y: 7.5, w: 3, h: 2, period: 4.8, phase: 0.2, warn: 1.0, strike: 0.35 },
      { type: 'wall', x0: 20, y0: 1, x1: 22, y1: 3, extend: 0 },
      { type: 'wall', x0: 16, y0: 10, x1: 18, y1: 8, extend: 0 },
      { type: 'wall', x0: 35, y0: 4, x1: 36, y1: 5, extend: 0 },
      { type: 'wall', x0: 36, y0: 9, x1: 35, y1: 10, extend: 0 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.5, y: 1.4, s: 1.1 }, { t: 'windsock', x: 7.5, y: 7.5, s: 1.1, seed: 0.8 }, { t: 'windsock', x: 15.5, y: 1.4, s: 1.0, seed: 0.2 }, { t: 'cloudDark', x: 11.5, y: 8.5, s: 1.4 }, { t: 'cloudDark', x: 26, y: 2.5, s: 1.5 },
      { t: 'cloudDark', x: 26, y: 11, s: 1.3 }, { t: 'rock', x: 22.5, y: 9.6, s: 1.2 }, { t: 'lightningrod', x: 36.4, y: 3.4, s: 1.1 }, { t: 'pine', x: 30.4, y: 10.6, s: 1.2 },
    ],
    autoDecor: { density: 0.12, seed: 407 },
  },
  {
    name: 'Luftschiffwerft', par: 6, theme: 'storm', maxStrokes: 24, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 10, w: 8, h: 5, look: { x: 20, y: 11 } }, { x: 17, y: 8, w: 7, h: 7, look: { x: 32, y: 5 } }],
    map: [
      '........................................',
      '........................................',
      '..............................#########.',
      '..............................#########.',
      '..............................#########.',
      '..............................######H##.',
      '..............................#########.',
      '..............................#########.',
      '.................#######......#########.',
      '.................#######................',
      '..########.......#######................',
      '..########.......#######................',
      '..#T######.......#######................',
      '..########.......#######................',
      '..########.......#######................',
      '........................................',
    ],
    intro: 'Die Werftkanone schießt den Ball über die Schlucht auf die Werftinsel – sie schwenkt dabei, der Moment entscheidet. Von dort bringt das Luftschiff den Ball zur Zielinsel, wo ein Fallgitter und ein Propeller das Loch bewachen.',
    obstacles: [
      { type: 'cannon', x: 8.6, y: 12, base: 0, amp: 0.32, speed: 0.9, range: 11, catchR: 0.6, loadTime: 0.7 },
      { type: 'bumper', x: 5.5, y: 10.8, r: 0.36, style: 'orb', kick: 8 },
      { type: 'lightning', x: 20, y: 9.5, w: 3, h: 2, period: 5, phase: 0.4, warn: 1.0, strike: 0.35 },
      { type: 'ferry', x0: 23.4, y0: 12, x1: 29.6, y1: 5.5, w: 2.4, h: 1.4, wait: 2.6, travel: 4.2, phase: 0.3, style: 'airship', flat: true },
      { type: 'gate', x: 33.5, y: 5, w: 0.3, h: 3, period: 6, open: 0.5, phase: 0, axis: 'y' },
      { type: 'rotor', x: 35.5, y: 3.0, blades: 3, len: 1.1, thick: 0.12, hubR: 0.28, speed: 2.2, height: 0.4, style: 'propeller', e: 0.7 },
      { type: 'wall', x0: 38, y0: 2, x1: 39, y1: 3, extend: 0 },
      { type: 'wall', x0: 39, y0: 8, x1: 38, y1: 9, extend: 0 },
    ],
    decor: [
      { t: 'windsock', x: 2.5, y: 9.4, s: 1.1, seed: 0.6 }, { t: 'lightningrod', x: 9.5, y: 15.5, s: 1.0 }, { t: 'cloudDark', x: 13, y: 8, s: 1.5 }, { t: 'cloudDark', x: 13, y: 15, s: 1.2 },
      { t: 'crate', x: 17.5, y: 7.4, s: 1.1 }, { t: 'barrel', x: 18.5, y: 7.4, s: 1.0 }, { t: 'lightningrod', x: 23.6, y: 7.4, s: 1.1 }, { t: 'cloudDark', x: 27, y: 12, s: 1.4 }, { t: 'cloudDark', x: 27, y: 2, s: 1.3 },
      { t: 'banner', x: 30.4, y: 1.4, s: 1.2, seed: 0.3 }, { t: 'banner', x: 38.6, y: 9.6, s: 1.2, seed: 0.8 }, { t: 'pine', x: 34.5, y: 9.5, s: 1.2 },
    ],
    autoDecor: { density: 0.12, seed: 409 },
  },
  {
    name: 'Wolkenschlucht', par: 6, theme: 'storm', maxStrokes: 24, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 2, w: 8, h: 7, look: { x: 18, y: 5 } }, { x: 15, y: 1, w: 10, h: 12, look: { x: 32, y: 10.5 } }],
    map: [
      '......................................',
      '...............##########.............',
      '..########.....##########.............',
      '..########.....##########.............',
      '..########.....##########.............',
      '..#T######.....##########.............',
      '..########.....##########.............',
      '..########.....##########.............',
      '..########.....##########.....#######.',
      '...............##########.....#######.',
      '...............##########.....####H##.',
      '...............##########.....#######.',
      '...............##########.....#######.',
      '..............................#######.',
    ],
    intro: 'Über den Aufwind auf die große Mittelinsel. Dort dreht ein Wirbelsturm: Ein langsamer Ball wird eingefangen und nach Süden geschleudert, wo der zweite Aufwind zur Zielinsel wartet. Blitze halten den Weg kurz.',
    obstacles: [
      { type: 'updraft', x: 8, y: 4, w: 2, h: 3, minSpeed: 2.5, land: 7, fly: 7 },
      { type: 'turntable', x: 19.5, y: 5.5, r: 1.8, speed: 1.9, exit: 90, style: 'tornado', captureSpeed: 9, eject: 6.5 },
      { type: 'lightning', x: 17, y: 10.5, w: 3, h: 2, period: 4.6, phase: 0, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 22, y: 2, w: 3, h: 2, period: 5.2, phase: 0.5, warn: 1.0, strike: 0.35 },
      { type: 'updraft', x: 23, y: 9, w: 2, h: 3, minSpeed: 2.5, land: 7, fly: 7 },
      { type: 'bumper', x: 32.5, y: 9.0, r: 0.36, style: 'orb', kick: 8 },
      { type: 'wall', x0: 36, y0: 8, x1: 37, y1: 9, extend: 0 },
      { type: 'wall', x0: 37, y0: 13, x1: 36, y1: 14, extend: 0 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.5, y: 1.4, s: 1.1 }, { t: 'windsock', x: 9.6, y: 9.5, s: 1.1, seed: 0.3 }, { t: 'cloudDark', x: 12, y: 1.5, s: 1.4 }, { t: 'cloudDark', x: 12, y: 11, s: 1.3 },
      { t: 'lightningrod', x: 14.4, y: 0.6, s: 1.0 }, { t: 'lightningrod', x: 25.5, y: 13.4, s: 1.0 }, { t: 'cloudDark', x: 27.5, y: 4, s: 1.5 }, { t: 'rock', x: 29.5, y: 7.4, s: 1.2 }, { t: 'pine', x: 30.5, y: 14.5, s: 1.2 }, { t: 'windsock', x: 37.5, y: 7.4, s: 1.0, seed: 0.7 },
    ],
    autoDecor: { density: 0.12, seed: 411 },
  },
  {
    name: 'Gewitterkessel', par: 6, theme: 'storm', maxStrokes: 24, hazardText: { oob: 'In den Kessel gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 18, w: 22, h: 4, look: { x: 3.5, y: 8 } }, { x: 2, y: 6, w: 4, h: 12, look: { x: 8, y: 3.5 } }, { x: 20, y: 6, w: 4, h: 12, look: { x: 17, y: 3.5 } }, { x: 6, y: 2, w: 14, h: 4, look: { x: 12.5, y: 3.5 } }],
    map: [
      '..........................',
      '..........................',
      '..######################..',
      '..##########H###########..',
      '..######################..',
      '..######################..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..####..............####..',
      '..######################..',
      '..######################..',
      '..##########T###########..',
      '..######################..',
      '..........................',
      '..........................',
    ],
    intro: 'Ein Ring aus Fels um den tobenden Kessel. Zwei Gewitterwolken laufen den Ring entlang, vier Blitzfelder schlagen versetzt ein. Links- oder rechtsherum, beides führt zum Loch auf der Nordseite.',
    obstacles: [
      { type: 'lightning', x: 4, y: 12, w: 4, h: 2, period: 5.5, phase: 0, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 22, y: 12, w: 4, h: 2, period: 5.5, phase: 0.5, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 8, y: 4, w: 2, h: 4, period: 5.5, phase: 0.25, warn: 1.0, strike: 0.35 },
      { type: 'lightning', x: 18, y: 4, w: 2, h: 4, period: 5.5, phase: 0.75, warn: 1.0, strike: 0.35 },
      { type: 'mover', x0: 4, y0: 19.5, x1: 4, y1: 4.5, w: 1.2, h: 1.0, period: 12, phase: 0, style: 'stormcloud', e: 0.6 },
      { type: 'mover', x0: 22, y0: 4.5, x1: 22, y1: 19.5, w: 1.2, h: 1.0, period: 12, phase: 0.5, style: 'stormcloud', e: 0.6 },
      { type: 'bumper', x: 12.5, y: 18.6, r: 0.36, style: 'orb', kick: 8 },
      { type: 'bumper', x: 10.5, y: 4.4, r: 0.36, style: 'orb', kick: 8 },
      { type: 'bumper', x: 14.5, y: 4.4, r: 0.36, style: 'orb', kick: 8 },
      { type: 'wall', x0: 2, y0: 20, x1: 4, y1: 22, extend: 0 },
      { type: 'wall', x0: 22, y0: 22, x1: 24, y1: 20, extend: 0 },
      { type: 'wall', x0: 2, y0: 4, x1: 4, y1: 2, extend: 0 },
      { type: 'wall', x0: 22, y0: 2, x1: 24, y1: 4, extend: 0 },
    ],
    decor: [
      { t: 'lightningrod', x: 1.2, y: 1.2, s: 1.2 }, { t: 'lightningrod', x: 24.8, y: 1.2, s: 1.2 }, { t: 'lightningrod', x: 1.2, y: 22.8, s: 1.2 }, { t: 'lightningrod', x: 24.8, y: 22.8, s: 1.2 },
      { t: 'cloudDark', x: 12.5, y: 11.5, s: 1.8 }, { t: 'cloudDark', x: 9, y: 9, s: 1.2 }, { t: 'cloudDark', x: 16, y: 14, s: 1.3 }, { t: 'windsock', x: 12.5, y: 0.8, s: 1.1, seed: 0.5 }, { t: 'pine', x: 0.8, y: 12, s: 1.2 },
    ],
    autoDecor: { density: 0.1, seed: 413 },
  },
  {
    name: 'Sturmpfad', par: 6, theme: 'storm', maxStrokes: 26, hazardText: { oob: 'Vom Grat in die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 1, w: 38, h: 3, look: { x: 40.5, y: 2 } }, { x: 40, y: 1, w: 2, h: 9, look: { x: 40.5, y: 10 } }, { x: 8, y: 9, w: 32, h: 3, look: { x: 6.5, y: 10 } }, { x: 6, y: 9, w: 2, h: 4, look: { x: 6.5, y: 12 } }, { x: 2, y: 11, w: 12, h: 2, look: { x: 3.5, y: 11.5 } }],
    map: [
      '............................................',
      '..############oooooooo####################..',
      '..#T##########oooooooo####################..',
      '..############oooooooo####################..',
      '........................................##..',
      '........................................##..',
      '........................................##..',
      '........................................##..',
      '........................................##..',
      '......####################oooooooo########..',
      '......####################oooooooo########..',
      '..#H######################oooooooo########..',
      '..############..............................',
      '............................................',
    ],
    intro: 'Ein langer Grat hoch über den Wolken: hin auf der Nordseite, zurück auf der Südseite. Wo das Geländer fehlt, drücken Böen den Ball zur Kante; an den Kehren lenken Banden, und Blitze fallen im Takt.',
    obstacles: [
      { type: 'field', x: 14, y: 1, w: 8, h: 3, fx: 0, fy: -2.4, style: 'wind', gust: 1.0, phase: 0 },
      { type: 'lightning', x: 30, y: 2, w: 2, h: 3, period: 5, phase: 0.2, warn: 1.0, strike: 0.35 },
      { type: 'rotor', x: 36.5, y: 2, blades: 3, len: 1.0, thick: 0.12, hubR: 0.28, speed: 2.4, height: 0.4, style: 'propeller', e: 0.7 },
      { type: 'wall', x0: 40, y0: 1, x1: 42, y1: 3, extend: 0 },
      { type: 'wall', x0: 42, y0: 10, x1: 40, y1: 12, extend: 0 },
      { type: 'field', x: 26, y: 9, w: 8, h: 3, fx: 0, fy: 2.4, style: 'wind', gust: 0.9, phase: 1.2 },
      { type: 'lightning', x: 19, y: 10, w: 2, h: 3, period: 5, phase: 0.7, warn: 1.0, strike: 0.35 },
      { type: 'bumper', x: 12.5, y: 9.6, r: 0.36, style: 'orb', kick: 8 },
      { type: 'wall', x0: 6, y0: 9, x1: 8, y1: 9, extend: 0 },
      { type: 'wall', x0: 6, y0: 13, x1: 8, y1: 11, extend: 0 },
      { type: 'wall', x0: 2, y0: 12, x1: 3, y1: 13, extend: 0 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.4, y: 0.4, s: 1.1 }, { t: 'windsock', x: 12.5, y: 4.4, s: 1.0, seed: 0.7 }, { t: 'windsock', x: 23.5, y: 4.4, s: 1.0, seed: 0.2 }, { t: 'cloudDark', x: 17.5, y: 6.5, s: 1.6 }, { t: 'cloudDark', x: 30, y: 6, s: 1.4 },
      { t: 'lightningrod', x: 42.6, y: 6.5, s: 1.1 }, { t: 'windsock', x: 24.5, y: 8.4, s: 1.0, seed: 0.5 }, { t: 'windsock', x: 35, y: 12.4, s: 1.0, seed: 0.9 }, { t: 'pine', x: 4.5, y: 13.5, s: 1.2 }, { t: 'rock', x: 14.5, y: 13.4, s: 1.2 }, { t: 'cloudDark', x: 4, y: 6.5, s: 1.3 },
    ],
    autoDecor: { density: 0.1, seed: 415 },
  },
  {
    name: 'Sturmfestung', par: 8, theme: 'storm', maxStrokes: 32, hazardText: { oob: 'In die Wolken gestürzt', lava: 'Zzzt! Blitzpfütze', water: 'Platsch! Regentümpel', zapped: 'Vom Blitz getroffen!' },
    views: [{ x: 2, y: 15, w: 8, h: 6, look: { x: 18, y: 17 } }, { x: 15, y: 14, w: 9, h: 7, look: { x: 33, y: 16.5 } }, { x: 30, y: 13, w: 9, h: 8, look: { x: 36, y: 7 } }, { x: 33, y: 3, w: 7, h: 10, look: { x: 36, y: 1.5 } }],
    map: [
      '..........................................',
      '..................................ooooo...',
      '..................................ooooo...',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '.................................#######..',
      '..............................#########...',
      '...............#########......#########...',
      '..########.....#########......#########...',
      '..########.....#########......#########...',
      '..#T######.....#########......#########...',
      '..########.....#########......#########...',
      '..########.....#########......#########...',
      '..########.....#########......#########...',
      '..........................................',
    ],
    intro: 'Der Weg zur Sturmfestung: mit dem Aufwind über die erste Schlucht, mit dem Ballon über die zweite, dann die Felsrampe hinauf zum Tor – Blitze schlagen davor ein. Drinnen wartet die Sturmhalle mit Propellern, Blitzfeldern, Fallgitter und der Sturmkanone.',
    obstacles: [
      { type: 'updraft', x: 8, y: 16, w: 2, h: 3, minSpeed: 2.5, land: 7.5, fly: 7 },
      { type: 'rotor', x: 5.5, y: 17.5, blades: 3, len: 1.2, thick: 0.12, hubR: 0.28, speed: 2.2, height: 0.4, style: 'propeller', e: 0.7 },
      { type: 'lightning', x: 19, y: 17, w: 2, h: 7, period: 5, phase: 0, warn: 1.0, strike: 0.35 },
      { type: 'ferry', x0: 23.4, y0: 17, x1: 29.6, y1: 17, w: 1.3, h: 1.3, wait: 2.6, travel: 3.4, style: 'balloon', flat: true },
      { type: 'mover', x0: 31, y0: 14.5, x1: 37, y1: 14.5, w: 1.4, h: 1.0, period: 6, style: 'stormcloud', e: 0.6 },
      { type: 'wall', x0: 38, y0: 21, x1: 39, y1: 20, extend: 0 },
      { type: 'wall', x0: 39, y0: 13, x1: 38, y1: 12, extend: 0 },
      { type: 'field', x: 33, y: 3, w: 7, h: 10, fx: 0, fy: -1.6, style: 'wind' },
      { type: 'lightning', x: 36, y: 8, w: 6, h: 2, period: 5.2, phase: 0.4, warn: 1.0, strike: 0.35 },
      { type: 'bumper', x: 34.5, y: 5.2, r: 0.36, style: 'orb', kick: 8 },
      { type: 'bumper', x: 38.5, y: 5.2, r: 0.36, style: 'orb', kick: 8 },
      { type: 'door', x: 36.5, y: 1.6, r: 1.0, style: 'fortress', px: 36.5, py: 0.5, gw: 3.6 },
    ],
    decor: [
      { t: 'lightningrod', x: 2.4, y: 14.4, s: 1.1 }, { t: 'windsock', x: 9.6, y: 21.5, s: 1.0, seed: 0.4 }, { t: 'cloudDark', x: 12, y: 14, s: 1.5 }, { t: 'cloudDark', x: 12, y: 21, s: 1.2 },
      { t: 'lightningrod', x: 15.4, y: 13.4, s: 1.0 }, { t: 'cloudDark', x: 26.5, y: 13.5, s: 1.4 }, { t: 'cloudDark', x: 27, y: 21, s: 1.3 }, { t: 'banner', x: 30.4, y: 12.4, s: 1.2, seed: 0.2 }, { t: 'banner', x: 39.6, y: 21.5, s: 1.2, seed: 0.7 },
      { t: 'banner', x: 32.4, y: 4.4, s: 1.3, seed: 0.6 }, { t: 'banner', x: 40.5, y: 4.4, s: 1.3, seed: 0.3 }, { t: 'lightningrod', x: 32.4, y: 9.5, s: 1.1 }, { t: 'lightningrod', x: 40.5, y: 9.5, s: 1.1 }, { t: 'pine', x: 30.5, y: 21.5, s: 1.2 },
    ],
    autoDecor: { density: 0.1, seed: 417 },
    inner: {
      name: 'Sturmhalle', theme: 'fortress', look: { x: 12, y: 4.5 }, hazardText: { lava: 'Zzzt! Blitzpfütze', oob: 'In den Festungsschacht gestürzt', zapped: 'Vom Blitz getroffen!' },
      views: [{ x: 2, y: 2, w: 22, h: 5, look: { x: 26, y: 4.5 } }, { x: 24, y: 2, w: 8, h: 5, look: { x: 27.5, y: 11 } }, { x: 24, y: 7, w: 8, h: 5, look: { x: 12, y: 15 } }, { x: 2, y: 12, w: 30, h: 6, look: { x: 4, y: 15 } }],
      map: [
        '..................................',
        '..................................',
        '..##############################..',
        '..####l##########l##############..',
        '..#T############################..',
        '..####l##########l##############..',
        '..##############################..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '........................########..',
        '..##############################..',
        '..##########ll##################..',
        '..##H#######ll##################..',
        '..##########ll##################..',
        '..##############################..',
        '..................................',
        '..................................',
      ],
      obstacles: [
        { type: 'rotor', x: 8.5, y: 4.5, blades: 3, len: 1.6, thick: 0.12, hubR: 0.3, speed: 1.8, height: 0.4, style: 'propeller', e: 0.7 },
        { type: 'lightning', x: 14.5, y: 4.5, w: 2, h: 5, period: 4.8, phase: 0, warn: 1.0, strike: 0.35 },
        { type: 'rotor', x: 20.5, y: 4.5, blades: 3, len: 1.6, thick: 0.12, hubR: 0.3, speed: -2.0, phase: 0.8, height: 0.4, style: 'propeller', e: 0.7 },
        { type: 'switch', x: 27.5, y: 4.5, r: 0.55, duration: 18, target: 'A' },
        { type: 'gate', x: 27.5, y: 12, w: 4, h: 0.3, linked: 'A', liftH: 1.5, barH: 1.1 },
        { type: 'lightning', x: 27.5, y: 9, w: 4, h: 2, period: 5.4, phase: 0.5, warn: 1.0, strike: 0.35 },
        { type: 'cannon', x: 26.5, y: 15.5, base: Math.PI, amp: 0.28, speed: 0.8, range: 15, catchR: 0.6, loadTime: 0.7 },
        { type: 'bumper', x: 8.5, y: 13.6, r: 0.4, style: 'orb', kick: 8 },
        { type: 'bumper', x: 8.5, y: 16.4, r: 0.4, style: 'orb', kick: 8 },
        { type: 'wall', x0: 2, y0: 13, x1: 3, y1: 14, extend: 0 },
        { type: 'wall', x0: 3, y0: 17, x1: 2, y1: 16, extend: 0 },
      ],
      decor: [
        { t: 'banner', x: 1.4, y: 1.4, s: 1.3, seed: 0.2 }, { t: 'banner', x: 12.5, y: 0.6, s: 1.2, seed: 0.7 }, { t: 'banner', x: 24.5, y: 0.6, s: 1.2, seed: 0.3 }, { t: 'brazierBlue', x: 32.6, y: 2.5, s: 1.1 }, { t: 'brazierBlue', x: 32.6, y: 11.5, s: 1.1 },
        { t: 'crate', x: 22.5, y: 8.4, s: 1.0 }, { t: 'barrel', x: 23.5, y: 8.6, s: 1.0 }, { t: 'brazierBlue', x: 1.4, y: 12.4, s: 1.1 }, { t: 'brazierBlue', x: 1.4, y: 17.6, s: 1.1 }, { t: 'banner', x: 14.5, y: 11.4, s: 1.2, seed: 0.5 }, { t: 'banner', x: 32.6, y: 18.5, s: 1.2, seed: 0.9 },
      ],
      autoDecor: { density: 0.14, seed: 419 },
    },
  },
];
