/*
  Bahn-Definitionen.
  Karten-Legende (1 Zeichen = 1 Kachel):
    .  Leere / Abgrund        #  Fairway (Gras / Stein / Schnee je nach Welt)
    s  Sand (bremst stark)    i  Eis (sehr rutschig)
    w  Wasser (Hindernis, +1) l  Lava (Hindernis, +1)
    o  Fairway ohne Randmauer (Klippe – der Ball kann in den Abgrund rollen)
    x  massiver Block (Mauer) T  Abschlag         H  Loch
  Koordinaten der Hindernisse sind in Kachel-Einheiten (Mitte einer Kachel = .5).
*/
const COURSES = [
  {
    name: 'Elfenwiese', par: 3, theme: 'meadow',
    intro: 'Sanfte Wiese mit zwei Steinpfeilern – ein Aufwärmen.',
    map: [
      '........................',
      '..########..............',
      '..########..............',
      '..T#####x#####..........',
      '..######x######.........',
      '..######x###x####.......',
      '..##########x#####......',
      '..##########x####H#.....',
      '..##########x######.....',
      '..################......',
      '........................',
    ],
    obstacles: [],
    decor: [
      { t: 'tower', x: 21, y: 2.5 },
      { t: 'tree', x: 16, y: 1.5, s: 1.3 },
      { t: 'flowerbush', x: 5.5, y: 6.5 }, { t: 'flowerbush', x: 10.5, y: 8.4 },
      { t: 'flowerbush', x: 14.5, y: 3.6 }, { t: 'flowerbush', x: 16.5, y: 6.4 },
    ],
    autoDecor: { density: 0.42, seed: 11 },
  },
  {
    name: 'Pilzhain', par: 3, theme: 'mushroom',
    intro: 'Riesenpilze federn den Ball zurück – finde die Lücken.',
    map: [
      '........................',
      '....###########.........',
      '..#############.........',
      '..T############.........',
      '..###############.......',
      '..#################.....',
      '....#####s##########....',
      '....#######x#######H#...',
      '....#######x########....',
      '....#####s########......',
      '........................',
    ],
    obstacles: [
      { type: 'bumper', x: 7.5, y: 2.5, r: 0.6 },
      { type: 'bumper', x: 11.5, y: 4.5, r: 0.7 },
      { type: 'bumper', x: 15.5, y: 5.5, r: 0.6 },
      { type: 'bumper', x: 7.5, y: 6.8, r: 0.55 },
      { type: 'bumper', x: 14.5, y: 8.4, r: 0.6 },
      { type: 'bumper', x: 17.5, y: 6.3, r: 0.5 },
    ],
    decor: [
      { t: 'mushroomBig', x: 20.5, y: 3.5, s: 1.4 }, { t: 'mushroomBig', x: 1, y: 8, s: 1.1 },
      { t: 'lantern', x: 9.5, y: 0.5 },
    ],
    autoDecor: { density: 0.45, seed: 23 },
  },
  {
    name: 'Zwergenschmiede', par: 3, theme: 'forge',
    intro: 'Zwei schmale Brücken über den Lavafluss – und Loren auf Schienen.',
    map: [
      '........................',
      '..#######lll#######.....',
      '..#######lll########....',
      '..T######lll#########...',
      '..###########xx######...',
      '..#######lll##########..',
      '..#######lll####x####H#.',
      '..#######lll####x######.',
      '..###########xxxx######.',
      '..#######lll##########..',
      '..#######lll#########...',
      '........................',
    ],
    obstacles: [
      { type: 'mover', x0: 12.5, y0: 1.5, x1: 12.5, y1: 10.5, w: 0.9, h: 0.9, period: 6.5, phase: 0.1, style: 'cart' },
      { type: 'mover', x0: 18.5, y0: 10.5, x1: 18.5, y1: 1.5, w: 0.9, h: 0.9, period: 5, phase: 0.6, style: 'cart' },
      { type: 'rail', x: 12.5, y0: 1, y1: 11 }, { type: 'rail', x: 18.5, y0: 1, y1: 11 },
    ],
    decor: [
      { t: 'tower', x: 22, y: 1.5, s: 1.2, roof: '#5a2a1a' },
      { t: 'anvil', x: 1, y: 6.5 }, { t: 'anvil', x: 23.2, y: 4 },
      { t: 'brazier', x: 9.5, y: 0.4 }, { t: 'brazier', x: 11.5, y: 11.6 },
    ],
    autoDecor: { density: 0.35, seed: 37 },
  },
  {
    name: 'Zauberwald', par: 3, theme: 'forest',
    intro: 'Das Loch liegt auf einer Insel. Nur Portale führen hinüber – eines davon ist eine Falle.',
    map: [
      '........................',
      '..########....#######...',
      '..########....###H###...',
      '..T#######....#######...',
      '..########....#######...',
      '..########..............',
      '..########..............',
      '..########..######......',
      '..########..######......',
      '..########..######......',
      '........................',
    ],
    obstacles: [
      { type: 'portal', x: 8.5, y: 8.5, tx: 13.5, ty: 8.5, color: '#4fd0ff', twoWay: true },
      { type: 'portal', x: 16.5, y: 8.5, tx: 15.5, ty: 3.5, color: '#c77dff', twoWay: true },
      { type: 'portal', x: 8.5, y: 1.5, tx: 3.5, ty: 8.5, color: '#ff5f7a' },
    ],
    decor: [
      { t: 'tree', x: 11, y: 4, s: 1.6, glow: true }, { t: 'tree', x: 20.5, y: 7.5, s: 1.4, glow: true },
      { t: 'crystal', x: 10.5, y: 1.2 }, { t: 'crystal', x: 11.3, y: 6.3 },
    ],
    autoDecor: { density: 0.55, seed: 41 },
  },
  {
    name: 'Drachenhöhle', par: 4, theme: 'dragon',
    intro: 'Sandkuhlen, Lavabecken – und ein Drache, der vor dem Loch patrouilliert.',
    map: [
      '........................',
      '..########ssss########..',
      '..T#######ssss########..',
      '..########ssss########..',
      '..#####lll####lll#####..',
      '..#####lll####lll#####..',
      '..####################..',
      '..####################..',
      '..#####xxxxxxxxxx#####..',
      '..######s########s####..',
      '..#########H##########..',
      '........................',
    ],
    obstacles: [
      { type: 'mover', x0: 4.3, y0: 9.7, x1: 19.7, y1: 9.7, w: 2.4, h: 1.4, period: 9, phase: 0, style: 'dragon' },
      { type: 'field', x: 10, y: 6, w: 4, h: 2, fx: 0, fy: 4.5, style: 'wind' },
    ],
    decor: [
      { t: 'gold', x: 11.5, y: 12 }, { t: 'gold', x: 12.6, y: 12.3 }, { t: 'bones', x: 4.5, y: 11.5 },
      { t: 'stalagmite', x: 0.8, y: 5.5, s: 1.4 }, { t: 'stalagmite', x: 23.2, y: 6.5, s: 1.5 },
      { t: 'brazier', x: 7.5, y: 8.5 }, { t: 'brazier', x: 16.5, y: 8.5 },
    ],
    autoDecor: { density: 0.4, seed: 53 },
  },
  {
    name: 'Eisgrotte', par: 3, theme: 'ice',
    intro: 'Spiegelglattes Eis, eiskalte Tümpel und ein rotierender Kristallstern.',
    map: [
      '........................',
      '...iiiiiiiiiiiiiiiii....',
      '..iiiiiiiwwiiiiiiiiii...',
      '..Tiiiiiiwwiiiiiiiiii...',
      '..iiiiiiiiiiiiiiiiiii...',
      '..iiiiiiiiiiiiii#####...',
      '..iiiiiiiiiiiiii##H##...',
      '..iiiiiwwiiiiiii#####...',
      '..iiiiiwwiiiiiiiiiii....',
      '...iiiiiiiiiiiiiiiii....',
      '........................',
    ],
    obstacles: [
      { type: 'rotor', x: 12.5, y: 5.5, blades: 4, len: 3.2, speed: 1.1, style: 'crystal' },
      { type: 'bumper', x: 5.5, y: 6.5, r: 0.5, style: 'crystal' },
    ],
    decor: [
      { t: 'crystalBlue', x: 1, y: 2, s: 1.6 }, { t: 'crystalBlue', x: 22.5, y: 8.5, s: 1.5 },
      { t: 'pineSnow', x: 22.5, y: 2, s: 1.3 },
    ],
    autoDecor: { density: 0.4, seed: 67 },
  },
  {
    name: 'Wolkenburg', par: 4, theme: 'sky',
    intro: 'Schwebende Inseln, Brücken ohne Geländer, Fallgatter, Rückenwind – und ein tiefer Abgrund.',
    map: [
      '........................',
      '..#####..........#####..',
      '..T####..........##H##..',
      '..#####..........#####..',
      '....o............o......',
      '....o............o......',
      '....######....######....',
      '.........o....o.........',
      '.........########.......',
      '........................',
    ],
    obstacles: [
      { type: 'gate', x: 4.5, y: 4.5, w: 1, h: 0.3, period: 5, open: 0.45, phase: 0, axis: 'x' },
      { type: 'gate', x: 17.5, y: 5.2, w: 1, h: 0.3, period: 5, open: 0.45, phase: 0.5, axis: 'x' },
      { type: 'boost', x: 10, y: 8, w: 4, h: 1, angle: 0 },
      { type: 'field', x: 14, y: 6, w: 6, h: 1, fx: -3.5, fy: 0, style: 'wind' },
    ],
    decor: [
      { t: 'tower', x: 1, y: 0.5, s: 1.3 }, { t: 'tower', x: 23, y: 0.8, s: 1.3 },
      { t: 'tower', x: 7.5, y: 9.5, s: 1.1 }, { t: 'tower', x: 18, y: 9.6, s: 1.1 },
      { t: 'cloud', x: 12, y: 3, s: 1.6, z: 0.4 }, { t: 'cloud', x: 3, y: 12, s: 1.4, z: 0.2 },
      { t: 'cloud', x: 21, y: 12.5, s: 1.3, z: 0.3 }, { t: 'cloud', x: 11.5, y: -1.5, s: 1.3, z: 0.6 },
    ],
    autoDecor: { density: 0.22, seed: 71 },
  },
  {
    name: 'Hexenturm', par: 5, theme: 'witch',
    intro: 'Lava, Eis, ein Fallgatter, Kessel auf Wanderschaft – und ein Portal als Abkürzung.',
    map: [
      '..........................',
      '..########.....#########..',
      '..T##lll##.....#lll###H#..',
      '..###lll##.....#lll#####..',
      '..########.....#########..',
      '..######.......###........',
      '..######iiiiiiiii###......',
      '..######iiiiiiiii###......',
      '..####...........###......',
      '..####################....',
      '..#####ss#####ss######....',
      '..####################....',
      '..........................',
    ],
    obstacles: [
      { type: 'rotor', x: 12.5, y: 7, blades: 3, len: 1.5, speed: 2.2, style: 'broom' },
      { type: 'gate', x: 16.5, y: 5.5, w: 3, h: 0.3, period: 6, open: 0.4, phase: 0.2, axis: 'x' },
      { type: 'mover', x0: 3.5, y0: 10, x1: 19.5, y1: 10, w: 1, h: 1, period: 9, phase: 0, style: 'cauldron' },
      { type: 'mover', x0: 19.5, y0: 10.9, x1: 3.5, y1: 10.9, w: 1, h: 1, period: 7, phase: 0.4, style: 'cauldron' },
      { type: 'portal', x: 20.5, y: 10.5, tx: 20.5, ty: 1.5, color: '#a6ff5e' },
      { type: 'boost', x: 15, y: 5, w: 3, h: 1, angle: -90 },
    ],
    decor: [
      { t: 'tower', x: 12.5, y: 2.5, s: 2.2, roof: '#2a1a3a', witch: true },
      { t: 'cauldron', x: 0.8, y: 9.5 }, { t: 'pumpkin', x: 24.5, y: 4.5 }, { t: 'pumpkin', x: 8.5, y: 12.3 },
      { t: 'deadTree', x: 23.5, y: 8, s: 1.4 },
    ],
    autoDecor: { density: 0.4, seed: 83 },
  },
];
